using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_bpsReceipt_PaymentAdvice_SubAgent : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //form manage
        string sFormConfigCode;
           public int iFormID;
        
        //for security handle
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_bpsReceipt_PaymentAdvice_SubAgent()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.bpsReceiptPaymentAdviceSubAgent);
            iFormID = clsSecurity.getFormID(FormName.bpsReceiptPaymentAdviceSubAgent);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_bpsReceipt_PaymentAdvice_SubAgent_Load(object sender, EventArgs e)
        {
            ClearFields();
        } 
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {            
            ClearFields();            
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtReceiptID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records                           
                                {
                                    #region Update
                                    tbl_bpsReceipt_SubagentPayment oldRecord = new tbl_bpsReceipt_SubagentPayment();
                                    if (oldRecord != null)
                                    {
                                        tbl_bpsReceipt_SubagentPayment detail = new tbl_bpsReceipt_SubagentPayment(txtReceiptID.Text.ToString(), dtpPaymentDate.Value, txtSubAgentName.Text.Trim(),
                                            Decimal.Parse(txtCashAmount.Text.Trim()), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                            clsSecurity.UserIDLoged, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.getServerDateTime(),
                                            clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                            false, false, false, false, false, false, clsSecurity.getServerDateTime());
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }

                                    #endregion
                                }
                                else  //insert records
                                {
                                    #region Insert
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtReceiptID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_bpsReceipt_SubagentPayment detail = new tbl_bpsReceipt_SubagentPayment(txtReceiptID.Text.ToString(), dtpPaymentDate.Value, txtSubAgentName.Text.Trim(),
                                        Decimal.Parse(txtCashAmount.Text.Trim()), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                        clsSecurity.UserIDLoged, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.getServerDateTime(),
                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                        false, false, false, false, false, false, clsSecurity.getServerDateTime());
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

                                    #endregion
                                }
                            }
                            else
                            {
                                MessageBox.Show(" City " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();                            
                        }
                   }
                }
            }
            
        } 
        #endregion

        #region Btn Print
        private void btnPrint_Click(object sender, EventArgs e)
        {

        } 
        #endregion

        #region Btn Customer Viewer
        private void btnCustomerViewer_Click(object sender, EventArgs e)
        {
            if (txtCustomerName.Tag != null && txtCustomerName.Tag.ToString().Trim().Length > 0)
            {
                frm_sasViewerCustomer frm = new frm_sasViewerCustomer();
                frm.glbCustomerID = txtCustomerName.Tag.ToString();
                if (frm.bNoAccess)
                   MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption()+" ["+frm.iFormID+"]", MessageBoxButtons.OK, MessageBoxIcon.Information);
                else
                {
                    frm.MdiParent = this.MdiParent;
                    frm.Show();
                }
            }
        }
         
        #endregion
        

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtReceiptID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblReceiptID, true);

            txtCustomerName.Tag = null;

            txtReceiptID.Clear();
            dtpPaymentDate.Value = clsSecurity.getServerDateTime();
            txtSubAgentName.Clear();
            txtReceiptTotal.Clear();
            txtCashAmount.Text = "0.00";

            txtJobNo.Clear();
            txtSalesRep.Clear();
            dtpReceiptDate.Value = clsSecurity.getServerDateTime();
            txtCustomerName.Clear();

            txtFlowReceipt.ForeColor = Color.Gray;
            txtFlowPAdviced.ForeColor = Color.Gray;
            txtFlowPaid.ForeColor = Color.Gray;
        }
        #endregion     

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    bool bPAdviced = false, bPaid = false;
                    tbl_bpsReceipt oReceipt = tbl_bpsReceipt.Select(sID);
                    if (oReceipt != null)
                    {
                        tbl_bpsReceipt_SubagentPayment detail = tbl_bpsReceipt_SubagentPayment.Select(sID);
                        if (detail != null)
                        {
                            //set the update flag and Locked
                            IsUpdate = true;
                            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtReceiptID, false);
                            clsCommon.SetEnableDisable_NormalLabel(lblReceiptID, false); 

                            //fill order detials
                            txtReceiptID.Text = detail.Receipt_ID;
                            dtpPaymentDate.Value = detail.DateCreate;
                            txtSubAgentName.Text = detail.SubAgentName;
                            txtCashAmount.Text = clsFormatter.FormatToCurrecyWithThousendSep(detail.GrandTotal); 

                            bPAdviced = true;
                            bPaid = detail.IsPaid;
                        }
                        //receipt detail only
                        FillDetailsByReceiptID(oReceipt.Receipt_ID);

                        //Set Flow
                        clsHelpMethods.SetProcessFlow_PaymentSubAgent(txtFlowReceipt, txtFlowPAdviced, bPAdviced, txtFlowPaid, bPaid);
                    }

                }
            }
            catch { }

            finally { }
        }
        #endregion

        #region FillDetailsByReceiptID
        private void FillDetailsByReceiptID(string ReceiptID)
        {
            try
            {
                if (ReceiptID.Length > 0)
                {
                    tbl_bpsReceipt detail = tbl_bpsReceipt.Select(ReceiptID);
                    if (detail != null)
                    {
                        txtCustomerName.Tag = detail.Customer_ID;

                        dtpReceiptDate.Value = detail.ReceiptDate;
                        txtCustomerName.Text = clsGenaralName.getName_Customer(detail.Customer_ID);
                        txtReceiptTotal.Text = clsFormatter.FormatToCurrecyWithThousendSep(detail.TotalAmount);

                        tbl_zOrderRefNo order = tbl_zOrderRefNo.Select(detail.OrderRefNo_ID);
                        if (order != null)
                        {
                            txtJobNo.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_OrderRefNo(detail.OrderRefNo_ID));
                            txtSalesRep.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Employee(order.Employee_ID));
                        }
                    }
                }
            }
            catch { }

            finally { }
        }

        #endregion


        #region Events KeyDown
        private void txtCityID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_ReceiptID();
            }
        }
        #endregion

        #region Events Double Click
        private void txtReceiptID_DoubleClick(object sender, EventArgs e)
        {
            Search_ReceiptID();
        }
        #endregion


        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;
            try
            {
                if (txtCustomerName.TextLength == 0)
                {
                    strMessage += "\n" + "Customer Name ";
                    bStatus = false;
                }
                if (bStatus == false)
                {
                    MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return bStatus;
        }        
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {                
                if (!clsCommon.isCurrency(txtCashAmount.Text.Trim()))
                {
                    strMessage += "\n Total Cash";
                    bStatus = false;
                }
                if (!clsCommon.isCurrency(txtReceiptTotal.Text.Trim()))
                {
                    strMessage += "\n Total Receiptes";
                    bStatus = false;
                }
              
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion


        #region Search Methods
        private void Search_ReceiptID()
        {
            try
            {
                clsSearch.Search_TransactionReceipt_Direct(ref txtReceiptID, true, true,false,false);
                if (txtReceiptID.TextLength > 0)
                    FillDetails(txtReceiptID.Text.Trim());
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }

        }
        #endregion






      
       


    }
}
