using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_LoanSettlemnet : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
        public int iFormID;
        public bool bNoAccess;
        #endregion

        #region  Form Load
        public frm_LoanSettlemnet()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.LoanSettlement);
            iFormID = clsSecurity.getFormID(FormName.LoanSettlement);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
                bNoAccess = true;

            InitializeComponent();
        }

        private void frm_masDesignPattern_Length_Load(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtAllocationID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblAllocationID, true);
            //clsCommon.SetEnableDisable_NormalTextbox(txtMettleName, true);
            //clsCommon.SetEnableDisable_NormalTextbox(txtRemarks, true);

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtAllocationID.Text = "<Auto Generate>";
            else
                txtAllocationID.Clear();

            rdoQtyAllocation.Checked = true;

            if (txtAllocationID.Enabled)
            {
                txtAllocationID.SelectAll();
                txtAllocationID.Focus();
            }
        }
        #endregion

        private void btnSave_Click_1(object sender, EventArgs e)
        {
            if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
            {
                if (frm_scsLoan.sLoanInID != "" && frm_scsLoan.sLoanInID.Length > 0 && frm_scsLoan.sLonOutID != "" && frm_scsLoan.sLonOutID.Length > 0)
                {
                    try
                    {
                        Cursor = Cursors.WaitCursor;
                        bool bIsPriceAllocatioon = false, bIsOk = false;
                        decimal dUnitPriceSettle = 0;

                        #region Select Allocation Type
                        bIsPriceAllocatioon = rdoPriceAllocation.Checked;
                        #endregion

                        #region Select  Document
                        tbl_scsLoanIn oLoanIn = null;
                        tbl_scsLoanOut oLoanOut = null;

                        #region Loan In Base
                        if (frm_scsLoan.isLoanIn)
                        {
                            string[] saLonId = frm_scsLoan.sLonOutID.ToString().Split(',');
                            oLoanIn = tbl_scsLoanIn.Select(frm_scsLoan.sLoanInID.Trim());
                            if (oLoanIn != null && oLoanIn.LoanIn_ID != "default" && saLonId != null)
                            {
                                foreach (string sLonID in saLonId)
                                {
                                    #region Settle Loan In
                                    decimal dSettleQty = 0;
                                    tbl_scsLoanOut oLoanOutForLoanIn = tbl_scsLoanOut.Select(sLonID);
                                    if (oLoanOutForLoanIn != null) // &&)
                                    {
                                        if (!oLoanOutForLoanIn.IsDeleted && !oLoanIn.IsDeleted)
                                        {
                                            if (!oLoanIn.IsSeattled)
                                            {
                                                if (oLoanOutForLoanIn.IsWeightCalculation == oLoanIn.IsWeightCalculation)//oLoanOutForLoanIn.IsWeightCalculation == oLoanIn.IsWeightCalculation
                                                {
                                                    if (!bIsPriceAllocatioon)
                                                        dSettleQty = oLoanOutForLoanIn.TotalWeight != 0 ? oLoanOutForLoanIn.TotalWeight : oLoanOutForLoanIn.TotalQty;
                                                    else
                                                        dUnitPriceSettle = oLoanOutForLoanIn.TotalWeightPrice != 0 ? oLoanOutForLoanIn.TotalWeightPrice : oLoanOutForLoanIn.TotalUnitPrice;

                                                    #region Settle Document
                                                    if (SettleLoanInFlow(oLoanOutForLoanIn, oLoanIn, dSettleQty, dUnitPriceSettle, oLoanOutForLoanIn.IsWeightCalculation, bIsPriceAllocatioon, true))
                                                    {
                                                        bIsOk = true;
                                                    }
                                                    #endregion
                                                }
                                                else
                                                    MessageBox.Show("Loan In and Loan Out Types are Not matched.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                            }
                                            else
                                                MessageBox.Show("This Document has allredy Settled.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                        }
                                        else
                                            MessageBox.Show("This Document is Deleted.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                    }

                                    #endregion
                                }
                            }

                            #region  Set Full Settlement
                            if (bIsOk)
                            {
                                oLoanIn.IsSeattled = chkisSettle.Checked;
                                oLoanIn.Update();

                                #region If Full Settle
                                if (chkisSettle.Checked)
                                {
                                    string[] saLonId_Temp = frm_scsLoan.sLonOutIDAll.ToString().Split(',');
                                    foreach (string sLonID in saLonId_Temp)
                                    {
                                        foreach (tbl_scsLoanSettle oSettle in tbl_scsLoanSettle.SelectAllByLoanOut_ID(sLonID).Where(p => p.LoanIn_ID != "default"))
                                        {
                                            tbl_scsLoanIn oSettleLoanIN = tbl_scsLoanIn.Select(oSettle.LoanIn_ID);
                                            if (oSettleLoanIN != null && oSettleLoanIN.LoanIn_ID != "default")
                                            {
                                                oSettleLoanIN.IsSeattled = chkisSettle.Checked;
                                                oSettleLoanIN.Update();
                                            }
                                            tbl_scsLoanOut oSettleLoanOut = tbl_scsLoanOut.Select(oSettle.LoanOut_ID);
                                            if (oSettleLoanOut != null && oSettleLoanOut.LoanOut_ID != "default")
                                            {
                                                oSettleLoanOut.IsSeattled = chkisSettle.Checked;
                                                oSettleLoanOut.Update();
                                            }
                                        }

                                    }
                                }
                                #endregion

                            }
                            #endregion
                        }
                        #endregion

                        #region Loan Out Base
                        else
                        {
                            string[] oLonId = frm_scsLoan.sLoanInID.ToString().Split(',');
                            oLoanOut = tbl_scsLoanOut.Select(frm_scsLoan.sLonOutID);

                            if (oLoanOut != null && oLoanOut.LoanOut_ID != "default" && oLonId != null)
                            {
                                foreach (string sLonID in oLonId)
                                {
                                    #region Settle Loan Out

                                    decimal dSettleQty = 0;
                                    tbl_scsLoanIn oLoanInForLoanOut = tbl_scsLoanIn.Select(sLonID);
                                    if (oLoanOut != null && oLoanInForLoanOut != null && !oLoanInForLoanOut.IsDeleted && !oLoanOut.IsDeleted)
                                    {
                                        if (!oLoanInForLoanOut.IsDeleted && !oLoanOut.IsDeleted)
                                        {

                                            if (!oLoanOut.IsSeattled)
                                            {
                                                if (oLoanInForLoanOut.IsWeightCalculation == oLoanOut.IsWeightCalculation)//oLoanInForLoanOut.IsWeightCalculation == oLoanOut.IsWeightCalculation
                                                {
                                                    if (!bIsPriceAllocatioon)
                                                        dSettleQty = oLoanInForLoanOut.TotalWeight != 0 ? oLoanInForLoanOut.TotalWeight : oLoanInForLoanOut.TotalQty;
                                                    else
                                                        dUnitPriceSettle = oLoanInForLoanOut.TotalWeightPrice != 0 ? oLoanInForLoanOut.TotalWeightPrice : oLoanInForLoanOut.TotalUnitPrice;


                                                    if (SettleLoanOutFlow(oLoanInForLoanOut, oLoanOut, dSettleQty, dUnitPriceSettle, oLoanInForLoanOut.IsWeightCalculation, bIsPriceAllocatioon, false))
                                                    {
                                                        bIsOk = true;
                                                    }

                                                }
                                                else
                                                    MessageBox.Show("Loan In and Loan Out Types are Not matched.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                            }
                                            else
                                                MessageBox.Show("This Document has allredy Settled.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                        }
                                        else
                                            MessageBox.Show("This Document is Deleted.......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                    }
                                    #endregion
                                }
                            }

                            #region  Set Full Settlement
                            if (bIsOk)
                            {
                                oLoanOut.IsSeattled = chkisSettle.Checked;
                                oLoanOut.Update();

                                #region If Full Settle
                                if (chkisSettle.Checked)
                                {
                                    string[] oLonId_Temp = frm_scsLoan.sLoanInIDAll.ToString().Split(',');
                                    foreach (string sLonID in oLonId_Temp)
                                    {
                                        foreach (tbl_scsLoanSettle oSettle in tbl_scsLoanSettle.SelectAllByLoanIn_ID(sLonID).Where(p => p.LoanIn_ID != "default"))
                                        {
                                            tbl_scsLoanIn oSettleLoanIN = tbl_scsLoanIn.Select(oSettle.LoanIn_ID);
                                            if (oSettleLoanIN != null && oSettleLoanIN.LoanIn_ID != "default")
                                            {
                                                oSettleLoanIN.IsSeattled = chkisSettle.Checked;
                                                oSettleLoanIN.Update();
                                            }
                                            tbl_scsLoanOut oSettleLoanOut = tbl_scsLoanOut.Select(oSettle.LoanOut_ID);
                                            if (oSettleLoanOut != null && oSettleLoanOut.LoanOut_ID != "default")
                                            {
                                                oSettleLoanOut.IsSeattled = chkisSettle.Checked;
                                                oSettleLoanOut.Update();
                                            }
                                        }

                                    }
                                }
                                #endregion
                            }
                            #endregion
                        }
                        #endregion

                        #endregion

                        if (bIsOk)
                            MessageBox.Show(frm_scsLoan.sLoanInID + " and " + frm_scsLoan.sLonOutID + " is Settled......! ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID,ex);
                        SEACCException.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Default;
                    }

                }
                else
                {
                    MessageBox.Show("Please Select Loan In and Loan Out for settle", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

            this.Close();
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        #region Methord for Settle current Document
        private bool SettleLoanInFlow(tbl_scsLoanOut oLoanOutForLoanIn, tbl_scsLoanIn oLoanIn, decimal dSettleQty, decimal dUnitPrice, bool isWeight, bool isPriceAllocatioon, bool isLoanInBase)
        {
            #region Setting up Allocation Code
            if (txtAllocationID.Text != "")
            {
                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                    txtAllocationID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);
            }
            frm_scsLoan.sAllocationID = txtAllocationID.Text;
            #endregion

            #region Settle Loan
            if (true)
            {
                bool isOk = true;
                if (oLoanOutForLoanIn.TotalWeight > oLoanIn.TotalWeight)
                {
                    //  MessageBox.Show("Over Allocation Than LoanOut Not Allow....!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                    // isOk = false;
                }
                else if (oLoanOutForLoanIn.TotalWeight < oLoanIn.TotalWeight)
                {

                }
                if (!isPriceAllocatioon)
                    oLoanIn.SeattleAmount += oLoanIn.TotalWeight != 0 ? oLoanIn.TotalWeight - dSettleQty : oLoanIn.TotalQty - dSettleQty;
                else
                    oLoanIn.SeattleAmount += oLoanIn.TotalWeightPrice != 0 ? oLoanIn.TotalWeightPrice - dUnitPrice : oLoanIn.TotalUnitPrice - dUnitPrice;

                oLoanIn.Update();

                //oLoanOutForLoanIn.IsSeattled = chkisSettle.Checked;
                oLoanOutForLoanIn.SeattleAmount = !isPriceAllocatioon ? dSettleQty : dUnitPrice;
                oLoanOutForLoanIn.Update();

                tbl_scsLoanSettle oLoanSettle = new tbl_scsLoanSettle(txtAllocationID.Text, oLoanIn.LoanIn_ID, oLoanOutForLoanIn.LoanOut_ID, oLoanOutForLoanIn.TotalQty, oLoanOutForLoanIn.TotalWeight, oLoanOutForLoanIn.TotalUnitPrice, oLoanOutForLoanIn.TotalWeightPrice, dtmAllocationDate.Value.Date, isPriceAllocatioon, isLoanInBase);
                oLoanSettle.Insert();
                return isOk;
            }

            #endregion
        }
        private bool SettleLoanOutFlow(tbl_scsLoanIn oLoanInForLoanOut, tbl_scsLoanOut oLoanOut, decimal dSettleQty, decimal dUnitPrice, bool isWeight, bool isPriceAllocatioon, bool isLoanInbase)
        {
            #region Setting up Allocation Code
            if (txtAllocationID.Text != "")
            {
                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                    txtAllocationID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);
            }
            frm_scsLoan.sAllocationID = txtAllocationID.Text;
            #endregion

            bool isOk = true;
            if (true)
            {
                #region Settle Loan
                if (true)
                {
                    if (!isPriceAllocatioon)
                        oLoanOut.SeattleAmount += oLoanOut.TotalWeight != 0 ? oLoanOut.TotalWeight - dSettleQty : oLoanOut.TotalQty - dSettleQty;
                    else
                        oLoanOut.SeattleAmount += oLoanOut.TotalWeightPrice != 0 ? oLoanOut.TotalWeightPrice - dUnitPrice : oLoanOut.TotalUnitPrice - dUnitPrice;

                    oLoanOut.Update();

                    //oLoanInForLoanOut.IsSeattled = true;
                    oLoanInForLoanOut.SeattleAmount = !isPriceAllocatioon ? dSettleQty : dUnitPrice;
                    oLoanInForLoanOut.Update();

                    tbl_scsLoanSettle oLoanSettle = new tbl_scsLoanSettle(txtAllocationID.Text, oLoanInForLoanOut.LoanIn_ID, oLoanOut.LoanOut_ID, oLoanInForLoanOut.TotalQty, oLoanInForLoanOut.TotalWeight, oLoanInForLoanOut.TotalUnitPrice, oLoanInForLoanOut.TotalWeightPrice, dtmAllocationDate.Value.Date, isPriceAllocatioon, isLoanInbase);
                    oLoanSettle.Insert();

                }
                #endregion
            }
            return isOk;
        }
        #endregion


    }
}
