using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_scsSectionGoodIssueNote : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //form manage
        string sFormConfigCode, sDepartmentID = "default", sSectionID = "default", sStoreID = "default", sSRNNoDepartment = "default", sSRNNoSection = "default", sSRNNoStore = "default";
           public int iFormID;

        //to keep glob ref no        
        public string glbGINNo = "", glbSRNo = "";

        //for security handle
        public bool bNoAccess;
        public bool bHasChecked;
        public bool bHasApproved;
        DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        DateTime glbCheckedDate = clsSecurity.getServerDateTime();
        #endregion

        #region Form Load
        public frm_scsSectionGoodIssueNote()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.scsGINSectionStock);
            iFormID = clsSecurity.getFormID(FormName.scsGINSectionStock);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
                bNoAccess = true;

            InitializeComponent();
        }
        private void frmCustomerOrder_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format    
            clsFormatter.setFormatForm(this, "Section Good Issue Note [iGIN]", 3, iFormID);           
            ClearFields();
            CusDataGridViewFormat();

            if (glbGINNo.Length > 0)
                FillDetails(glbGINNo);

            //if the GIN fired by SR   
            if (glbSRNo.Length > 0)
            {
                txtSRNID.Text = glbSRNo;
                FillDetailsFromSR(txtSRNID.Text.Trim());
            }
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 0)
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                }
            }
            catch (Exception) { }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (CheckJobNoValidity())
                {
                    if (CheckNumberValidity())
                    {
                        if (CheckStockValidity())
                        {
                            if (CheckValidity_Customer())
                            {
                                if (clsMethods_GL.CheckValidity_FinancialYear(dtpGINDate.Value.Date))
                                {
                                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                                    {
                                        if (clsSecurity.permissionToSave_Store(clsSecurity.UserIDLoged, txtStoreID.Tag.ToString(), IsUpdate))
                                        { 
                                        try
                                        {
                                            Cursor = Cursors.WaitCursor;
                                            ValidateEmptyForeignKey();

                                            if (IsUpdate)  //update records
                                            {
                                                #region Update Code
                                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordUpdateIsBlock), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                                #endregion
                                            }
                                            else  //insert records
                                            {
                                                #region Insert Data
                                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                                    txtGoodIssueNoteID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                                //create order ref number
                                                if (txtOrderRefNo.Tag == null || txtOrderRefNo.Tag.ToString().Trim() == "default")
                                                {
                                                    txtOrderRefNo.Tag = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.zIssuedRefNo));
                                                    tbl_zIssuedRefNo orf = new tbl_zIssuedRefNo(txtOrderRefNo.Tag.ToString().Trim(), txtOrderRefNo.Text.Trim());
                                                    orf.Insert();
                                                }

                                                if (clsValidate.CheckValidity_TransactionCodeLength(txtGoodIssueNoteID.Text)) //if (txtGoodIssueNoteID.Text.Trim().Length > 0)
                                                {
                                                    //Header
                                                    tbl_scsSectionGoodIssueNote detail = new tbl_scsSectionGoodIssueNote(txtGoodIssueNoteID.Text.Trim(), dtpGINDate.Value, txtRemark.Text.Trim(), txtJobID.Tag.ToString(),
                                                        txtLocationID.Tag.ToString(), getSelectAriaID(), txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), txtOrderRefNo.Tag.ToString(),
                                                        clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, "default", "default", clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                        clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID,
                                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), glbCheckedDate, glbApprovedDate, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                                        bHasChecked, bHasApproved, false, false, false, 0, false);
                                                    detail.Insert();

                                                    //Detail                                
                                                    foreach (DataGridViewRow row in dgvDetail.Rows)
                                                    {
                                                        try
                                                        {
                                                            string sItemCode = "", sUom = "default", sJobCode = "", sSelectArea_ID = "", sDepartment_ID = "",
                                                            sSection_ID = "", sStore_ID = "", sDepartmentNote_ID = "", sSectionNote_ID = "", sStoreNote_ID = "",
                                                            sItemSubCategoryID1 = "", sItemSubCategoryID2 = "", sItemSerialNo1 = "", sItemSerialNo2 = "";
                                                            decimal dWeight = 0, dQuantity = 0;
                                                            sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "");
                                                            sUom = clsValidate.ValidateGridTag(dgvDetail, "UOM", row.Index, "default");
                                                            dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                                                            dQuantity = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                                                            sJobCode = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                                                            sSelectArea_ID = clsValidate.ValidateGridValue(dgvDetail, "SelectArea_ID", row.Index, "default");
                                                            sDepartment_ID = clsValidate.ValidateGridValue(dgvDetail, "Department_ID", row.Index, "default");
                                                            sSection_ID = clsValidate.ValidateGridValue(dgvDetail, "Section_ID", row.Index, "default");
                                                            sStore_ID = clsValidate.ValidateGridValue(dgvDetail, "Store_ID", row.Index, "default");
                                                            sDepartmentNote_ID = clsValidate.ValidateGridValue(dgvDetail, "DepartmentNote_ID", row.Index, "default");
                                                            sSectionNote_ID = clsValidate.ValidateGridValue(dgvDetail, "SectionNote_ID", row.Index, "default");
                                                            sStoreNote_ID = clsValidate.ValidateGridValue(dgvDetail, "StoreNote_ID", row.Index, "default");
                                                            sItemSubCategoryID1 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID1", row.Index, "default");
                                                            sItemSubCategoryID2 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID2", row.Index, "default");
                                                            sItemSerialNo1 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo1", row.Index, "0");
                                                            sItemSerialNo2 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo2", row.Index, "0");

                                                            if (sItemCode.Length > 0)
                                                            {
                                                                tbl_scsSectionGoodIssueNote_Detail items = new tbl_scsSectionGoodIssueNote_Detail(row.Index, txtGoodIssueNoteID.Text.Trim(),
                                                                    sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, sJobCode, txtLocationID.Tag.ToString(),
                                                                    sSelectArea_ID, sDepartment_ID, sSection_ID, sStore_ID, sDepartmentNote_ID, sSectionNote_ID, sStoreNote_ID,
                                                                    sUom, dQuantity, 0, dWeight, 0, 0, 0, "", false);
                                                                items.Insert();

                                                                ////Update Store Stock                                                           
                                                                //clsHelpMethods.UpdateOrInsertSectionStock(clsConfig.bStockValidateQty_iGIN, clsConfig.bStockValidateWeight_iGIN, sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2,
                                                                //   sJobCode, txtLocationID.Tag.ToString(), dQuantity, dWeight, 0, 0, false, false, true);

                                                                //update SR 
                                                                #region Update SR Status
                                                                string sSrnID = clsHelpMethods.GetSelectAreaNoteID(sSelectArea_ID, sDepartmentNote_ID, sSectionNote_ID, sStoreNote_ID);
                                                                if (sSrnID.Trim().Length > 0 && sSrnID.Trim().ToLower() != "default")
                                                                {
                                                                    if (clsAutocode.getSelectAreaCode(SelectArea.Department) == sSelectArea_ID)
                                                                    {
                                                                        //pls do the code
                                                                    }
                                                                    else if (clsAutocode.getSelectAreaCode(SelectArea.Section) == sSelectArea_ID)
                                                                    {
                                                                        foreach (tbl_scsSectionReqositionNote_Detail SR in tbl_scsSectionReqositionNote_Detail.SelectAllBySectionReqositionNote_ID(sSrnID).Where(p => p.Item_ID == sItemCode))
                                                                        {
                                                                            SR.QtySettle += dQuantity;
                                                                            SR.WeightSettle += dWeight;
                                                                            SR.Update();
                                                                            clsProcessMethods.SetSettle_SectionSR(sSrnID);
                                                                        }
                                                                    }
                                                                    else if (clsAutocode.getSelectAreaCode(SelectArea.Store) == sSelectArea_ID)
                                                                    {
                                                                        foreach (tbl_scsStoreReqositionNote_Detail SR in tbl_scsStoreReqositionNote_Detail.SelectAllByStoreRecositionNote_ID(sSrnID).Where(p => p.Item_ID == sItemCode))
                                                                        {
                                                                            SR.QtySettle += dQuantity;
                                                                            SR.WeightSettle += dWeight;
                                                                            SR.Update();
                                                                            clsProcessMethods.SetSettle_StoreSR(sSrnID);
                                                                        }
                                                                    }
                                                                }
                                                                #endregion
                                                            }
                                                        }
                                                        catch (Exception ex)
                                                        {
                                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                                            SEACCException.Show(ex);
                                                        }
                                                    }

                                                    Attachments.Insert(txtGoodIssueNoteID.Text.ToString());

                                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                }
                                                //else
                                                //{
                                                //    MessageBox.Show("Good Issue Note " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                //}
                                                #endregion
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                            SEACCException.Show(ex);
                                        }
                                        finally
                                        {
                                            Cursor = Cursors.Default;
                                            FillDetails(txtGoodIssueNoteID.Text.Trim());
                                        }
                                    }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        #endregion

        #region Btn Print
        private void btnPrint_Click(object sender, EventArgs e)
        {
            try
            {
                bool isDuplicate = false;
                if (txtGoodIssueNoteID.Text.Trim().Length > 0 && txtGoodIssueNoteID.Text.Trim() != "<Auto Generate>")
                {
                    //update receipt
                    string sCreateUser = "", sCheckedUser = "", sApprovedUser = "";
                    tbl_scsSectionGoodIssueNote gin = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text.Trim());
                    if (gin != null)
                    {
                        if (gin.PrintCount>0)
                            isDuplicate = true;
                        gin.PrintCount ++;
                        //order.IsLocked = true;
                        sCreateUser = "[ " + clsGenaralName.getName_User(gin.CreateUser_ID) + " ] [ " + gin.DateCreate.ToShortDateString() + " ]";
                        if (gin.CheckedUser_ID != "default")
                            sCheckedUser = "[ " + clsGenaralName.getName_User(gin.CheckedUser_ID) + " ] [ " + gin.DateChecked.ToShortDateString() + " ]";
                        if (gin.ApprovedUser_ID != "default")
                            sApprovedUser = "[ " + clsGenaralName.getName_User(gin.ApprovedUser_ID) + " ] [ " + gin.DateApproved.ToShortDateString() + " ]";
                        gin.Update();
                    }

                    Cursor = Cursors.WaitCursor;
                    string s_Path = "", sReportTitle = "GOODS ISSUE NOTE [GIN]", sFormula = "";

                    sFormula = "{vw_rpt_scsSectionGoodIssueNote.sectionGoodIssueNote_ID} = '" + txtGoodIssueNoteID.Text.Trim() + "'";

                    ReportDocument RD = new ReportDocument();
                    s_Path = Application.StartupPath.Replace("\\bin\\Debug", "");
                    s_Path += "\\reports\\rpt_scsSectionGoodIssueNote.rpt";

                    frm_ReportViewer viewer = new frm_ReportViewer();
                    RD.Load(s_Path);
                    clsSecurity.LogonServer(ref RD);
                    RD.Refresh();

                    //RD.DataDefinition.FormulaFields["HeaderTitle"].Text = clsCommon.fncsetstring(sHeaderTitle);
                    RD.DataDefinition.FormulaFields["ReportTitle"].Text = clsCommon.fncsetstring(sReportTitle);
                    RD.DataDefinition.FormulaFields["DateRange"].Text = clsCommon.fncsetstring(clsSecurity.getServerDateTime().ToShortDateString());
                    RD.DataDefinition.FormulaFields["CreateUserName"].Text = clsCommon.fncsetstring(sCreateUser);
                    RD.DataDefinition.FormulaFields["CheckUserName"].Text = clsCommon.fncsetstring(sCheckedUser);
                    RD.DataDefinition.FormulaFields["ApproveUserName"].Text = clsCommon.fncsetstring(sApprovedUser);
                    RD.DataDefinition.FormulaFields["CompanyName"].Text = clsCommon.fncsetstring(clsSecurity.CompanyName);
                    RD.DataDefinition.FormulaFields["CompanyAddress1"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress1);
                    RD.DataDefinition.FormulaFields["CompanyAddress2"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress2);
                    RD.DataDefinition.FormulaFields["DigiteqName"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqName);
                    RD.DataDefinition.FormulaFields["DigiteqEmail"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqEmail);
                    if(isDuplicate)
                        RD.DataDefinition.FormulaFields["DuplicateCopy"].Text = clsCommon.fncsetstring("Duplicate Copy");

                    viewer.crystalReportViewer1.ReportSource = RD;
                    viewer.crystalReportViewer1.SelectionFormula = sFormula;
                    viewer.crystalReportViewer1.Visible = true;
                    viewer.crystalReportViewer1.DisplayToolbar = true;
                    viewer.crystalReportViewer1.CloseView(false);
                    viewer.WindowState = FormWindowState.Maximized;

                    viewer.ShowDialog();

                    RD.Close();
                    RD.Dispose();
                }
                else
                    MessageBox.Show("Please Select the Goods Issue Note To Print Report", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region Btn Add SRN
        private void btnAddStore_Click(object sender, EventArgs e)
        {
            if (txtSRNID.Text.Trim().Length > 0)
            {
                FillDetailsFromSR(txtSRNID.Text.Trim());
            }
        }
        #endregion

        #region Btn add Item
        private void btnAddItem_Click(object sender, EventArgs e)
        {
            if (txtItemID.Tag != null && txtItemID.Tag.ToString().Trim().Length > 0)
            {
                tbl_genItemMaster detail = tbl_genItemMaster.Select(txtItemID.Tag.ToString().Trim());
                if (detail != null)
                {
                    clsCommon.ValidateForeignKey(ref txtItemSubCategory);
                    clsCommon.ValidateForeignKey(ref txtItemSerialNo, "0");
                    RefreshGridByItem_ID(detail.Item_ID);
                }
            }
        }
        #endregion

        #region Btn Add JobOder
        private void btnJobOder_Click(object sender, EventArgs e)
        {
            if (txtJobID.Text.Trim().Length > 0)
            {
                tbl_pmsProductionJobRegister detail = tbl_pmsProductionJobRegister.Select(txtJobID.Text.Trim());
                if (detail != null)
                {
                    RefreshGridByJob_ID(detail.ProductionJob_ID);
                }
            }
        }
        #endregion

        #region Btn IGRN
        private void btnIGRN_Click(object sender, EventArgs e)
        {
            if (txtGoodIssueNoteID.Text != "default" && txtGoodIssueNoteID.Text.Trim().Length > 0 && txtGoodIssueNoteID.Text != "<Auto Generate>")
            {
                tbl_scsSectionGoodIssueNote detail = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text.ToString());
                if (detail != null)
                {
                    if (!detail.IsSeattled)
                    {
                        if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Store))
                        {
                            //frm_scsStoreGoodReceiveNote frm = new frm_scsStoreGoodReceiveNote();
                            //frm.MdiParent = this.ParentForm;
                            //if (frm.bNoAccess)
                            //   MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption()+" ["+frm.iFormID+"]", MessageBoxButtons.OK, MessageBoxIcon.Information);
                            //else
                            //{
                            //    frm.glbGINNo = detail.SectionGoodIssueNote_ID;
                            //    frm.Show();
                            //}

                            frm_scsStoreGoodReceiveNote frm = new frm_scsStoreGoodReceiveNote(FormName.sasGRNTradingStock);
                            clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorStock, this.MdiParent);
                        }
                        else if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Section))
                        {
                            frm_scsSectionGoodReceiveNote frmGIN = new frm_scsSectionGoodReceiveNote();
                            frmGIN.MdiParent = this.MdiParent;
                            if (frmGIN.bNoAccess)
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption() + " [" + frmGIN.iFormID + "]", MessageBoxButtons.OK, MessageBoxIcon.Information);
                            else
                            {
                                frmGIN.glbGINNo = detail.SectionGoodIssueNote_ID;
                                frmGIN.Show();
                            }
                        }
                        else if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Department))
                        {
                            //Pls Do
                        }
                    }
                    else
                        MessageBox.Show("Already Received \n\nThis GIN Quantity has already being received by Good Requisition Note(s)", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        #endregion

        #region Btn Option
        private void btnOption_Click(object sender, EventArgs e)
        {
            frmOption op = new frmOption();
            op.ShowDialog();

            if (frmOption.bEMail)
            {
                sendEmail();
            }
            else if (frmOption.bSMS)
            {

            }
            else if (frmOption.bCancel)
            {
                cancelOrder();
            }
            else if (frmOption.bPrint)
            {

            }
            else
            {

            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColor1, clsFormatter.colorDigiteqTheamColorPsmForColour, clsFormatter.colorDigiteqTheamColorStockBackColour);
            clsHelpMethods.FormatGrid_Stock(dgvDetail);

            //Change Grid Headers
            dgvDetail.Columns["ItemSubCategoryID1"].HeaderText = clsConfig.sItemSubCategory;
            dgvDetail.Columns["GoodsFrom"].HeaderText = "Requested By";
            dgvDetail.Columns["Note_ID"].HeaderText = "iSR Number";
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            lblCancelled.Visible = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtGoodIssueNoteID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, true);
            setEnableItems(false);
            clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblLocationID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, true);

            txtLocationID.Tag = null;
            txtItemSubCategory.Tag = null;
            txtItemSerialNo.Tag = null;            
            txtOrderRefNo.Tag = null;

            txtItemSerialNo.Clear();
            txtItemSubCategory.Clear();
            txtGoodIssueNoteID.Clear();
            txtRemark.Clear();
            txtLocationID.Clear();
            clearLocationFields();
            txtOrderRefNo.Clear();

            bHasApproved = false;
            bHasChecked = false;
            //userDetailsColorChanges();

            chkSettings.Checked = true;
            chkShowSettle.Checked = false;
            dgvDetail.Rows.Clear();
            dtpGINDate.Value = clsSecurity.getServerDateTime();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtGoodIssueNoteID.Text = "<Auto Generate>";
            else
                txtGoodIssueNoteID.Clear();
            if (txtGoodIssueNoteID.Enabled)
            {
                txtGoodIssueNoteID.SelectAll();
                txtGoodIssueNoteID.Focus();
            }

            Attachments.Clear();
        }
        #endregion

        #region Clear Items and Jobs
        private void clearItamAndJob()
        {
            txtItemID.Tag = null;
            txtJobID.Tag = null;
            txtSRNID.Tag = null;
            txtItemID.Clear();
            txtJobID.Clear();
            txtSRNID.Clear();

        }
        #endregion

        #region Clear Location Field
        private void clearLocationFields()
        {
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtJobID.Tag = null;
            txtSRNID.Tag = null;
            txtItemID.Tag = null;
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtJobID.Clear();
            txtSRNID.Clear();
            txtItemID.Clear();
            setEnableItems(false);
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_scsSectionGoodIssueNote detail = tbl_scsSectionGoodIssueNote.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    if (detail.IsDeleted)
                        lblCancelled.Visible = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtGoodIssueNoteID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, false);
                    clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblLocationID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false);


                    //asign values
                    txtLocationID.Tag = detail.FromSection_ID;
                    txtDepartmentID.Tag = detail.ToDepartment_ID;
                    txtSectionID.Tag = detail.ToSection_ID;
                    txtStoreID.Tag = detail.ToStore_ID;
                    txtSRNID.Tag = detail.SectionRequisitionNote_ID;
                    txtJobID.Tag = detail.Job_ID;

                    //fill order detials
                    tbl_zIssuedRefNo order = tbl_zIssuedRefNo.Select(detail.IssuedRefNo_ID);
                    if (order != null)
                    {
                        txtOrderRefNo.Tag = order.IssuedRefNo_ID;
                        txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(order.IssuedRefNo);
                    }

                    txtGoodIssueNoteID.Text = detail.SectionGoodIssueNote_ID;
                    txtRemark.Text = detail.Remark;
                    dtpGINDate.Value = detail.SectionGoodIssueNoteDate;
                    txtLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.FromSection_ID));
                    txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(detail.ToDepartment_ID));
                    txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.ToSection_ID));
                    txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(detail.ToStore_ID));
                    //txtToLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(detail.ToStore_ID));
                    txtSRNID.Text = clsCommon.GetForeignKeyValue(detail.StoreRequisitionNote_ID);
                    txtJobID.Text = clsCommon.GetForeignKeyValue(detail.Job_ID);
                    chkSettings.Checked = false;

                    if (detail.IsApproved)
                    {
                        bHasApproved = true;
                        glbApprovedDate = detail.DateApproved;
                    }
                    if (detail.IsChecked)
                    {
                        bHasChecked = true;
                        glbCheckedDate = detail.DateChecked;
                    }
                    //userDetailsColorChanges();


                    //fill item details
                    RefreshGrid(detail.SectionGoodIssueNote_ID);

                    //Set Flow
                    clsHelpMethods.SetProcessFlow_Stock_Internal(detail.IssuedRefNo_ID, txtFlowSR, txtFlowGIN, txtFlowGRN);

                    Attachments.FillAttachments( sID);
                }

            }
        }
        private void FillDetailsFromSR(string sSR_ID)
        {
            tbl_scsDepartmentReqositionNote oSR_Department = tbl_scsDepartmentReqositionNote.Select(txtSRNID.Text.Trim());
            if (oSR_Department != null)
            {
                //RefreshGridByDepartmentSRN_ID(oSR_Department.DepartmentReqositionNote_ID);
                //FillDetailsTextBoxes(oSR_Department.FromDepartment_ID, "default", "default", oSR_Department.ToStore_ID, sSR_ID);
            }

            tbl_scsSectionReqositionNote oSR_Section = tbl_scsSectionReqositionNote.Select(txtSRNID.Text.Trim());
            if (oSR_Section != null)
            {
                FillDetailsTextBoxes("default", oSR_Section.FromSection_ID, "default", oSR_Section.ToSection_ID, sSR_ID, oSR_Section.IssuedRefNo_ID);
                RefreshGridBySectionSRN_ID(oSR_Section.SectionReqositionNote_ID);                
            }

            tbl_scsStoreReqositionNote oSR_Store = tbl_scsStoreReqositionNote.Select(txtSRNID.Text.Trim());
            if (oSR_Store != null)
            {
                FillDetailsTextBoxes("default", "default", oSR_Store.FromStore_ID, oSR_Store.ToSection_ID, sSR_ID, oSR_Store.IssuedRefNo_ID);
                RefreshGridByStoreSRN_ID(oSR_Store.StoreRecositionNote_ID);                
            }

        }
        private void FillDetailsTextBoxes(string sDepartmentID, string sSectionID, string sStoreID, string sLocationID, string sRequisitionID, string sIssueRefID)
        {
            txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(sDepartmentID));
            txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(sSectionID));
            txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(sStoreID));
            txtLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(sLocationID));

            txtDepartmentID.Tag = sDepartmentID;
            txtSectionID.Tag = sSectionID;
            txtStoreID.Tag = sStoreID;
            txtLocationID.Tag = sLocationID;


            txtSRNID.Text = sRequisitionID;
            txtSRNID.Tag = sRequisitionID;

            //add order ref detail           
            txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_IssuedRefNo(sIssueRefID));
            txtOrderRefNo.Tag = sIssueRefID;
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false); 
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid(string sGINID)
        {
            int iRow;
            dgvDetail.Rows.Clear();

            List<tbl_scsSectionGoodIssueNote_Detail> details = tbl_scsSectionGoodIssueNote_Detail.SelectAllBySectionGoodIssueNote_ID(sGINID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsSectionGoodIssueNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                string sToLocation = clsHelpMethods.GetToLocationName(detail.ToSelectArea_ID, detail.ToDepartment_ID, detail.ToSection_ID, detail.ToStore_ID);
                string sToNoteID = clsHelpMethods.GetSelectAreaNoteID(detail.ToSelectArea_ID, detail.DepartmentReqositionNote_ID, detail.SectionRequisitionNote_ID, detail.StoreRequisitionNote_ID);

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID, detail.ToSelectArea_ID, detail.ToDepartment_ID, detail.ToSection_ID,
                    detail.ToStore_ID, detail.DepartmentReqositionNote_ID, detail.SectionRequisitionNote_ID, detail.StoreRequisitionNote_ID,
                   sToLocation, sToNoteID, detail.Qty, detail.Weight, detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID,
                   detail.ItemSerialNo, detail.ItemSerialNo2, "O", 0, 0, detail.Remark,0);
            }
        }
        private void RefreshGridByJob_ID(string sJob_ID)
        {
            int iRow;
            List<tbl_pmsPrePlan> PrePlans = tbl_pmsPrePlan.SelectAllByProductionJob_ID(sJob_ID);
            foreach (tbl_pmsPrePlan PrePlan in PrePlans)
            {
                #region Inputs
                List<tbl_pmsPrePlan_SectionPath_InputItem> inputs = tbl_pmsPrePlan_SectionPath_InputItem.SelectAllByPrePlan_ID(PrePlan.PrePlan_ID);
                foreach (tbl_pmsPrePlan_SectionPath_InputItem input in inputs)
                {
                    if (input.Section_ID == txtLocationID.Tag.ToString())
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        ValidateEmptyForeignKey();
                        string sToLocation = clsHelpMethods.getToLocationName(txtDepartmentID, txtSectionID, txtStoreID);
                        string sNoteID = "N/A";

                        tbl_genItemMaster item = tbl_genItemMaster.Select(input.Item_ID);
                        if (item != null)
                        {
                            clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, input.Line_No, item.Item_ID, item.Uom_ID, sJob_ID, getSelectAriaID(), txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(),
                                txtStoreID.Tag.ToString(), "default", "default", "default", sToLocation, sNoteID, input.Qty, input.Weight,
                                "default", "default", "0", "0", "N", 0, 0, "",0);
                        }
                    }
                }
                #endregion

                #region Outputs
                List<tbl_pmsPrePlan_SectionPath_OutputItem> outputs = tbl_pmsPrePlan_SectionPath_OutputItem.SelectAllByPrePlan_ID(PrePlan.PrePlan_ID);
                foreach (tbl_pmsPrePlan_SectionPath_OutputItem output in outputs)
                {
                    if (output.Section_ID == txtLocationID.Tag.ToString())
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        ValidateEmptyForeignKey();
                        string sToLocation = clsHelpMethods.getToLocationName(txtDepartmentID, txtSectionID, txtStoreID);
                        string sNoteID = "N/A";
                        tbl_genItemMaster item = tbl_genItemMaster.Select(output.Item_ID);
                        if (item != null)
                        {
                            clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, output.Line_No, item.Item_ID, item.Uom_ID, sJob_ID, getSelectAriaID(), txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(),
                                txtStoreID.Tag.ToString(), "default", "default", "default", sToLocation, sNoteID, output.Qty, output.Weight,
                                "default", "default", "0", "0", "N", 0, 0, "",0);
                        }
                    }
                }
                #endregion

            }
        }
        private void RefreshGridBySectionSRN_ID(string sGIN_ID)
        {
            int iRow;
            List<tbl_scsSectionReqositionNote_Detail> details = tbl_scsSectionReqositionNote_Detail.SelectAllBySectionReqositionNote_ID(sGIN_ID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsSectionReqositionNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                string sFromLocation = clsGenaralName.getName_Section(detail.FromSection_ID);
                string sFromNoteID = detail.SectionReqositionNote_ID;
                decimal dQty = detail.Qty - detail.QtySettle, dWeight = detail.Weight - detail.WeightSettle;

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID, getSelectAriaID(), detail.ToDepartment_ID,
                    detail.ToSection_ID, detail.ToStore_ID, "default", detail.SectionReqositionNote_ID, "default", sFromLocation, sFromNoteID, dQty, dWeight,
                    detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "N", 0, 0, "",0);
            }
        }
        private void RefreshGridByStoreSRN_ID(string sGIN_ID)
        {
            int iRow;
            List<tbl_scsStoreReqositionNote_Detail> details = tbl_scsStoreReqositionNote_Detail.SelectAllByStoreRecositionNote_ID(sGIN_ID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsStoreReqositionNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                string sFromLocation = clsGenaralName.getName_Store(detail.FromStore_ID);
                string sFromNoteID = detail.StoreRecositionNote_ID;
                decimal dQty = detail.Qty - detail.QtySettle, dWeight = detail.Weight - detail.WeightSettle;

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID, getSelectAriaID(), detail.ToDepartment_ID,
                    detail.ToSection_ID, detail.ToStore_ID, "default", "default", detail.StoreRecositionNote_ID, sFromLocation, sFromNoteID, dQty, dWeight,
                    detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "N", detail.UnitPrice, detail.TotalAmount, "",0);
            }
        }
        private void RefreshGridByDepartmentSRN_ID(string sGIN_ID)
        {
           //Pls Do
        }
        private void RefreshGridByItem_ID(string sItem_ID)
        {
            int iRow;
            string sJobID = "default";
            tbl_genItemMaster detail = tbl_genItemMaster.Select(sItem_ID);
            if (detail != null)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                if (txtJobID.Tag != null && clsConfig.bJobIdRequiredGIN)
                    sJobID = txtJobID.Tag.ToString();
                ValidateEmptyForeignKey();
                string sToLocation = clsHelpMethods.getToLocationName(txtDepartmentID, txtSectionID, txtStoreID);
                string sNoteID = "N/A";

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, dgvDetail.Rows.Count, detail.Item_ID, detail.Uom_ID, sJobID, getSelectAriaID(), txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(),
                    txtStoreID.Tag.ToString(), "default", "default", "default", sToLocation, sNoteID, 0, 0,
                    txtItemSubCategory.Tag.ToString(), txtItemSubCategory.Text.Trim(), txtItemSerialNo.Tag.ToString(), txtItemSerialNo.Text.Trim(), "N", 0, 0, "",0);
            }
        }
        #endregion

        #region Events Datagried
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellDoubleClick(sender, e);
        }
        private void dgvDetail_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellDoubleClick(sender, e, dgvDetail);
        }
        private void dgvDetail_CellEndEdit(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellEndEdit(sender, e, dgvDetail);
        }
        private void dgvDetail_CellParsing(object sender, DataGridViewCellParsingEventArgs e)
        {
            clsEvent.StockGrid_CellParsing(sender, e, dgvDetail);
        }
        private void DataGrid_CellMouseMove(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM" || sColName == "ItemSerialNo1")
                {
                    Cursor = Cursors.Hand;
                }
            }
        }
        private void DataGrid_CellMouseLeave(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM" || sColName == "ItemSerialNo1")
                {
                    Cursor = Cursors.Default;
                }
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtGoodreceivedNoteID_DoubleClick(object sender, EventArgs e)
        {
            Search_StoreGoodIssuneNote();
        }
        private void txtJobOder_DoubleClick(object sender, EventArgs e)
        {
            clearItamAndJob();
            Search_JobID();
        }
        private void txtGINNoStore_DoubleClick(object sender, EventArgs e)
        {
            clearItamAndJob();
            loadSRNnumber();
        }
        private void txtLocationID_DoubleClick(object sender, EventArgs e)
        {
            Search_StoreTo();
        }
        private void txtCheckedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }
        private void txtApprovedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }
        private void txtDepartmentID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Department();
        }
        private void txtSectionID_DoubleClick_1(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Section();
        }
        private void txtStoreID_DoubleClick_1(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Store();
        }
        private void txtItemID_DoubleClick(object sender, EventArgs e)
        {
            if (!clsConfig.bJobIdRequiredGIN)
                clearItamAndJob();
            Search_ItemID();
        }
        #endregion

        #region Events KeyDown
        private void txtGoodreceivedNoteID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_StoreGoodIssuneNote();
            }
        }
        private void txtGINNoSection_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SectionStoreReqositionNote();
            }
        }
        private void txtGINNoStore_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearItamAndJob();
                loadSRNnumber();
            }
        }
        private void txtLocationID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_StoreTo();
            }
        }
        private void txtApprovedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_ApprovedBy();
            }
        }
        private void txtCheckedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CheckedBy();
            }
        }
        private void frm_sasStoreGoodReceiveNote_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        private void txtJobOder_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearItamAndJob();
                Search_JobID();
            }
        }
        private void txtDepartmentID_KeyDown_1(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Department();
            }
        }
        private void txtSectionID_KeyDown_1(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Section();
            }
        }
        private void txtStoreID_KeyDown_1(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Store();
            }
        }
        private void txtItemID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                if (!clsConfig.bJobIdRequiredGIN)
                    clearItamAndJob();
                Search_ItemID();
            }
        }

        #endregion




        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtLocationID, "Issuer"))
            {
                if (clsValidate.ValidateTextBox_EmptyValue(txtOrderRefNo, "Issue Ref No"))
                {
                    bStatus = true;
                }
            }
            return bStatus;
        }
        private bool CheckJobNoValidity()
        {
            string  sJobNo = "";//strMessage = "",
            bool bStatus = true;
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                sJobNo = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                if (!clsValidate.GetProductionJobPrePlanValidation(sJobNo))
                {
                    bStatus = false;
                    break;
                }
            }
            if (bStatus == false)
            {
                MessageBox.Show("Job No. " + sJobNo + " should be planned atleast " + clsConfig.sProductionJobPrePlanDates + " days before to proceed.", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            return bStatus;
        }
        private bool CheckJobSelectValidity()
        {
            string strMessage = "";
            bool bStatus = true;
            if (clsConfig.bJobIdRequiredGIN)
            {
                if (txtJobID.Tag == null || txtJobID.Tag.ToString().ToLower() == "default")
                {
                    strMessage += "Job Order ";
                    bStatus = false;
                }
                if (bStatus == false)
                {
                    MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            return bStatus;
        }
        private bool CheckStockValidity()
        {
            #region Comment
            //string strMessage = "", sItemCode = "", sJobCode = "";
            //decimal dWeightActual = 0;
            //decimal dQty = 0;
            //bool bStatus = true;
            //foreach (DataGridViewRow row in dgvDetail.Rows)
            //{
            //    sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "default");
            //    dWeightActual = clsValidate.ValidateGridValue(dgvDetail, "WeightActual", row.Index, decimal.Parse("0.00"));
            //    dQty = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
            //    sJobCode = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");

            //    List<tbl_genSection_Stock> stocks = tbl_genSection_Stock.SelectAllByItem_ID(sItemCode);// Select(txtLocationID.Tag.ToString(), sItemCode,sJobCode);
            //    bool isCheck = false;
            //    foreach (tbl_genSection_Stock stock in stocks)
            //    {
            //        if (stock.Section_ID == txtLocationID.Tag.ToString())
            //        {
            //            isCheck = true;
            //            if (stock.Weight < dWeightActual)
            //            {
            //                strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Not Sufficient Weight in " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
            //                bStatus = false;
            //            }
            //            if (stock.Qty < dQty)
            //            {
            //                strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Not Sufficient Quantity in " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
            //                bStatus = false;
            //            }
            //        }
            //    }
            //    if (!isCheck)
            //    {
            //        strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Not Stock in " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
            //        bStatus = false;
            //    }
            //}
            //if (bStatus == false)
            //{
            //    MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            //}
            //return bStatus; 
            #endregion

            string strMessage = "", sItemCode = "", sJobCode = "";
            decimal dWeight = 0;
            decimal dQty = 0;
            bool bStatus = true;
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "default");
                dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                dQty = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                sJobCode = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");

                if (!clsConfig.bSectionStockWithJobID)
                    sJobCode = "default";
                tbl_genSection_Stock stock = tbl_genSection_Stock.Select(txtLocationID.Tag.ToString(), sItemCode, sJobCode, "default", "default", "0", "0");
                if (stock != null)
                {
                    if (stock.Weight < dWeight)
                    {
                        strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Required Weight Is Not Availabe As IT Is In " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
                        bStatus = false;
                    }
                    if (stock.Qty < dQty)
                    {
                        strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Required Quantity Is Not Availabe As IT Is In " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
                        bStatus = false;
                    }
                }
                else
                {
                    strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Is Not Available In " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + " Stock\n";
                    bStatus = false;
                }
            }
            if (bStatus == false)
            {
                MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
          //  string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception)
            {
                //SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                //MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckValidity_Customer()
        {
            bool bStatus = true;
            try
            {
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    string sJobID = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                    if (sJobID.Length > 0)
                    {
                        tbl_pmsProductionJobRegister job = tbl_pmsProductionJobRegister.Select(sJobID);
                        if (job != null && job.ProductionJob_ID != "default")
                        {
                            tbl_genCustomerMaster customer = tbl_genCustomerMaster.Select(job.Customer_ID);
                            if (customer != null && customer.Customer_ID != "default")
                            {
                                if (customer.IsBlacklisted)
                                {
                                    bStatus = false;
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.CustomerIsBlackListed), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return bStatus;
        }     
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKey()
        {
            clsCommon.ValidateForeignKey(ref txtDepartmentID);
            clsCommon.ValidateForeignKey(ref txtSectionID);
            clsCommon.ValidateForeignKey(ref txtStoreID);
            clsCommon.ValidateForeignKey(ref txtJobID);
            clsCommon.ValidateForeignKey(ref txtItemID);
            clsCommon.ValidateForeignKey(ref txtSRNID);
        }
        #endregion

        #region Search Methods
        private void Search_StoreGoodIssuneNote()
        {
            clsSearch.Search_TransactionSectionGoodIssueNote_Direct(ref txtGoodIssueNoteID, chkShowSettle.Checked);
            if (txtGoodIssueNoteID.Text.Trim().Length > 0)
                FillDetails(txtGoodIssueNoteID.Text);
        }
        private void Search_DepartmentStoreReqositionNote()
        {
            clsSearch.Search_TransactionDepartmentStoreReqositionNote_Use(ref txtSRNID, txtDepartmentID.Tag.ToString());
            if (txtSRNID.TextLength > 0)
                btnAddStore_Click(null, new EventArgs());
        }
        private void Search_SectionStoreReqositionNote()
        {
            clsSearch.Search_TransactionSectionStoreReqositionNote_Use(ref txtSRNID, txtSectionID.Tag.ToString());
            if (txtSRNID.TextLength > 0)
                btnAddStore_Click(null, new EventArgs());
        }
        private void Search_StoreGoodIssueNote()
        {
            clsSearch.Search_TransactionStoreStoreReqositionNote_Use(ref txtSRNID, txtStoreID.Tag.ToString());
            if (txtSRNID.TextLength > 0)
                btnAddStore_Click(null, new EventArgs());
        }
        private void Search_Section()
        {
            clsSearch.Search_MasterSection(ref txtSectionID);
            if (txtSectionID.Tag != null)
                setEnableItems(true);
        }
        private void Search_Store()
        {
            clsSearch.Search_MasterStore(ref txtStoreID, true);
            if (txtStoreID.Tag != null)
                setEnableItems(true);
        }
        private void Search_Department()
        {
            clsSearch.Search_MasterDepartment(ref txtDepartmentID);
            if (txtDepartmentID.Tag != null)
                setEnableItems(true);
        }

        private void Search_StoreTo()
        {
            clsSearch.Search_MasterSection(ref txtLocationID);
        }

       

        private void Search_JobID()
        {
            if (CheckValidity_EmptyField())
                clsSearch.Search_TransactionProductionJobRegister(ref txtJobID);
        }
        private void Search_ItemID()
        {
            if (CheckValidity_EmptyField() && CheckJobSelectValidity())
            {
                string sStoreID = "", sSectionID = "", sDepartmentID = "";
                if (txtLocationID.Tag != null && txtLocationID.Tag.ToString().Trim().Length > 0)
                    sSectionID = txtLocationID.Tag.ToString();

                clsHelpMethods.SearchItemAdvanceStock(ref txtItemID, ref txtItemSubCategory, ref txtItemSerialNo, sStoreID, sSectionID, sDepartmentID);
                if (txtItemID.Tag != null && txtItemID.Tag.ToString().Trim().Length > 0) //call add button
                    btnAddItem_Click(btnAddItem, new EventArgs());
            }
        }
        #endregion

        #region Set Enable/Desable Items
        private void setEnableItems(bool Val)
        {
            clearItamAndJob();
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtItemID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblItem, Val);
            btnAddItem.Enabled = Val;
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtJobID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblJob, Val);
            btnAddJob.Enabled = Val;
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtSRNID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblSRN, Val);
            btnAddSRN.Enabled = Val;
        }
        #endregion

        #region Get Select Aria ID
        private string getSelectAriaID()
        {
            string rtn = "";
            if (txtDepartmentID.Tag != null && txtDepartmentID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Department);
            else if (txtSectionID.Tag != null && txtSectionID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Section);
            else if (txtStoreID.Tag != null && txtStoreID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Store);
            else
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Default);
            return rtn;
        }
        #endregion

    

        #region Load SRN Number
        private void loadSRNnumber()
        {
            //if (CheckValidity())
            //{
            if (txtDepartmentID.Tag != null && txtDepartmentID.Tag.ToString().Trim() != "default")
                    Search_DepartmentStoreReqositionNote();
            else if (txtSectionID.Tag != null && txtSectionID.Tag.ToString().Trim() != "default")
                    Search_SectionStoreReqositionNote();
            else if (txtStoreID.Tag != null && txtStoreID.Tag.ToString().Trim() != "default")
                    Search_StoreGoodIssueNote();
            //}
        }
        #endregion

        #region Send E-Mail
        public void sendEmail()
        {
          //  frmEmail oEmail = new frmEmail();
          //  oEmail.Show();
        }
        #endregion

        #region Cancel Order
        private void cancelOrder()
        {
            try
            {
                if (txtGoodIssueNoteID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_scsSectionGoodIssueNote detail = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text.Trim());
                        if (detail != null)
                        {
                            if (!detail.IsLocked)
                            {
                                if (!detail.IsDeleted)
                                {
                                    if (!detail.IsSeattled)
                                    {
                                        DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForDelete, " GIN : " + detail.SectionGoodIssueNote_ID), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                                        if (msgResult == DialogResult.Yes)
                                        {
                                            detail.ModifiedUser_ID = clsSecurity.UserIDLoged;
                                            detail.DateModified = clsSecurity.getServerDateTime();
                                            detail.IsDeleted = true;
                                            detail.Update();

                                            //Update Other Tables
                                            #region Update Other Tables
                                            List<tbl_scsSectionGoodIssueNote_Detail> details = tbl_scsSectionGoodIssueNote_Detail.SelectAllBySectionGoodIssueNote_ID(detail.SectionGoodIssueNote_ID);
                                            foreach (tbl_scsSectionGoodIssueNote_Detail GINdetail in details)
                                            {
                                                ///Update Stock
                                                //clsHelpMethods.UpdateOrInsertSectionStock(true, true, GINdetail.Item_ID, GINdetail.ItemSubCategory_ID, GINdetail.ItemSubCategory2_ID, GINdetail.ItemSerialNo, GINdetail.ItemSerialNo2,
                                                //    GINdetail.Job_ID, GINdetail.FromSection_ID, GINdetail.Qty, GINdetail.Weight, 0, 0, false, true, true);

                                                ///Unsettle SR - Store
                                                foreach (tbl_scsStoreReqositionNote_Detail srST in tbl_scsStoreReqositionNote_Detail.SelectAllByStoreRecositionNote_ID(GINdetail.StoreRequisitionNote_ID).Where(p => p.Item_ID == GINdetail.Item_ID))
                                                {
                                                    srST.QtySettle = srST.QtySettle - GINdetail.Qty;
                                                    srST.WeightSettle = srST.WeightSettle - GINdetail.Weight;
                                                    srST.Update();
                                                    clsProcessMethods.SetSettle_StoreSR(GINdetail.StoreRequisitionNote_ID);
                                                }
                                                ///Unsettle GIN - Section
                                                foreach (tbl_scsSectionReqositionNote_Detail srSC in tbl_scsSectionReqositionNote_Detail.SelectAllBySectionReqositionNote_ID(GINdetail.SectionRequisitionNote_ID).Where(p => p.Item_ID == GINdetail.Item_ID))
                                                {
                                                    srSC.QtySettle = srSC.QtySettle - GINdetail.Qty;
                                                    srSC.WeightSettle = srSC.WeightSettle - GINdetail.Weight;
                                                    srSC.Update();
                                                    clsProcessMethods.SetSettle_SectionSR(GINdetail.SectionRequisitionNote_ID);
                                                }
                                                ///Unsettle GIN - Department
                                                ///Pls Do
                                            }
                                            #endregion

                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                            ClearFields();
                                        }
                                    }
                                    else
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.GRNdoneForGIN), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                                }
                                else
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AlreadyDeleted), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                            }
                            else
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordLockedCantDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                        }
                    }
                  
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        private void frm_scsSectionGoodIssueNote_FormClosing(object sender, FormClosingEventArgs e)
        {
            Attachments.Close();
        }

        #region User Checked Approve Details
        private void btnChecked_Click(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }

        private void btnApproved_Click(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }

        #region Approved and Checked Search
        private void Search_ApprovedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpGINDate.Value.Date))
                {
                    if (clsSecurity.PermissionToApproved(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtGoodIssueNoteID.Text != null && txtGoodIssueNoteID.TextLength > 0 && txtGoodIssueNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForApproved), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetApproved login = new frmSetApproved();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetApproved.bChecked)
                                {
                                    bHasApproved = true;
                                    glbApprovedDate = clsSecurity.getServerDateTime();
                                    if (IsUpdate)
                                    {
                                        //userDetailsColorChanges();

                                        tbl_scsSectionGoodIssueNote objGIN = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text.Trim());
                                        if (objGIN != null)
                                        {
                                            objGIN.IsApproved = true;
                                            objGIN.DateApproved = clsSecurity.getServerDateTime();
                                            objGIN.ApprovedUser_ID = frmSetApproved.sApprovedUserID;
                                            objGIN.Update();
                                        }
                                    }
                                }
                                else if (frmSetApproved.bReset)
                                    bHasApproved = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Approve", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToApprove), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_CheckedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpGINDate.Value.Date))
                {
                    if (clsSecurity.PermissionToChecked(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtGoodIssueNoteID.Text != null && txtGoodIssueNoteID.TextLength > 0 && txtGoodIssueNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForChecked), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetChecked login = new frmSetChecked();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetChecked.bChecked)
                                {
                                    bHasChecked = true;
                                    glbCheckedDate = clsSecurity.getServerDateTime();

                                    if (IsUpdate)
                                    {
                                   //     userDetailsColorChanges();

                                        tbl_scsSectionGoodIssueNote objGIN = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text.Trim());
                                        if (objGIN != null)
                                        {
                                            objGIN.IsChecked = true;
                                            objGIN.DateChecked = clsSecurity.getServerDateTime();
                                            objGIN.CheckedUser_ID = frmSetChecked.sCheckedUserID;
                                            objGIN.Update();
                                        }
                                    }

                                }
                                else if (frmSetChecked.bReset)
                                    bHasChecked = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Check", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToCheck), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion
        private void btnUserDetails_Click(object sender, EventArgs e)
        {
            if (txtGoodIssueNoteID.Text != "" || txtGoodIssueNoteID.Text != "<Auto Generate>")
            {
                tbl_scsSectionGoodIssueNote detail = tbl_scsSectionGoodIssueNote.Select(txtGoodIssueNoteID.Text);
                if (detail != null)
                {
                    DataTable dt_UserDetails = new DataTable();
                    dt_UserDetails.Columns.Add("usertype", typeof(string));
                    dt_UserDetails.Columns.Add("Column1", typeof(string));
                    dt_UserDetails.Columns.Add("user", typeof(string));
                    dt_UserDetails.Columns.Add("Column2", typeof(string));
                    dt_UserDetails.Columns.Add("datetime", typeof(string));

                    dt_UserDetails.Rows.Add("Created By", ":", clsGenaralName.getName_User(detail.CreateUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateCreate));

                    if (detail.DateCreate != detail.DateModified)
                        dt_UserDetails.Rows.Add("Last Modified By", ":", clsGenaralName.getName_User(detail.ModifiedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateModified));

                    if (detail.IsChecked)
                        dt_UserDetails.Rows.Add("Checked By", ":", clsGenaralName.getName_User(detail.CheckedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateChecked));

                    if (detail.IsApproved)
                        dt_UserDetails.Rows.Add("Approved By", ":", clsGenaralName.getName_User(detail.ApprovedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateApproved));

                    if (detail.IsDeleted)
                        dt_UserDetails.Rows.Add("Cancelled by", ":", clsGenaralName.getName_User(detail.DeletedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateDeleted));

                    Point startPoint = this.PointToScreen(new Point());

                    frmApprovedCheckedValidity frm = new frmApprovedCheckedValidity();
                    frm.ShowWindow(startPoint.X, (startPoint.Y + this.Size.Height), dt_UserDetails);
                }
            }
        }

        #region User Details Color Changes
        //private void userDetailsColorChanges()
        //{
        //    if (bHasApproved)
        //    {
        //        this.btnApproved.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        this.btnChecked.BackColor = System.Drawing.Color.DarkGray;
        //        btnApproved.Enabled = false;
        //        btnChecked.Enabled = false;

        //    }
        //    if (bHasChecked)
        //    {
        //        this.btnChecked.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        btnChecked.Enabled = false;
        //    }
        //    if (!bHasApproved && !bHasChecked)
        //    {
        //        this.btnApproved.ForeColor = System.Drawing.Color.Red;
        //        this.btnChecked.ForeColor = System.Drawing.Color.Red;
        //        this.btnApproved.BackColor = System.Drawing.Color.White;
        //        this.btnChecked.BackColor = System.Drawing.Color.White;
        //        btnApproved.Enabled = true;
        //        btnChecked.Enabled = true;
        //    }
        //}
        #endregion
        #endregion

    }

}