using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_scsSectionRequisitionNote : SEACC_Form
    {
        #region Variables
        //to manage update and insert

        //form manage
        //to keep glob ref no        
        public string glbSRNo = "";

        //for security handle
        //public bool bNoAccess;
        //public bool bHasChecked;
        //public bool bHasApproved;
        //    DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        //    DateTime glbCheckedDate = clsSecurity.getServerDateTime();
        #endregion

        #region Form Load
        public frm_scsSectionRequisitionNote(FormName _enmForm)
        {
            //sFormConfigCode = clsAutocode.getFormConfigCode(FormName.scsSRNSectionStock);
            //iFormID = clsSecurity.getFormID(FormName.scsSRNSectionStock);
            //if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            //{
            //    bNoAccess = true;
            //}
            enmForm = _enmForm;
            InitializeComponent();
            Initialize();
        }
        private void frmCustomerOrder_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            //clsFormatter.setFormatForm(this, "Section Requisition Note [SR]", 3, iFormID);
            ClearFields();
            SetVisibility_ActionButons(true, true, true, true, false, true, true, true, true);
            CusDataGridViewFormat();

            //if the GIN fired by SR   
            if (glbSRNo.Length > 0)
                FillDetails(glbSRNo);
        }
        #endregion       

        #region Btn New
        private void frm_scsSectionRequisitionNote_SF_newButton_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion        

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 0)
                    {
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                        clsHelpMethods.Grid_LineNoChange(dgvDetail);
                    }
                }
            }
            catch (Exception) { }
        }
        #endregion

        #region Btn Save
        private void frm_scsSectionRequisitionNote_SF_saveButton_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (CheckNumberValidity())
                {
                    if (CheckStockValidity())
                    {
                        if (CheckValidity_Customer())
                        {
                            if (clsMethods_GL.CheckValidity_FinancialYear(dtpSRNDate.Value.Date))
                            {
                                if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                                {
                                    if (clsSecurity.permissionToSave_Store(clsSecurity.UserIDLoged, txtStoreID.Tag.ToString(), IsUpdate))
                                    {
                                        try
                                        {
                                            Cursor = Cursors.WaitCursor;
                                            ValidateEmptyForeignKey();

                                            if (IsUpdate)
                                            {
                                                #region Update
                                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordUpdateIsBlock), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                                #endregion
                                            }
                                            else
                                            {
                                                #region Insert
                                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                                    txtSectionRequisitionNoteID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                                //create order ref number
                                                if (txtOrderRefNo.Tag == null || txtOrderRefNo.Tag.ToString().Trim() == "default")
                                                {
                                                    txtOrderRefNo.Tag = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.zIssuedRefNo));
                                                    tbl_zIssuedRefNo orf = new tbl_zIssuedRefNo(txtOrderRefNo.Tag.ToString().Trim(), txtOrderRefNo.Text.Trim());
                                                    orf.Insert();
                                                }

                                                if (clsValidate.CheckValidity_TransactionCodeLength(txtSectionRequisitionNoteID.Text)) //if (txtSectionRequisitionNoteID.Text.Trim().Length > 0)
                                                {
                                                    //Header                                        
                                                    tbl_scsSectionReqositionNote detail = new tbl_scsSectionReqositionNote(txtSectionRequisitionNoteID.Text.Trim(), dtpSRNDate.Value, txtRemark.Text.Trim(),
                                                        txtjobID.Tag.ToString(), txtLocationID.Tag.ToString(), clsHelpMethods.getSelectAreaID(txtDepartmentID, txtSectionID, txtStoreID),
                                                        txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), txtOrderRefNo.Tag.ToString(), "default",
                                                        clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, "default", "default", clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                        clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), glbCheckedDate, glbApprovedDate, bHasChecked, bHasApproved, false, false, false, 0, false, false);
                                                    detail.Insert();

                                                    //Detail                                
                                                    foreach (DataGridViewRow row in dgvDetail.Rows)
                                                    {
                                                        try
                                                        {
                                                            string sItemCode = "", sUom = "default", sJobCode = "", sSelectArea_ID = "", sDepartment_ID = "",
                                                            sSection_ID = "", sStore_ID = "",// sDepartmentNote_ID = "", sSectionNote_ID = "", sStoreNote_ID = "",
                                                            sItemSubCategoryID1 = "", sItemSubCategoryID2 = "", sItemSerialNo1 = "", sItemSerialNo2 = "";
                                                            decimal dWeight = 0, dQuantitiy = 0;
                                                            int iLineNo = 0;

                                                            iLineNo = clsValidate.ValidateGridValue(dgvDetail, "LineNo", row.Index, int.Parse("0"));
                                                            sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "");
                                                            sUom = clsValidate.ValidateGridTag(dgvDetail, "UOM", row.Index, "");
                                                            dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                                                            sJobCode = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                                                            dQuantitiy = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                                                            sSelectArea_ID = clsValidate.ValidateGridValue(dgvDetail, "SelectArea_ID", row.Index, "default");
                                                            sDepartment_ID = clsValidate.ValidateGridValue(dgvDetail, "Department_ID", row.Index, "default");
                                                            sSection_ID = clsValidate.ValidateGridValue(dgvDetail, "Section_ID", row.Index, "default");
                                                            sStore_ID = clsValidate.ValidateGridValue(dgvDetail, "Store_ID", row.Index, "default");
                                                            //  sDepartmentNote_ID = "default";
                                                            //  sSectionNote_ID = "default";
                                                            //  sStoreNote_ID = "default";
                                                            sItemSubCategoryID1 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID1", row.Index, "default");
                                                            sItemSubCategoryID2 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID2", row.Index, "default");
                                                            sItemSerialNo1 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo1", row.Index, "0");
                                                            sItemSerialNo2 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo2", row.Index, "0");

                                                            if (sItemCode.Length > 0)
                                                            {
                                                                tbl_scsSectionReqositionNote_Detail items = new tbl_scsSectionReqositionNote_Detail(iLineNo, txtSectionRequisitionNoteID.Text.Trim(), sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2,
                                                                    sJobCode, txtLocationID.Tag.ToString(), sSelectArea_ID, sDepartment_ID, sSection_ID, sStore_ID, sUom, dQuantitiy, 0, dWeight, 0, 0, 0, "", false);
                                                                items.Insert();
                                                            }
                                                        }
                                                        catch (Exception ex)
                                                        {
                                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                                            SEACCException.Show(ex);
                                                        }
                                                    }

                                                    Attachments.Insert(txtSectionRequisitionNoteID.Text.ToString());

                                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                }
                                                //else
                                                //{
                                                //    MessageBox.Show("Store Requisition Note " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                //}
                                                #endregion
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                            SEACCException.Show(ex);
                                        }
                                        finally
                                        {
                                            Cursor = Cursors.Default;
                                            FillDetails(txtSectionRequisitionNoteID.Text.Trim());
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        #endregion

        #region Btn Print
        private void frm_scsSectionRequisitionNote_SF_printButton_Click(object sender, EventArgs e)
        {
            Print(false);
        }
        #endregion

        #region Btn Draft
        private void frm_scsSectionRequisitionNote_SF_draftButton_Click(object sender, EventArgs e)
        {
            Print(true);
        }
        #endregion

        #region Btn Checked, Approve and User Details
        private void frm_scsSectionRequisitionNote_SF_checkButton_Click(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }

        private void frm_scsSectionRequisitionNote_SF_approveButton_Click(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }

        private void frm_scsSectionRequisitionNote_SF_History_Click(object sender, EventArgs e)
        {
            UserDetails();
        }
        #endregion

        #region Btn Job
        private void BtnJob_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtjobID.Text.Trim().Length > 0)
                {
                    tbl_pmsProductionJobRegister detail = tbl_pmsProductionJobRegister.Select(txtjobID.Text.Trim());
                    if (detail != null)
                    {
                        RefreshGridByJob_ID(detail.ProductionJob_ID);
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        #endregion

        #region Btn Add Item
        private void btnAddItem_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtItemID.Tag != null && txtItemID.Tag.ToString().Trim().Length > 0)
                {
                    tbl_genItemMaster detail = tbl_genItemMaster.Select(txtItemID.Tag.ToString());
                    if (detail != null)
                    {
                        clsCommon.ValidateForeignKey(ref txtItemSubCategory);
                        clsCommon.ValidateForeignKey(ref txtItemSerialNo, "0");
                        RefreshGridByItem_ID(detail.Item_ID);
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        #endregion

        #region Btn IGIN
        private void btnIGIN_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtSectionRequisitionNoteID.Text != "default" && txtSectionRequisitionNoteID.Text.Trim().Length > 0 && txtSectionRequisitionNoteID.Text != "<Auto Generate>")
                {
                    tbl_scsSectionReqositionNote detail = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text.ToString());
                    if (detail != null)
                    {
                        if (!detail.IsSeattled)
                        {
                            if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Store))
                            {
                                //frm_scsStoreGoodIssueNote frmGIN = new frm_scsStoreGoodIssueNote();
                                //if (frmGIN.bNoAccess)
                                //    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption() + " [" + frmGIN.iFormID + "]", MessageBoxButtons.OK, MessageBoxIcon.Information);
                                //else
                                //{
                                //    frmGIN.glbSRNo = detail.SectionReqositionNote_ID;
                                //    frmGIN.MdiParent = this.MdiParent;
                                //    frmGIN.Show();
                                //}

                                frm_scsStoreGoodIssueNote frm = new frm_scsStoreGoodIssueNote(FormName.sasGINTradingStock);
                                clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorStock, (this.Parent as Form).MdiParent);
                            }
                            else if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Section))
                            {
                                frm_scsSectionGoodIssueNote frmGIN = new frm_scsSectionGoodIssueNote();
                                if (frmGIN.bNoAccess)
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption() + " [" + frmGIN.iFormID + "]", MessageBoxButtons.OK, MessageBoxIcon.Information);
                                else
                                {
                                    frmGIN.glbSRNo = detail.SectionReqositionNote_ID;
                                    frmGIN.MdiParent = (this.Parent as Form).MdiParent;
                                    frmGIN.Show();
                                }
                            }
                            else if (detail.ToSelectArea_ID == clsAutocode.getSelectAreaCode(SelectArea.Department))
                            {
                                //Pls Do
                            }

                        }
                        else
                            MessageBox.Show("Already Issued \n\nThis Store Requisition Quantity has already being issued by Good Issue Note(s)", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        #endregion

        #region Btn Option
        private void btnOption_Click(object sender, EventArgs e)
        {
            frmOption op = new frmOption();
            op.ShowDialog();

            if (frmOption.bEMail)
            {
                sendEmail();
            }
            else if (frmOption.bSMS)
            {

            }
            else if (frmOption.bCancel)
            {
                cancelOrder();
            }
            else if (frmOption.bPrint)
            {

            }
            else
            {

            }
        }
        #endregion

        #region Btn Temp
        private void frm_scsSectionRequisitionNote_SF_tempButton_Click(object sender, EventArgs e)
        {
            if (txtSectionRequisitionNoteID.TextLength > 0 && txtSectionRequisitionNoteID.Text != "<Auto Generate>")
            {
                //set the flag and enble the id
                IsUpdate = false;
                lblCancelled.Visible = false;

                clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtSectionRequisitionNoteID, true);
                clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, true);
                clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, true);
                setEnableItems(true);
                clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, true);
                clsCommon.SetEnableDisable_NormalLabel(lblLocationID, true);
                clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, true);

                txtSectionRequisitionNoteID.Tag = null;
                dtpSRNDate.Value = clsSecurity.getServerDateTime();

                txtOrderRefNo.Tag = null;
                txtOrderRefNo.Text = "";

                bHasApproved = false;
                bHasChecked = false;
                userDetailsColorChanges();

                //Reset Primary Key
                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                    txtSectionRequisitionNoteID.Text = "<Auto Generate>";
                else
                    txtSectionRequisitionNoteID.Clear();
                if (txtSectionRequisitionNoteID.Enabled)
                {
                    txtSectionRequisitionNoteID.SelectAll();
                    txtSectionRequisitionNoteID.Focus();
                }

                Attachments.Clear();
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat_New(dgvDetail, clsFormatter.colorGrid, UI_Color);
            //clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColor1, clsFormatter.colorDigiteqTheamColorPsmForColour, clsFormatter.colorDigiteqTheamColorStockBackColour);
            clsHelpMethods.FormatGrid_Stock(dgvDetail);

            //Change Grid Headers
            dgvDetail.Columns["ItemSubCategoryID1"].HeaderText = clsConfig.sItemSubCategory;
            dgvDetail.Columns["GoodsFrom"].HeaderText = "Request From";
            dgvDetail.Columns["Note_ID"].HeaderText = "iSR Number";
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            lblCancelled.Visible = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtSectionRequisitionNoteID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, true);
            setEnableItems(false);
            clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblLocationID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, true);
            btnAddItem.Enabled = false;

            txtLocationID.Tag = null;
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtjobID.Tag = null;
            txtItemID.Tag = null;
            txtItemSubCategory.Tag = null;
            txtItemSerialNo.Tag = null;
            txtOrderRefNo.Tag = null;

            txtItemSerialNo.Clear();
            txtItemSubCategory.Clear();
            txtSectionRequisitionNoteID.Clear();
            txtRemark.Clear();
            txtLocationID.Clear();
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtjobID.Clear();
            txtItemID.Clear();
            txtOrderRefNo.Clear();

            bHasApproved = false;
            bHasChecked = false;
            userDetailsColorChanges();

            chkSettings.Checked = true;
            chkShowSettle.Checked = false;
            dgvDetail.Rows.Clear();
            dtpSRNDate.Value = clsSecurity.getServerDateTime();


            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtSectionRequisitionNoteID.Text = "<Auto Generate>";
            else
                txtSectionRequisitionNoteID.Clear();
            if (txtSectionRequisitionNoteID.Enabled)
            {
                txtSectionRequisitionNoteID.SelectAll();
                txtSectionRequisitionNoteID.Focus();
            }

            Attachments.Clear();
        }
        #endregion

        #region Clear Items and Jobs
        private void clearItamAndJob()
        {
            txtItemID.Tag = null;
            txtjobID.Tag = null;
            txtItemID.Clear();
            txtjobID.Clear();
        }
        #endregion

        #region Clear Location Field
        private void clearLocationFields()
        {
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtjobID.Tag = null;
            txtItemID.Tag = null;
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtjobID.Clear();
            txtItemID.Clear();
            setEnableItems(false);
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_scsSectionReqositionNote detail = tbl_scsSectionReqositionNote.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        if (detail.IsDeleted)
                            lblCancelled.Visible = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtSectionRequisitionNoteID, false);
                        clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, false);
                        clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblLocationID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false);

                        //asign values
                        txtLocationID.Tag = detail.FromSection_ID;
                        txtDepartmentID.Tag = detail.ToDepartment_ID;
                        txtSectionID.Tag = detail.ToSection_ID;
                        txtStoreID.Tag = detail.ToStore_ID;
                        txtjobID.Tag = detail.Job_ID;

                        //fill order detials
                        tbl_zIssuedRefNo order = tbl_zIssuedRefNo.Select(detail.IssuedRefNo_ID);
                        if (order != null)
                        {
                            txtOrderRefNo.Tag = order.IssuedRefNo_ID;
                            txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(order.IssuedRefNo);
                        }

                        txtSectionRequisitionNoteID.Text = detail.SectionReqositionNote_ID;
                        txtRemark.Text = detail.Remark;
                        dtpSRNDate.Value = detail.SectionReqositionNoteDate;
                        txtLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.FromSection_ID));
                        txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(detail.ToDepartment_ID));
                        txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.ToSection_ID));
                        txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(detail.ToStore_ID));
                        txtjobID.Text = clsCommon.GetForeignKeyValue(detail.Job_ID);
                        chkSettings.Checked = false;

                        if (detail.IsApproved)
                        {
                            bHasApproved = true;
                            glbApprovedDate = detail.DateApproved;
                        }
                        if (detail.IsChecked)
                        {
                            bHasChecked = true;
                            glbCheckedDate = detail.DateChecked;
                        }
                        userDetailsColorChanges();

                        //fill item details
                        RefreshGrid(detail.SectionReqositionNote_ID);

                        //Set Flow
                        clsHelpMethods.SetProcessFlow_Stock_Internal(detail.IssuedRefNo_ID, txtFlowSR, txtFlowGIN, txtFlowGRN);

                        Attachments.FillAttachments(sID);
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid(string sSRNID)
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<tbl_scsSectionReqositionNote_Detail> details = tbl_scsSectionReqositionNote_Detail.SelectAllBySectionReqositionNote_ID(sSRNID).ToList(); //.OrderBy(p => p.Line_No)
                foreach (tbl_scsSectionReqositionNote_Detail detail in details)
                {

                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    string sToLocation = clsHelpMethods.GetToLocationName(detail.ToSelectArea_ID, detail.ToDepartment_ID, detail.ToSection_ID, detail.ToStore_ID);
                    string sNoteID = detail.SectionReqositionNote_ID;
                    clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID, detail.ToSelectArea_ID, detail.ToDepartment_ID, detail.ToSection_ID,
                        detail.ToStore_ID, "default", "default", "default", sToLocation, sNoteID, detail.Qty, detail.Weight,
                        detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "O", 0, 0, detail.Remark,0);

                    if (detail.IsLocked)
                        dgvDetail.Rows[iRow].DefaultCellStyle.ForeColor = clsCommon.ColourForLockedRecord;
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        private void RefreshGridByJob_ID(string sJob_ID)
        {
            try
            {
                int iRow;
                List<tbl_pmsPrePlan> PrePlans = tbl_pmsPrePlan.SelectAllByProductionJob_ID(sJob_ID);
                foreach (tbl_pmsPrePlan PrePlan in PrePlans)
                {
                    List<tbl_pmsPrePlan_SectionPath_InputItem> inputs = tbl_pmsPrePlan_SectionPath_InputItem.SelectAllByPrePlan_ID(PrePlan.PrePlan_ID).OrderBy(p => p.Line_No).ToList();
                    foreach (tbl_pmsPrePlan_SectionPath_InputItem input in inputs)
                    {
                        if (input.Section_ID == txtLocationID.Tag.ToString())
                        {
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            ValidateEmptyForeignKey();
                            string sToLocation = clsHelpMethods.getToLocationName(txtDepartmentID, txtSectionID, txtStoreID);
                            string sNoteID = "N/A";
                            ValidateEmptyForeignKey();
                            tbl_genItemMaster item = tbl_genItemMaster.Select(input.Item_ID);
                            if (item != null)
                            {
                                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, input.Line_No, item.Item_ID, item.Uom_ID, sJob_ID, clsHelpMethods.getSelectAreaID(txtDepartmentID, txtSectionID, txtStoreID),
                                    txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), "default", "default", "default", 
                                    sToLocation, sNoteID, input.Qty, input.Weight, "default", "default", "0", "0", "N", 0, 0, "",0);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        private void RefreshGridByItem_ID(string sItem_ID)
        {
            try
            {
                int iRow;
                string sJobID = "default";
                tbl_genItemMaster detail = tbl_genItemMaster.Select(sItem_ID);
                if (detail != null)
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    if (txtjobID.Tag != null && clsConfig.bJobIdRequiredGIN)
                        sJobID = txtjobID.Tag.ToString();
                    ValidateEmptyForeignKey();
                    string sToLocation = clsHelpMethods.getToLocationName(txtDepartmentID, txtSectionID, txtStoreID);
                    string sNoteID = "N/A";

                    clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, dgvDetail.Rows.Count, detail.Item_ID, detail.Uom_ID, sJobID, clsHelpMethods.getSelectAreaID(txtDepartmentID, txtSectionID, txtStoreID),
                        txtDepartmentID.Tag.ToString(), txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), "default", "default", "default", sToLocation, sNoteID, 0, 0,
                         txtItemSubCategory.Tag.ToString(), txtItemSubCategory.Text.Trim(), txtItemSerialNo.Tag.ToString(), txtItemSerialNo.Text.Trim(), "N", 0, 0, "",0);
                }

            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }
        #endregion

        #region Events Datagried
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellDoubleClick(sender, e);
        }
        private void dgvDetail_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellDoubleClick(sender, e, dgvDetail);
        }
        private void dgvDetail_CellEndEdit(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellEndEdit(sender, e, dgvDetail);
        }
        private void dgvDetail_CellParsing(object sender, DataGridViewCellParsingEventArgs e)
        {
            clsEvent.StockGrid_CellParsing(sender, e, dgvDetail);
        }
        private void DataGrid_CellMouseMove(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM")
                {
                    Cursor = Cursors.Hand;
                }
            }
        }
        private void DataGrid_CellMouseLeave(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM")
                {
                    Cursor = Cursors.Default;
                }
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtjobID_DoubleClick(object sender, EventArgs e)
        {
            clearItamAndJob();
            Search_JobID();
        }
        private void txtSectionRequisitionNoteID_DoubleClick(object sender, EventArgs e)
        {
            Search_SectionGoodReceiveNote();
        }

        private void txtItemID_DoubleClick(object sender, EventArgs e)
        {
            if (!clsConfig.bJobIdRequiredGIN)
                clearItamAndJob();
            Search_ItemID();
        }
        private void txtDepartmentID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Department();
        }
        private void txtSectionID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Section();
        }
        private void txtStoreID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Store();
        }
        private void txtLocationID_DoubleClick(object sender, EventArgs e)
        {
            Search_StoreTo();
        }
        private void txtCheckedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }
        private void txtApprovedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }
        #endregion

        #region Events KeyDown
        private void txtSectionRequisitionNoteID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SectionGoodReceiveNote();
            }
        }
        private void txtItemID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                if (!clsConfig.bJobIdRequiredGIN)
                    clearItamAndJob();
                Search_ItemID();
            }
        }
        private void txtjobID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearItamAndJob();
                Search_JobID();
            }
        }
        private void txtDepartmentID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Department();
            }
        }
        private void txtSectionID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Section();
            }
        }
        private void txtStoreID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Store();
            }
        }
        private void txtLocationID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_StoreTo();
            }
        }
        private void txtApprovedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_ApprovedBy();
            }
        }
        private void txtCheckedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CheckedBy();
            }
        }
        private void frm_sasStoreGoodReceiveNote_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtLocationID, "Issuer"))
            {
                if (clsValidate.ValidateTextBox_EmptyValue(txtOrderRefNo, "Issue Ref No"))
                {
                    bStatus = true;
                }
            }
            return bStatus;
        }
        private bool CheckJobSelectValidity()
        {
            string strMessage = "";
            bool bStatus = true;
            if (clsConfig.bJobIdRequiredGIN)
            {
                if (txtjobID.Tag == null || txtjobID.Tag.ToString().ToLower() == "default")
                {
                    strMessage += "Job Order ";
                    bStatus = false;
                }
                if (bStatus == false)
                {
                    MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            return bStatus;
        }
        private bool CheckStockValidity()
        {
            // string strMessage = "", sItemCode = "";
            // decimal dWeightActual = 0;
            bool bStatus = true;
            //try
            //{
            //    foreach (DataGridViewRow row in dgvDetail.Rows)
            //    {
            //        sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "default");
            //        dWeightActual = clsValidate.ValidateGridValue(dgvDetail, "WeightActual", row.Index, decimal.Parse("0.00"));
            //        tbl_genSection_Stock stock = tbl_genSection_Stock.Select(txtLocationID.Tag.ToString(), sItemCode);
            //        if (stock != null)
            //        {
            //            if (stock.AvailableQty < dWeightActual)
            //            {
            //                strMessage += "Item: " + sItemCode + " Not Sufficient Stock in " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
            //                bStatus = false;
            //            }
            //        }
            //        else
            //        {
            //            strMessage += "Item: " + sItemCode + " Not Stock in " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + "\n";
            //            bStatus = false;
            //        }
            //    }
            //    if (bStatus == false)
            //    {
            //        MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            //    }
            //}
            //catch (Exception ex)
            //{
            //    clsValidate.WriteErrorLog("", iFormID,ex);
            //    SEACCException.Show(ex);
            //    return false;
            //}
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckValidity_Customer()
        {
            bool bStatus = true;
            try
            {
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    string sJobID = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                    if (sJobID.Length > 0)
                    {
                        tbl_pmsProductionJobRegister job = tbl_pmsProductionJobRegister.Select(sJobID);
                        if (job != null && job.ProductionJob_ID != "default")
                        {
                            tbl_genCustomerMaster customer = tbl_genCustomerMaster.Select(job.Customer_ID);
                            if (customer != null && customer.Customer_ID != "default")
                            {
                                if (customer.IsBlacklisted)
                                {
                                    bStatus = false;
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.CustomerIsBlackListed), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return bStatus;
        }
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKey()
        {
            clsCommon.ValidateForeignKey(ref txtDepartmentID);
            clsCommon.ValidateForeignKey(ref txtSectionID);
            clsCommon.ValidateForeignKey(ref txtStoreID);
            clsCommon.ValidateForeignKey(ref txtItemID);
            clsCommon.ValidateForeignKey(ref txtjobID);
        }
        #endregion

        #region Search Methods
        private void Search_JobID()
        {
            if (CheckValidity_EmptyField())
                clsSearch.Search_TransactionProductionJobRegister(ref txtjobID);
        }

        private void Search_ItemID()
        {
            if (CheckValidity_EmptyField() && CheckJobSelectValidity())
            {
                clsHelpMethods.SearchItemAdvance(ref txtItemID, ref txtItemSubCategory, ref txtItemSerialNo);
                if (txtItemID.Tag != null && txtItemID.Tag.ToString().Trim().Length > 0) //call add button
                    btnAddItem_Click(btnAddItem, new EventArgs());
            }

        }
        private void Search_SectionGoodReceiveNote()
        {
            clsSearch.Search_TransactionSectionStoreReqositionNote(ref txtSectionRequisitionNoteID, chkShowSettle.Checked);
            if (txtSectionRequisitionNoteID.Text.Trim().Length > 0)
                FillDetails(txtSectionRequisitionNoteID.Text.Trim());
        }
        private void Search_Department()
        {
            clsSearch.Search_MasterDepartment(ref txtDepartmentID);
            if (txtDepartmentID.Tag != null)
                setEnableItems(true);
        }
        private void Search_Section()
        {
            clsSearch.Search_MasterSection(ref txtSectionID);
            if (txtSectionID.Tag != null)
                setEnableItems(true);
        }
        private void Search_Store()
        {
            clsSearch.Search_MasterStore(ref txtStoreID, true);
            if (txtStoreID.Tag != null)
                setEnableItems(true);
        }
        private void Search_StoreTo()
        {
            clsSearch.Search_MasterSection(ref txtLocationID);
        }

        #endregion

        #region Print Method
        private void Print(bool bIsDraft)
        {
            try
            {
                string sDuplicate = "";
                if (txtSectionRequisitionNoteID.Text.Trim().Length > 0 && txtSectionRequisitionNoteID.Text.Trim() != "<Auto Generate>")
                {
                    //update receipt
                    string sCreateUser = "", sCheckedUser = "", sApprovedUser = "";
                    tbl_scsSectionReqositionNote sr = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text.Trim());
                    if (sr != null)
                    {
                        if (!bIsDraft)
                        {
                            if (sr.PrintCount > 0)
                                sDuplicate = "Duplicate Copy " + sr.PrintCount;

                            sr.PrintCount++;
                            sr.Update();
                        }
                        //order.IsLocked = true;
                        sCreateUser = "[ " + clsGenaralName.getName_User(sr.CreateUser_ID) + " ] [ " + sr.DateCreate.ToShortDateString() + " ]";
                        if (sr.CheckedUser_ID != "default")
                            sCheckedUser = "[ " + clsGenaralName.getName_User(sr.CheckedUser_ID) + " ] [ " + sr.DateChecked.ToShortDateString() + " ]";
                        if (sr.ApprovedUser_ID != "default")
                            sApprovedUser = "[ " + clsGenaralName.getName_User(sr.ApprovedUser_ID) + " ] [ " + sr.DateApproved.ToShortDateString() + " ]";
                    }

                    Cursor = Cursors.WaitCursor;
                    string s_Path = "", sReportTitle = "STORE REQUISITION NOTE [SR]", sFormula = "";

                    sFormula = "{vw_rpt_scsSectionRequisitionNote.sectionReqositionNote_ID} = '" + txtSectionRequisitionNoteID.Text.Trim() + "'";

                    ReportDocument RD = new ReportDocument();
                    s_Path = Application.StartupPath.Replace("\\bin\\Debug", "");
                    s_Path += "\\Reports\\SCS\\NotePrinting\\rpt_scsSectionRequisitionNote.rpt";

                    frm_ReportViewer viewer = new frm_ReportViewer();
                    RD.Load(s_Path);
                    clsSecurity.LogonServer(ref RD);
                    RD.Refresh();

                    //RD.DataDefinition.FormulaFields["HeaderTitle"].Text = clsCommon.fncsetstring(sHeaderTitle);
                    RD.DataDefinition.FormulaFields["ReportTitle"].Text = clsCommon.fncsetstring(sReportTitle);
                    RD.DataDefinition.FormulaFields["DateRange"].Text = clsCommon.fncsetstring(clsSecurity.getServerDateTime().ToShortDateString());
                    RD.DataDefinition.FormulaFields["CreateUserName"].Text = clsCommon.fncsetstring(sCreateUser);
                    RD.DataDefinition.FormulaFields["CheckUserName"].Text = clsCommon.fncsetstring(sCheckedUser);
                    RD.DataDefinition.FormulaFields["ApproveUserName"].Text = clsCommon.fncsetstring(sApprovedUser);
                    RD.DataDefinition.FormulaFields["CompanyName"].Text = clsCommon.fncsetstring(clsSecurity.CompanyName);
                    RD.DataDefinition.FormulaFields["CompanyAddress1"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress1);
                    RD.DataDefinition.FormulaFields["CompanyAddress2"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress2);
                    RD.DataDefinition.FormulaFields["DigiteqName"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqName);
                    RD.DataDefinition.FormulaFields["DigiteqEmail"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqEmail);

                    RD.DataDefinition.FormulaFields["DuplicateCopy"].Text = clsCommon.fncsetstring(sDuplicate);
                    RD.DataDefinition.FormulaFields["IsDraft"].Text = bIsDraft ? clsCommon.fncsetstring("DRAFT") : "";
                    RD.DataDefinition.FormulaFields["isDel"].Text = sr.IsDeleted ? clsCommon.fncsetstring("CANCELLED") : "";

                    if (bIsDraft)
                    {
                        if (!clsConfig.isVisibleCompanyInfoInDraftPrint)
                        {
                            RD.DataDefinition.FormulaFields["CompanyName"].Text = "";
                            RD.DataDefinition.FormulaFields["CompanyAddress1"].Text = "";
                            RD.DataDefinition.FormulaFields["CompanyAddress2"].Text = "";
                        }
                    }

                    viewer.crystalReportViewer1.ReportSource = RD;
                    viewer.crystalReportViewer1.SelectionFormula = sFormula;
                    viewer.crystalReportViewer1.Visible = true;
                    viewer.crystalReportViewer1.DisplayToolbar = true;
                    viewer.crystalReportViewer1.CloseView(false);
                    viewer.WindowState = FormWindowState.Maximized;

                    viewer.ShowDialog();

                    RD.Close();
                    RD.Dispose();
                }
                else
                    MessageBox.Show("Please Select the Store Requisition Note To Print Report", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region Set Enable/Desable Items
        private void setEnableItems(bool Val)
        {
            clearItamAndJob();

            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtItemID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblItem, Val);
            btnAddItem.Enabled = Val;
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtjobID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblJob, Val);
            btnAddJob.Enabled = Val;

        }
        #endregion

        #region Send E-Mail
        public void sendEmail()
        {
            //  frmEmail oEmail = new frmEmail();
            //   oEmail.Show();
        }
        #endregion

        #region Cancel Order
        private void cancelOrder()
        {
            try
            {
                if (txtSectionRequisitionNoteID.Text.Trim().Length > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_scsSectionReqositionNote detail = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text.Trim());
                        if (detail != null)
                        {
                            if (!detail.IsLocked)
                            {
                                if (!detail.IsDeleted)
                                {
                                    if (!detail.IsSeattled)
                                    {
                                        DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForDelete, " SR : " + detail.SectionReqositionNote_ID), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                                        if (msgResult == DialogResult.Yes)
                                        {
                                            detail.ModifiedUser_ID = clsSecurity.UserIDLoged;
                                            detail.DateModified = clsSecurity.getServerDateTime();
                                            detail.IsDeleted = true;
                                            detail.Update();
                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                            ClearFields();
                                        }
                                    }
                                    else
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.GINdoneForSRN), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                                }
                                else
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AlreadyDeleted), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                            }
                            else
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordLockedCantDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                        }

                    }

                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region User Checked Approve Details
        #region Approved and Checked Search
        private void Search_ApprovedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpSRNDate.Value.Date))
                {
                    if (clsSecurity.PermissionToApproved(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtSectionRequisitionNoteID.Text != null && txtSectionRequisitionNoteID.TextLength > 0 && txtSectionRequisitionNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForApproved), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetApproved login = new frmSetApproved();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetApproved.bChecked)
                                {
                                    bHasApproved = true;
                                    glbApprovedDate = clsSecurity.getServerDateTime();
                                    if (IsUpdate)
                                    {
                                        userDetailsColorChanges();

                                        tbl_scsSectionReqositionNote objDO = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text.Trim());
                                        if (objDO != null)
                                        {
                                            objDO.IsApproved = true;
                                            objDO.DateApproved = clsSecurity.getServerDateTime();
                                            objDO.ApprovedUser_ID = frmSetApproved.sApprovedUserID;
                                            objDO.Update();
                                        }
                                    }
                                }
                                else if (frmSetApproved.bReset)
                                    bHasApproved = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Approve", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToApprove), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_CheckedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpSRNDate.Value.Date))
                {
                    if (clsSecurity.PermissionToChecked(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtSectionRequisitionNoteID.Text != null && txtSectionRequisitionNoteID.TextLength > 0 && txtSectionRequisitionNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForChecked), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetChecked login = new frmSetChecked();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetChecked.bChecked)
                                {
                                    bHasChecked = true;
                                    glbCheckedDate = clsSecurity.getServerDateTime();

                                    if (IsUpdate)
                                    {
                                        userDetailsColorChanges();

                                        tbl_scsSectionReqositionNote objDO = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text.Trim());
                                        if (objDO != null)
                                        {
                                            objDO.IsChecked = true;
                                            objDO.DateChecked = clsSecurity.getServerDateTime();
                                            objDO.CheckedUser_ID = frmSetChecked.sCheckedUserID;
                                            objDO.Update();
                                        }
                                    }

                                }
                                else if (frmSetChecked.bReset)
                                    bHasChecked = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Check", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToCheck), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        private void UserDetails()
        {
            try
            {
                if (txtSectionRequisitionNoteID.Text != "" || txtSectionRequisitionNoteID.Text != "<Auto Generate>")
                {
                    tbl_scsSectionReqositionNote detail = tbl_scsSectionReqositionNote.Select(txtSectionRequisitionNoteID.Text);
                    if (detail != null)
                    {
                        DataTable dt_UserDetails = new DataTable();
                        dt_UserDetails.Columns.Add("usertype", typeof(string));
                        dt_UserDetails.Columns.Add("Column1", typeof(string));
                        dt_UserDetails.Columns.Add("user", typeof(string));
                        dt_UserDetails.Columns.Add("Column2", typeof(string));
                        dt_UserDetails.Columns.Add("datetime", typeof(string));

                        dt_UserDetails.Rows.Add("Created By", ":", clsGenaralName.getName_User(detail.CreateUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateCreate));

                        if (detail.DateCreate != detail.DateModified)
                            dt_UserDetails.Rows.Add("Last Modified By", ":", clsGenaralName.getName_User(detail.ModifiedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateModified));

                        if (detail.IsChecked)
                            dt_UserDetails.Rows.Add("Checked By", ":", clsGenaralName.getName_User(detail.CheckedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateChecked));

                        if (detail.IsApproved)
                            dt_UserDetails.Rows.Add("Approved By", ":", clsGenaralName.getName_User(detail.ApprovedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateApproved));

                        if (detail.IsDeleted)
                            dt_UserDetails.Rows.Add("Cancelled by", ":", clsGenaralName.getName_User(detail.DeletedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateDeleted));

                        Point startPoint = this.PointToScreen(new Point());

                        frmApprovedCheckedValidity frm = new frmApprovedCheckedValidity();
                        frm.ShowWindow(startPoint.X, (startPoint.Y + this.Size.Height), dt_UserDetails);
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
        }

        #region User Details Color Changes
        //private void userDetailsColorChanges()
        //{
        //    if (bHasApproved)
        //    {
        //        this.btnApproved.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        this.btnChecked.BackColor = System.Drawing.Color.DarkGray;
        //        btnApproved.Enabled = false;
        //        btnChecked.Enabled = false;

        //    }
        //    if (bHasChecked)
        //    {
        //        this.btnChecked.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        btnChecked.Enabled = false;
        //    }
        //    if (!bHasApproved && !bHasChecked)
        //    {
        //        this.btnApproved.ForeColor = System.Drawing.SystemColors.ControlText;
        //        this.btnChecked.ForeColor = System.Drawing.SystemColors.ControlText;
        //        this.btnApproved.BackColor = System.Drawing.Color.LightGray;
        //        this.btnChecked.BackColor = System.Drawing.Color.LightGray;
        //        btnApproved.Enabled = true;
        //        btnChecked.Enabled = true;
        //    }
        //}
        #endregion       
        #endregion

        #region Setting Panel Events
        public override void SettingsClick()
        {
            xSetting.Visible = true;
            xSetting.Focus();
        }

        private void btn_Close_Click(object sender, EventArgs e)
        {
            xSetting.Visible = false;
        }

        private void xSetting_Leave(object sender, EventArgs e)
        {
            xSetting.Visible = false;
        }
        #endregion


    }
}
