using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_scsSectionGoodReceiveNote : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //form manage
        string sFormConfigCode;
        public int iFormID;

        //to keep glob ref no        
        public string glbGRNNo = "", glbGINNo = "";

        //for security handle
        public bool bNoAccess;
        public bool bHasChecked;
        public bool bHasApproved;
        DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        DateTime glbCheckedDate = clsSecurity.getServerDateTime();
        #endregion

        #region Form Load
        public frm_scsSectionGoodReceiveNote()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.scsGRNSectionStock);
            iFormID = clsSecurity.getFormID(FormName.scsGRNSectionStock);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frmCustomerOrder_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format     

            clsFormatter.setFormatForm(this, "Goods Received Note [GRN]", 3, iFormID);
            CusDataGridViewFormat();
            ClearFields();

            //if the SRN fired by GIN
            if (glbGINNo.Length > 0)
            {
                txtGinID.Text = glbGINNo;
                FillDetailsFromGIN(txtGinID.Text.Trim());
            }

            if (glbGRNNo.Length > 0)
                FillDetails(glbGRNNo);

        }
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 0)
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                }
            }
            catch (Exception) { }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (CheckNumberValidity())
                {
                    if (CheckJobNoValidity())
                    {
                        if (CheckValidity_Customer())
                        {
                            if (clsMethods_GL.CheckValidity_FinancialYear(dtpGRNDate.Value.Date))
                            {
                                if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                                {
                                    if (clsSecurity.permissionToSave_Store(clsSecurity.UserIDLoged, txtStoreID.Tag.ToString(), IsUpdate))
                                    {
                                        try
                                        {
                                            Cursor = Cursors.WaitCursor;
                                            ValidateEmptyForeignKey();

                                            if (IsUpdate)  //update records
                                            {
                                                #region Update Code
                                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordUpdateIsBlock), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                                #endregion
                                            }
                                            else  //insert records
                                            {
                                                #region Insert
                                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                                    txtGoodreceivedNoteID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                                //create order ref number
                                                if (txtOrderRefNo.Tag == null || txtOrderRefNo.Tag.ToString().Trim() == "default")
                                                {
                                                    txtOrderRefNo.Tag = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.zIssuedRefNo));
                                                    tbl_zIssuedRefNo orf = new tbl_zIssuedRefNo(txtOrderRefNo.Tag.ToString().Trim(), txtOrderRefNo.Text.Trim());
                                                    orf.Insert();
                                                }

                                                if (clsValidate.CheckValidity_TransactionCodeLength(txtGoodreceivedNoteID.Text)) // if (txtGoodreceivedNoteID.TextLength > 0)
                                                {
                                                    //GRN Header
                                                    tbl_scsSectionGoodReceiveNote detail = new tbl_scsSectionGoodReceiveNote(txtGoodreceivedNoteID.Text.Trim(), dtpGRNDate.Value, txtRemark.Text.Trim(), "default", getSelectAriaID(), getToDepartment(), getToSection(),
                                                        getToStore(), txtLocationID.Tag.ToString(), getDepartmentGIN(), getSectionGIN(), getStoreGIN(), txtOrderRefNo.Tag.ToString(),
                                                        clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, "default", "default", clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                        clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID,
                                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), glbCheckedDate, glbApprovedDate, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                                        bHasChecked, bHasApproved, false, false, false, 0);
                                                    detail.Insert();

                                                    //GRN Detail                                
                                                    foreach (DataGridViewRow row in dgvDetail.Rows)
                                                    {
                                                        try
                                                        {
                                                            string sItemCode = "", sUom = "default", sJobCode = "", sSelectArea_ID = "", sDepartment_ID = "",
                                                                sSection_ID = "", sStore_ID = "", sDepartmentNote_ID = "", sSectionNote_ID = "", sStoreNote_ID = "",
                                                                sItemSubCategoryID1 = "", sItemSubCategoryID2 = "", sItemSerialNo1 = "", sItemSerialNo2 = "";
                                                            decimal dWeight = 0, dQuantity = 0;
                                                            sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "");
                                                            sJobCode = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                                                            sUom = clsValidate.ValidateGridTag(dgvDetail, "UOM", row.Index, "default");
                                                            dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                                                            dQuantity = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                                                            sSelectArea_ID = clsValidate.ValidateGridValue(dgvDetail, "SelectArea_ID", row.Index, "");
                                                            sDepartment_ID = clsValidate.ValidateGridValue(dgvDetail, "Department_ID", row.Index, "");
                                                            sSection_ID = clsValidate.ValidateGridValue(dgvDetail, "Section_ID", row.Index, "");
                                                            sStore_ID = clsValidate.ValidateGridValue(dgvDetail, "Store_ID", row.Index, "");
                                                            sDepartmentNote_ID = clsValidate.ValidateGridValue(dgvDetail, "DepartmentNote_ID", row.Index, "");
                                                            sSectionNote_ID = clsValidate.ValidateGridValue(dgvDetail, "SectionNote_ID", row.Index, "");
                                                            sStoreNote_ID = clsValidate.ValidateGridValue(dgvDetail, "StoreNote_ID", row.Index, "");
                                                            sItemSubCategoryID1 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID1", row.Index, "default");
                                                            sItemSubCategoryID2 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID2", row.Index, "default");
                                                            sItemSerialNo1 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo1", row.Index, "0");
                                                            sItemSerialNo2 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo2", row.Index, "0");

                                                            if (sItemCode.Length > 0)
                                                            {
                                                                tbl_scsSectionGoodReceiveNote_Detail items = new tbl_scsSectionGoodReceiveNote_Detail(clsHelpMethods.GetMaxzimumLineNoSectionGoodReceiveNote(txtGoodreceivedNoteID.Text.Trim()), txtGoodreceivedNoteID.Text.Trim(),
                                                                    sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, sJobCode, sSelectArea_ID,
                                                                   sDepartment_ID, sSection_ID, sStore_ID, txtLocationID.Tag.ToString(), sDepartmentNote_ID, sSectionNote_ID, sStoreNote_ID,
                                                                   sUom, dQuantity, 0, dWeight, 0, 0, 0, "", false);
                                                                items.Insert();

                                                                ////Update Store Stock                                                           
                                                                //clsHelpMethods.UpdateOrInsertSectionStock(clsConfig.bStockValidateQty_iGRN, clsConfig.bStockValidateWeight_iGRN, sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2,
                                                                //   sJobCode, txtLocationID.Tag.ToString(), dQuantity, dWeight, 0, 0, false, true, true);

                                                                //update GIN 
                                                                #region Update GIN Status
                                                                string sGinID = clsHelpMethods.GetSelectAreaNoteID(sSelectArea_ID, sDepartmentNote_ID, sSectionNote_ID, sStoreNote_ID);
                                                                if (clsAutocode.getSelectAreaCode(SelectArea.Department) == sSelectArea_ID)
                                                                {
                                                                    //Pls Do
                                                                }
                                                                else if (clsAutocode.getSelectAreaCode(SelectArea.Section) == sSelectArea_ID)
                                                                {
                                                                    tbl_scsSectionGoodIssueNote_Detail GIN = tbl_scsSectionGoodIssueNote_Detail.Select(sGinID, sItemCode, sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2);
                                                                    if (GIN != null)
                                                                    {
                                                                        GIN.QtySettle += dQuantity;
                                                                        GIN.WeightSettle += dWeight;
                                                                        GIN.Update();
                                                                        clsProcessMethods.SetSettle_SectionGIN(sGinID);
                                                                    }
                                                                }
                                                                else if (clsAutocode.getSelectAreaCode(SelectArea.Store) == sSelectArea_ID)
                                                                {
                                                                    foreach (tbl_scsStoreGoodIssueNote_Detail GIN in tbl_scsStoreGoodIssueNote_Detail.SelectAllByStoreGoodIssueNote_ID(sGinID).Where(p => p.Item_ID == sItemCode))
                                                                    {
                                                                        GIN.QtySettle += dQuantity;
                                                                        GIN.WeightSettle += dWeight;
                                                                        GIN.Update();
                                                                        clsProcessMethods.SetSettle_StoreGIN(sGinID);
                                                                    }
                                                                }
                                                                #endregion
                                                            }
                                                        }
                                                        catch (Exception ex)
                                                        {
                                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                                            SEACCException.Show(ex);
                                                        }
                                                    }

                                                    Attachments.Insert(txtGoodreceivedNoteID.Text.ToString());

                                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                }
                                                //else
                                                //{
                                                //    MessageBox.Show("Good Receive Note " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                                //}
                                                #endregion
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            clsValidate.WriteErrorLog("", iFormID, ex);
                                            SEACCException.Show(ex);
                                        }
                                        finally
                                        {
                                            Cursor = Cursors.Default;
                                            tbl_scsSectionGoodReceiveNote oldRecord = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text.Trim());
                                            if (oldRecord != null)
                                                FillDetails(txtGoodreceivedNoteID.Text.Trim());
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        #endregion

        #region Btn Print
        private void btnPrint_Click(object sender, EventArgs e)
        {
            try
            {
                bool isDuplicate = false;
                if (txtGoodreceivedNoteID.Text.Trim().Length > 0 && txtGoodreceivedNoteID.Text.Trim() != "<Auto Generate>")
                {
                    //update receipt
                    string sCreateUser = "", sCheckedUser = "", sApprovedUser = "";
                    tbl_scsSectionGoodReceiveNote grn = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text.Trim());
                    if (grn != null)
                    {
                        if (grn.PrintCount > 0)
                            isDuplicate = true;

                        grn.PrintCount++;
                        //order.IsLocked = true;
                        sCreateUser = "[ " + clsGenaralName.getName_User(grn.CreateUser_ID) + " ] [ " + grn.DateCreate.ToShortDateString() + " ]";
                        if (grn.CheckedUser_ID != "default")
                            sCheckedUser = "[ " + clsGenaralName.getName_User(grn.CheckedUser_ID) + " ] [ " + grn.DateChecked.ToShortDateString() + " ]";
                        if (grn.ApprovedUser_ID != "default")
                            sApprovedUser = "[ " + clsGenaralName.getName_User(grn.ApprovedUser_ID) + " ] [ " + grn.DateApproved.ToShortDateString() + " ]";
                        grn.Update();
                    }

                    Cursor = Cursors.WaitCursor;
                    string s_Path = "", sReportTitle = "GOODS RECEIVED NOTE [GRN]", sFormula = "";

                    sFormula = "{vw_rpt_scsSectionGoodReceiveNote.sectionGoodReceiveNote_ID} = '" + txtGoodreceivedNoteID.Text.Trim() + "'";

                    ReportDocument RD = new ReportDocument();
                    s_Path = Application.StartupPath.Replace("\\bin\\Debug", "");
                    s_Path += "\\reports\\rpt_scsSectionGoodReceiveNote.rpt";

                    frm_ReportViewer viewer = new frm_ReportViewer();
                    RD.Load(s_Path);
                    clsSecurity.LogonServer(ref RD);
                    RD.Refresh();

                    //RD.DataDefinition.FormulaFields["HeaderTitle"].Text = clsCommon.fncsetstring(sHeaderTitle);
                    RD.DataDefinition.FormulaFields["ReportTitle"].Text = clsCommon.fncsetstring(sReportTitle);
                    RD.DataDefinition.FormulaFields["DateRange"].Text = clsCommon.fncsetstring(clsSecurity.getServerDateTime().ToShortDateString());
                    RD.DataDefinition.FormulaFields["CreateUserName"].Text = clsCommon.fncsetstring(sCreateUser);
                    RD.DataDefinition.FormulaFields["CheckUserName"].Text = clsCommon.fncsetstring(sCheckedUser);
                    RD.DataDefinition.FormulaFields["ApproveUserName"].Text = clsCommon.fncsetstring(sApprovedUser);
                    RD.DataDefinition.FormulaFields["CompanyName"].Text = clsCommon.fncsetstring(clsSecurity.CompanyName);
                    RD.DataDefinition.FormulaFields["CompanyAddress1"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress1);
                    RD.DataDefinition.FormulaFields["CompanyAddress2"].Text = clsCommon.fncsetstring(clsSecurity.CompanyAddress2);
                    RD.DataDefinition.FormulaFields["DigiteqName"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqName);
                    RD.DataDefinition.FormulaFields["DigiteqEmail"].Text = clsCommon.fncsetstring(clsSecurity.DigiteqEmail);
                    if (isDuplicate)
                        RD.DataDefinition.FormulaFields["DuplicateCopy"].Text = clsCommon.fncsetstring("Duplicate Copy");

                    viewer.crystalReportViewer1.ReportSource = RD;
                    viewer.crystalReportViewer1.SelectionFormula = sFormula;
                    viewer.crystalReportViewer1.Visible = true;
                    viewer.crystalReportViewer1.DisplayToolbar = true;
                    viewer.crystalReportViewer1.CloseView(false);
                    viewer.WindowState = FormWindowState.Maximized;

                    viewer.ShowDialog();

                    RD.Close();
                    RD.Dispose();
                }
                else
                    MessageBox.Show("Please Select the Goods Received Note To Print Report", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region Btn Add GIN
        private void btnAddStore_Click(object sender, EventArgs e)
        {
            if (txtGinID.Text.Trim().Length > 0)
            {
                FillDetailsFromGIN(txtGinID.Text.Trim());
            }
        }
        #endregion

        #region Btn Option
        private void btnOption_Click(object sender, EventArgs e)
        {
            frmOption op = new frmOption();
            op.ShowDialog();

            if (frmOption.bEMail)
            {
                sendEmail();
            }
            else if (frmOption.bSMS)
            {

            }
            else if (frmOption.bCancel)
            {
                cancelOrder();
            }
            else if (frmOption.bPrint)
            {

            }
            else
            {

            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColor1, clsFormatter.colorDigiteqTheamColorPsmForColour, clsFormatter.colorDigiteqTheamColorStockBackColour);
            clsHelpMethods.FormatGrid_Stock(dgvDetail);

            //Change Grid Headers
            dgvDetail.Columns["ItemSubCategoryID1"].HeaderText = clsConfig.sItemSubCategory;
            dgvDetail.Columns["GoodsFrom"].HeaderText = "Issued From";
            dgvDetail.Columns["Note_ID"].HeaderText = "iGIN Number";
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            lblCancelled.Visible = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtGoodreceivedNoteID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblLocationID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, true);

            setEnableItems(false);

            txtLocationID.Tag = null;
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtGinID.Tag = null;
            txtOrderRefNo.Tag = null;

            clearLocationFields();
            txtGoodreceivedNoteID.Clear();
            txtRemark.Clear();
            txtLocationID.Clear();
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtGinID.Clear();
            txtOrderRefNo.Clear();

            bHasApproved = false;
            bHasChecked = false;
            //   userDetailsColorChanges();

            chkSettings.Checked = true;
            chkShowSettle.Checked = false;
            dgvDetail.Rows.Clear();
            dtpGRNDate.Value = clsSecurity.getServerDateTime();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtGoodreceivedNoteID.Text = "<Auto Generate>";
            else
                txtGoodreceivedNoteID.Clear();
            if (txtGoodreceivedNoteID.Enabled)
            {
                txtGoodreceivedNoteID.SelectAll();
                txtGoodreceivedNoteID.Focus();
            }

            Attachments.Clear();
        }
        #endregion


        #region Clear Location Field
        private void clearLocationFields()
        {
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtGinID.Tag = null;
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtGinID.Clear();
            setEnableItems(false);
        }
        #endregion

        #region Clear Items and Jobs
        private void clearItamAndJob()
        {
            txtGinID.Tag = null;
            txtGinID.Clear();

        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_scsSectionGoodReceiveNote detail = tbl_scsSectionGoodReceiveNote.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    if (detail.IsDeleted)
                        lblCancelled.Visible = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtGoodreceivedNoteID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtLocationID, false);
                    clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblGoodreceivedNoteID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblLocationID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false);


                    string sFromNoteID = clsHelpMethods.GetSelectAreaNoteID(detail.FromSelectArea_ID, detail.DepartmentGoodIssueNote_ID, detail.SectionGoodIssueNote_ID, detail.StoreGoodIssueNote_ID);


                    txtLocationID.Tag = detail.ToSection_ID;
                    txtDepartmentID.Tag = detail.FromDepartment_ID;
                    txtSectionID.Tag = detail.FromSection_ID;
                    txtStoreID.Tag = detail.FromStore_ID;
                    txtGinID.Tag = sFromNoteID;
                    txtJobIDTemp.Tag = detail.Job_ID;

                    //fill order detials
                    tbl_zIssuedRefNo order = tbl_zIssuedRefNo.Select(detail.IssuedRefNo_ID);
                    if (order != null)
                    {
                        txtOrderRefNo.Tag = order.IssuedRefNo_ID;
                        txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_OrderRefNo(order.IssuedRefNo));
                    }

                    txtGoodreceivedNoteID.Text = detail.SectionGoodReceiveNote_ID;
                    txtRemark.Text = detail.Remark;
                    dtpGRNDate.Value = detail.SectionGoodReceiveNoteDate;
                    txtLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.ToSection_ID));
                    txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(detail.FromDepartment_ID));
                    txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.FromSection_ID));
                    txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(detail.FromStore_ID));
                    txtGinID.Text = sFromNoteID; // clsCommon.GetForeignKeyValue(detail.StoreGoodIssueNote_ID);
                    txtJobIDTemp.Text = clsCommon.GetForeignKeyValue(detail.Job_ID);
                    chkSettings.Checked = false;

                    if (detail.IsApproved)
                    {
                        bHasApproved = true;
                        glbApprovedDate = detail.DateApproved;
                    }
                    if (detail.IsChecked)
                    {
                        bHasChecked = true;
                        glbCheckedDate = detail.DateChecked;
                    }
                    //userDetailsColorChanges();

                    //fill item details
                    RefreshGrid(detail.SectionGoodReceiveNote_ID);

                    //Set Flow
                    clsHelpMethods.SetProcessFlow_Stock_Internal(detail.IssuedRefNo_ID, txtFlowSR, txtFlowGIN, txtFlowGRN);

                    Attachments.FillAttachments(sID);
                }
            }
        }
        private void FillDetailsFromGIN(string sGIN_ID)
        {
            tbl_scsDepartmentGoodIssueNote oSR_Department = tbl_scsDepartmentGoodIssueNote.Select(sGIN_ID);
            if (oSR_Department != null)
            {
                //FillDetailsTextBoxes(oSR_Department.FromDepartment_ID, "default", "default", oSR_Department.ToStore_ID, glbSRNo, oSR_Department.IssuedRefNo_ID);
                //RefreshGridByDepartmentSRN_ID(oSR_Department.DepartmentReqositionNote_ID);
            }

            tbl_scsSectionGoodIssueNote oGIN_Section = tbl_scsSectionGoodIssueNote.Select(sGIN_ID);
            if (oGIN_Section != null)
            {
                FillDetailsTextBoxes("default", oGIN_Section.FromSection_ID, "default", oGIN_Section.ToSection_ID, sGIN_ID, oGIN_Section.IssuedRefNo_ID);
                RefreshGridBySectionGIN_ID(oGIN_Section.SectionGoodIssueNote_ID);
            }

            tbl_scsStoreGoodIssueNote oGIN_Store = tbl_scsStoreGoodIssueNote.Select(txtGinID.Text.Trim());
            if (oGIN_Store != null)
            {
                FillDetailsTextBoxes("default", "default", oGIN_Store.FromStore_ID, oGIN_Store.ToSection_ID, sGIN_ID, oGIN_Store.IssuedRefNo_ID);
                RefreshGridByStoreGIN_ID(oGIN_Store.StoreGoodIssueNote_ID);
            }
        }
        private void FillDetailsTextBoxes(string sDepartmentID, string sSectionID, string sStoreID, string sLocationID, string sGIN_ID, string sIssueRefID)
        {
            txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(sDepartmentID));
            txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(sSectionID));
            txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(sStoreID));
            txtLocationID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(sLocationID));

            txtDepartmentID.Tag = sDepartmentID;
            txtSectionID.Tag = sSectionID;
            txtStoreID.Tag = sStoreID;
            txtLocationID.Tag = sLocationID;

            txtGinID.Text = sGIN_ID;
            txtGinID.Tag = sGIN_ID;

            //add order ref detail           
            txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_IssuedRefNo(sIssueRefID));
            txtOrderRefNo.Tag = sIssueRefID;
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid(string sGRNID)
        {
            int iRow;
            dgvDetail.Rows.Clear();

            List<tbl_scsSectionGoodReceiveNote_Detail> details = tbl_scsSectionGoodReceiveNote_Detail.SelectAllBySectionGoodReceiveNote_ID(sGRNID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsSectionGoodReceiveNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                string sFromLocation = clsHelpMethods.GetToLocationName(detail.FromSelectArea_ID, detail.FromDepartment_ID, detail.FromSection_ID, detail.FromStore_ID);
                string sFromNoteID = clsHelpMethods.GetSelectAreaNoteID(detail.FromSelectArea_ID, detail.DepartmentGoodIssueNote_ID, detail.SectionGoodIssueNote_ID, detail.StoreGoodIssueNote_ID);

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID, detail.FromSelectArea_ID,
                    detail.FromDepartment_ID, detail.FromSection_ID, detail.FromStore_ID, detail.DepartmentGoodIssueNote_ID,
                    detail.SectionGoodIssueNote_ID, detail.StoreGoodIssueNote_ID, sFromLocation, sFromNoteID, detail.Qty, detail.Weight,
                    detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "O", 0, 0, detail.Remark,0);
                if (detail.IsLocked)
                    dgvDetail.Rows[iRow].DefaultCellStyle.ForeColor = clsCommon.ColourForLockedRecord;
            }
        }
        private void RefreshGridByDepartmentGIN_ID(string sGIN_ID)
        {
            //Pls Do
        }
        private void RefreshGridBySectionGIN_ID(string sGIN_ID)
        {
            int iRow;
            List<tbl_scsSectionGoodIssueNote_Detail> details = tbl_scsSectionGoodIssueNote_Detail.SelectAllBySectionGoodIssueNote_ID(sGIN_ID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsSectionGoodIssueNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                ValidateEmptyForeignKey();
                string sFromLocation = clsGenaralName.getName_Section(detail.FromSection_ID);
                string sFromNoteID = detail.SectionGoodIssueNote_ID;
                decimal dQty = detail.Qty - detail.QtySettle, dWeight = detail.Weight - detail.WeightSettle;

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID,
                    clsAutocode.getSelectAreaCode(SelectArea.Section), "default", detail.FromSection_ID,
                    "default", "default", detail.SectionGoodIssueNote_ID, "default", sFromLocation, sFromNoteID, dQty, dWeight,
                    detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "N", 0, 0, "",0);
            }
        }
        private void RefreshGridByStoreGIN_ID(string sGIN_ID)
        {
            int iRow;
            List<tbl_scsStoreGoodIssueNote_Detail> details = tbl_scsStoreGoodIssueNote_Detail.SelectAllByStoreGoodIssueNote_ID(sGIN_ID).OrderBy(p => p.Line_No).ToList();
            foreach (tbl_scsStoreGoodIssueNote_Detail detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                ValidateEmptyForeignKey();
                string sFromLocation = clsGenaralName.getName_Section(detail.FromStore_ID);
                string sFromNoteID = detail.StoreGoodIssueNote_ID;
                decimal dQty = detail.Qty - detail.QtySettle, dWeight = detail.Weight - detail.WeightSettle;

                clsHelpMethods.Fill_StockDatagrid(dgvDetail, iRow, detail.Line_No, detail.Item_ID, detail.Uom_ID, detail.Job_ID,
                    clsAutocode.getSelectAreaCode(SelectArea.Store), "default", "default",
                    detail.FromStore_ID, "default", "default", detail.StoreGoodIssueNote_ID, sFromLocation, sFromNoteID, dQty, dWeight,
                    detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2, "N", 0, 0, "",0);
            }
        }
        #endregion

        #region Events Datagried
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellDoubleClick(sender, e);
        }
        private void dgvDetail_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellDoubleClick(sender, e, dgvDetail);
        }
        private void dgvDetail_CellEndEdit(object sender, DataGridViewCellEventArgs e)
        {
            clsEvent.StockGrid_CellEndEdit(sender, e, dgvDetail);
        }
        private void dgvDetail_CellParsing(object sender, DataGridViewCellParsingEventArgs e)
        {
            clsEvent.StockGrid_CellParsing(sender, e, dgvDetail);
        }
        private void DataGrid_CellMouseMove(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM" || sColName == "ItemSerialNo1")
                {
                    Cursor = Cursors.Hand;
                }
            }
        }
        private void DataGrid_CellMouseLeave(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                DataGridView dgv = (DataGridView)sender;
                if (e.ColumnIndex >= 0)
                    sColName = dgv.Columns[e.ColumnIndex].Name;


                if (sColName == "ItemCode" || sColName == "ItemName" || sColName == "ItemSubCategoryID1" || sColName == "GoodsFrom" || sColName == "Note_ID" || sColName == "UOM" || sColName == "ItemSerialNo1")
                {
                    Cursor = Cursors.Default;
                }
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtGoodreceivedNoteID_DoubleClick(object sender, EventArgs e)
        {
            Search_SectionGoodReceiveNote();
        }
        private void txtDepartmentID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Department();
        }
        private void txtSectionID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Section();
        }
        private void txtStoreID_DoubleClick(object sender, EventArgs e)
        {
            clearLocationFields();
            Search_Store();
        }
        private void txtGINNoStore_DoubleClick(object sender, EventArgs e)
        {
            clearItamAndJob();
            loadGINnumber();
        }
        private void txtLocationID_DoubleClick(object sender, EventArgs e)
        {
            Search_SectionTo();
        }
        private void txtCheckedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }
        private void txtApprovedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }
        #endregion

        #region Events KeyDown  
        private void txtGoodreceivedNoteID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SectionGoodReceiveNote();
            }
        }
        private void txtDepartmentID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Department();
            }
        }
        private void txtSectionID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Section();
            }
        }
        private void txtStoreID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearLocationFields();
                Search_Store();
            }
        }
        private void txtGINNoStore_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clearItamAndJob();
                loadGINnumber();
            }
        }
        private void txtLocationID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SectionTo();
            }
        }
        private void txtApprovedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_ApprovedBy();
            }
        }

        private void txtCheckedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CheckedBy();
            }
        }

        private void frm_sasStoreGoodReceiveNote_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }

        #endregion

        #region Events KeyUp

        #endregion

        #region Calcualte Values
        private decimal GetTotalPrice(decimal dPrice, decimal dQuantity)
        {
            decimal dTotalPrice = 0;
            dTotalPrice = dPrice * dQuantity;
            return dTotalPrice;
        }
        #endregion

        #region Check Validity
        private bool CheckJobNoValidity()
        {
            string sJobNo = "";//strMessage = "",
            bool bStatus = true;
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                sJobNo = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                if (!clsValidate.GetProductionJobPrePlanValidation(sJobNo))
                {
                    bStatus = false;
                    break;
                }
            }
            if (bStatus == false)
            {
                MessageBox.Show("Job No. " + sJobNo + " should be planned atleast " + clsConfig.sProductionJobPrePlanDates + " days before to proceed.", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtLocationID, "Receiver"))
            {
                bStatus = true;
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            // string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception)
            {
                //SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                //MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckStockValidityWhenRemove(string sNoteID)
        {
            string strMessage = "", sItemCode = "", sJobCode = "";
            decimal dWeightActual = 0;
            decimal dQty = 0;
            bool bStatus = true;

            List<tbl_scsSectionGoodReceiveNote_Detail> details = tbl_scsSectionGoodReceiveNote_Detail.SelectAllBySectionGoodReceiveNote_ID(sNoteID);
            foreach (tbl_scsSectionGoodReceiveNote_Detail GRNdetail in details)
            {
                sItemCode = GRNdetail.Item_ID;
                dWeightActual = GRNdetail.Weight;
                dQty = GRNdetail.Qty;
                sJobCode = GRNdetail.Job_ID;
                if (!clsConfig.bSectionStockWithJobID)
                    sJobCode = "default";

                tbl_genSection_Stock stock = tbl_genSection_Stock.Select(txtLocationID.Tag.ToString(), sItemCode, sJobCode, "default", "default", "0", "0");
                if (stock != null)
                {
                    if (stock.Weight < dWeightActual)
                    {
                        strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Stocks-in-hand is Not Sufficient Weight to Cancel this note \n";
                        bStatus = false;
                    }
                    if (stock.Qty < dQty)
                    {
                        strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Stocks-in-hand is Not Sufficient Quantity to Cancel this note \n";
                        bStatus = false;
                    }
                }
                else
                {
                    strMessage += "Item: " + clsGenaralName.getName_Item(sItemCode) + " Is Not Available In " + clsGenaralName.getName_Section(txtLocationID.Tag.ToString()) + " Stock\n";
                    bStatus = false;
                }
            }

            if (bStatus == false)
            {
                MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckValidity_Customer()
        {
            bool bStatus = true;
            try
            {
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    string sJobID = clsValidate.ValidateGridValue(dgvDetail, "JobCode", row.Index, "default");
                    if (sJobID.Length > 0)
                    {
                        tbl_pmsProductionJobRegister job = tbl_pmsProductionJobRegister.Select(sJobID);
                        if (job != null && job.ProductionJob_ID != "default")
                        {
                            tbl_genCustomerMaster customer = tbl_genCustomerMaster.Select(job.Customer_ID);
                            if (customer != null && customer.Customer_ID != "default")
                            {
                                if (customer.IsBlacklisted)
                                {
                                    bStatus = false;
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.CustomerIsBlackListed), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
            return bStatus;
        }
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKey()
        {
            clsCommon.ValidateForeignKey(ref txtDepartmentID);
            clsCommon.ValidateForeignKey(ref txtSectionID);
            clsCommon.ValidateForeignKey(ref txtStoreID);
            clsCommon.ValidateForeignKey(ref txtGinID);
        }
        #endregion

        #region Search Methods
        private void Search_SectionGoodReceiveNote()
        {
            clsSearch.Search_TransactionSectionGoodReceiveNote_Direct(ref txtGoodreceivedNoteID, chkShowSettle.Checked);
            if (txtGoodreceivedNoteID.Text.Trim().Length > 0)
            {
                FillDetails(txtGoodreceivedNoteID.Text.Trim());
            }
        }

        private void Search_Department()
        {
            clsSearch.Search_MasterDepartment(ref txtDepartmentID);
            if (txtDepartmentID.Tag != null)
                setEnableItems(true);
        }
        private void Search_DepartmentGoodIssueNote()
        {
            clsSearch.Search_TransactionDepartmentGoodIssueNoteByDepartmentID(ref txtGinID, txtDepartmentID.Tag.ToString(), txtLocationID.Tag.ToString());
        }
        private void Search_Section()
        {
            clsSearch.Search_MasterSection(ref txtSectionID);
            if (txtSectionID.Tag != null)
                setEnableItems(true);
        }

        private void Search_SectionGoodIssueNote()
        {
            clsSearch.Search_TransactionSectionGoodIssueNoteBySectionID(ref txtGinID, txtSectionID.Tag.ToString(), txtLocationID.Tag.ToString());
        }

        private void Search_Store()
        {
            clsSearch.Search_MasterStore(ref txtStoreID, true);
            if (txtStoreID.Tag != null)
                setEnableItems(true);
        }
        private void Search_SectionTo()
        {
            clsSearch.Search_MasterSection(ref txtLocationID);
        }

        private void Search_StoreGoodIssueNote()
        {
            clsSearch.Search_TransactionStoreGoodIssueNoteBySectionID(ref txtGinID, txtStoreID.Tag.ToString(), txtLocationID.Tag.ToString());
        }
        #endregion

        #region Set Enable/Desable Items
        private void setEnableItems(bool Val)
        {
            clearItamAndJob();
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtItemIDTemp, false);
            clsCommon.SetEnableDisable_NormalLabel(lblItemTemp, false);
            btnAddItemTemp.Enabled = false;
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtJobIDTemp, false);
            clsCommon.SetEnableDisable_NormalLabel(lblJobTemp, false);
            btnAddJobTemp.Enabled = false;
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtGinID, Val);
            clsCommon.SetEnableDisable_NormalLabel(lblGIN, Val);
            btnAddGIN.Enabled = Val;
        }
        #endregion

        #region Get Select Aria ID
        private string getSelectAriaID()
        {
            string rtn = "";
            if (txtDepartmentID.Tag != null && txtDepartmentID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Department);
            else if (txtSectionID.Tag != null && txtSectionID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Section);
            else if (txtStoreID.Tag != null && txtStoreID.Tag.ToString() != "default")
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Store);
            else
                rtn = clsAutocode.getSelectAreaCode(SelectArea.Default);
            return rtn;
        }
        #endregion

        #region Get Select To Location
        private string getSelectToLocationID()
        {
            string rtn = "";
            if (txtDepartmentID.Tag != null)
                rtn = clsGenaralName.getName_Department(txtDepartmentID.Tag.ToString());
            else if (txtSectionID.Tag != null)
                rtn = clsGenaralName.getName_Section(txtSectionID.Tag.ToString());
            else if (txtStoreID.Tag != null)
                rtn = clsGenaralName.getName_Store(txtStoreID.Tag.ToString());
            else
                rtn = "default";
            return rtn;
        }
        #endregion

        #region Get To Location
        private string getToDepartment()
        {
            string rtn = "";
            if (txtDepartmentID.Tag != null)
                rtn = txtDepartmentID.Tag.ToString();
            else
                rtn = "default";
            return rtn;
        }
        private string getToSection()
        {
            string rtn = "";
            if (txtSectionID.Tag != null)
                rtn = txtSectionID.Tag.ToString();
            else
                rtn = "default";
            return rtn;
        }
        private string getToStore()
        {
            string rtn = "";
            if (txtStoreID.Tag != null)
                rtn = txtStoreID.Tag.ToString();
            else
                rtn = "default";
            return rtn;
        }
        #endregion

        #region Get Location GIN Number
        private string getDepartmentGIN()
        {
            string rtn = "";
            if (txtDepartmentID.Tag != null && txtDepartmentID.Tag.ToString() != "default" && txtGinID.Text.Trim().Length > 0)
                rtn = txtGinID.Text.Trim();
            else
                rtn = "default";
            return rtn;
        }
        private string getSectionGIN()
        {
            string rtn = "";
            if (txtSectionID.Tag != null && txtSectionID.Tag.ToString() != "default" && txtGinID.Text.Trim().Length > 0)
                rtn = txtGinID.Text.Trim();
            else
                rtn = "default";
            return rtn;
        }
        private string getStoreGIN()
        {
            string rtn = "";
            if (txtStoreID.Tag != null && txtStoreID.Tag.ToString() != "default" && txtGinID.Text.Trim().Length > 0)
                rtn = txtGinID.Text.Trim();
            else
                rtn = "default";
            return rtn;
        }
        #endregion

        #region Load GIN Number
        private void loadGINnumber()
        {
            if (txtLocationID.Tag != null && txtLocationID.Tag.ToString().Length > 0)
            {
                if (txtDepartmentID.Tag != null)
                    Search_DepartmentGoodIssueNote();
                else if (txtSectionID.Tag != null)
                    Search_SectionGoodIssueNote();
                else if (txtStoreID.Tag != null)
                    Search_StoreGoodIssueNote();
            }
            else
            {
                MessageBox.Show("Please Select Receiver..........", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                txtLocationID.Focus();
            }
        }
        #endregion

        #region Send E-Mail
        public void sendEmail()
        {
            //   frmEmail oEmail = new frmEmail();
            //  oEmail.Show();
        }
        #endregion

        #region Cancel Order
        private void cancelOrder()
        {
            try
            {
                if (txtGoodreceivedNoteID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_scsSectionGoodReceiveNote detail = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text.Trim());
                        if (detail != null)
                        {
                            if (!detail.IsLocked)
                            {
                                if (!detail.IsDeleted)
                                {
                                    DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForDelete, " GRN : " + detail.SectionGoodReceiveNote_ID), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                                    if (msgResult == DialogResult.Yes)
                                    {

                                        if (CheckStockValidityWhenRemove(detail.SectionGoodReceiveNote_ID))
                                        {
                                            detail.ModifiedUser_ID = clsSecurity.UserIDLoged;
                                            detail.DateModified = clsSecurity.getServerDateTime();
                                            detail.IsDeleted = true;
                                            detail.Update();

                                            #region Update Other Tables
                                            List<tbl_scsSectionGoodReceiveNote_Detail> details = tbl_scsSectionGoodReceiveNote_Detail.SelectAllBySectionGoodReceiveNote_ID(detail.SectionGoodReceiveNote_ID);
                                            foreach (tbl_scsSectionGoodReceiveNote_Detail GRNdetail in details)
                                            {
                                                ///Update Stock
                                                //clsHelpMethods.UpdateOrInsertSectionStock(true, true, GRNdetail.Item_ID, GRNdetail.ItemSubCategory_ID, GRNdetail.ItemSubCategory2_ID, GRNdetail.ItemSerialNo, GRNdetail.ItemSerialNo2,
                                                //    GRNdetail.Job_ID, GRNdetail.ToSection_ID, GRNdetail.Qty, GRNdetail.Weight, 0, 0, false, false, true);

                                                ///Unsettle GIN - Store
                                                foreach (tbl_scsStoreGoodIssueNote_Detail ginST in tbl_scsStoreGoodIssueNote_Detail.SelectAllByStoreGoodIssueNote_ID(GRNdetail.StoreGoodIssueNote_ID).Where(p => p.Item_ID == GRNdetail.Item_ID))
                                                {
                                                    ginST.QtySettle = ginST.QtySettle - GRNdetail.Qty;
                                                    ginST.WeightSettle = ginST.WeightSettle - GRNdetail.Weight;
                                                    ginST.Update();
                                                    clsProcessMethods.SetSettle_StoreGIN(GRNdetail.StoreGoodIssueNote_ID);
                                                }
                                                ///Unsettle GIN - Section
                                                tbl_scsSectionGoodIssueNote_Detail ginSC = tbl_scsSectionGoodIssueNote_Detail.Select(GRNdetail.SectionGoodIssueNote_ID, GRNdetail.Item_ID, GRNdetail.ItemSubCategory_ID, GRNdetail.ItemSubCategory2_ID, GRNdetail.ItemSerialNo, GRNdetail.ItemSerialNo2);
                                                if (ginSC != null)
                                                {
                                                    ginSC.QtySettle = ginSC.QtySettle - GRNdetail.Qty;
                                                    ginSC.WeightSettle = ginSC.WeightSettle - GRNdetail.Weight;
                                                    ginSC.Update();
                                                    clsProcessMethods.SetSettle_SectionGIN(GRNdetail.SectionGoodIssueNote_ID);
                                                }
                                                ///Unsettle GIN - Department
                                                ///Pls Do
                                            }
                                            #endregion

                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                            ClearFields();
                                        }
                                    }
                                }
                                else
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AlreadyDeleted), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                            }
                            else
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordLockedCantDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                        }
                    }

                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion 

        private void btnAddItemTemp_Click(object sender, EventArgs e)
        {

        }

        private void frm_scsSectionGoodReceiveNote_FormClosing(object sender, FormClosingEventArgs e)
        {
            Attachments.Close();
        }

        #region User Checked Approve Details
        private void btnChecked_Click(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }

        private void btnApproved_Click(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }

        #region Approved and Checked Search
        private void Search_ApprovedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpGRNDate.Value.Date))
                {
                    if (clsSecurity.PermissionToApproved(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtGoodreceivedNoteID.Text != null && txtGoodreceivedNoteID.TextLength > 0 && txtGoodreceivedNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForApproved), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetApproved login = new frmSetApproved();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetApproved.bChecked)
                                {
                                    bHasApproved = true;
                                    glbApprovedDate = clsSecurity.getServerDateTime();
                                    if (IsUpdate)
                                    {
                                        //userDetailsColorChanges();

                                        tbl_scsSectionGoodReceiveNote objGRN = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text.Trim());
                                        if (objGRN != null)
                                        {
                                            objGRN.IsApproved = true;
                                            objGRN.DateApproved = clsSecurity.getServerDateTime();
                                            objGRN.ApprovedUser_ID = frmSetApproved.sApprovedUserID;
                                            objGRN.Update();
                                        }
                                    }
                                }
                                else if (frmSetApproved.bReset)
                                    bHasApproved = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Approve", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToApprove), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_CheckedBy()
        {
            try
            {
                if (clsMethods_GL.CheckValidity_FinancialYear(dtpGRNDate.Value.Date))
                {
                    if (clsSecurity.PermissionToChecked(clsSecurity.UserIDLoged, iFormID))
                    {
                        if (txtGoodreceivedNoteID.Text != null && txtGoodreceivedNoteID.TextLength > 0 && txtGoodreceivedNoteID.Text != "<Auto Generate>")
                        {
                            DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForChecked), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (msgResult == DialogResult.Yes)
                            {
                                frmSetChecked login = new frmSetChecked();
                                login.iFormID = iFormID;
                                login.userID = clsSecurity.UserIDLoged;
                                login.ShowDialog();
                                if (frmSetChecked.bChecked)
                                {
                                    bHasChecked = true;
                                    glbCheckedDate = clsSecurity.getServerDateTime();

                                    if (IsUpdate)
                                    {
                                        //userDetailsColorChanges();

                                        tbl_scsSectionGoodReceiveNote objGRN = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text.Trim());
                                        if (objGRN != null)
                                        {
                                            objGRN.IsChecked = true;
                                            objGRN.DateChecked = clsSecurity.getServerDateTime();
                                            objGRN.CheckedUser_ID = frmSetChecked.sCheckedUserID;
                                            objGRN.Update();
                                        }
                                    }

                                }
                                else if (frmSetChecked.bReset)
                                    bHasChecked = false;
                            }
                        }
                        else
                            MessageBox.Show("Please Fill Details to Check", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                    }
                    else
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToCheck), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Stop);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion
        private void btnUserDetails_Click(object sender, EventArgs e)
        {
            if (txtGoodreceivedNoteID.Text != "" || txtGoodreceivedNoteID.Text != "<Auto Generate>")
            {
                tbl_scsSectionGoodReceiveNote detail = tbl_scsSectionGoodReceiveNote.Select(txtGoodreceivedNoteID.Text);
                if (detail != null)
                {
                    DataTable dt_UserDetails = new DataTable();
                    dt_UserDetails.Columns.Add("usertype", typeof(string));
                    dt_UserDetails.Columns.Add("Column1", typeof(string));
                    dt_UserDetails.Columns.Add("user", typeof(string));
                    dt_UserDetails.Columns.Add("Column2", typeof(string));
                    dt_UserDetails.Columns.Add("datetime", typeof(string));

                    dt_UserDetails.Rows.Add("Created By", ":", clsGenaralName.getName_User(detail.CreateUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateCreate));

                    if (detail.DateCreate != detail.DateModified)
                        dt_UserDetails.Rows.Add("Last Modified By", ":", clsGenaralName.getName_User(detail.ModifiedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateModified));

                    if (detail.IsChecked)
                        dt_UserDetails.Rows.Add("Checked By", ":", clsGenaralName.getName_User(detail.CheckedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateChecked));

                    if (detail.IsApproved)
                        dt_UserDetails.Rows.Add("Approved By", ":", clsGenaralName.getName_User(detail.ApprovedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateApproved));

                    if (detail.IsDeleted)
                        dt_UserDetails.Rows.Add("Cancelled by", ":", clsGenaralName.getName_User(detail.DeletedUser_ID), "|", clsFormatter.FormatDate_Short_WithTime(detail.DateDeleted));

                    Point startPoint = this.PointToScreen(new Point());

                    frmApprovedCheckedValidity frm = new frmApprovedCheckedValidity();
                    frm.ShowWindow(startPoint.X, (startPoint.Y + this.Size.Height), dt_UserDetails);
                }
            }
        }

        #region User Details Color Changes
        //private void userDetailsColorChanges()
        //{
        //    if (bHasApproved)
        //    {
        //        this.btnApproved.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        this.btnChecked.BackColor = System.Drawing.Color.DarkGray;
        //        btnApproved.Enabled = false;
        //        btnChecked.Enabled = false;

        //    }
        //    if (bHasChecked)
        //    {
        //        this.btnChecked.BackColor = System.Drawing.Color.FromArgb(3, 87, 11);
        //        btnChecked.Enabled = false;
        //    }
        //    if (!bHasApproved && !bHasChecked)
        //    {
        //        this.btnApproved.ForeColor = System.Drawing.Color.Red;
        //        this.btnChecked.ForeColor = System.Drawing.Color.Red;
        //        this.btnApproved.BackColor = System.Drawing.Color.White;
        //        this.btnChecked.BackColor = System.Drawing.Color.White;
        //        btnApproved.Enabled = true;
        //        btnChecked.Enabled = true;
        //    }
        //}
        #endregion
        #endregion

    }
}
