using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;


namespace Digiteq
{
    public partial class frm_scsStockAdd : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;
        static bool IsUpdateAdjustment = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;

        //for security handle
        public bool bNoAccess;
        public bool bHasChecked;
        public bool bHasApproved;
        DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        DateTime glbCheckedDate = clsSecurity.getServerDateTime();

        #endregion

        #region Form Load
        public frm_scsStockAdd()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.scsStockAdd);
            iFormID = clsSecurity.getFormID(FormName.scsStockAdd);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_scsStockAdjustment_Load(object sender, EventArgs e)
        {
            clsFormatter.setFormatForm(this, " Stock Add ", 2, iFormID);
            CusDataGridViewFormat();
            ClearFields();
        } 
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKey()
        {
            clsCommon.ValidateForeignKey(ref txtDepartmentID);
            clsCommon.ValidateForeignKey(ref txtSectionID);
            clsCommon.ValidateForeignKey(ref txtStoreID);
            clsCommon.ValidateForeignKey(ref txtCheckedBy);
            clsCommon.ValidateForeignKey(ref txtApprovedBy);
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            ValidateEmptyForeignKey();

                            if (IsUpdate)  //update records
                            {
                            } 
                            else  //insert records
                            {
                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                    txtStockAddID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                if (txtStockAddID.TextLength > 0)
                                {
                                    //Stock Adjustmen Header
                                    tbl_scsStockAdd detail = new tbl_scsStockAdd(txtStockAddID.Text.ToString(), dtpAdjustmentDate.Value, txtRemark.Text.ToString(),
                                            txtDepartmentID.Tag.ToString(),txtSectionID.Tag.ToString(), txtStoreID.Tag.ToString(), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                            txtCheckedBy.Tag.ToString(), txtApprovedBy.Tag.ToString(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                            glbCheckedDate, glbApprovedDate, bHasChecked, bHasApproved, false, false, false);
                                    detail.Insert();

                                    foreach (DataGridViewRow row in dgvDetail.Rows)
                                    {
                                        try
                                        {
                                            string sItemCode = "", sItemName = "default", sUOM = "", sWeight = "",
                                          //  sSelectArea_ID = "", sDepartment_ID = "default", sSection_ID = "", sStore_ID = "",
                                            sItemSubCategoryID1 = "", sItemSubCategoryID2 = "", sItemSerialNo1 = "", sItemSerialNo2 = "";
                                                
                                            decimal dWeight = 0, dQuantity = 0;

                                            sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "default");
                                            sItemName = clsValidate.ValidateGridValue(dgvDetail, "ItemName", row.Index, "");
                                            sUOM = clsValidate.ValidateGridValue(dgvDetail, "UOM", row.Index, "default");
                                            sWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, "");
                                            dQuantity = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                                            dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                                            sItemSubCategoryID1 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID1", row.Index, "default");
                                            sItemSubCategoryID2 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID2", row.Index, "default");
                                            sItemSerialNo1 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo1", row.Index, "0");
                                            sItemSerialNo2 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo2", row.Index, "0");

                                            //sSelectArea_ID = clsValidate.ValidateGridValue(dgvDetail, "SelectArea_ID", row.Index, "default");
                                            //sDepartment_ID = clsValidate.ValidateGridValue(dgvDetail, "Department_ID", row.Index, "default");
                                            //sSection_ID = clsValidate.ValidateGridValue(dgvDetail, "Section_ID", row.Index, "default");
                                            //sStore_ID = clsValidate.ValidateGridValue(dgvDetail, "Store_ID", row.Index, "default");

                                            if (sItemCode.Length > 0)
                                            {
                                                if (txtStoreID.TextLength > 0)
                                                {
                                                    #region Store
                                                    tbl_genStore_Stock stock = tbl_genStore_Stock.Select(txtStoreID.Tag.ToString(), sItemCode,"default",sItemSubCategoryID1,sItemSubCategoryID2,sItemSerialNo1,sItemSerialNo2);
                                                    if (stock != null)
                                                    {
                                                        //insert add details  
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(), sItemCode,sItemSubCategoryID1,
                                                            sItemSubCategoryID2,sItemSerialNo1,sItemSerialNo2,dQuantity,dWeight);
                                                        STAdetail.Insert();

                                                        //update stock detail
                                                        stock.Qty += dQuantity;
                                                        stock.Weight += dWeight;
                                                        stock.Update();
                                                    }
                                                    else
                                                    {
                                                        //insert add details 
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(),sItemCode,sItemSubCategoryID1,
                                                            sItemSubCategoryID2,sItemSerialNo1,sItemSerialNo2,dQuantity, dWeight);
                                                        STAdetail.Insert();

                                                        //insert stock details
                                                      //  clsHelpMethods_Local.Store_NewStock(txtStoreID.Tag.ToString(), sItemCode, "default", sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, dWeight, 0, dQuantity, 0, 0, 0, 0, 0);
                                                    }
                                                    #endregion
                                                }
                                                else if (txtSectionID.TextLength > 0)
                                                {
                                                    #region Section
                                                    tbl_genSection_Stock Section = tbl_genSection_Stock.Select(txtSectionID.Tag.ToString(), sItemCode, "default", sItemSubCategoryID1, sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2);
                                                    if (Section != null)
                                                    {
                                                        //insert add details 
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(), sItemCode, sItemSubCategoryID1,
                                                            sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, dQuantity, dWeight);
                                                        STAdetail.Insert();

                                                        //update stock detail
                                                        Section.Qty += dQuantity;
                                                        Section.Weight += dWeight;
                                                        Section.Update();
                                                    }
                                                    else
                                                    {
                                                        //insert add details 
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(), sItemCode, sItemSubCategoryID1,
                                                            sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, dQuantity, dWeight);
                                                        STAdetail.Insert();

                                                        //insert stock details
                                                        clsHelpMethods.Section_NewStock(txtSectionID.Tag.ToString(), sItemCode,"default", dWeight, dQuantity,0, 0, 0);
                                                    }
                                                    #endregion
                                                }
                                                else if (txtDepartmentID.TextLength > 0)
                                                {
                                                    #region Department
                                                    tbl_genDepartment_Stock Department = tbl_genDepartment_Stock.Select(txtDepartmentID.Tag.ToString(), sItemCode,"default");
                                                    if (Department != null)
                                                    {
                                                        //insert add details 
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(), sItemCode, sItemSubCategoryID1,
                                                            sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, dQuantity, dWeight);
                                                        STAdetail.Insert();

                                                        //update stock detail
                                                        Department.Qty += dQuantity;
                                                        Department.Weight += dWeight;
                                                        Department.Update();
                                                    }
                                                    else
                                                    {
                                                        //insert add details 
                                                        tbl_scsStockAdd_Detail STAdetail = new tbl_scsStockAdd_Detail(txtStockAddID.Text.ToString(), sItemCode, sItemSubCategoryID1,
                                                            sItemSubCategoryID2, sItemSerialNo1, sItemSerialNo2, dQuantity, dWeight);
                                                        STAdetail.Insert();

                                                        //insert stock details
                                                    //    clsHelpMethods_Local.Department_NewStock(txtDepartmentID.Tag.ToString(), sItemCode, "default", dWeight, dQuantity, 0, 0, 0);
                                                    }
                                                    #endregion
                                                }
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            clsValidate.WriteErrorLog("", iFormID,ex);
                                           SEACCException.Show(ex);
                                        }//error may come because last row of the grid may not have information
                                    }
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);                      
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                           SEACCException.Show(ex);
                            clsValidate.WriteErrorLog("", iFormID,ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            tbl_scsStockAdd oldRecord = tbl_scsStockAdd.Select(txtStockAddID.Text.Trim());
                            if (oldRecord != null)
                                FillDetails(txtStockAddID.Text.Trim());
                        }
                    }
                   
                }
            }
        }
        #endregion

        #region Btn new
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                //delete one record
                string strMessage = "";
                Cursor = Cursors.WaitCursor;
                if (txtStockAddID.TextLength > 0)
                {
                    DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForDelete, ""), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                    if (msgResult == DialogResult.Yes)
                    {
                        tbl_scsStockAdd detail = tbl_scsStockAdd.Select(txtStockAddID.Text.ToString());
                        if (detail != null)
                        {
                            detail.IsDeleted = true;
                            detail.Update();
                            detail.DateModified = clsSecurity.getServerDateTime();
                            detail.ModifiedUser_ID = clsSecurity.UserIDLoged;
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            ClearFields();
                        }
                    }
                    //else if (msgResult == DialogResult.No)
                    //{
                    //    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyCancel), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    //}
                }
                else
                {
                    strMessage += "\n" + "Plase select the recode ";
                    MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 0)
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                }
            }
            catch (Exception) { }
        }
        #endregion

        #region btn Abb
        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (AddCheckValidity())
            {
                if (AddCheckNumberValidity())
                {
                    int iRow;
                    clsCommon.ValidateForeignKey(ref txtItemSubCategory);
                    clsCommon.ValidateForeignKey(ref txtItemSerialNo, "0");
                    if (IsUpdateAdjustment)
                        iRow = int.Parse(txtRowNo.Text.Trim());
                    else
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                    }

                    dgvDetail["ItemCode", iRow].Value = txtInputMaterialID.Tag.ToString().Trim();
                    dgvDetail["ItemName", iRow].Value = txtInputMaterialID.Text.Trim();

                    tbl_genItemMaster detail = tbl_genItemMaster.Select(txtInputMaterialID.Tag.ToString());
                    tbl_zUom Uomdetail = tbl_zUom.Select(detail.Uom_ID);
                    if (Uomdetail != null)
                        dgvDetail["UOM", iRow].Value = clsCommon.GetForeignKeyValue(Uomdetail.UomCode);
                    dgvDetail["Weight", iRow].Value = txtWeight.Text.Trim();
                    dgvDetail["Quantity", iRow].Value = txtMaterialQty.Text.Trim();
                    dgvDetail["Department_ID", iRow].Value = txtDepartmentID.Text.Trim();
                    dgvDetail["Section_ID", iRow].Value = txtSectionID.Text.Trim();
                    dgvDetail["Store_ID", iRow].Value = txtStoreID.Text.Trim();
                    dgvDetail["ItemSubCategoryID1", iRow].Tag = txtItemSubCategory.Tag.ToString();
                    dgvDetail["ItemSubCategoryID1", iRow].Value = clsCommon.GetForeignKeyValue(clsGenaralName.getName_ItemSubCategory(txtItemSubCategory.Tag.ToString()));
                    dgvDetail["ItemSubCategoryID2", iRow].Tag = txtItemSubCategory.Text.Trim();
                    dgvDetail["ItemSubCategoryID2", iRow].Value = clsCommon.GetForeignKeyValue(clsGenaralName.getName_ItemSubCategory2(txtItemSubCategory.Text.Trim()));
                    dgvDetail["ItemSerialNo1", iRow].Value = txtItemSerialNo.Tag.ToString();
                    dgvDetail["ItemSerialNo2", iRow].Value = txtItemSerialNo.Text.Trim();

                    ClearFieldContact();
                }
            }
        }
        #endregion

        #region Btn Add InputMaterial
        //private void btnAddInputMaterial_Click(object sender, EventArgs e)
        //{
        //    string sItemID = "";
        //    if (txtInputTypeID.Tag != null && txtInputTypeID.Tag.ToString().Trim().Length > 0)
        //        sItemID = clsHelpMethods.ItemSearchByItemTypeID(txtInputTypeID.Tag.ToString(), iFormID);

        //    FillDetailsInputProduct(sItemID);
        //}
        #endregion

        #region Btn Info Input Item
        private void btnInfoInputItem_Click(object sender, EventArgs e)
        {
            if (txtInputMaterialID.Tag != null && txtInputMaterialID.Tag.ToString().Trim().Length > 0)
            {
                clsHelpMethods_Local.ItemViewerByItemTypeID(txtInputMaterialID.Tag.ToString(), iFormID);
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStockAddID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtSectionID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtStoreID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtDepartmentID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtInputMaterialID, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtMaterialQty, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtWeight, true);
            clsCommon.SetEnableDisable_NormalLabel(lblSANCode, true);
                   

            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
            txtInputMaterialID.Tag = null;

            txtRemark.Clear();
            txtStockAddID.Clear();
            txtInputMaterialID.Clear();
            txtMaterialQty.Clear();
            txtWeight.Clear();
            txtRemark.Clear();
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            dgvDetail.Rows.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtStockAddID.Text = "<Auto Generate>";
            else
                txtStockAddID.Clear();
            if (txtStockAddID.Enabled)
            {
                txtStockAddID.SelectAll();
                txtStockAddID.Focus();
            }
        }
        #endregion



        #region Clear Stoke Contact
        private void ClearStokeContact()
        {
            txtDepartmentID.Clear();
            txtSectionID.Clear();
            txtStoreID.Clear();
            txtDepartmentID.Tag = null;
            txtSectionID.Tag = null;
            txtStoreID.Tag = null;
        }
        #endregion

        #region Clear Field Contact
        private void ClearFieldContact()
        {
            //set the flag and enble the id
            IsUpdateAdjustment = false;
            txtInputMaterialID.Clear();
            txtMaterialQty.Clear();
            txtWeight.Clear();
            txtRemark.Clear();
        }
        #endregion

        #region Fill Details Input Products
        private void FillDetailsInputProduct(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_genItemMaster detail = tbl_genItemMaster.Select(sID);
                    if (detail != null)
                    {
                        txtInputMaterialID.Tag = detail.Item_ID;
                        txtInputMaterialID.Text = detail.ItemName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_scsStockAdd detail = tbl_scsStockAdd.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStockAddID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtSectionID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtStoreID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtDepartmentID, false);
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtInputMaterialID, false);
                    clsCommon.SetEnableDisable_NormalTextbox(txtMaterialQty, false);
                    clsCommon.SetEnableDisable_NormalTextbox(txtWeight, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblSANCode, false);
                   
                    //asign values
                    txtDepartmentID.Tag = detail.Department_ID;
                    txtSectionID.Tag = detail.Section_ID;
                    txtStoreID.Tag = detail.Store_ID;

                    txtRemark.Text = detail.Remark;
                    txtDepartmentID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Department(detail.Department_ID));
                    txtSectionID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Section(detail.Section_ID));
                    txtStoreID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Store(detail.Store_ID));
                    txtStockAddID.Text = clsCommon.GetForeignKeyValue(detail.StockAdd_ID);

                    txtApprovedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.ApprovedUser_ID));
                    txtCheckedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.CheckedUser_ID));
                    txtPreparedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.CreateUser_ID));
                    txtPreparedBy.Tag = detail.CreateUser_ID;
                    txtCheckedBy.Tag = detail.CheckedUser_ID;
                    txtApprovedBy.Tag = detail.ApprovedUser_ID;
                    if (detail.IsApproved)
                    {
                        bHasApproved = true;
                        glbApprovedDate = detail.DateApproved;
                        dtpDateApprovedBy.Value = detail.DateApproved;
                        dtpTimeApprovedBy.Value = detail.DateApproved;
                        clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, false);
                        clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, false);
                    }
                    if (detail.IsChecked)
                    {
                        bHasChecked = true;
                        glbCheckedDate = detail.DateChecked;
                        dtpDateCheckedBy.Value = detail.DateChecked;
                        dtpTimeCheckedBy.Value = detail.DateChecked;
                        clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, false);
                        clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, false);
                    }
                    dtpDatePreparedBy.Value = detail.DateCreate;
                    dtpTimePreparedBy.Value = detail.DateCreate;


                    //fill item details
                    RefreshGrid(detail.StockAdd_ID);
                }
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid(string StockAdjustmentID)
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<tbl_scsStockAdd_Detail> details = tbl_scsStockAdd_Detail.SelectAllByStockAdd_ID(StockAdjustmentID);
                foreach (tbl_scsStockAdd_Detail detail in details)
                {
                    if (detail.StockAdd_ID != "default")
                    {

                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;

                        dgvDetail["ItemCode", iRow].Value = detail.Item_ID;
                        tbl_genItemMaster Itemdetail = tbl_genItemMaster.Select(detail.Item_ID);
                        dgvDetail["ItemName", iRow].Value = Itemdetail.ItemName;
                        tbl_zUom Uomdetail = tbl_zUom.Select(Itemdetail.Uom_ID);
                        if (Uomdetail != null)
                            dgvDetail["UOM", iRow].Value = clsCommon.GetForeignKeyValue(Uomdetail.UomCode);
                        dgvDetail["Weight", iRow].Value = clsFormatter.FormatToNumberWithFourDecimalPlaces(detail.Weight);
                        dgvDetail["Quantity", iRow].Value = clsFormatter.FormatToNumberWithTwoDecimalPlaces(detail.Qty);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        }
        #endregion

        #region Evenst Double Click
        //private void txtInputTypeID_DoubleClick(object sender, EventArgs e)
        //{
        //    clsSearch.Search_MasterItemType(ref txtInputTypeID);
        //}
        private void txtInputMaterialID_DoubleClick(object sender, EventArgs e)
        {
            clsHelpMethods.SearchItemAdvance(ref txtInputMaterialID, ref txtItemSubCategory, ref txtItemSerialNo);          
        }
        private void txtDepartmentID_DoubleClick(object sender, EventArgs e)
        {
            ClearStokeContact();
            clsSearch.Search_MasterDepartment(ref txtDepartmentID);
        }
        private void txtSectionID_DoubleClick(object sender, EventArgs e)
        {
            ClearStokeContact();
            clsSearch.Search_MasterSection(ref txtSectionID);
        }
        private void txtStoreID_DoubleClick(object sender, EventArgs e)
        {
            ClearStokeContact();
            clsSearch.Search_MasterStore(ref txtStoreID, true);
        }
        private void txtCheckedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_CheckedBy();
        }
        private void txtApprovedBy_DoubleClick(object sender, EventArgs e)
        {
            Search_ApprovedBy();
        }
        private void txtSANID_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_TransactionStockAdd(ref txtStockAddID);
            FillDetails(txtStockAddID.Text);
        }
        #endregion

        #region Events key Press
        private void txtMaterialQty_KeyPress(object sender, KeyPressEventArgs e)
        {
            clsValidate.AllowIntegerCommaAndHyphen(e, sender);
           // clsValidate.AllowInteger(e);
        }

        private void txtWeight_KeyPress(object sender, KeyPressEventArgs e)
        {
            clsValidate.AllowIntegerCommaAndHyphen(e, sender);
        }
        #endregion

        #region Event KeyDown
        private void txtCheckedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CheckedBy();
            }
        }
        private void txtSANID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                //this condition have to add false boolean, coz this methods change in stock adjustment form - edit by janith
                clsSearch.Search_TransactionStockAdjustment(ref txtStockAddID, false);
                FillDetails(txtStockAddID.Text);
            }
        } 
        private void txtApprovedBy_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_ApprovedBy();
            }
        }       
        private void txtDepartmentID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                ClearStokeContact();
                clsSearch.Search_MasterDepartment(ref txtDepartmentID);
            }
        }
        private void txtSectionID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                ClearStokeContact();
                clsSearch.Search_MasterSection(ref txtSectionID);
            }
        }
        private void txtInputMaterialID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)            
                clsHelpMethods.SearchItemAdvance(ref txtInputMaterialID, ref txtItemSubCategory, ref txtItemSerialNo);            
            else
                clsHelpMethods.SearchItemAdvanceByKeyPress(ref txtInputMaterialID, ref txtInputMaterialID, ref txtItemSerialNo, e);               
            
        }
        private void txtStoreID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                ClearStokeContact();
                clsSearch.Search_MasterStore(ref txtStoreID, true);
            }

        }
        #endregion

        #region Check Add Validity
        private bool AddCheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            
            if (txtInputMaterialID.TextLength == 0)
            {
                strMessage += "\n" + "Material Name";
                bStatus = false;
            }
            if (txtMaterialQty.TextLength == 0 )
            {
                strMessage += "\n" + "Material Quantity";
                bStatus = false;
            }
            if (txtWeight.TextLength == 0)
            {
                strMessage += "\n" + "Material Weight";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool AddCheckNumberValidity()
        {
            string strMessage = "Please do not enter same Item to Datagrid";
            bool bStatus = true;

            try
            {
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    if (txtInputMaterialID.Tag.ToString() == clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "") && txtItemSubCategory.Tag.ToString() == clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID1", row.Index, ""))
                    {
                        bStatus = false;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;
            if (txtSectionID.TextLength == 0 && txtStoreID.TextLength == 0 && txtDepartmentID.TextLength == 0)
            {
                strMessage += "\n" + "Stock";
                bStatus = false;
            } 
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "Please do not enter same Item to Datagrid";
            bool bStatus = true;

            try
            {

            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Search Methodes
        private void Search_ApprovedBy()
        {
            try
            {
                frmSetApproved login = new frmSetApproved();
                login.iFormID = iFormID;
                login.ShowDialog();
                if (frmSetApproved.bChecked)
                {
                    bHasApproved = true;
                    glbApprovedDate = clsSecurity.getServerDateTime();
                    dtpDateApprovedBy.Value = clsSecurity.getServerDateTime();
                    dtpTimeApprovedBy.Value = clsSecurity.getServerDateTime();
                    txtApprovedBy.Text = frmSetApproved.sApprovedUserName;
                    txtApprovedBy.Tag = frmSetApproved.sApprovedUserID;
                    clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, false);
                    clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, false);
                }
                else if (frmSetApproved.bReset)
                {
                    txtDateApprovedBy.Visible = true;
                    txtApprovedBy.Text = "";
                    txtApprovedBy.Tag = null;
                    bHasApproved = false;
                    clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, true);
                    clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, true);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        }
        private void Search_CheckedBy()
        {
            try
            {
                frmSetChecked login = new frmSetChecked();
                login.iFormID = iFormID;
                login.ShowDialog();
                if (frmSetChecked.bChecked)
                {
                    bHasChecked = true;
                    glbCheckedDate = clsSecurity.getServerDateTime();
                    dtpDateCheckedBy.Value = clsSecurity.getServerDateTime();
                    dtpTimeCheckedBy.Value = clsSecurity.getServerDateTime();
                    txtCheckedBy.Text = frmSetChecked.sCheckedUserName;
                    txtCheckedBy.Tag = frmSetChecked.sCheckedUserID;
                    clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, false);
                    clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, false);
                }
                else if (frmSetChecked.bReset)
                {
                    txtCheckedBy.Text = "";
                    txtCheckedBy.Tag = null;
                    bHasChecked = false;
                    clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, true);
                    clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, true);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        } 
        #endregion
        
    
    } 
       
}
