using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_masChequeMaster : MettroForm
    {
        #region Variables
        //to manage update and insert

        #endregion
        
        #region  Form Load
        public frm_masChequeMaster()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ChequeType);
            iFormID = clsSecurity.getFormID(FormName.ChequeType);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }            
            InitializeComponent();
        }

        private void frm_masChequeMaster_Load(object sender, EventArgs e)
        {
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtChequeTypeCode.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zChequeType detail = tbl_zChequeType.Select(txtChequeTypeCode.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtChequeTypeCode.Text.ToString(), TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                   
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                {
                    try
                    {
                        Cursor = Cursors.WaitCursor;
                        if (txtChequeTypeCode.TextLength > 0)
                        {
                            if (IsUpdate)  //update records
                            {
                                tbl_zChequeType oldRecord = tbl_zChequeType.Select(txtChequeTypeCode.Text.Trim());
                                if (oldRecord != null)
                                {

                                    tbl_zChequeType detail = new tbl_zChequeType(txtChequeTypeCode.Text.Trim(), txtChequeTypeName.Text.Trim());
                                    detail.Update();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtChequeTypeCode.Text.ToString(), TxnActivity.Update);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else  //insert records
                            {
                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                    txtChequeTypeCode.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                //Inquiry Header
                                tbl_zChequeType detail = new tbl_zChequeType(txtChequeTypeCode.Text.Trim(), txtChequeTypeName.Text.Trim());
                                detail.Insert();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtChequeTypeCode.Text.ToString(), TxnActivity.Insert);
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        else
                        {
                            MessageBox.Show("Check Type " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID,ex);
                        SEACCException.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Default;
                        ClearFields();
                        RefreshGrid();
                    }

                }
            }
        }
        #endregion
       

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtChequeTypeCode, true);
            clsCommon.SetEnableDisable_NormalLabel(lblChequeTypeCode, true);

            txtChequeTypeName.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtChequeTypeCode.Text = "<Auto Generate>";
            else
                txtChequeTypeCode.Clear();

            if (txtChequeTypeCode.Enabled)
            {
                txtChequeTypeCode.SelectAll();
                txtChequeTypeCode.Focus();
            }
        }
        #endregion 

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zChequeType> details = tbl_zChequeType.SelectAll();
            foreach (tbl_zChequeType detail in details)
            {
                if (detail.ChequeType_ID.Trim() != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["ChequeTypeCode", iRow].Value = detail.ChequeType_ID;
                    dgvDetail["CheckTypeName", iRow].Value = detail.TypeName;
                }
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_zChequeType detail = tbl_zChequeType.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtChequeTypeCode, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblChequeTypeCode, false);

                        //asign values
                        txtChequeTypeCode.Text = detail.ChequeType_ID;
                        txtChequeTypeName.Text = detail.TypeName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtChequeTypeName, "Type Name"))
            {
                bStatus = true;
            }
            return bStatus;
        }
        #endregion



        #region Events KeyDown
          private void txtChequeTypeCode_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_txtChequeTypeCode();
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtChequeTypeCode_DoubleClick(object sender, EventArgs e)
        {
            Search_txtChequeTypeCode();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["ChequeTypeCode", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods
        private void Search_txtChequeTypeCode()
        {
            try
            {
                clsSearch.Search_MasterChequeType(ref txtChequeTypeCode);
                if (txtChequeTypeCode.Tag != null && txtChequeTypeCode.Tag.ToString().Trim().Length > 0)
                    FillDetails(txtChequeTypeCode.Tag.ToString().Trim());
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion
    }
}
