using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_mtrJobLaminationMaterialType : MettroForm
    {


        #region Form Load
        public frm_mtrJobLaminationMaterialType()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ZLaminationMaterialType);
            iFormID = clsSecurity.getFormID(FormName.ZLaminationMaterialType);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_mtrCustomerClass_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
            
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtJobLaminationMaterialTypeID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zJobLaminationMaterialType detail = tbl_zJobLaminationMaterialType.Select(txtJobLaminationMaterialTypeID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtJobLaminationMaterialTypeID.Text, TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtJobLaminationMaterialTypeID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    
                                    tbl_zJobLaminationMaterialType oldRecord = tbl_zJobLaminationMaterialType.Select(txtJobLaminationMaterialTypeID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_zJobLaminationMaterialType detail = new tbl_zJobLaminationMaterialType(txtJobLaminationMaterialTypeID.Text.Trim(), txtJobLaminationMaterialTypeName.Text.Trim(),decimal.Parse(txtDencity.Text));
                                        detail.Update();
                                        clsHelpMethods.InsertTransactionHistory(iFormID, txtJobLaminationMaterialTypeID.Text, TxnActivity.Update);
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtJobLaminationMaterialTypeID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_zJobLaminationMaterialType detail = new tbl_zJobLaminationMaterialType(txtJobLaminationMaterialTypeID.Text.Trim(), txtJobLaminationMaterialTypeName.Text.Trim(), decimal.Parse(txtDencity.Text));
                                    detail.Insert();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtJobLaminationMaterialTypeID.Text, TxnActivity.Insert);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show(" Job Lamination Material " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {

            //set the flag and enble the id

            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtJobLaminationMaterialTypeID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblClassID, true);

            txtJobLaminationMaterialTypeName.Clear();
            txtDencity.Clear();

           if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtJobLaminationMaterialTypeID.Text = "<Auto Generate>";
           else
                txtJobLaminationMaterialTypeID.Clear();

            if (txtJobLaminationMaterialTypeID.Enabled)
            {
                txtJobLaminationMaterialTypeID.SelectAll();
                txtJobLaminationMaterialTypeID.Focus();
            }
            //txtClassID.Text = "ok";
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zJobLaminationMaterialType> details = tbl_zJobLaminationMaterialType.SelectAll();
            foreach (tbl_zJobLaminationMaterialType detail in details)
            {
                if (detail.LaminationMaterailType_ID.Trim() != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["CategoryID", iRow].Value = detail.LaminationMaterailType_ID;
                    dgvDetail["CategoryName", iRow].Value = detail.LaminationMaterailTypeName;
                    dgvDetail["Prifix", iRow].Value =clsFormatter.FormatToNumberWithOneDecimalPlaces(detail.Dencity);
                }
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_zJobLaminationMaterialType detail = tbl_zJobLaminationMaterialType.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtJobLaminationMaterialTypeID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblClassID, false);

                    //asign values
                    txtJobLaminationMaterialTypeID.Text = detail.LaminationMaterailType_ID;
                    txtJobLaminationMaterialTypeName.Text = detail.LaminationMaterailTypeName;
                    txtDencity.Text = detail.Dencity.ToString();
                }
            }
        }
        #endregion


        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtJobLaminationMaterialTypeName.TextLength == 0)
            {
                strMessage += "\n" + "Lamination Material Type Name";
                bStatus = false;
            }
            if (txtDencity.TextLength == 0)
            {
                strMessage += "\n" + "Dencity Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtClassID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_MasterJobLaminationMaterialType(ref txtJobLaminationMaterialTypeID);
                if (txtJobLaminationMaterialTypeID.Tag != null)
                    FillDetails(txtJobLaminationMaterialTypeID.Tag.ToString());
            }   
        }
        private void frm_mtrItemClass_KeyDown(object sender, KeyEventArgs e)
        {

        }
        #endregion

        #region Events DoubleClick
        private void txtClassID_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_MasterJobLaminationMaterialType(ref txtJobLaminationMaterialTypeID);
            if (txtJobLaminationMaterialTypeID.Tag != null)
                FillDetails(txtJobLaminationMaterialTypeID.Tag.ToString());
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["CategoryID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Event Key Press
        private void txtDencity_KeyPress(object sender, KeyPressEventArgs e)
        {
            clsValidate.AllowDecimalWithLength((TextBox)sender, e, 18, 6);
        }
        #endregion

    }
}
