#region Using Directives
using System;
using System.Collections.Generic;
using System.Windows.Forms;
using DataTire;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
#endregion

namespace Digiteq.Master_Forms
{
    public partial class frm_securityConfigStatusType : Form
    {
        
        //to manage update and insert
        static bool IsUpdate = false;
        public string glbUserID = "";
        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
    
        
        #region Form Load

        private void frm_securityConfigStatusType_Load(object sender, EventArgs e)
        {
            //format Form
            RefreshGrid();
            CusDataGridViewFormat();

            ClearFields();
        }

        public frm_securityConfigStatusType()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.SecurityConfigType_Status);
            iFormID = clsSecurity.getFormID(FormName.SecurityConfigType_Status);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }

            InitializeComponent();
        } 
        #endregion

        #region Btn New

        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region  Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtStatusId.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_securityConfigType_Status detail = tbl_securityConfigType_Status.Select(txtStatusId.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion
        
        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {

            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtStatusId.Text.Trim().Length > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_securityConfigType_Status oldRecord = tbl_securityConfigType_Status.Select(txtStatusId.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        tbl_securityConfigType_Status detail = new tbl_securityConfigType_Status(txtStatusId.Text.Trim(), txtStatus.Text.Trim(), txtRemark.Text.Trim());
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtStatusId.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_securityConfigType_Status detail = new tbl_securityConfigType_Status(txtStatusId.Text.Trim(), txtStatus.Text.Trim(), txtRemark.Text.Trim());
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }

                            }
                            else
                            {
                                MessageBox.Show("Status " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }

                        }

                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        } 
        #endregion


        #region Datagrid Format

        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();

                List<tbl_securityConfigType_Status> details = tbl_securityConfigType_Status.SelectAll();
                foreach (tbl_securityConfigType_Status detail in details)
                {
                    if (detail.ConfigTypeStatus_ID.Trim() != "default")
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["TypeStatusID", iRow].Value = detail.ConfigTypeStatus_ID;
                        dgvDetail["TypeStatus", iRow].Value = detail.ConfigTypeStatus;
                        dgvDetail["Remark", iRow].Value = detail.Remark;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enable the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStatusId, true);
            clsCommon.SetEnableDisable_NormalLabel(lblTypeStatusId, true);

            txtStatus.Clear();
            txtRemark.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtStatusId.Text = "<Auto Generate>";
            else
                txtStatusId.Clear();
            if (txtStatusId.Enabled)
            {
                txtStatusId.SelectAll();
                txtStatusId.Focus();
            }
        }
        #endregion

        #region Fill Details

        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_securityConfigType_Status detail = tbl_securityConfigType_Status.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStatusId, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeStatusId, false);

                        //asign values
                        txtStatusId.Text = detail.ConfigTypeStatus_ID;
                        txtStatus.Text= detail.ConfigTypeStatus;
                        txtRemark.Text = detail.Remark;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion

     
        #region Events KeyDown
        private void txtStatusId_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityStatusID();
            }  
        }

        private void frm_securityConfigStatusType_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }

        #endregion

        #region Events DoubleClick
        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        private void txtStatusId_DoubleClick(object sender, EventArgs e)
        {
            Search_SecurityStatusID();
        }


        #endregion

        #region Events Datagrid

        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["TypeStatusID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        
        #region Check Validity
        private bool CheckValidity()
        {
            string strMassage = "";
            bool bStatus = true;

            if (txtStatus.Text.Trim().Length == 0)
            {
                strMassage = strMassage + "\n " + "Type Status";
              //  string.Concat(strMassage, "\n ", "Type Status");
                bStatus = false;
            }

            if (txtRemark.Text.Trim().Length == 0)
            {
                strMassage += "\n " + "Remark";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (!bStatus)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMassage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;

        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Search Methods
        private void Search_SecurityStatusID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigStatusID();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtStatusId.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion




        
    }
}
