using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
namespace Digiteq
{
    public partial class frm_mtrUom : MettroForm
    {
        


        #region Form Load
        public frm_mtrUom()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ZUom);
            iFormID = clsSecurity.getFormID(FormName.ZUom);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_mtrBranch_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtUomID.TextLength > 0)
                {
                    if (CheckValidity())
                    {
                        if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                        {
                            //delete one record
                            Cursor = Cursors.WaitCursor;
                            tbl_zUom detail = tbl_zUom.Select(txtUomID.Text.Trim());
                            if (detail != null)
                            {
                                detail.Delete();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtUomID.Text, TxnActivity.Cancel);
                            }

                            Cursor = Cursors.Default;
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            ClearFields();
                            RefreshGrid();
                        }
                        else //if no permission to delete
                        {
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtUomID.TextLength > 0)
                            {
                                #region Update
                                if (IsUpdate)  //update records
                                {

                                    tbl_zUom oldRecord = tbl_zUom.Select(txtUomID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_zUom detail = new tbl_zUom(txtUomID.Text.Trim(), txtUomName.Text.Trim(), txtCategoryName.Tag.ToString(), txtUomCode.Text.Trim(),
                                            chkVisibal.Checked, chksales.Checked, chkPacking.Checked, rdoCalculationKilo.Checked, rdoCalculationBag.Checked, rdoIsQty.Checked, rdoIsWeight.Checked, rdoIsLength.Checked);
                                        detail.Update();
                                        clsHelpMethods.InsertTransactionHistory(iFormID, txtUomID.Text, TxnActivity.Update);
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                #endregion
                                #region Insert
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtUomID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_zUom detail = new tbl_zUom(txtUomID.Text.Trim(), txtUomName.Text.Trim(), txtCategoryName.Tag.ToString(), txtUomCode.Text.Trim(),
                                        chkVisibal.Checked, chksales.Checked, chkPacking.Checked, rdoCalculationKilo.Checked, rdoCalculationBag.Checked, rdoIsQty.Checked, rdoIsWeight.Checked, rdoIsLength.Checked);
                                    detail.Insert();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtUomID.Text, TxnActivity.Insert);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                } 
                                #endregion
                            }
                            else
                            {
                                MessageBox.Show(" Uom " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtUomID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblUomID, true);

            txtCategoryName.Tag = null;
            txtCategoryName.Clear();
            txtUomName.Clear();
            txtUomID.Clear();
            txtUomCode.Clear();

            chkPacking.Checked = false;
            chksales.Checked = false;
            chkVisibal.Checked = false;
            rdoCalculationBag.Checked = false;
            rdoCalculationKilo.Checked = false;

            rdoIsLength.Checked = false;
            rdoIsWeight.Checked = false;
            rdoIsQty.Checked = false;

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtUomID.Text = "<Auto Generate>";
            else
                txtUomID.Clear();
            if (txtUomID.Enabled)
            {
                txtUomID.SelectAll();
                txtUomID.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zUom> details = tbl_zUom.SelectAll();
            foreach (tbl_zUom detail in details)
            {
                if (detail.Uom_ID != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["UomID", iRow].Value = detail.Uom_ID;
                    dgvDetail["UomName", iRow].Value = detail.UomName;
                    dgvDetail["UomCode", iRow].Value = detail.UomCode;
                    dgvDetail["UomCategoryID", iRow].Value = clsGenaralName.getName_UomCategory(detail.UomCategory_ID);
                }
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_zUom detail = tbl_zUom.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtUomID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblUomID, false);

                    //asign values
                    txtCategoryName.Tag = detail.UomCategory_ID;
                    txtCategoryName.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_UomCategory(detail.UomCategory_ID));
                    txtUomID.Text = detail.Uom_ID;
                    txtUomName.Text = detail.UomName;
                    txtUomCode.Text = detail.UomCode;

                    chkPacking.Checked = detail.IsForPacking;
                    chksales.Checked = detail.IsForSales;
                    chkVisibal.Checked = detail.IsVisible;
                    rdoCalculationBag.Checked = detail.IsForBagCalculation;
                    rdoCalculationKilo.Checked = detail.IsForKiloCalculation;

                    rdoIsLength.Checked = detail.IsLength;
                    rdoIsWeight.Checked = detail.IsWeight;
                    rdoIsQty.Checked = detail.IsQty;
                }
            }
        }
        #endregion


        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtCategoryName.TextLength == 0)
            {
                strMessage += "\n" + "Uom Category Name ";
                bStatus = false;
            }
            if (txtUomName.TextLength == 0)
            {
                strMessage += "\n" + "Uom Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtUomID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_UomID();
            }   
        }
        private void txtUomCategoryName_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_UomCategoryID();
            } 
        }
        private void frm_mtrUom_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtUomID_DoubleClick(object sender, EventArgs e)
        {
            Search_UomID();
        }
        private void txtUomCategoryName_DoubleClick(object sender, EventArgs e)
        {
            Search_UomCategoryID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {

                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["UomID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods
        private void Search_UomCategoryID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_UomCategory();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    if (frmSearchMaster.s_SearchText.Length > 0)
                        txtCategoryName.Text = frmSearchMaster.s_SearchText;
                    if (frmSearchMaster.s_SearchID.Length > 0)
                        txtCategoryName.Tag = frmSearchMaster.s_SearchID;
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }

        }
        private void Search_UomID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_Uom();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtUomID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion
        
    }
}
