using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_mtrItemType : MettroForm
    {


        #region Form Load
        public frm_mtrItemType()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ZItemType);
            iFormID = clsSecurity.getFormID(FormName.ZItemType);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_mtrItemType_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (CheckValidity())
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zItemType detail = tbl_zItemType.Select(txtTypeID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtTypeID.Text, TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (System.Data.SqlClient.SqlException sqlException)
            {
                if (sqlException.Number == 547)
                    MessageBox.Show("Unable to delete the recode.\nPlease remove Item Master references befor delete seleted data. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                else
                    SEACCException.Show(sqlException);
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtTypeID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_zItemType oldRecord = tbl_zItemType.Select(txtTypeID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        tbl_zItemType detail = new tbl_zItemType(txtTypeID.Text.Trim(), txtTypeName.Text.Trim(), txtClassName.Tag.ToString(), txtPrifix.Text.Trim().ToUpper(), oldRecord.Prefrix2, oldRecord.TypeCounter, oldRecord.TypeLength, oldRecord.CompanyID, oldRecord.CompanyBranch_ID, oldRecord.Remark);
                                        detail.Update();
                                        clsHelpMethods.InsertTransactionHistory(iFormID, txtTypeID.Text, TxnActivity.Update);
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtTypeID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_zItemType detail = new tbl_zItemType(txtTypeID.Text.Trim(), txtTypeName.Text.Trim(), txtClassName.Tag.ToString(), txtPrifix.Text.Trim().ToUpper(), "", 1, 5, clsSecurity.CompanyID, clsSecurity.BranchID, "");
                                    detail.Insert();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtTypeID.Text, TxnActivity.Insert);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Item Type " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblSupplierTypeID, true);

            txtClassName.Tag = null;
            txtClassName.Clear();
            txtTypeName.Clear();
            txtPrifix.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtTypeID.Text = "<Auto Generate>";
            else
                txtTypeID.Clear();


            if (txtTypeID.Enabled)
            {
                txtTypeID.SelectAll();
                txtTypeID.Focus();
            }

        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zItemType> details = tbl_zItemType.SelectAll().Where(i => i.CompanyBranch_ID == clsSecurity.BranchID).ToList();
            foreach (tbl_zItemType detail in details)
            {
                if (detail.ItemType_ID.Trim() != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["CategoryID", iRow].Value = detail.ItemType_ID;
                    dgvDetail["CategoryName", iRow].Value = detail.TypeName;
                    dgvDetail["Prifix", iRow].Value = detail.Prefrix;
                }
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_zItemType detail = tbl_zItemType.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblSupplierTypeID, false);

                    //asign values
                    txtClassName.Tag = detail.ItemClass_ID;
                    txtClassName.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_ItemClass(detail.ItemClass_ID));
                    txtTypeID.Text = detail.ItemType_ID;
                    txtTypeName.Text = detail.TypeName;
                    txtPrifix.Text = detail.Prefrix;
                }
            }
        }
        #endregion


        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtClassName.TextLength == 0)
            {
                strMessage += "\n" + "ItemClass Name ";
                bStatus = false;
            }
            if (txtTypeName.TextLength == 0)
            {
                strMessage += "\n" + "ItemType Name ";
                bStatus = false;
            }
            if (txtPrifix.TextLength == 0)
            {
                strMessage += "\n" + "Prifix Name ";
                bStatus = false;
            }
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                if (clsValidate.ValidateGridValue(dgvDetail, "Prifix", row.Index, "").ToString() == txtPrifix.Text.ToUpper() && IsUpdate == false && txtPrifix.TextLength != 0)
                {
                    strMessage += "\n" + " You Can't Enter Same Prifix Name ";
                    bStatus = false;
                    break;
                }
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtItemType_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_MasterItemType(ref txtTypeID);
                FillDetails(frmSearchMaster.s_SearchID);
            }
        }
        private void frm_mtrItemType_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }

        private void txtClassName_KeyDown(object sender, KeyEventArgs e)
        {

            if (e.KeyCode == Keys.F1)
            {
                Search_ClassID();
            }
        }
        #endregion

        #region Events DoubleClick

        private void txtItemType_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_MasterItemType(ref txtTypeID);
            FillDetails(frmSearchMaster.s_SearchID);
        }

        private void txtClassName_DoubleClick(object sender, EventArgs e)
        {
            Search_ClassID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["CategoryID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods  
        private void Search_ClassID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_ItemClass();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    if (frmSearchMaster.s_SearchText.Length > 0)
                        txtClassName.Text = frmSearchMaster.s_SearchText;
                    if (frmSearchMaster.s_SearchID.Length > 0)
                        txtClassName.Tag = frmSearchMaster.s_SearchID;
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion


    }
}
