using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DataTire;
using Digiteq;
using SEACC_WPFControls;
using Digiteq_Logic;
using System.Data;
namespace Digiteq
{
    /// <summary>
    /// Interaction logic for UC_DistrictMaster.xaml
    /// </summary>
    public partial class UC_DistrictMaster : UserControl
    {
     
        #region Form Load
        public UC_DistrictMaster()
        {
            #region Initialize Usercontrol
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.District_Creation;
            SEACC_Form.Initialize(); 
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("DistrictCode");
            dgr_Main.dt.Columns.Add("ProvinceCode");
            dgr_Main.dt.Columns.Add("DistrictName"); 
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, true, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_Print.Click += btn_Print_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click; 
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("District Code", "DistrictCode", 80, false);
            dgr_Main.Add_DatagridColoumn("Province", "ProvinceCode", 95);
            dgr_Main.Add_DatagridColoumn("Name", "DistrictName", 200);  
            #endregion

            ClearFields();
            RefreshGrid();
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_genMasDistrict item in tbl_genMasDistrict.SelectAll().Where(p => p.District_ID != "default" && p.IsCanceled == false))
                {
                    dgr_Main.dt.Rows.Add(item.District_ID, clsRef_Name.get_Province_Name(item.Province_ID), item.DistrictName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_genMasDistrict OldDetails = tbl_genMasDistrict.Select(txtDistrictCode.Text.Trim());
                            if (OldDetails != null)
                            {
                                tbl_genMasDistrict oDistrict = new tbl_genMasDistrict(txtDistrictCode.Text, txtDistrictName.Text, txtProvinceCode.Tag.ToString(), OldDetails.IsCanceled, OldDetails.UserID_Created, clsSecurity.UserIDLoged, OldDetails.UserID_Canceled, OldDetails.TerminalID_Created, clsSecurity.TerminalID, OldDetails.TerminalID_Canceled, OldDetails.Date_Created, clsSecurity.getServerDateTime(), OldDetails.Date_Canceled);
                                oDistrict.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtDistrictCode.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_genMasDistrict oDistrict = new tbl_genMasDistrict(txtDistrictCode.Text, txtDistrictName.Text, txtProvinceCode.Tag.ToString(), false, clsSecurity.UserIDLoged, "default", "default", clsSecurity.TerminalID, "default", "default", clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime());
                        oDistrict.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_Print_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                enum_ReportName Report = enum_ReportName.DistrictList;

              //  tbl_securityReportMaster oReports = tbl_securityReportMaster.Select(((int)Report));
               // if (oReports != null)
                {
                    string sFilter = "";

                    DataSets.dts_Masters glb_dts_Masters = new DataSets.dts_Masters();
                  //  glb_dts_Masters.dt_Company.Adddt_CompanyRow(clsSecurity.DigiteqName, clsSecurity.DigiteqEmail, clsSecurity.decryptPassword(clsCommon.getCompanyName()), clsSecurity.decryptPassword(clsCommon.getCompanyAddress1()), clsCommon.getCompanyAddress2(), clsCommon.getCompanyImage(), oReports.DisplayName, oReports.DisplayName2, "", clsSecurity.UserNameLoged, sFilter == "" ? "-" : sFilter);

                    DataSets.dts_ReportExport glb_dts_ExportReport = new DataSets.dts_ReportExport();

                    foreach (tbl_genMasDistrict item in tbl_genMasDistrict.SelectAll().Where(p => p.District_ID != "default" && p.IsCanceled == false))
                    {
                        glb_dts_Masters.dt_District.Adddt_DistrictRow(item.District_ID, item.DistrictName, clsRef_Name.get_Province_Name(item.Province_ID));
                    }
                    frm_ReportViwer CRViwer = new frm_ReportViwer();
                  //  CRViwer.Print(oReports.ReportPath, glb_dts_Masters, glb_dts_ExportReport.dt_rptParameter);
                }
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.IsUpdateMode)
            {
                if (txtDistrictCode.Tag != null)
                {
                    bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);

                    if (bMessegeBoxResult)
                    {
                        tbl_genMasDistrict oDistrict = tbl_genMasDistrict.Select(txtDistrictCode.Text.Trim());
                        if (oDistrict != null)
                        {
                            oDistrict.IsCanceled = true;
                            oDistrict.Date_Canceled = clsSecurity.getServerDateTime();
                            oDistrict.TerminalID_Canceled = clsSecurity.TerminalID;
                            oDistrict.Update();
                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        } 



        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtDistrictCode, true, false,false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtProvinceCode, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtDistrictName, true, false,false);

            txtDistrictCode.Text = "";
            txtDistrictCode.Tag = null;
            txtDistrictName.Text = "";
            txtProvinceCode.Text = "";

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtDistrictCode.setReadOnlyStatus(true);
                txtDistrictCode.Text = "<Auto Generate>";
            }
            else
                txtDistrictCode.setReadOnlyStatus(false);
        }
        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtDistrictCode))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtProvinceCode))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtDistrictName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_genMasDistrict oDetail = tbl_genMasDistrict.Select(txtDistrictName.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_genMasDistrict FillDetails = tbl_genMasDistrict.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtDistrictCode.IsEnabled = false;
                        txtDistrictCode.Text = FillDetails.District_ID;
                        txtDistrictCode.Tag = FillDetails.District_ID;
                        txtProvinceCode.Text =clsRef_Name.get_Province_Name(FillDetails.Province_ID);
                        txtProvinceCode.Tag = FillDetails.Province_ID;
                        txtDistrictName.Text = FillDetails.DistrictName;

                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event
        private void grd_District_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search Event
        private void txtDistrictCode_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {

        }

        private void txtProvinceCode_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ProvinceCode);
            if (RowDataSearch.DialogResult == true)
            {
                txtProvinceCode.Text = lstResult[1];
                txtProvinceCode.Tag = lstResult[0];
             
            }
        }
        #endregion

        private void txtDistrictName_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Districts);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtDistrictCode.Text = lstResult[0];
                fillDetails(lstResult[0]);
            }
        }
    }
}
