using DataTire;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Digiteq
{
    public partial class frm_masAccCreateFinancialYear_New : MettroForm
    {
        

 

        #region Form Load
        public frm_masAccCreateFinancialYear_New()
        {
            //662
            //CON/652
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.accFinancialCreation);
            iFormID = clsSecurity.getFormID(FormName.accFinancialCreation);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
                bNoAccess = true;

            InitializeComponent();
        }

        private void frm_masAccCreateFinancialYear_New_Load(object sender, EventArgs e)
        {
            ThemeColor = clsFormatter.colorAccounts;
            clsFormatter.setFormatForm(this, "Create Financial Year", 3, iFormID);
            RefreshGrid();
            GridFormat();
        } 
        #endregion

        #region Grid Format
        private void GridFormat()
        {
            dgvFinancialYear.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Calibri", 9F, System.Drawing.FontStyle.Bold);
            dgvFinancialYear.RowsDefaultCellStyle.Font = new System.Drawing.Font("Calibri", 9F, System.Drawing.FontStyle.Bold);
        } 
        #endregion

        #region Action Button
        private void btnNewFinancialYear_Click(object sender, EventArgs e)
        {
            string  sFinYear = "", sFinYear_Title = "";
            DateTime dtYearStartDate = DateTime.Now;
            DateTime dtYearEndDate = DateTime.Now;

            try
            {
                bool bFinYearStatus = getAutoGeneratedFinYear_New(sFormConfigCode, ref sFinYear, ref dtYearStartDate, ref dtYearEndDate);

                if (bFinYearStatus && sFinYear != null)
                {
                    sFinYear_Title = "Financial Year - " + sFinYear;
                    #region Header
                    tbl_accFinancialYearMaster detail = new tbl_accFinancialYearMaster(sFinYear,
                                        sFinYear_Title,
                                        dtYearStartDate,
                                        dtYearEndDate, 1,
                                        clsSecurity.UserIDLoged,
                                        clsSecurity.getServerDateTime(),
                                        clsSecurity.UserIDLoged,
                                        clsSecurity.TerminalID,
                                        clsSecurity.UserIDLoged,
                                        clsSecurity.TerminalID,
                                        clsSecurity.getServerDateTime(),
                                        clsSecurity.getServerDateTime());

                    detail.Insert();
                    #endregion

                    AddFinancialYearMonths(sFinYear, dtYearStartDate, dtYearEndDate);

                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                RefreshGrid();
            }
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvFinancialYear.Rows.Clear();

                foreach (tbl_accFinancialYearMaster detail in tbl_accFinancialYearMaster.SelectAll())
                {
                    if (detail.FinancialYear_ID.Trim() != "default")
                    {
                        dgvFinancialYear.Rows.Add();
                        iRow = dgvFinancialYear.Rows.Count - 1;
                        dgvFinancialYear["FinancialYear", iRow].Value = detail.FinancialYear_ID;
                        dgvFinancialYear["Title", iRow].Value = detail.FinancialYearName;
                        dgvFinancialYear["startDate", iRow].Value = String.Format("{0:MM/dd/yyyy}", detail.DateStart);
                        dgvFinancialYear["endDate", iRow].Value = String.Format("{0:MM/dd/yyyy}", detail.DateEnd);
                        dgvFinancialYear["status", iRow].Value = clsGenaralName.GetStatusName(detail.StatusID);
                        dgvFinancialYear["ClosedBy", iRow].Value = clsGenaralName.getName_User(detail.ClosedUser_ID);
                        dgvFinancialYear["ClosedDate", iRow].Value = String.Format("{0:MM/dd/yyyy}", detail.DateClosed);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Save Financial Year Months
        private void AddFinancialYearMonths(string sFinYear, DateTime dtStartDate, DateTime dtEndDate)
        {
            DateTime StartDate = DateTime.Now;
            DateTime EndDate = DateTime.Now;
            int iMonth = 0, iDay = 1;

            for (StartDate = dtStartDate; StartDate <= dtEndDate; StartDate = dtStartDate.AddMonths(iMonth))
            {
                EndDate = StartDate.AddMonths(1).AddDays(-1);
                if (StartDate < EndDate)
                {
                    tbl_accFinancialYearMaster_Month Mdetail = new tbl_accFinancialYearMaster_Month(sFinYear, StartDate.ToString("MMMM"),
                        StartDate,
                        EndDate,
                        false,
                        clsSecurity.UserIDLoged,
                        clsSecurity.getServerDateTime(),
                        clsSecurity.UserIDLoged,
                        clsSecurity.UserIDLoged,
                        clsSecurity.TerminalID,
                        clsSecurity.TerminalID,
                        clsSecurity.getServerDateTime(),
                        clsSecurity.getServerDateTime());

                    Mdetail.Insert();
                }

                iMonth++;
            }
        }
        #endregion

        #region Get Auto Generated Financial year
        private bool getAutoGeneratedFinYear_New(string sFormConfigValueCode, ref string sFY_code, ref DateTime dtFinYearStartDate, ref DateTime dtFinYearEndDate)
        {
            bool bStatus = false;
            DateTime dtFinYearStart = DateTime.Now;
            int iYearStartMonth = int.Parse(clsConfig.sFinancialYear_StartMonth);

            tbl_securityConfigForms detail = tbl_securityConfigForms.Select(sFormConfigValueCode);
            if (detail.Counter != 0)
            {
                sFY_code = Convert.ToString(detail.Counter) + "/" + Convert.ToString(detail.Counter + 1);
                dtFinYearStartDate = new DateTime(detail.Counter, iYearStartMonth, 1);
                dtFinYearEndDate = dtFinYearStartDate.AddYears(1).AddDays(-1);

                detail.Counter++;
                detail.Update();

                bStatus = true;
            }

            return bStatus;
        } 
        #endregion

        #region Financial Year Help Methods
        //private static string GetFinancialYear(string sFinYear)
        //{
        //    DateTime dtFinYearStart = new DateTime(int.Parse(sFinYear), 1, 1);
        //    DateTime dtFinYearEnd = dtFinYearStart;
        //    string sDisplayFinYear = "";
        //    if (sFinYear != null)
        //    {
        //        dtFinYearEnd = dtFinYearStart.AddYears(1);
        //        sDisplayFinYear = dtFinYearStart.Year.ToString() + "/" + dtFinYearEnd.Year.ToString();
        //    }

        //    return sDisplayFinYear;
        //}
        //private static DateTime GetFinancialYear_StartDate(string sFinYear, int iStartMonth, int iStartDay)
        //{
        //    DateTime dtFinYearStart = DateTime.Now;
        //    DateTime dtFinYearStartDate = DateTime.Now;
        //    if (sFinYear != null)
        //    {
        //        //dtFinYearStartDate = dtFinYearStart.AddMonths(iStartMonth).AddDays(iStartDay);
        //        dtFinYearStart = new DateTime(int.Parse(sFinYear), iStartMonth, 1);
        //    }

        //    return dtFinYearStart;
        //}

        //private static DateTime GetFinancialYear_EndDate(DateTime dtStartDate)
        //{
        //    //DateTime dtFinYearStart = new DateTime(int.Parse(sFinYear), 1, 1);
        //    DateTime dtFinYearEnd = dtStartDate;
        //    if (dtStartDate != null)
        //    {
        //        dtFinYearEnd = dtStartDate.AddYears(1).AddDays(-1);
        //    }

        //    return dtFinYearEnd;
        //} 
        #endregion
    }
}
