using DataTire;
using Digiteq.Properties;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace Digiteq
{
    public partial class frm_accCreditorSettlement : SEACC_Form
    {
        
        public DataTable dtAPN;
        public DataTable dtPV;
        public DataTable dtDebitNote;
        public DataTable dtJornalEntry_DB;
        public DataTable dtJornalEntry_CR;

        public string glbSupplier_ID = "";


        #region Form load
        public frm_accCreditorSettlement(FormName _enmForm)
        {
            enmForm = _enmForm;
            InitializeComponent();
            Initialize();
        }

        private void frm_accDebtorsSettlement_Load(object sender, EventArgs e)
        {
            SetVisibility_ActionButons(true, false, false, true, false, false, false, false, false);

            CusDataGridViewFormat();
            zpnlSelettedAPN.AllowDrop = true;
            zpnlSettledPayment.AllowDrop = true;
            CreateDataTables();
            ClearFields();

            if (glbSupplier_ID.Length > 0)
            {
                txtSupplierID.Tag = glbSupplier_ID;
                txtSupplierID.Text = clsGenaralName.getName_Supplier(glbSupplier_ID);
                LoadDetail();
            }
        }
        #endregion

        #region Create data table
        private void CreateDataTables()
        {
            dtAPN = new DataTable();
            dtPV = new DataTable();
            dtDebitNote = new DataTable();
            dtJornalEntry_DB = new DataTable();
            dtJornalEntry_CR = new DataTable();

            dtAPN.Columns.Add("APNID", typeof(string));
            dtAPN.Columns.Add("BillNo", typeof(string));
            dtAPN.Columns.Add("APNAmount", typeof(decimal));
            dtAPN.Columns.Add("APNBalance", typeof(decimal));

            dtPV.Columns.Add("PVID", typeof(string));
            dtPV.Columns.Add("PVAmount", typeof(decimal));
            dtPV.Columns.Add("PVBalance", typeof(decimal));

            dtDebitNote.Columns.Add("DebitNoteID", typeof(string));
            dtDebitNote.Columns.Add("DebitNoteAmount", typeof(decimal));
            dtDebitNote.Columns.Add("DebitNoteBalance", typeof(decimal));

            dtJornalEntry_DB.Columns.Add("JornalEntryID", typeof(string));
            dtJornalEntry_DB.Columns.Add("LineNo", typeof(int));
            dtJornalEntry_DB.Columns.Add("JornalEntryAmount", typeof(decimal));
            dtJornalEntry_DB.Columns.Add("JornalEntryBalance", typeof(decimal));


            dtJornalEntry_CR.Columns.Add("JornalEntryID", typeof(string));
            dtJornalEntry_CR.Columns.Add("LineNo", typeof(int));
            dtJornalEntry_CR.Columns.Add("JornalEntryAmount", typeof(decimal));
            dtJornalEntry_CR.Columns.Add("JornalEntryBalance", typeof(decimal));
        }
        #endregion        

        #region Btn New
        private void frm_accCreditorSettlement_SF_newButton_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Save
        private void frm_accCreditorSettlement_SF_saveButton_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            //    string sAPNSettlementID = "";

                            foreach (Control con in zpnlSelettedAPN.Controls)
                            {
                                //   sAPNSettlementID = clsAutocode.getAutoGeneratedCode(sFormConfigCode);
                                //   txtAPNSettlementID.Text = sAPNSettlementID;

                                if (con is TextBox && con.Visible == true)
                                {
                                    string[] sData = con.Tag.ToString().Split(',');
                                    //   int iLineNo = int.Parse(sAPNSettlementID);

                                    #region Apn
                                    if (sData[0] == "APN")
                                    {
                                        tbl_accAccountPayableNote oApn = tbl_accAccountPayableNote.Select(sData[2]);
                                        if (oApn != null)
                                        {
                                            foreach (Control conPayment in zpnlSettledPayment.Controls)
                                            {
                                                if (conPayment is TextBox && conPayment.Visible == true)
                                                {
                                                    string[] sData1 = (conPayment.Tag.ToString().Split(','));

                                                    #region PV
                                                    if (sData1[0] == "PV")
                                                    {
                                                        tbl_accPaymentVoucher oPv = tbl_accPaymentVoucher.Select(sData1[2]);
                                                        if (oPv != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledAPN_WithPV(oPv.PaymentVoucher_ID, oApn.AccountPayableNote_ID);
                                                        }
                                                    }
                                                    #endregion
                                                    #region DBN
                                                    else if (sData1[0] == "DBN")
                                                    {
                                                        tbl_accDebitNote oDbn = tbl_accDebitNote.Select(sData1[2]);
                                                        if (oDbn != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledAPN_WithDebitNote(oDbn.DebitNote_ID, oApn.AccountPayableNote_ID);
                                                        }
                                                    }
                                                    #endregion
                                                    #region JE
                                                    else if (sData1[0] == "Adj")
                                                    {
                                                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData1[2]).Where(p => p.Line_No == int.Parse(sData1[3])).FirstOrDefault();
                                                        if (oJED != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledAPN_WithJournalEntryDR(oJED.JournalEntry_ID, oJED.Line_No, oApn.AccountPayableNote_ID, txtSupplierID.Tag.ToString());
                                                        }
                                                    }
                                                    #endregion
                                                }
                                            }
                                        }
                                    }
                                    #endregion

                                    #region Adj
                                    else if (sData[0] == "Adj")
                                    {
                                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData[2]).Where(p => p.Line_No == int.Parse(sData[3])).FirstOrDefault();
                                        if (oJED != null)
                                        {
                                            foreach (Control conPayment in zpnlSettledPayment.Controls)
                                            {
                                                if (conPayment is TextBox && conPayment.Visible == true)
                                                {
                                                    string[] sData1 = (conPayment.Tag.ToString().Split(','));

                                                    #region PV
                                                    if (sData1[0] == "PV")
                                                    {
                                                        tbl_accPaymentVoucher oPv = tbl_accPaymentVoucher.Select(sData1[2]);
                                                        if (oPv != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledJECR_WithPV(oJED.JournalEntry_ID, oJED.Line_No, oPv.PaymentVoucher_ID);
                                                        }
                                                    }
                                                    #endregion
                                                    #region DBN
                                                    else if (sData1[0] == "DBN")
                                                    {
                                                        tbl_accDebitNote oDbn = tbl_accDebitNote.Select(sData1[2]);
                                                        if (oDbn != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledJECR_WithDebitNote(oJED.JournalEntry_ID, oJED.Line_No, oDbn.DebitNote_ID);
                                                        }
                                                    }
                                                    #endregion
                                                    #region JE
                                                    else if (sData1[0] == "Adj")
                                                    {
                                                        tbl_accJournalEntry_Detail oJEDDR = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData1[2]).Where(p => p.Line_No == int.Parse(sData1[3])).FirstOrDefault();
                                                        if (oJED != null)
                                                        {
                                                            clsHelpMethods_Local.AutoSettledJECR_WithJournalEntryDR(oJED.JournalEntry_ID, oJED.Line_No, oJEDDR.JournalEntry_ID, oJEDDR.Line_No);
                                                        }
                                                    }
                                                    #endregion
                                                }
                                            }

                                        }
                                    }
                                    #endregion
                                }
                            }

                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

                        }
                        catch (Exception ex)
                        {
                            SEACCException.Show(ex);
                            clsValidate.WriteErrorLog("", iFormID, ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                        }
                    }
                }
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormatModify(this.dgvDetail, clsFormatter.colorDigiteqTheamColorSales2, clsFormatter.colorDigiteqTheamColorSales2ForColour, clsFormatter.colorDigiteqTheamColorSales2BackColour);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            IsUpdate = false;
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(this.txtSupplierID, true);
            clsCommon.SetEnableDisable_NormalLabel(this.lblCustomerID, true);
            this.txtSupplierID.Tag = null;
            this.txtAPNSettlementID.Tag = null;
            this.txtSupplierID.Clear();
            this.txtBalance.Text = "0.00";
            this.lblAPNAmount.Text = "0.00";
            this.lblPaymentAmount.Text = "0.00";
            this.pgrPayment.Value = 0;
            this.pgrAPN.Value = 0;

            this.zpnlSelettedAPN.Controls.Clear();
            this.zpnlSettledPayment.Controls.Clear();


            bool flag = clsAutocode.IsAutoGenerated(sFormConfigCode);
            if (flag)
            {
                this.txtAPNSettlementID.Text = "<Auto Generate>";
            }
            else
            {
                this.txtAPNSettlementID.Clear();
            }
            bool enabled = this.txtAPNSettlementID.Enabled;
            if (enabled)
            {
                this.txtAPNSettlementID.SelectAll();
                this.txtAPNSettlementID.Focus();
            }

            //   btnDelete.Visible = false;
            btnNew.Visible = false;
            btnSave.Visible = false;
            //    btnPrint.Visible = false;

            dtpFromDate.Value = clsMethods_GL.getFinancialYear_StartDate(clsMethods_GL.getFinancialYear_ID_Current());
            dtpToDate.Value = clsSecurity.getServerDateTime();

            dgvDetail.Rows.Clear();

            dtDebitNote.Rows.Clear();
            dtPV.Rows.Clear();
            dtAPN.Rows.Clear();
            dtJornalEntry_DB.Rows.Clear();
            dtJornalEntry_CR.Rows.Clear();

            dgvAPN.Rows.Clear();
            dgvPV.Rows.Clear();

            dgvAPN.Columns[3].DefaultCellStyle.Format = "dd/MM/yyyy";
            dgvPV.Columns[2].DefaultCellStyle.Format = "dd/MM/yyyy";
            //  dgnDbn.Rows.Clear();
            //  dgvAdj.Rows.Clear();
        }

        private void ClearSelections()
        {

            this.txtBalance.Text = "0.00";
            this.lblAPNAmount.Text = "0.00";
            this.lblPaymentAmount.Text = "0.00";
            this.pgrPayment.Value = 0;
            this.pgrAPN.Value = 0;

            this.zpnlSelettedAPN.Controls.Clear();
            this.zpnlSettledPayment.Controls.Clear();

            dgvDetail.Rows.Clear();

            dtPV.Rows.Clear();
            dtAPN.Rows.Clear();

            dgvAPN.Rows.Clear();
            dgvPV.Rows.Clear();
        }
        #endregion        

        #region Load Details
        private void LoadDetail()
        {
            if (txtSupplierID.Tag != null && txtSupplierID.Tag.ToString().Trim().Length > 0)
            {
                ClearSelections();

                LoadAPN(txtSupplierID.Tag.ToString());
                LoadPaymentVouchers(txtSupplierID.Tag.ToString());
                LoadDebitNotes(txtSupplierID.Tag.ToString());
                LoadAdjustments(txtSupplierID.Tag.ToString());

                dgvAPN.Sort(dgvAPN.Columns["Date"], ListSortDirection.Descending);
                dgvPV.Sort(dgvPV.Columns["PVDate"], ListSortDirection.Descending);
            }
        }

        #region Load APN
        private void LoadAPN(string sSupplierID)
        {
            int iAmount = 0;
            try
            {
                foreach (tbl_accAccountPayableNote detail in tbl_accAccountPayableNote.SelectAllBySupplier_ID(sSupplierID).Where(p => p.AccountPayableNoteDate.Date >= dtpFromDate.Value.Date && p.AccountPayableNoteDate.Date <= dtpToDate.Value.Date && p.AccountPayableNote_ID != "default" && !p.IsDeleted && !p.IsSeattled))
                {
                    this.dgvAPN.Rows.Add();
                    int rowIndex = this.dgvAPN.Rows.Count - 1;
                    this.dgvAPN["Txn", rowIndex].Value = "APN";
                    this.dgvAPN["TxnID", rowIndex].Value = detail.AccountPayableNote_ID;
                    this.dgvAPN["refNo", rowIndex].Value = detail.BillNo;
                    this.dgvAPN["Date", rowIndex].Value = detail.AccountPayableNoteDate;
                    this.dgvAPN["Amount", rowIndex].Value = (detail.GrandTotal - detail.SettledAmount);

                    iAmount += (int)detail.GrandTotal;
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
            this.pgrAPN.Maximum = iAmount;
            this.pgrPayment.Maximum = iAmount;
        }
        #endregion

        #region Load PaymentVouchers
        private void LoadPaymentVouchers(string sSupplierID)
        {
            try
            {
                foreach (tbl_accPaymentVoucher detail in tbl_accPaymentVoucher.SelectAllBySupplier_ID(sSupplierID).Where(p => p.PaymentVoucherDate.Date >= dtpFromDate.Value.Date && p.PaymentVoucherDate.Date <= dtpToDate.Value.Date && p.PaymentVoucher_ID != "default" && !p.IsDeleted && !p.IsSeattled))
                {
                    this.dgvPV.Rows.Add();
                    int rowIndex = this.dgvPV.Rows.Count - 1;
                    this.dgvPV["TxnPv", rowIndex].Value = "PV";
                    this.dgvPV["TxnIDPV", rowIndex].Value = detail.PaymentVoucher_ID;
                    this.dgvPV["PVDate", rowIndex].Value = detail.PaymentVoucherDate;
                    this.dgvPV["PVAmount", rowIndex].Value = (detail.TotalAmount - detail.SettledAmount);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Load JV
        private void LoadAdjustments(string sSupplierID)
        {
            try
            {
                foreach (tbl_accJournalEntry_Detail detailJED in tbl_accJournalEntry_Detail.SelectAllBySupplier_ID(sSupplierID).Where(p => p.Supplier_ID != "default" && !p.IsSeattled))
                {
                    tbl_accJournalEntry detail = tbl_accJournalEntry.Select(detailJED.JournalEntry_ID);
                    if (detail != null && detail.JournalEntryDate.Date >= dtpFromDate.Value.Date && detail.JournalEntryDate.Date <= dtpToDate.Value.Date && !detail.IsDeleted)
                    {
                        if (detailJED.IsCredit)
                        {
                            this.dgvAPN.Rows.Add();
                            int rowIndex = this.dgvAPN.Rows.Count - 1;
                            this.dgvAPN["Txn", rowIndex].Value = "Adj";
                            this.dgvAPN["TxnID", rowIndex].Value = detail.JournalEntry_ID;
                            this.dgvAPN["TxnID", rowIndex].Tag = detailJED.Line_No;
                            this.dgvAPN["refNo", rowIndex].Value = " - ";
                            this.dgvAPN["Date", rowIndex].Value = detail.JournalEntryDate;
                            this.dgvAPN["Amount", rowIndex].Value = (detailJED.Amount - detailJED.SeattleAmount);
                        }
                        else
                        {
                            this.dgvPV.Rows.Add();
                            int rowIndex = this.dgvPV.Rows.Count - 1;
                            this.dgvPV["TxnPv", rowIndex].Value = "Adj";
                            this.dgvPV["TxnIDPV", rowIndex].Value = detail.JournalEntry_ID;
                            this.dgvPV["TxnIDPV", rowIndex].Tag = detailJED.Line_No;
                            this.dgvPV["PVDate", rowIndex].Value = detail.JournalEntryDate;
                            this.dgvPV["PVAmount", rowIndex].Value = (detailJED.Amount - detailJED.SeattleAmount);
                        }
                    }
                }
            }

            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Load DebitNotes
        private void LoadDebitNotes(string Supplier_ID)
        {
            try
            {
                foreach (tbl_accDebitNote detail in tbl_accDebitNote.SelectAll().Where(p => p.Supplier_ID == Supplier_ID && p.DebitNote_Date.Date >= dtpFromDate.Value.Date && p.DebitNote_Date.Date <= dtpToDate.Value.Date && p.DebitNote_ID != "default" && !p.IsDeleted && !p.IsSettled))
                {
                    this.dgvPV.Rows.Add();
                    int rowIndex = this.dgvPV.Rows.Count - 1;
                    this.dgvPV["TxnPv", rowIndex].Value = "DBN";
                    this.dgvPV["TxnIDPV", rowIndex].Value = detail.DebitNote_ID;
                    this.dgvPV["PVDate", rowIndex].Value = detail.DebitNote_Date;
                    this.dgvPV["PVAmount", rowIndex].Value = (detail.GrandTotal - detail.SettledAmount);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #endregion

        #region Events DoubleClick
        private void txtSupplierID_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_MasterSupplier(ref txtSupplierID);
            LoadDetail();
        }
        #endregion

        #region Events DragDrop
        private void zpnlSelettedAPN_DragDrop_1(object sender, DragEventArgs e)
        {
            try
            {
                if (e.Effect == DragDropEffects.Move)
                {
                    string[] sData = ((System.String)e.Data.GetData(typeof(System.String))).Split(',');
                    TextBox textBox = new TextBox();
                    textBox.Multiline = true;
                    if (sData[0] == "APN")
                    {
                        tbl_accAccountPayableNote oApn = tbl_accAccountPayableNote.Select(sData[2]);
                        if (oApn != null)
                        {
                            textBox.Size = new Size(80, 40);

                            textBox.Name = oApn.AccountPayableNote_ID;
                            decimal dAmount = oApn.GrandTotal - oApn.SettledAmount;
                            textBox.Text = "No : " + oApn.AccountPayableNote_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                            textBox.Tag = (System.String)e.Data.GetData(typeof(System.String));
                            textBox.BackColor = Color.FromArgb(179, 113, 113);
                            textBox.ForeColor = Color.White;

                            zpnlSelettedAPN.Controls.Add(textBox);
                            dgvAPN.Rows.RemoveAt(int.Parse(sData[1]));
                            calculate();
                        }
                    }
                    else if (sData[0] == "Adj")
                    {
                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData[2]).Where(p => p.Line_No == int.Parse(sData[3])).FirstOrDefault();

                        if (oJED != null)
                        {
                            textBox.Size = new Size(80, 40);

                            textBox.Name = oJED.JournalEntry_ID;
                            decimal dAmount = oJED.Amount - oJED.SeattleAmount;
                            textBox.Text = "No : " + oJED.JournalEntry_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                            textBox.Tag = (System.String)e.Data.GetData(typeof(System.String));
                            textBox.BackColor = Color.FromArgb(179, 113, 113);
                            textBox.ForeColor = Color.White;

                            zpnlSelettedAPN.Controls.Add(textBox);
                            dgvAPN.Rows.RemoveAt(int.Parse(sData[1]));
                            calculate();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }

        private void zpnlSelettedAPN_DragEnter(object sender, DragEventArgs e)
        {
            if (dgvAPN.SelectedRows.Count > 0)
                e.Effect = DragDropEffects.Move;
        }

        private void zpnlSettledPayment_DragDrop(object sender, DragEventArgs e)
        {
            try
            {
                if (e.Effect == DragDropEffects.Move)
                {
                    string[] sData = ((System.String)e.Data.GetData(typeof(System.String))).Split(',');
                    TextBox textBox = new TextBox();
                    textBox.Multiline = true;
                    if (sData[0] == "PV")
                    {
                        tbl_accPaymentVoucher oPv = tbl_accPaymentVoucher.Select(sData[2]);
                        if (oPv != null)
                        {
                            textBox.Size = new Size(80, 40);

                            textBox.Name = oPv.PaymentVoucher_ID;
                            decimal dAmount = oPv.TotalAmount - oPv.SettledAmount;
                            textBox.Text = "No : " + oPv.PaymentVoucher_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                            textBox.Tag = (System.String)e.Data.GetData(typeof(System.String));
                            textBox.BackColor = Color.FromArgb(179, 113, 113);
                            textBox.ForeColor = Color.White;

                            zpnlSettledPayment.Controls.Add(textBox);
                            dgvPV.Rows.RemoveAt(int.Parse(sData[1]));
                            calculate();
                        }
                    }
                    else if (sData[0] == "DBN")
                    {
                        tbl_accDebitNote oDbn = tbl_accDebitNote.Select(sData[2]);
                        if (oDbn != null)
                        {
                            textBox.Size = new Size(80, 40);

                            textBox.Name = oDbn.AccountPayableNote_ID;
                            decimal dAmount = oDbn.GrandTotal - oDbn.SettledAmount;
                            textBox.Text = "No : " + oDbn.AccountPayableNote_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                            textBox.Tag = (System.String)e.Data.GetData(typeof(System.String));
                            textBox.BackColor = Color.FromArgb(179, 113, 113);
                            textBox.ForeColor = Color.White;

                            zpnlSettledPayment.Controls.Add(textBox);
                            dgvPV.Rows.RemoveAt(int.Parse(sData[1]));
                            calculate();
                        }
                    }
                    else if (sData[0] == "Adj")
                    {
                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData[2]).Where(p => p.Line_No == int.Parse(sData[3])).FirstOrDefault();
                        if (oJED != null)
                        {
                            textBox.Size = new Size(80, 40);

                            textBox.Name = oJED.JournalEntry_ID;
                            decimal dAmount = oJED.Amount - oJED.SeattleAmount;
                            textBox.Text = "No : " + oJED.JournalEntry_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                            textBox.Tag = (System.String)e.Data.GetData(typeof(System.String));
                            textBox.BackColor = Color.FromArgb(179, 113, 113);
                            textBox.ForeColor = Color.White;

                            zpnlSettledPayment.Controls.Add(textBox);
                            dgvPV.Rows.RemoveAt(int.Parse(sData[1]));
                            calculate();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }

        private void zpnlSettledPayment_DragEnter(object sender, DragEventArgs e)
        {
            if (dgvPV.SelectedRows.Count > 0)
                e.Effect = DragDropEffects.Move;
        }
        #endregion

        #region Events MouseLeave
        private void dgvAPN_MouseLeave(object sender, EventArgs e)
        {
            Cursor = Cursors.Default;
        }

        private void dgvPV_MouseLeave(object sender, EventArgs e)
        {
            Cursor = Cursors.Default;
        }
        #endregion

        #region Events MouseDown
        private void dgvAPN_MouseUp(object sender, MouseEventArgs e)
        {
            if (dgvAPN.RowCount > 0)
            {
                string sTxnId = dgvAPN.SelectedRows[0].Cells[1].Value.ToString();
                string sTxnType = dgvAPN.SelectedRows[0].Cells[0].Value.ToString();
                string lineNo = "0";
                try
                {
                    lineNo = dgvAPN.SelectedRows[0].Cells[1].Tag.ToString();
                }
                catch (Exception)
                {
                }

                string text = sTxnType + "," + dgvAPN.CurrentCell.RowIndex + "," + sTxnId + "," + lineNo;
                if (text != null)
                    dgvAPN.DoDragDrop(text, DragDropEffects.Move);
            }
        }

        private void dgvPV_MouseUp(object sender, MouseEventArgs e)
        {
            if (dgvPV.RowCount > 0)
            {
                string sTxnId = dgvPV.SelectedRows[0].Cells[1].Value.ToString();
                string sTxnType = dgvPV.SelectedRows[0].Cells[0].Value.ToString();
                string lineNo = "0";
                try
                {
                    lineNo = dgvPV.SelectedRows[0].Cells[1].Tag.ToString();
                }
                catch (Exception)
                {
                }
                string text = sTxnType + "," + dgvPV.CurrentCell.RowIndex + "," + sTxnId + "," + lineNo;
                if (text != null)
                    dgvPV.DoDragDrop(text, DragDropEffects.Move);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtSupplierID.TextLength == 0)
            {
                strMessage += "\n" + "Supplier Name ";
                bStatus = false;
            }

            if (bStatus == false)
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {

            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Fill Datagrid
        private void FillDetail()
        {
            try
            {
                int iRow = 0;
                dgvDetail.Rows.Clear();

                decimal dPVAvailableAmount = 0, dDebitNoteAvailableAmount = 0, dJournalEntryAvailableAmount = 0, dSettledAmount = 0, dAPNBalance = 0;
                #region APN
                foreach (DataRow invRow in dtAPN.Rows)
                {
                    tbl_accAccountPayableNote objAPN = tbl_accAccountPayableNote.Select(invRow["APNID"].ToString());
                    if (objAPN != null)
                    {
                        dAPNBalance = decimal.Parse(invRow["APNBalance"].ToString());

                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        Fill_Datagrid(iRow, objAPN.AccountPayableNoteDate.ToShortDateString(), objAPN.AccountPayableNote_ID, objAPN.GrandTotal, " APN - " + objAPN.AccountPayableNote_ID, 0, dAPNBalance, dAPNBalance * -1);

                        #region PV
                        foreach (DataRow chkRow in dtPV.Rows)
                        {
                            tbl_accPaymentVoucher objPV = tbl_accPaymentVoucher.Select(chkRow["PVID"].ToString());
                            if (objPV != null)
                            {
                                dSettledAmount = 0;
                                dPVAvailableAmount = decimal.Parse(chkRow["PVBalance"].ToString());
                                dAPNBalance = decimal.Parse(invRow["APNBalance"].ToString());
                                if (dPVAvailableAmount > 0 && dAPNBalance > 0)
                                {
                                    if (dAPNBalance <= dPVAvailableAmount) //if PV has enough cash to settled 
                                    {
                                        dSettledAmount = dAPNBalance;
                                        invRow["APNBalance"] = 0;
                                        chkRow["PVBalance"] = (dPVAvailableAmount - dAPNBalance);
                                    }
                                    else //if APN amount is greter than PV amount  
                                    {
                                        dSettledAmount = dPVAvailableAmount;
                                        invRow["APNBalance"] = (dAPNBalance - dPVAvailableAmount);
                                        chkRow["PVBalance"] = 0;
                                    }
                                    //add to grid
                                    dgvDetail.Rows.Add();
                                    iRow = dgvDetail.Rows.Count - 1;
                                    Fill_Datagrid(iRow, "", "", objPV.TotalAmount, " Payment Voucher - " + objPV.PaymentVoucher_ID, dSettledAmount, 0, getAPNBalance(invRow));
                                }
                            }
                        }
                        #endregion

                        #region DBN
                        foreach (DataRow creRow in dtDebitNote.Rows)
                        {
                            tbl_accDebitNote objDebitNote = tbl_accDebitNote.Select(creRow["DebitNoteID"].ToString());
                            if (objDebitNote != null)
                            {
                                dSettledAmount = 0;
                                dDebitNoteAvailableAmount = decimal.Parse(creRow["DebitNoteBalance"].ToString());
                                dAPNBalance = decimal.Parse(invRow["APNBalance"].ToString());
                                if (dDebitNoteAvailableAmount > 0 && dAPNBalance > 0)
                                {
                                    if (dAPNBalance <= dDebitNoteAvailableAmount) //if DBN has enough cash to settled 
                                    {
                                        dSettledAmount = dAPNBalance;
                                        invRow["APNBalance"] = 0;
                                        creRow["DebitNoteBalance"] = (dDebitNoteAvailableAmount - dAPNBalance);
                                    }
                                    else //if APN amount is greter than Receipt amount  
                                    {
                                        dSettledAmount = dDebitNoteAvailableAmount;
                                        invRow["APNBalance"] = (dAPNBalance - dDebitNoteAvailableAmount);
                                        creRow["DebitNoteBalance"] = 0;
                                    }
                                    //add to grid
                                    dgvDetail.Rows.Add();
                                    iRow = dgvDetail.Rows.Count - 1;
                                    Fill_Datagrid(iRow, "", "", objDebitNote.SettledAmount, " Debit Note - " + objDebitNote.DebitNote_ID, dSettledAmount, 0, getAPNBalance(invRow));
                                }
                            }
                        }
                        #endregion

                        #region JE
                        foreach (DataRow creRow in dtJornalEntry_DB.Rows)
                        {
                            tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(creRow["JornalEntryID"].ToString()).Where(p => p.Line_No == int.Parse(creRow["LineNo"].ToString())).FirstOrDefault();
                            if (oJED != null)
                            {
                                dSettledAmount = 0;
                                dJournalEntryAvailableAmount = decimal.Parse(creRow["JornalEntryBalance"].ToString());
                                dAPNBalance = decimal.Parse(invRow["APNBalance"].ToString());
                                if (dJournalEntryAvailableAmount > 0 && dAPNBalance > 0)
                                {
                                    if (dAPNBalance <= dJournalEntryAvailableAmount) //if DBN has enough cash to settled 
                                    {
                                        dSettledAmount = dAPNBalance;
                                        invRow["APNBalance"] = 0;
                                        creRow["JornalEntryBalance"] = (dJournalEntryAvailableAmount - dAPNBalance);
                                    }
                                    else //if APN amount is greter than Receipt amount  
                                    {
                                        dSettledAmount = dJournalEntryAvailableAmount;
                                        invRow["APNBalance"] = (dAPNBalance - dJournalEntryAvailableAmount);
                                        creRow["JornalEntryBalance"] = 0;
                                    }
                                    //add to grid
                                    dgvDetail.Rows.Add();
                                    iRow = dgvDetail.Rows.Count - 1;
                                    Fill_Datagrid(iRow, "", "", oJED.SeattleAmount, " Journal Entry - " + oJED.JournalEntry_ID, dSettledAmount, 0, getAPNBalance(invRow));
                                }
                            }
                        }
                        #endregion
                    }
                }
                #endregion
                #region JE
                foreach (DataRow invRow in dtJornalEntry_CR.Rows)
                {
                    tbl_accJournalEntry_Detail oJEDCR = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(invRow["JornalEntryID"].ToString()).Where(p => p.Line_No == int.Parse(invRow["LineNo"].ToString())).FirstOrDefault();
                    if (oJEDCR != null)
                    {
                        tbl_accJournalEntry oJE = tbl_accJournalEntry.Select(oJEDCR.JournalEntry_ID);
                        if (oJE != null)
                        {
                            dAPNBalance = decimal.Parse(invRow["JornalEntryBalance"].ToString());

                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, oJE.JournalEntryDate.ToShortDateString(), oJEDCR.JournalEntry_ID, oJEDCR.Amount, " JE - " + oJEDCR.JournalEntry_ID, 0, dAPNBalance, dAPNBalance * -1);


                            #region PV
                            foreach (DataRow chkRow in dtPV.Rows)
                            {
                                tbl_accPaymentVoucher objPV = tbl_accPaymentVoucher.Select(chkRow["PVID"].ToString());
                                if (objPV != null)
                                {
                                    dSettledAmount = 0;
                                    dPVAvailableAmount = decimal.Parse(chkRow["PVBalance"].ToString());
                                    dAPNBalance = decimal.Parse(invRow["JornalEntryBalance"].ToString());
                                    if (dPVAvailableAmount > 0 && dAPNBalance > 0)
                                    {
                                        if (dAPNBalance <= dPVAvailableAmount) //if PV has enough cash to settled 
                                        {
                                            dSettledAmount = dAPNBalance;
                                            invRow["JornalEntryBalance"] = 0;
                                            chkRow["PVBalance"] = (dPVAvailableAmount - dAPNBalance);
                                        }
                                        else //if APN amount is greter than PV amount  
                                        {
                                            dSettledAmount = dPVAvailableAmount;
                                            invRow["JornalEntryBalance"] = (dAPNBalance - dPVAvailableAmount);
                                            chkRow["PVBalance"] = 0;
                                        }
                                        //add to grid
                                        dgvDetail.Rows.Add();
                                        iRow = dgvDetail.Rows.Count - 1;
                                        Fill_Datagrid(iRow, "", "", objPV.TotalAmount, " Payment Voucher - " + objPV.PaymentVoucher_ID, dSettledAmount, 0, getJEBalance(invRow));
                                    }
                                }
                            }
                            #endregion

                            #region DBN
                            foreach (DataRow creRow in dtDebitNote.Rows)
                            {
                                tbl_accDebitNote objDebitNote = tbl_accDebitNote.Select(creRow["DebitNoteID"].ToString());
                                if (objDebitNote != null)
                                {
                                    dSettledAmount = 0;
                                    dDebitNoteAvailableAmount = decimal.Parse(creRow["DebitNoteBalance"].ToString());
                                    dAPNBalance = decimal.Parse(invRow["JornalEntryBalance"].ToString());
                                    if (dDebitNoteAvailableAmount > 0 && dAPNBalance > 0)
                                    {
                                        if (dAPNBalance <= dDebitNoteAvailableAmount) //if DBN has enough cash to settled 
                                        {
                                            dSettledAmount = dAPNBalance;
                                            invRow["JornalEntryBalance"] = 0;
                                            creRow["DebitNoteBalance"] = (dDebitNoteAvailableAmount - dAPNBalance);
                                        }
                                        else //if APN amount is greter than Receipt amount  
                                        {
                                            dSettledAmount = dDebitNoteAvailableAmount;
                                            invRow["JornalEntryBalance"] = (dAPNBalance - dDebitNoteAvailableAmount);
                                            creRow["DebitNoteBalance"] = 0;
                                        }
                                        //add to grid
                                        dgvDetail.Rows.Add();
                                        iRow = dgvDetail.Rows.Count - 1;
                                        Fill_Datagrid(iRow, "", "", objDebitNote.SettledAmount, " Debit Note - " + objDebitNote.DebitNote_ID, dSettledAmount, 0, getJEBalance(invRow));
                                    }
                                }
                            }
                            #endregion

                            #region JE
                            foreach (DataRow creRow in dtJornalEntry_DB.Rows)
                            {
                                tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(creRow["JornalEntryID"].ToString()).Where(p => p.Line_No == int.Parse(creRow["LineNo"].ToString())).FirstOrDefault();
                                if (oJED != null)
                                {
                                    dSettledAmount = 0;
                                    dJournalEntryAvailableAmount = decimal.Parse(creRow["JornalEntryBalance"].ToString());
                                    dAPNBalance = decimal.Parse(invRow["JornalEntryBalance"].ToString());
                                    if (dJournalEntryAvailableAmount > 0 && dAPNBalance > 0)
                                    {
                                        if (dAPNBalance <= dJournalEntryAvailableAmount) //if DBN has enough cash to settled 
                                        {
                                            dSettledAmount = dAPNBalance;
                                            invRow["JornalEntryBalance"] = 0;
                                            creRow["JornalEntryBalance"] = (dJournalEntryAvailableAmount - dAPNBalance);
                                        }
                                        else //if APN amount is greter than Receipt amount  
                                        {
                                            dSettledAmount = dJournalEntryAvailableAmount;
                                            invRow["JornalEntryBalance"] = (dAPNBalance - dJournalEntryAvailableAmount);
                                            creRow["JornalEntryBalance"] = 0;
                                        }
                                        //add to grid
                                        dgvDetail.Rows.Add();
                                        iRow = dgvDetail.Rows.Count - 1;
                                        Fill_Datagrid(iRow, "", "", oJED.SeattleAmount, " Journal Entry - " + oJED.JournalEntry_ID, dSettledAmount, 0, getJEBalance(invRow));
                                    }
                                }
                            }
                            #endregion
                        }
                    }
                }
                #endregion
                //   if (iRow > 7)
                //   dgvDetail.Columns["PaymentType"].Width -= 16;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        private decimal getAPNBalance(DataRow dr)
        {
            decimal dBalance = 0;
            dBalance = decimal.Parse(dr["APNBalance"].ToString());
            if (dBalance > 0)
                dBalance *= -1;
            return dBalance;
        }
        private decimal getJEBalance(DataRow dr)
        {
            decimal dBalance = 0;
            dBalance = decimal.Parse(dr["JornalEntryBalance"].ToString());
            if (dBalance > 0)
                dBalance *= -1;
            return dBalance;
        }
        private void Fill_Datagrid(int iRow, string sDate, string sAPNID, decimal sOriginalAmount, string sIncomeType, decimal dDebit, decimal dCredit, decimal dBalance)
        {
            try
            {
                dgvDetail["SettlementDate", iRow].Value = sDate;
                dgvDetail["APNID", iRow].Value = sAPNID;
                dgvDetail["Narration", iRow].Value = sIncomeType;
                dgvDetail["DocumentAmount", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(sOriginalAmount);
                dgvDetail["DebitAmount", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(dDebit);
                dgvDetail["CreditAmount", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(dCredit);
                dgvDetail["BalanceAmount", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(dBalance);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region calculate APN
        private void calculate()
        {
            try
            {
                dtJornalEntry_CR.Rows.Clear();
                dtAPN.Rows.Clear();

                dtPV.Rows.Clear();
                dtDebitNote.Rows.Clear();
                dtJornalEntry_DB.Rows.Clear();

                #region CR
                decimal dInvoiceTotal = 0;
                foreach (Control con in zpnlSelettedAPN.Controls)
                {
                    if (con is TextBox && con.Visible == true)
                    {
                        string[] sData = con.Tag.ToString().Split(',');

                        #region Apn
                        if (sData[0] == "APN")
                        {
                            tbl_accAccountPayableNote oApn = tbl_accAccountPayableNote.Select(sData[2]);
                            if (oApn != null)
                            {
                                dInvoiceTotal += (oApn.GrandTotal - oApn.SettledAmount);
                                dtAPN.Rows.Add(oApn.AccountPayableNote_ID, oApn.BillNo, oApn.GrandTotal, oApn.GrandTotal - oApn.SettledAmount);
                            }
                        }
                        #endregion
                        #region Adj
                        else if (sData[0] == "Adj")
                        {
                            tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData[2]).Where(p => p.Line_No == int.Parse(sData[3])).FirstOrDefault();
                            if (oJED != null)
                            {
                                dInvoiceTotal += (oJED.Amount - oJED.SeattleAmount);
                                dtJornalEntry_CR.Rows.Add(oJED.JournalEntry_ID, oJED.Line_No, oJED.Amount, oJED.Amount - oJED.SeattleAmount);
                            }
                        }
                        #endregion
                    }
                }

                try
                {
                    pgrAPN.Value = int.Parse(dInvoiceTotal.ToString());
                }
                catch (Exception)
                {
                    pgrAPN.Value = pgrAPN.Maximum;
                }
                #endregion

                #region DB
                decimal dChequeTotal = 0;
                foreach (Control con in zpnlSettledPayment.Controls)
                {
                    if (con is TextBox && con.Visible == true)
                    {
                        string[] sData = (con.Tag.ToString().Split(','));

                        #region PV
                        if (sData[0] == "PV")
                        {
                            tbl_accPaymentVoucher oPv = tbl_accPaymentVoucher.Select(sData[2]);
                            if (oPv != null)
                            {
                                dChequeTotal += (oPv.TotalAmount - oPv.SettledAmount);
                                dtPV.Rows.Add(oPv.PaymentVoucher_ID, oPv.TotalAmount, oPv.TotalAmount - oPv.SettledAmount);
                            }
                        }
                        #endregion
                        #region DBN
                        else if (sData[0] == "DBN")
                        {
                            tbl_accDebitNote oDbn = tbl_accDebitNote.Select(sData[2]);
                            if (oDbn != null)
                            {
                                dChequeTotal += (oDbn.GrandTotal - oDbn.SettledAmount);
                                dtDebitNote.Rows.Add(oDbn.DebitNote_ID, oDbn.GrandTotal, oDbn.GrandTotal - oDbn.SettledAmount);
                            }
                        }
                        #endregion
                        #region JE
                        else if (sData[0] == "Adj")
                        {
                            tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sData[2]).Where(p => p.Line_No == int.Parse(sData[3])).FirstOrDefault();
                            if (oJED != null)
                            {
                                dChequeTotal += (oJED.Amount - oJED.SeattleAmount);
                                dtJornalEntry_DB.Rows.Add(oJED.JournalEntry_ID, oJED.Line_No, oJED.Amount, oJED.Amount - oJED.SeattleAmount);
                            }
                        }
                        #endregion
                    }
                }
                try
                {
                    pgrPayment.Value = int.Parse(dChequeTotal.ToString());
                }
                catch (Exception)
                {
                    pgrPayment.Value = pgrPayment.Maximum;
                }
                #endregion

                lblAPNAmount.Text = clsFormatter.FormatToCurrecyWithThousendSep(dInvoiceTotal);
                lblPaymentAmount.Text = clsFormatter.FormatToCurrecyWithThousendSep(dChequeTotal);

                #region Calculate balances
                decimal dInvoice = 0, dPayament = 0, dBalance = 0;
                try
                {
                    if (lblAPNAmount.TextLength > 0)
                        dInvoice = decimal.Parse(lblAPNAmount.Text.Trim());
                    if (lblPaymentAmount.TextLength > 0)
                        dPayament = decimal.Parse(lblPaymentAmount.Text.Trim());
                }
                catch (Exception) { }
                dBalance = dPayament - dInvoice;
                txtBalance.Text = clsFormatter.FormatToCurrecyWithThousendSep(dBalance);
                #endregion

                FillDetail();
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        private void dtpFromDate_ValueChanged(object sender, EventArgs e)
        {
            LoadDetail();
        }

        private void dgvPV_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            if (dgvPV.RowCount > 0)
            {
                string sTxnId = dgvPV.SelectedRows[0].Cells[1].Value.ToString();
                string sTxnType = dgvPV.SelectedRows[0].Cells[0].Value.ToString();
                int iRowIndex = dgvPV.CurrentCell.RowIndex;
                string lineNo = "0";
                try
                {
                    lineNo = dgvPV.SelectedRows[0].Cells[1].Tag.ToString();
                }
                catch (Exception)
                {
                }

                string sText = sTxnType + "," + iRowIndex + "," + sTxnId + "," + lineNo;
                if (sText != null && sText != "")
                {
                    #region PV
                    if (sTxnType == "PV")
                    {
                        tbl_accPaymentVoucher oPv = tbl_accPaymentVoucher.Select(sTxnId);
                        if (oPv != null)
                        {
                            decimal dAmount = oPv.TotalAmount - oPv.SettledAmount;
                            string sDisplayText = "No : " + oPv.PaymentVoucher_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);

                            zpnlSettledPayment.Controls.Add(CreateTextBox(oPv.PaymentVoucher_ID, sDisplayText, sText));
                            dgvPV.Rows.RemoveAt(iRowIndex);
                            calculate();
                        }
                    }
                    #endregion

                    #region DBN
                    else if (sTxnType == "DBN")
                    {
                        tbl_accDebitNote oDbn = tbl_accDebitNote.Select(sTxnId);
                        if (oDbn != null)
                        {
                            decimal dAmount = oDbn.GrandTotal - oDbn.SettledAmount;
                            string sDisplayText = "No : " + oDbn.AccountPayableNote_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);

                            zpnlSettledPayment.Controls.Add(CreateTextBox(oDbn.AccountPayableNote_ID, sDisplayText, sText));
                            dgvPV.Rows.RemoveAt(iRowIndex);
                            calculate();
                        }
                    }
                    #endregion

                    #region Adj
                    else if (sTxnType == "Adj")
                    {
                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sTxnId).Where(p => p.Line_No == int.Parse(lineNo)).FirstOrDefault();
                        if (oJED != null)
                        {
                            decimal dAmount = oJED.Amount - oJED.SeattleAmount;
                            string sDisplayText = "No : " + oJED.JournalEntry_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);

                            zpnlSettledPayment.Controls.Add(CreateTextBox(oJED.JournalEntry_ID, sDisplayText, sText));
                            dgvPV.Rows.RemoveAt(iRowIndex);
                            calculate();
                        }
                    }
                    #endregion
                }
            }
        }

        private void dgvAPN_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            if (dgvAPN.RowCount > 0)
            {
                string sTxnId = dgvAPN.SelectedRows[0].Cells[1].Value.ToString();
                string sTxnType = dgvAPN.SelectedRows[0].Cells[0].Value.ToString();
                int iRowIndex = dgvAPN.CurrentCell.RowIndex;
                string lineNo = "0";
                try
                {
                    lineNo = dgvAPN.SelectedRows[0].Cells[1].Tag.ToString();
                }
                catch (Exception)
                {
                }

                string sText = sTxnType + "," + iRowIndex + "," + sTxnId + "," + lineNo;
                if (sText != null && sText != "")
                {
                    #region APN
                    if (sTxnType == "APN")
                    {
                        tbl_accAccountPayableNote oApn = tbl_accAccountPayableNote.Select(sTxnId);
                        if (oApn != null)
                        {
                            decimal dAmount = oApn.GrandTotal - oApn.SettledAmount;
                            string sDisplayText = "No : " + oApn.AccountPayableNote_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);

                            zpnlSelettedAPN.Controls.Add(CreateTextBox(oApn.AccountPayableNote_ID, sDisplayText, sText));
                            dgvAPN.Rows.RemoveAt(iRowIndex);
                            calculate();
                        }
                    }
                    #endregion

                    #region ADJ
                    else if (sTxnType == "Adj")
                    {
                        tbl_accJournalEntry_Detail oJED = tbl_accJournalEntry_Detail.SelectAllByJournalEntry_ID(sTxnId).Where(p => p.Line_No == int.Parse(lineNo)).FirstOrDefault();

                        if (oJED != null)
                        {
                            decimal dAmount = oJED.Amount - oJED.SeattleAmount;
                            string sDisplayText = "No : " + oJED.JournalEntry_ID + " \r\n" + "Amt : " + clsFormatter.FormatToCurrecyWithThousendSep(dAmount);

                            zpnlSelettedAPN.Controls.Add(CreateTextBox(oJED.JournalEntry_ID, sDisplayText, sText));
                            dgvAPN.Rows.RemoveAt(iRowIndex);
                            calculate();
                        }
                    }
                    #endregion
                }
            }
        }

        private TextBox CreateTextBox(string sTxID, string sDisplayDetails, string sText)
        {
            TextBox txtBox = new TextBox();
            txtBox.Multiline = true;
            txtBox.Size = new Size(80, 40);

            txtBox.Name = sTxID.ToString();
            txtBox.Text = sDisplayDetails.ToString();
            txtBox.Tag = sText.ToString();
            txtBox.BackColor = Color.FromArgb(179, 113, 113);
            txtBox.ForeColor = Color.White;

            return txtBox;
        }

    }
}