import * as Yup from "yup";
import { todayISO } from "../../../helpers/transformDateFields";

export const getFields = (uiDataFiltered) => ({
    id: {
      name: "id",
      type: "text",
      placeholder: "ID",
      initialValue: "<Auto>",
      disabled: true,
    },
    make: {
      name: "make",
      type: "select",
      placeholder: "Make",
      dataBinding: {
        data: uiDataFiltered.Make,
        keyField: "id",
        valueField: "value",
      },
      validation: Yup.number().required("Type of Vehicle is required"),
    },
    model: {
      name: "model",
      type: "select",
      placeholder: "Model",
      dataBinding: {
        data: uiDataFiltered.Model,
        keyField: "id",
        valueField: "value",
      },
       validation: Yup.number().required("Type of Vehicle is required"),
    },
    grade: {
      name: "grade",
      type: "select",
      placeholder: "Grade",
      dataBinding: {
        data: uiDataFiltered.Grade,
        keyField: "id",
        valueField: "value",
      },
       validation: Yup.number().required("Grade of Vehicle is required"),
    },
    colour: {
      name: "colour",
      type: "select",
      placeholder: "Colour",
      dataBinding: {
        data: uiDataFiltered.Colour,
        keyField: "id",
        valueField: "value",
      },
       validation: Yup.number().required("Colour of Vehicle is required"),
    },
    year: {
      name: "year",
      type: "number",
      placeholder: "Year",
      initialValue: 2024,
      validation: Yup.number().required("Year is required"),
    },
    millage: {
      name: "millage",
      type: "number",
      placeholder: "Millage",
      initialValue: 0,
      validation: Yup.number().required("Millage is required"),
    },
    engineCapacity: {
      name: "engineCapacity",
      type: "number",
      placeholder: "Engine Capacity",
      initialValue: 0,
      // validation: Yup.number().required("Engine Capacity is required"),
    },
    fuelType: {
      name: "fuelType",
      type: "select",
      placeholder: "Fuel Type",
      dataBinding: {
        data: uiDataFiltered.FuelType,
        keyField: "id",
        valueField: "value",
      },
       validation: Yup.number().required("Fuel Type of Vehicle is required"),
    },
    transmission: {
      name: "transmission",
      type: "select",
      placeholder: "Transmission",
      dataBinding: {
        data: uiDataFiltered.Transmission,
        keyField: "id",
        valueField: "value",
      },
       validation: Yup.number().required("Transmission of Vehicle is required"),
    },
    chassisNo: {
      name: "chassisNo",
      type: "text",
      placeholder: "Chassis No",
      initialValue: "",
      // validation: Yup.string().required("Chassis No is required"),
    },
    supplier: {
      name: "supplier",
      type: "partner-select",
      placeholder: "Supplier",
      initialValue: 0,
      validation: Yup.number().required("Supplier is required"),
      isOpen: false,
    },
    purchaseDate: {
      name: "purchaseDate",
      type: "date",
      placeholder: "Purchase Date",
      initialValue: todayISO(),
      // validation: Yup.string().required("Purchase Date is required"),
    },
    cifYen: {
      name: "cifYen",
      type: "number",
      placeholder: "CIF YEN",
      initialValue: 0,
      // validation: Yup.number().required("CIF YEN is required"),
    },
    auctionPrice: {
      name: "auctionPrice",
      type: "number",
      placeholder: "Auction Price",
      initialValue: 0,
      // validation: Yup.number().required("Auction Price is required"),
    },
    tax: {
      name: "tax",
      type: "number",
      placeholder: "TAX",
      initialValue: 0,
      // validation: Yup.number().required("TAX is required"),
    },
    freight: {
      name: "freight",
      type: "number",
      placeholder: "Freight",
      initialValue: 0,
      // validation: Yup.number().required("Freight is required"),
    },
    paymentDate: {
      name: "paymentDate",
      type: "date",
      placeholder: "Payment Date",
      initialValue: todayISO(),
      // validation: Yup.string().required("Payment Date is required"),
    },
    paymentAmount: {
      name: "paymentAmount",
      type: "number",
      placeholder: "Payment Amount",
      initialValue: 0,
      // validation: Yup.number().required("Payment Amount is required"),
    },
    paymentRate: {
      name: "paymentRate",
      type: "number",
      placeholder: "Payment Rate",
      initialValue: 0,
      // validation: Yup.number().required("Payment Rate is required"),
    },
    paymentAmountYen: {
      name: "paymentAmountYen",
      type: "number",
      placeholder: "Payment Amount (YEN)",
      initialValue: 0,
      // validation: Yup.number().required("Payment Amount (YEN) is required"),
    },
    paymentDetails: {
      name: "paymentDetails",
      type: "text",
      placeholder: "Payment Details",
      initialValue: "",
      // validation: Yup.string().required("Payment Details is required"),
    },
    lcOpenDetailsBank: {
      name: "lcOpenDetailsBank",
      type: "text",
      placeholder: "L.C Open Details (Bank)",
      initialValue: 0,
      // validation: Yup.string().required("L.C Open Details (Bank) is required"),
    },
    JPY: {
      name: "JPY",
      type: "number",
      placeholder: "JPY",
      initialValue: 0,
      // validation: Yup.number().required("JPY is required"),
    },
    lcOpenDetailsDate: {
      name: "lcOpenDetailsDate",
      type: "date",
      placeholder: "L.C Open Date",
      initialValue: todayISO(),
      // validation: Yup.date().required("L.C Open Date is required"),
    },
    lcMarginAmount: {
      name: "lcMarginAmount",
      type: "number",
      placeholder: "L.C Margin Amount",
      initialValue: 0,
      // validation: Yup.number().required("L.C Margin Amount is required"),
    },
    lcMarginDate: {
      name: "lcMarginDate",
      type: "date",
      placeholder: "L.C Margin Date",
      initialValue: todayISO(),
      // validation: Yup.date().required("L.C Margin Date is required"),
    },
    lcSettlementAmount: {
      name: "lcSettlementAmount",
      type: "number",
      placeholder: "L.C Settlement Amount",
      initialValue: 0,
      validation: Yup.number().required("L.C Settlement Amount is required"),
    },
    lcSettlementCharges: {
      name: "lcSettlementCharges",
      type: "number",
      placeholder: "L.C Settlement Charges",
      initialValue: 0,
      validation: Yup.number().required("L.C Settlement Charges is required"),
    },
    lcSettlementDate: {
      name: "lcSettlementDate",
      type: "date",
      placeholder: "L.C Settlement Date",
      initialValue: todayISO(),
      // validation: Yup.date().required("L.C Settlement Date is required"),
    },
    dutyAmount: {
      name: "dutyAmount",
      type: "number",
      placeholder: "Duty Amount",
      initialValue: 0,
      validation: Yup.number().required("Duty Amount is required"),
    },
    dutyDate: {
      name: "dutyDate",
      type: "date",
      placeholder: "Duty Date",
      initialValue: todayISO(),
      // validation: Yup.date().required("Duty Date is required"),
    },
    clearingCharges: {
      name: "clearingCharges",
      type: "number",
      placeholder: "Clearing Charges",
      initialValue: 0,
      validation: Yup.number().required("Clearing Charges is required"),
    },
    clearingDate: {
      name: "clearingDate",
      type: "date",
      placeholder: "Clearing Date",
      initialValue: todayISO(),
      // validation: Yup.date().required("Clearing Date is required"),
    },
    salesTax: {
      name: "salesTax",
      type: "number",
      placeholder: "Sales Tax",
      initialValue: 0,
      validation: Yup.number().required("Sales Tax is required"),
    },
    transportCost: {
      name: "transportCost",
      type: "number",
      placeholder: "Transport Cost",
      initialValue: 0,
      validation: Yup.number().required("Transport Cost is required"),
    },
    totalCost: {
      name: "totalCost",
      type: "number",
      placeholder: "Total Cost",
      initialValue: 0,
      validation: Yup.number().required("Total Cost is required"),
    },
    description: {
      name: "description",
      type: "textarea",
      placeholder: "Description",
      initialValue: "",
      // validation: Yup.string().required("Description is required"),
    },
    images: {
      name: "images",
      type: "images",
      placeholder: "",
      initialValue: [],
      // validation: Yup.array().of(Yup.mixed()),
    },
});
