using System;
using System.Windows;
using System.Collections.Generic;
using Microsoft.Win32;
using System.IO;
using System.Data;
using DataTire;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using SEACC_WPFControls;
using System.ComponentModel;
using System.Linq;

namespace Digiteq_Logic
{
    public class clsCommon : Window
    {
        //        public void Marquee_Display(bool bStatusn, double Width)
        //        {
        //            FRM_Marquee_mini fMN = new FRM_Marquee_mini();
        //            fMN.Width = Width;
        //            fMN.Left = this.Width;

        //            fMN.Top = System.Windows.SystemParameters.WorkArea.Bottom - 100;
        //            if (bStatusn)
        //                fMN.Show();
        //        }
        //        public static string FormatToCurrecyWithThousendSep(decimal dCurrency)
        //        {
        //            string value = "0.00";
        //            value = String.Format("{0:0,0.00}", dCurrency);
        //            return value;
        //        }
        //        public static void Set_UserIndicator(ref SEACC_UserIndicator_Small userIndicator, string UserID)
        //        {
        //            try
        //            {
        //                if (UserID != "default")
        //                {
        //                    tbl_genMasEmployee oEmployee = tbl_genMasEmployee.Select(UserID, clsSecurity.CompanyID, clsSecurity.BranchID);
        //                    if (oEmployee.Employee_ID != null)
        //                        userIndicator.Set(UserID, oEmployee.FullName, clsCommon.Convert_ByteToBitMap(oEmployee.Employee_Image));
        //                }
        //            }
        //            catch (Exception)
        //            {
        //            }
        //        }

        //        public static string GetDisplayValue_Date(DateTime DateTime)
        //        {
        //            string result = "-";
        //            try
        //            {
        //                result = (DateTime == clsConfig.defaultDateTime) ? "-" : DateTime.ToString(clsConfig.Format_Date);
        //            }
        //            catch (Exception)
        //            {
        //            }
        //            return result;
        //        }

        //        public static string GetDisplayValue_Time(DateTime DateTime)
        //        {
        //            string result = "-";
        //            try
        //            {
        //                result = (DateTime == clsConfig.defaultDateTime) ? "-" : DateTime.ToString(clsConfig.Format_Time);
        //            }
        //            catch (Exception)
        //            {
        //            }
        //            return result;
        //        }

        //        public static byte[] Convert_BitMapToByteArray(BitmapImage imageC)
        //        {
        //            MemoryStream memStream = new MemoryStream();
        //            JpegBitmapEncoder encoder = new JpegBitmapEncoder();
        //            encoder.Frames.Add(BitmapFrame.Create(imageC));
        //            encoder.Save(memStream);
        //            return memStream.ToArray();
        //        }

        //        public static BitmapImage Convert_ByteToBitMap(byte[] ByteImage)
        //        {
        //            BitmapImage bitmap = new BitmapImage();
        //            try
        //            {
        //                if (ByteImage.Length > 0)
        //                {
        //                    using (var stream = new MemoryStream(ByteImage))
        //                    {
        //                        bitmap.BeginInit();
        //                        bitmap.StreamSource = stream;
        //                        bitmap.CacheOption = BitmapCacheOption.OnLoad;
        //                        bitmap.EndInit();
        //                        bitmap.Freeze();
        //                    }
        //                }
        //            }
        //            catch (Exception)
        //            {
        //            }
        //            return bitmap;
        //        }

        public static string getAutoGeneratedCode(FormName enmFormName)
        {
            string sCode = "";
            tbl_securityFormMaster detail = tbl_securityFormMaster.Select((int)enmFormName);
            if (detail != null)
            {
                if (detail.Prefix1 != null && detail.Prefix1.Length > 0)
                    sCode += detail.Prefix1;

                sCode += detail.Counter.ToString(getWidthFormat(detail.Length));
                detail.Counter++;
                detail.Update();
            }
            return sCode;
        }

        public static string getWidthFormat(int Size)
        {
            string Zero = "";
            for (int x = 0; x < Size; x++)
            {
                Zero += "0";
            }
            return Zero;
        }

        //        public static string[] getEmpShiftDetails(string emp_ID, DateTime considerableDate)
        //        {
        //            string[] shiftDetails = new string[4] {"","","","0"};
        //            //DataTable dtResult_Table = DBHandling.ExecQuery("SELECT TOP 1 ES.shift_ID, S.shift_Name, S.shiftStartTime, S.shiftMinutes FROM tbl_tasMasEmployeeShift AS ES LEFT OUTER JOIN tbl_tasShiftMaster AS S ON ES.shift_ID = S.shift_ID  where ES.effectiveFrom_Date='" + considerableDate.Date+ "' AND ES.employee_ID = '" + emp_ID + "' AND ES.isCanceled = 0 order by ES.effectiveFrom_Date DESC").Tables[0];
        //            DataTable dtResult_Table = DBHandling.ExecQuery("SELECT TOP 1 ES.shift_ID, S.shift_Name, S.shiftStartTime, S.shiftMinutes FROM tbl_tasMasEmployeeShift AS ES LEFT OUTER JOIN tbl_tasShiftMaster AS S ON ES.shift_ID = S.shift_ID  where ES.effectiveFrom_Date<='" + considerableDate.Date.ToString("yyyy-MM-dd") + "' AND ES.employee_ID = '" + emp_ID + "' AND ES.isCanceled = 0 order by ES.effectiveFrom_Date DESC").Tables[0];
        //            if (dtResult_Table != null && dtResult_Table.Rows.Count > 0)
        //            {
        //                shiftDetails[0] = dtResult_Table.Rows[0]["shift_ID"].ToString();

        //                if (shiftDetails[0] != "" && dtResult_Table.Rows[0]["shiftMinutes"].ToString() !="")
        //                {
        //                    shiftDetails[1] = dtResult_Table.Rows[0]["shift_Name"].ToString();
        //                    shiftDetails[2] = dtResult_Table.Rows[0]["shiftStartTime"].ToString();
        //                    shiftDetails[3] = dtResult_Table.Rows[0]["shiftMinutes"].ToString();
        //                }
        //            }
        //            return shiftDetails;
        //        }

        //        static BrushConverter bc = new BrushConverter();

        //        #region General Values
        //        public static string SoftwareVersion = "";
        //        public static string CompanyName = "";
        //        public static string CompanyAddress1 = "";
        //        public static string CompanyAddress2 = "";

        //        //    public static Font defaultFont = new Font("Calibiri", 6, FontStyle.Bold);
        //        public static bool isTrunk = false;
        //        //  public static Color ColourForLockedRecord = Color.DarkRed;
        //        public static System.Diagnostics.Process oskProcess = null;
        //        #endregion

        //        #region General functions
        //        public static bool isCurrency(string val)
        //        {
        //            Double result;
        //            return Double.TryParse(val, System.Globalization.NumberStyles.Currency,
        //                System.Globalization.CultureInfo.CurrentCulture, out result);
        //        }
        //        public static bool isValueZero(string val)
        //        {
        //            if (val.Length > 0)
        //            {
        //                double dValue = double.Parse(val);
        //                if (dValue != 0)
        //                    return true;
        //                else
        //                    return false;
        //            }
        //            else
        //                return false;

        //        }
        //        public static string RemoveNewLinestring(string sTemp)
        //        {
        //            string s = sTemp.Replace("\n", "").Trim();
        //            return s.Replace("\r", "").Trim();

        //        }
        //        public static string fncsetstring(string sTemp)
        //        {
        //            return "'" + sTemp.Replace("'", "''").Trim() + "'";
        //        }

        //        private static string regRegistryName = "Software\\52465123-sys\\456465465461312313111321";// + "1212";

        //        public static string RegRegistryName
        //        {
        //            get { return clsCommon.regRegistryName; }
        //            set { clsCommon.regRegistryName = value; }
        //        }


        //        #region get company name

        //        public static string getRegDBComapanyName()
        //        {
        //            RegistryKey key = Registry.LocalMachine.OpenSubKey(RegRegistryName);
        //            string result = key.GetValue("companyname").ToString();

        //            return result;
        //        }
        //        #endregion


        //        //public static void SetEnableDisable_TimePicker(SEACC_TimeSelector myTimeSelector, bool bEnable)
        //        //{
        //        //    myTimeSelector.SetTime(DateTime.Now);

        //        //    if (bEnable)
        //        //    {
        //        //        myTimeSelector.IsEnabled = true;
        //        //        myTimeSelector.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //        //    }
        //        //    else
        //        //    {
        //        //        myTimeSelector.IsEnabled = false;
        //        //        myTimeSelector.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //        //    }
        //        //}

        //        //public static void SetEnableDisable_LableDateTimePicker(SEACC_LabelDateTimeSelector myDateTimeSelector, bool bEnable)
        //        //{

        //        //    if (bEnable)
        //        //    {
        //        //        myDateTimeSelector.IsEnabled = true;
        //        //        myDateTimeSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //        //    }
        //        //    else
        //        //    {
        //        //        myDateTimeSelector.IsEnabled = false;
        //        //        myDateTimeSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //        //    }
        //        //}

        //        //public static void SetEnableDisable_LabelDateSelector(SEACC_LabelDateSelector myDateSelector, bool bEnable)
        //        //{
        //        //    myDateSelector.setDate(DateTime.Now);

        //        //    if (bEnable)
        //        //    {
        //        //        myDateSelector.IsEnabled = true;
        //        //        myDateSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //        //    }
        //        //    else
        //        //    {
        //        //        myDateSelector.IsEnabled = false;
        //        //        myDateSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //        //    }
        //        //}

        //        public static void SetEnableDisable_LableTimePicker(SEACC_LabelTimeSelector myTimeSelector, bool bEnable)
        //        {
        //            myTimeSelector.SetTime(DateTime.Now);

        //            if (bEnable)
        //            {
        //                myTimeSelector.IsEnabled = true;
        //                myTimeSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTimeSelector.IsEnabled = false;
        //                myTimeSelector.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_TimeSpan(SEACC_TimeSpan myTimeSpan, bool bEnable)
        //        {
        //            myTimeSpan.SetTimeSpan(new TimeSpan(0, 0, 0));

        //            if (bEnable)
        //            {
        //                myTimeSpan.IsEnabled = true;
        //                myTimeSpan.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTimeSpan.IsEnabled = false;
        //                myTimeSpan.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_LableTimeSpan(SEACC_LabelTimeSpan myTimeSpan, bool bEnable)
        //        {
        //            myTimeSpan.SetTimeSpan(new TimeSpan(0, 0, 0));

        //            if (bEnable)
        //            {
        //                myTimeSpan.IsEnabled = true;
        //                myTimeSpan.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTimeSpan.IsEnabled = false;
        //                myTimeSpan.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_RadioButttons(RadioButton myRadioButtons, bool bEnable)
        //        {

        //            if (bEnable)
        //            {
        //                myRadioButtons.IsEnabled = true;
        //                myRadioButtons.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");

        //            }
        //            else
        //            {
        //                myRadioButtons.IsEnabled = false;
        //                myRadioButtons.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }


        //        public static void SetEnableDisable_Button(Button myButton, bool bEnable)
        //        {

        //            if (bEnable)
        //            {
        //                myButton.IsEnabled = true;
        //                myButton.Background = (Brush)bc.ConvertFrom("#FF41B1E1");

        //            }
        //            else
        //            {
        //                myButton.IsEnabled = false;
        //                myButton.Background = (Brush)bc.ConvertFrom("#FF99B9C7");
        //            }
        //        }

        //        public static void SetEnableDisable_NormalLabel(Label myLabel, bool bEnable)
        //        {
        //            if (bEnable)
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#633232");
        //                myLabel.Foreground = brush;
        //            }
        //            else
        //            {

        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#838080");
        //                myLabel.Foreground = brush;
        //            }
        //        }

        //        public static void SetEnableDisable_DatePicker(DatePicker myDatePicker, bool bEnable)
        //        {
        //            myDatePicker.SelectedDate = DateTime.Now;

        //            if (bEnable)
        //            {
        //                myDatePicker.IsEnabled = true;
        //                myDatePicker.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myDatePicker.IsEnabled = false;
        //                myDatePicker.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }

        //        }

        //        public static void SetEnableDisable_ComboBox(ComboBox myComboBox, bool bEnable)
        //        {
        //            myComboBox.SelectedItem = "--Please Select--";

        //            if (bEnable)
        //            {
        //                myComboBox.IsEnabled = true;
        //                myComboBox.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //                myComboBox.SetValue(Border.BorderBrushProperty, (Brush)bc.ConvertFrom("#FF41B1E1"));
        //                myComboBox.Background = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myComboBox.IsEnabled = false;
        //                myComboBox.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_DataGrid(DataGrid myDataGrid, bool bEnable, string colorCode_HeaderBackGround, string ColorcodeForForeground)
        //        {
        //            if (bEnable)
        //            {

        //                double myPadding = 6.00;
        //                double myBorder = 0.00;
        //                myDataGrid.GridLinesVisibility = DataGridGridLinesVisibility.Horizontal;
        //                myDataGrid.CanUserSortColumns = true;
        //                myDataGrid.CanUserAddRows = false;
        //                myDataGrid.CanUserDeleteRows = false;
        //                myDataGrid.CanUserResizeColumns = false;
        //                // myDataGrid.IsReadOnly = true;
        //                myDataGrid.HorizontalAlignment = HorizontalAlignment.Left;
        //                myDataGrid.AutoGenerateColumns = false;
        //                //myDataGrid.AlternatingRowBackground = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFE0E0E0"));
        //                myDataGrid.HorizontalGridLinesBrush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFDADADA"));
        //                // myDataGrid.VerticalGridLinesBrush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFA4A2A2"));
        //                myDataGrid.CanUserReorderColumns = false;
        //                myDataGrid.CanUserSortColumns = false;
        //                myDataGrid.FontSize = 10;
        //                myDataGrid.HeadersVisibility = DataGridHeadersVisibility.Column;
        //                myDataGrid.AutoGenerateColumns = false;
        //                myDataGrid.ColumnHeaderHeight = 29;
        //                myDataGrid.FontSize = 11;
        //                myDataGrid.RowHeight = 22;


        //                var style = new Style(typeof(System.Windows.Controls.Primitives.DataGridColumnHeader));
        //                if (colorCode_HeaderBackGround != "")
        //                {
        //                    style.Setters.Add(new Setter { Property = BackgroundProperty, Value = (Brush)bc.ConvertFrom(colorCode_HeaderBackGround) });
        //                }

        //                style.Setters.Add(new Setter { Property = ForegroundProperty, Value = (Brush)bc.ConvertFrom(ColorcodeForForeground) });
        //                style.Setters.Add(new Setter { Property = PaddingProperty, Value = new Thickness(Math.Round(myPadding / 2, 0)) });
        //                style.Setters.Add(new Setter { Property = BorderThicknessProperty, Value = new Thickness(Math.Round(myBorder / 2, 0)) });
        //                // style.Setters.Add(new Setter { Property = DataGridCell, Value = new Thickness(Math.Round(myBorder / 2, 0)) });
        //                myDataGrid.ColumnHeaderStyle = style;

        //            }
        //        }

        //        public static void SetEnableDisable_DataGrid_NewGrid(DataGrid myDataGrid, bool bEnable, string colorCode_HeaderBackGround, string ColorcodeForForeground)
        //        {
        //            if (bEnable)
        //            {

        //                double myPadding = 6.00;
        //                double myBorder = 0.00;
        //                myDataGrid.GridLinesVisibility = DataGridGridLinesVisibility.Horizontal;
        //                myDataGrid.CanUserSortColumns = true;
        //                myDataGrid.CanUserAddRows = false;
        //                myDataGrid.CanUserDeleteRows = false;
        //                myDataGrid.CanUserResizeColumns = false;
        //                // myDataGrid.IsReadOnly = true;
        //                myDataGrid.HorizontalAlignment = HorizontalAlignment.Left;
        //                myDataGrid.AutoGenerateColumns = false;
        //                //myDataGrid.AlternatingRowBackground = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFE0E0E0"));
        //                myDataGrid.HorizontalGridLinesBrush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFDADADA"));
        //                // myDataGrid.VerticalGridLinesBrush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#FFA4A2A2"));
        //                myDataGrid.CanUserReorderColumns = false;
        //                myDataGrid.CanUserSortColumns = false;
        //                myDataGrid.FontSize = 10;
        //                myDataGrid.HeadersVisibility = DataGridHeadersVisibility.Column;
        //                myDataGrid.AutoGenerateColumns = false;
        //                myDataGrid.ColumnHeaderHeight = 29;
        //                myDataGrid.FontSize = 11;
        //                myDataGrid.RowHeight = 22;


        //                var style = new Style(typeof(System.Windows.Controls.Primitives.DataGridColumnHeader));
        //                if (colorCode_HeaderBackGround != "")
        //                {
        //                    style.Setters.Add(new Setter { Property = BackgroundProperty, Value = (Brush)bc.ConvertFrom(colorCode_HeaderBackGround) });
        //                }

        //                style.Setters.Add(new Setter { Property = ForegroundProperty, Value = (Brush)bc.ConvertFrom(ColorcodeForForeground) });
        //                style.Setters.Add(new Setter { Property = PaddingProperty, Value = new Thickness(Math.Round(myPadding / 2, 0)) });
        //                style.Setters.Add(new Setter { Property = BorderThicknessProperty, Value = new Thickness(Math.Round(myBorder / 2, 0)) });
        //                // style.Setters.Add(new Setter { Property = DataGridCell, Value = new Thickness(Math.Round(myBorder / 2, 0)) });
        //                myDataGrid.ColumnHeaderStyle = style;

        //            }
        //        }

        //        public static void SetEnableDisable_Buttons(Button myButton, bool bEnable, string BackGroundColor, string ForeGroundColor, string BorderBrushColor, double BThikness, int Width, int Height)
        //        {
        //            if (bEnable)
        //            {
        //                double Thikness = BThikness;

        //                myButton.IsEnabled = true;
        //                myButton.Background = (Brush)bc.ConvertFrom(BackGroundColor);
        //                myButton.Foreground = (Brush)bc.ConvertFrom(ForeGroundColor);
        //                myButton.Width = Width;
        //                myButton.Height = Height;
        //                myButton.BorderBrush = (Brush)bc.ConvertFrom(BorderBrushColor);
        //                myButton.BorderThickness = new Thickness(Math.Round(Thikness / 2, 0));
        //                myButton.SetResourceReference(Button.StyleProperty, "ButtonStyleKey");
        //            }
        //            else
        //            {
        //                myButton.IsEnabled = false;
        //            }
        //        }

        //        public static void SetEnableDisable_CheckBox(CheckBox myCheckBox, bool bEnable)
        //        {

        //            if (bEnable)
        //            {
        //                myCheckBox.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myCheckBox.BorderBrush = (Brush)bc.ConvertFrom("Black");
        //            }
        //        }

        //        public static void SetEnableDisable_ForigenKeyLabelTextBox(SEACC_LableTextBox myTextBox, bool bEnable, bool isNumeric, bool isMultiline)
        //        {
        //            myTextBox.ISNumaric = isNumeric;
        //            myTextBox.setReadOnlyStatus(true);
        //            myTextBox.ErrorText = "";
        //            myTextBox.IsMultiline = isMultiline;
        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //                myTextBox.TextBox_Background = (Brush)bc.ConvertFrom("#D8D8D8");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        //public static void DynamicBackgroundColor(SEACC_LableTextBox myTextBox, bool bEnable, bool isNumeric, bool isMultiline,string Background)
        //        //{
        //        //    myTextBox.ISNumaric = isNumeric;
        //        //    myTextBox.setReadOnlyStatus(false);
        //        //    myTextBox.ErrorText = "";
        //        //    myTextBox.IsMultiline = isMultiline;
        //        //    if (bEnable)
        //        //    {
        //        //        myTextBox.IsEnabled = true;
        //        //        myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom(Background);
        //        //        myTextBox.TextBox_Background = (Brush)bc.ConvertFrom("#D8D8D8");
        //        //    }
        //        //    else
        //        //    {
        //        //        myTextBox.IsEnabled = false;
        //        //        myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //        //    }
        //        //}


        //        public static void SetEnableDisable_PrimaryKeyLabelTextBox(SEACC_LableTextBox myTextBox, bool bEnable, bool isNumeric, bool isMultiline)
        //        {
        //            myTextBox.ISNumaric = isNumeric;
        //            myTextBox.IsMultiline = isMultiline;
        //            myTextBox.ErrorText = "";
        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //                myTextBox.TextBox_Background = (Brush)bc.ConvertFrom("#D8D8D8");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_LableTextbox(SEACC_LableTextBox myTextBox, bool bEnable, bool isNumaric, bool isMultiline)
        //        {
        //            myTextBox.ISNumaric = isNumaric;
        //            myTextBox.IsMultiline = isMultiline;
        //            myTextBox.ErrorText = "";
        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }
        //        public static void SetEnableDisable_SEACCNormalTextbox(SEACC_TextBox myTextBox, bool bEnable, bool isNumaric, bool isMultiline)
        //        {
        //            myTextBox.ISNumaric = isNumaric;
        //            myTextBox.IsMultiline = isMultiline;
        //            myTextBox.ErrorText = "";
        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }


        //        #region SetEnableDisable SEACC TextBox
        //        public static void SetEnableDisable_NormalTextbox(SEACC_TextBox myTextBox, bool bEnable, bool isNumaric)
        //        {
        //            myTextBox.ErrorText = "";
        //            myTextBox.ISNumaric = isNumaric;


        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");

        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_ForigenKeyTextBox(SEACC_TextBox myTextBox, bool bEnable, bool isNumaric)
        //        {
        //            myTextBox.ErrorText = "";
        //            myTextBox.ISNumaric = isNumaric;
        //            myTextBox.setReadOnlyStatus(true);

        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //                myTextBox.Background = (Brush)bc.ConvertFrom("#D8D8D8");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.TextBox_BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }

        //        public static void SetEnableDisable_PrimaryKeyTextbox(SEACC_TextBox myTextBox, bool bEnable)
        //        {

        //            if (bEnable)
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#D3ADCA");
        //                myTextBox.IsEnabled = true;
        //                myTextBox.Background = brush;
        //            }
        //            else
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#ABABAB");
        //                myTextBox.IsEnabled = false;
        //                myTextBox.Background = brush;
        //            }
        //        }
        //        #endregion



        //        public static void SetEnableDisable_PrimaryKeyTextbox(TextBox myTextBox, bool bEnable)
        //        {

        //            if (bEnable)
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#D3ADCA");
        //                myTextBox.IsEnabled = true;
        //                myTextBox.Background = brush;
        //            }
        //            else
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#ABABAB");
        //                myTextBox.IsEnabled = false;
        //                myTextBox.Background = brush;
        //            }
        //        }

        //        public static void SetEnableDisable_ForeignKeyTextboxOptional(TextBox myTextBox, bool bEnable)
        //        {
        //            myTextBox = new TextBox();
        //            if (bEnable)
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#d3d3d3");
        //                myTextBox.IsEnabled = true;
        //                myTextBox.Background = brush;
        //            }
        //            else
        //            {
        //                var converter = new System.Windows.Media.BrushConverter();
        //                var brush = (Brush)converter.ConvertFromString("#ABABAB");
        //                myTextBox.IsEnabled = false;
        //                myTextBox.Background = brush;
        //            }
        //        }

        //        //PasswordBox
        //        public static void SetEnableDisable_PasswordBox(PasswordBox myTextBox, bool bEnable, bool isNumaric)
        //        {

        //            if (bEnable)
        //            {
        //                myTextBox.IsEnabled = true;
        //                myTextBox.BorderBrush = (Brush)bc.ConvertFrom("#FF41B1E1");
        //            }
        //            else
        //            {
        //                myTextBox.IsEnabled = false;
        //                myTextBox.BorderBrush = (Brush)bc.ConvertFrom("#ABABAB");
        //            }
        //        }


        //        #region Get Company Details
        public static byte[] getCompanyImage()
        {
            byte[] sCompanyImage = null;
            tbl_genCompanyImage comI = tbl_genCompanyImage.Select(clsSecurity.CompanyID);

            if (comI != null)
                sCompanyImage = comI.MainLogo;

            return sCompanyImage;
        }
        public static string getCompanyName()
        {
            string sCompanyName = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
                sCompanyName = com.CompanyName;

            return sCompanyName;
        }
        public static string getCompanyAddress1()
        {
            string sAddress1 = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
                sAddress1 = com.Address;

            return sAddress1;
        }
        public static string getCompanyAddress2()
        {
            string sAddress2 = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
            {
                //sAddress2 = "Tel:" + com.Telephone1 +","+ com.Telephone2 +" FAX:" + com.Fax;

                if (com.Telephone1.Length > 0)
                    sAddress2 = "Tel:" + com.Telephone1;
                if (com.Telephone2.Length > 0)
                    sAddress2 += "," + com.Telephone2;
                if (com.Fax.Length > 0)
                    sAddress2 += "," + " FAX:" + com.Fax;
            }
            return sAddress2;
        }
        public static string getStoragePeriod(Enum enmFormName)
        {//((StoragePeriod)oGRN.Storage_Period).ToString()
            string sPeriod = "";
            if (enmFormName.ToString() == "D15")
            {
                sPeriod = "1-15 days";
            }
            if (enmFormName.ToString() == "D30")
            {
                sPeriod = "1-30 days";
            }

            return sPeriod;
        }

        public static List<string> getEnumDescription(Type enumType)
        {
            List<string> lPeriod = new List<string>();

            foreach (var record in Enum.GetValues(enumType).Cast<Enum>().Select(value => new
            {
                (Attribute.GetCustomAttribute(value.GetType().GetField(value.ToString()), typeof(DescriptionAttribute)) as DescriptionAttribute).Description,
                value
            })
        .OrderBy(item => item.value)
        .ToList())
            {
                lPeriod.Add(record.Description);
            }
            return lPeriod;
        }
        //public static List<string> getEnumDescription()
        //{
        //    List<string> lPeriod = new List<string>();

        //    foreach (var record in Enum.GetValues(typeof(StoragePeriod)).Cast<Enum>().Select(value => new
        //    {
        //        (Attribute.GetCustomAttribute(value.GetType().GetField(value.ToString()), typeof(DescriptionAttribute)) as DescriptionAttribute).Description,
        //        value
        //    })
        //.OrderBy(item => item.value)
        //.ToList())
        //    {
        //        lPeriod.Add(record.Description);
        //    }
        //    return lPeriod;
        //}

        //        #endregion
        //        public static string getCompanyAddress2_DAPL()
        //        {
        //            string sAddress2 = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                sAddress2 = "Tel / FAX : " + com.Telephone1;

        //            return sAddress2;
        //        }

        //        public static string getCompanyVAT()
        //        {
        //            string VAT = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                VAT = com.VatRegisterNo;

        //            return VAT;
        //        }
        //        public static string getCompanyNBT()
        //        {
        //            string NBT = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                NBT = com.CompanyMDName;

        //            return NBT;
        //        }

        //        public static string getCompanySVAT()
        //        {
        //            string SVAT = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                SVAT = com.MdTelephone;

        //            return SVAT;
        //        }
        //        public static string getCompanyEmail()
        //        {
        //            string Email = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                Email = com.Email;

        //            return Email;
        //        }
        //        public static string getCompanyWeb()
        //        {
        //            string Web = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                Web = com.Url;

        //            return Web;
        //        }
        //        public static string getCompanyBusinessRegisterNo()
        //        {
        //            string BusinessRegisterNo = "";
        //            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
        //            if (com != null)
        //                BusinessRegisterNo = com.BusinessRegisterNo;

        //            return BusinessRegisterNo;
        //        }
        //        #endregion

        //        #region Currency To Word
        //        /// <summary>
        //        /// Create For Convert Decimal Value To Words
        //        /// </summary>
        //        /// <param name="number"></param>
        //        /// <returns></returns>
        //        /// 
        //        public static string CurrencyToWord(decimal Curr)
        //        {
        //            string decimalPlace = "", Value = "";// Value = "Rupees ";
        //            int des = 0;

        //            decimalPlace = Convert.ToString(Curr - Math.Floor(Curr));
        //            if (decimalPlace.Length >= 2)
        //            {
        //                des = Convert.ToInt32(decimalPlace.Substring(2));
        //            }

        //            Value += NumberToWords(Convert.ToInt32(decimal.Truncate(Curr)));

        //            if (des > 0)
        //            {
        //                Value += " and Cents " + NumberToWords(des);
        //            }
        //            return Value + " Only";
        //        }
        //        public static string NumberToWords(int number)
        //        {
        //            if (number == 0)
        //                return "Zero";

        //            if (number < 0)
        //                return "minus " + NumberToWords(Math.Abs(number));

        //            string words = "";

        //            if ((number / 1000000) > 0)
        //            {
        //                words += NumberToWords(number / 1000000) + " Million ";
        //                number %= 1000000;
        //            }

        //            if ((number / 1000) > 0)
        //            {
        //                words += NumberToWords(number / 1000) + " Thousand ";
        //                number %= 1000;
        //            }

        //            if ((number / 100) > 0)
        //            {
        //                words += NumberToWords(number / 100) + " Hundred ";
        //                number %= 100;
        //            }

        //            if (number > 0)
        //            {
        //                if (words != "")
        //                    words += "and ";

        //                var unitsMap = new[] { "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen" };
        //                var tensMap = new[] { "Zero", "Ten", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety" };

        //                if (number < 20)
        //                    words += unitsMap[number];
        //                else
        //                {
        //                    words += tensMap[number / 10];
        //                    if ((number % 10) > 0)
        //                        words += "-" + unitsMap[number % 10];
        //                }
        //            }

        //            return words;
        //        }
        //        #endregion

        //        #region Validate Values
        //        public static void ValidateDeciamlValue(ref TextBox tbox)
        //        {
        //            if (tbox.Text.Trim().Length <= 0)
        //                tbox.Text = "0.00";
        //        }

        //        public static void ValidateIntegerlValue(ref TextBox tbox)
        //        {
        //            if (tbox.Text.Trim().Length <= 0)
        //                tbox.Text = "0";
        //        }
        //        #endregion

        //        #region Combine Date and Time
        //        public static DateTime CombineDateAndTime(string sDate, string sTime)
        //        {
        //            DateTime rtnVal = clsSecurity.getServerDateTime();
        //            try
        //            {
        //                rtnVal = DateTime.Parse(sDate + " " + sTime);
        //            }
        //            catch (Exception)
        //            {
        //                return rtnVal;
        //            }
        //            return rtnVal;
        //        }

        //        public static DateTime CombineDateAndTime(DateTime Date, DateTime Time)
        //        {
        //            DateTime rtnVal = clsConfig.defaultDateTime;
        //            try
        //            {
        //                rtnVal = new DateTime(Date.Year, Date.Month, Date.Day, Time.Hour, Time.Minute, Time.Second);
        //            }
        //            catch (Exception)
        //            {
        //                return rtnVal;
        //            }
        //            return rtnVal;
        //        }
        //        #endregion

        //        #region Get Telephone Fax Customer/Supplier
        //        public static string getCustomerTelephoneAndFax(string CustomerID)
        //        {
        //            string sTelephoneFax = "";
        //            tbl_genCustomerMaster Cus = tbl_genCustomerMaster.Select(CustomerID);
        //            if (Cus != null)
        //            {
        //                if (Cus.Telephone.Trim().Length > 0 || Cus.Fax.Trim().Length > 0)
        //                {
        //                    sTelephoneFax = (Cus.Telephone.Trim().Length > 0) ? Cus.Telephone : "N/A";
        //                    sTelephoneFax += " / ";
        //                    sTelephoneFax += (Cus.Telephone.Trim().Length > 0) ? Cus.Telephone : "N/A";
        //                }
        //                else
        //                    sTelephoneFax = "N/A";
        //            }
        //            return sTelephoneFax;
        //        }

        //        public static string getSupplerTelephoneAndFax(string CustomerID)
        //        {
        //            string sTelephoneFax = "";
        //            tbl_genSupplierMaster Cus = tbl_genSupplierMaster.Select(CustomerID);
        //            if (Cus != null)
        //            {
        //                sTelephoneFax = Cus.Telephone + "  /  " + Cus.Fax;
        //            }
        //            return sTelephoneFax;
        //        }
        //        #endregion

        //        public static List<string> getCompanyDays(DateTime fromDate, DateTime toDate)
        //        {
        //            List<string> dtDayDescs = new List<string>();

        //            DataTable dtDBResult_Table = DBHandling.ExecQuery("SELECT HolidayCalander.holiday_Date, Holiday.holydayType_Name, HolidayCalander.holiday_Description FROM tbl_tasHolidayType AS Holiday RIGHT OUTER JOIN tbl_tasHolidayCalander AS HolidayCalander ON Holiday.holydayType_ID = HolidayCalander.holydayType_ID").Tables[0];

        //            for (DateTime date = fromDate; date.Date <= toDate.Date; date = date.AddDays(1))
        //            {
        //                dtDayDescs.Add(date.ToString("ddd"));

        //                DataRow[] result = dtDBResult_Table.Select("holiday_Date = #" + date.Date + "#");
        //                if (result != null)
        //                    if (result.Length > 0)
        //                    {
        //                        dtDayDescs[dtDayDescs.Count - 1] = result[0]["holydayType_Name"].ToString().Substring(0, 4);
        //                    }
        //            }
        //            return dtDayDescs;
        //        }
    }
}