using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;
using DataTire;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_mtrSecurityItemExceedLock : Form
    {
        
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
   

        #region FormLoad
        public frm_mtrSecurityItemExceedLock()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.SecurityItemExceedLock);
            iFormID = clsSecurity.getFormID(FormName.SecurityItemExceedLock);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_mtrSecurityItemExceedLock_Load(object sender, EventArgs e)
        {
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtValueID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_securityItemExceedLock detail = tbl_securityItemExceedLock.Select(int.Parse(txtValueID.Text.Trim()));
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtValueID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_securityItemExceedLock oldRecord = tbl_securityItemExceedLock.Select(int.Parse(txtValueID.Text.Trim()));
                                    if (oldRecord != null)
                                    {

                                        //Country Header
                                        tbl_securityItemExceedLock detail = new tbl_securityItemExceedLock(int.Parse(txtValueID.Text.Trim()),txtValueName.Text.Trim(),chkConfigValue.Checked);
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                //else  //insert records
                                //{
                                //    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                //       txtValueID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                //    //Inquiry Header
                                //    tbl_securityItemExceedLock detail = new tbl_securityItemExceedLock(int.Parse(txtValueID.Text.Trim()), txtValueName.Text.Trim(), chkConfigValue.Checked);
                                //    detail.Insert();
                                //    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                //}
                            }
                            else
                            {
                                MessageBox.Show("Item Exceed " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtValueID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblValueID,true);
            

            txtValueName. Clear();
            chkConfigValue.Checked = false;
            
       

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtValueID.Text = "<Auto Generate>";
            else
                txtValueID.Clear();
            if (txtValueID.Enabled)
            {
              txtValueName.SelectAll();
              txtValueName.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<tbl_securityItemExceedLock> details = tbl_securityItemExceedLock.SelectAll();
                foreach (tbl_securityItemExceedLock detail in details)
                {
                    if (detail.ValueID != 0)
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["ValueID", iRow].Value = detail.ValueID;
                        dgvDetail["ValueName", iRow].Value = detail.ValueName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(int sID)
        {
            try
            {
                if (sID > 0)
                {
                    tbl_securityItemExceedLock detail = tbl_securityItemExceedLock.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtValueID,false);
                        clsCommon.SetEnableDisable_NormalLabel(lblValueID,false);

                        //asign values
                        txtValueID.Text =Convert.ToString(detail.ValueID);
                        txtValueName.Text = detail.ValueName;
                        chkConfigValue.Checked = detail.ConfigValue;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtValueName.TextLength == 0)
            {
                strMessage += "\n" + "Terminal Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtValueID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityItemExceedLock();
            }
        }

        #endregion

        #region Events DoubleClick
        private void txtValueID_DoubleClick(object sender, EventArgs e)
        {
            Search_SecurityItemExceedLock();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["ValueID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(Convert.ToInt32(sID.Trim()));
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods
        private void Search_SecurityItemExceedLock()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.SecurityItemExceedLock();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtValueID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(int.Parse (frmSearchMaster.s_SearchID));
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

       
    }
}
