using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_AlertMaster : Form
    {
        

        static bool IsUpdate = false;   
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess; 



        #region Form Load
        public frm_AlertMaster()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.AlertMaster);
            iFormID = clsSecurity.getFormID(FormName.AlertMaster);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_Alert_Load(object sender, EventArgs e)
        {
            CusDataGridViewFormat();
            ClearFields();
            RefreshGrid();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtAlertID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_utlAlert oldRecord = tbl_utlAlert.Select(txtAlertID.Text.Trim());
                                    if (oldRecord != null)
                                    {

                                        tbl_utlAlert detail = new tbl_utlAlert(oldRecord.Alert_ID, txtAlertName.Text.Trim().ToUpper(), txtFormCatagory.Text.ToString().Trim(), oldRecord.IsActive);
                                    detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                   MessageBox.Show("Cannot insert new Alert...!");
                                }
                            }
                            else
                            {
                                MessageBox.Show("Country " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(DGAlert);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtAlertID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblAlertID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtFormCatagory, true);
            txtAlertName.Clear();
            txtFormCatagory.Clear();
            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtAlertID.Text = "<Auto Generate>";
            else
                txtAlertID.Clear();
            if (txtAlertID.Enabled)
            {
                txtAlertID.SelectAll();
                txtAlertID.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                DGAlert.Rows.Clear();

                List<tbl_utlAlert> details = tbl_utlAlert.SelectAll().Where(c => c.IsActive= true).ToList();
                foreach (tbl_utlAlert detail in details)
                {
                    if (detail.Alert_ID.Trim() != "default")
                    {
                        DGAlert.Rows.Add();
                        iRow = DGAlert.Rows.Count - 1;

                        DGAlert["AlertId", iRow].Value = detail.Alert_ID;
                        DGAlert["Alertname", iRow].Value = detail.AlertName;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_utlAlert detail = tbl_utlAlert.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtAlertID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblAlertID, false);
                        clsCommon.SetEnableDisable_ForeignKeyTextboxOptional(txtFormCatagory, false);
                        //asign values
                        txtAlertID.Text = detail.Alert_ID;
                        txtAlertName.Text = detail.AlertName;
                        txtFormCatagory.Text = detail.FormCategory_ID;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtAlertName.TextLength == 0)
            {
                strMessage += "\n" + "Alert Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion


        #region Events KeyDown
        private void frm_Alert_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events Datagrid
        private void DGAlert_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = DGAlert["AlertId", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void DGAlert_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            DGAlert_CellClick(sender, e);
        }
        #endregion    

    }
}
