using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;

namespace SEACC_Tender
{
    /// <summary>
    /// Interaction logic for frm_MasItem.xaml
    /// </summary>
    public partial class frm_MasItem : Window
    {
        bool bIsInsertMode = false;
        List<string> lstReturn = new List<string>();

        #region Form Load
        public frm_MasItem()
        {
            InitializeComponent();

            #region Data Table Initialize
            dgr_Main.dt.Columns.Add("ItemID");
            dgr_Main.dt.Columns.Add("ItemCode");
            dgr_Main.dt.Columns.Add("GenericName");
            dgr_Main.dt.Columns.Add("Brand");
            dgr_Main.dt.Columns.Add("Manufacturer");
            #endregion

            #region Datagrid Column Initialize
            dgr_Main.Add_DatagridColoumn("Item ID", "ItemID", 100, false);
            dgr_Main.Add_DatagridColoumn("Item Code", "ItemCode", 70);
            dgr_Main.Add_DatagridColoumn("Generic Name", "GenericName", 140);
            dgr_Main.Add_DatagridColoumn("Brand", "Brand", 80);
            dgr_Main.Add_DatagridColoumn("Manufacturer", "Manufacturer", 90);
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        public List<string> Show()
        {
            this.ShowDialog();
            return lstReturn;
        }

        #region Drag Event
        private void Grid_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            this.DragMove();
        }
        #endregion

        #region Action Buttons
        #region OK
        private void btnOK_Click(object sender, RoutedEventArgs e)
        {
            if (!bIsInsertMode)
            {
                try
                {
                    object oItem = dgr_Main.grdMain.SelectedItem;
                    if (oItem != null)
                    {
                        lstReturn.Add((dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text);
                        lstReturn.Add((dgr_Main.grdMain.SelectedCells[1].Column.GetCellContent(oItem) as TextBlock).Text);
                        lstReturn.Add((dgr_Main.grdMain.SelectedCells[2].Column.GetCellContent(oItem) as TextBlock).Text);

                        this.DialogResult = true;
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
            }
            else
            {
                if (CheckValidity())
                {
                    try
                    {
                        #region Insert
                        txtItem_ID.Tag = SEACC_Tender.UserControls.clsCommon.getAutoGeneratedCode(FormName.ItemMaster);

                        tbl_genItemMaster oDetails = new tbl_genItemMaster(txtItem_ID.Tag.ToString(), txtItem_code.Text, txtGenericname.Text, txtSpecification.Text,txtPackSize.Text,"","","",0,0,0,0,0,0,0,0,0,0,0,0,0,false,false,false,false,false,"default",
                            txtCategory.Tag.ToString(),txtClass.Tag.ToString(), txtItem_type.Tag.ToString(),"default", txtBrand.Tag.ToString(),"default",txtUoM.Tag.ToString(),0,0,0,0,0,0,0,"default",false,false,false,false,false,"",false,false,clsSecurity.CompanyID,"", 
                            txtTag1.Tag.ToString(), txtTag2.Tag.ToString(), false,false,false);
                        oDetails.Insert();

                        lstReturn.Add(txtItem_ID.Tag.ToString());
                        lstReturn.Add(txtItem_code.Text);
                        lstReturn.Add(txtGenericname.Text);

                        this.DialogResult = true;
                        #endregion
                    }
                    catch (Exception ex)
                    {
                        SEACCExeption.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Arrow;
                    }
                }
            }
        }
        #endregion

        #region New Item
        private void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
            this.Width = 875;
            bIsInsertMode = true;
        }
        #endregion

        #region Colapsed
        private void btn_Close2_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
            this.Width = 450;
            RefreshGrid();
            bIsInsertMode = false;
        } 
        #endregion

        #region Close
        private void btn_Close_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }
        #endregion 
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            bIsInsertMode = false;
            lstReturn.Clear();

            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtItem_ID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtItem_code, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtGenericname, true, false, false);

            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtClass, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtUoM, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtCategory, true, false, false);  
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtItem_type, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtBrand, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtTag1, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtTag2, true, false, false);

            cls_Formater.SetEnableDisable_LableTextbox(txtPackSize, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtSpecification, true, false, false);

            txtItem_ID.Text = "<Auto Generated>";
            txtItem_code.Text = "";
            txtGenericname.Text = "";
            txtBrand.Text = "";
            txtItem_type.Text = "";
            txtTag1.Text = "";
            txtTag2.Text = "";
            txtPackSize.Text = "";
            txtSpecification.Text = "";
            txtUoM.Text = "";
            txtCategory.Text = "";
            txtClass.Text = "";

            txtItem_ID.Tag = null;
            txtBrand.Tag = null;
            txtItem_type.Tag = null;
            txtTag1.Tag = null;
            txtTag2.Tag = null;
            txtPackSize.Tag = null;
            txtSpecification.Tag = null;
            txtUoM.Tag = null;
            txtCategory.Tag = null;
            txtClass.Tag = null;

        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_genItemMaster oDetail in tbl_genItemMaster.SelectAll().Where(p => p.IsDeleted != true && p.Item_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(oDetail.Item_ID, oDetail.GenerateCode, oDetail.ItemName, clsRef_Name.get_Item_Brand(oDetail.Brand_ID), clsRef_Name.get_Item_Type(oDetail.ItemType_ID));
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion

        #region CheckValidity
        private bool CheckValidity()
        {
            bool status = false;
            if (CheckEmptyFields())
                status = true;

            return status;
        }
        private bool CheckEmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;
            if (!clsValidation.Validate_EmptyValue(txtItem_code, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtGenericname, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtBrand, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtItem_type, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtTag1, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtTag2, ref strMessage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtPackSize, ref strMessage))
                bStatus = false;

            if (bStatus == false)
            {
                SEACCMessageBox.Show("Information", "Please fill required field " + strMessage, MessageBoxButton.OK);
            }
            return bStatus;
        }
        #endregion

        #region Search
        private void txtBrand_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Brand);
            if (RowDataSearch.DialogResult == true)
            {
                txtBrand.Tag = lstResult[0];
                txtBrand.Text = lstResult[1];
            }
        }

        private void txtItem_type_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ItemType);
            if (RowDataSearch.DialogResult == true)
            {
                txtItem_type.Tag = lstResult[0];
                txtItem_type.Text = lstResult[1];
            }
        }

        private void txtTag1_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Tag1);
            if (RowDataSearch.DialogResult == true)
            {
                txtTag1.Tag = lstResult[0];
                txtTag1.Text = lstResult[1];
            }
        }

        private void txtTag2_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Tag2);
            if (RowDataSearch.DialogResult == true)
            {
                txtTag2.Tag = lstResult[0];
                txtTag2.Text = lstResult[1];
            }
        }

        private void txtClass_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ItemClass);
            if (RowDataSearch.DialogResult == true)
            {
                txtClass.Tag = lstResult[0];
                txtClass.Text = lstResult[1];
            }
        }

        private void txtCategory_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ItemCategory);
            if (RowDataSearch.DialogResult == true)
            {
                txtCategory.Tag = lstResult[0];
                txtCategory.Text = lstResult[1];
            }
        }
        private void txtUoM_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.UOM);
            if (RowDataSearch.DialogResult == true)
            {
                txtUoM.Tag = lstResult[0];
                txtUoM.Text = lstResult[1];
            }
        }
        #endregion

    }
}
