using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;

namespace SEACC_Tender
{
    public partial class frm_MasCompetitor : Window
    {
        bool bIsInsertMode = false;
        List<string> lstReturn = new List<string>();
        public event EventHandler TextChanged;

        #region Form Load
        public frm_MasCompetitor()
        {
            InitializeComponent();

            #region Data Table Initialize
            dgr_Main.dt.Columns.Add("CompetitorID");
            dgr_Main.dt.Columns.Add("Competitor");
            dgr_Main.dt.Columns.Add("Country");
            dgr_Main.dt.Columns.Add("Remarks");
            #endregion

            #region Datagrid Column Initialize
            dgr_Main.Add_DatagridColoumn("CompetitorID", "CompetitorID", 100, false);
            dgr_Main.Add_DatagridColoumn("Competitor", "Competitor", 150);
            dgr_Main.Add_DatagridColoumn("Country", "Country", 100);
            dgr_Main.Add_DatagridColoumn("Remarks", "Remarks", 100);
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        public List<string> Show()
        {
            this.ShowDialog();
            return lstReturn;
        }

        #region Grid Drag Event
        private void Grid_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            this.DragMove();
        } 
        #endregion

        #region Action Buttons
        #region OK Button
        private void btnOK_Click(object sender, RoutedEventArgs e)
        {
            if (!bIsInsertMode)
            {
                try
                {
                    object oItem = dgr_Main.grdMain.SelectedItem;
                    if (oItem != null)
                    {
                        lstReturn.Add((dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text);
                        lstReturn.Add((dgr_Main.grdMain.SelectedCells[1].Column.GetCellContent(oItem) as TextBlock).Text);
                       
                        this.DialogResult = true;
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
            }
            else
            {
                if (CheckValidity())
                {
                    try
                    {
                        #region Insert
                        txtCompetitor_code.Text =SEACC_Tender.UserControls.clsCommon.getAutoGeneratedCode(FormName.Competitors);

                        tbl_ttsMasCompetitor oDetails = new tbl_ttsMasCompetitor(txtCompetitor_code.Text, txtCompetitorname.Text, txtRemarks.Text,txtCountry.Tag.ToString(), txtCity.Tag.ToString(), "", false);
                        oDetails.Insert();

                        lstReturn.Add(txtCompetitor_code.Text);
                        lstReturn.Add(txtCompetitorname.Text);

                        this.DialogResult = true;
                        #endregion
                    }
                    catch (Exception ex)
                    {
                        SEACCExeption.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Arrow;
                    }
                }
            }
        }
        #endregion

        #region New Button
        private void btn_New_Click(object sender, RoutedEventArgs e)
        { 
            ClearFields();
            this.Width = 840;
            bIsInsertMode = true;
        }
        #endregion

        #region Close Button
        private void btn_Close_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }
        #endregion 

        #region Grid Collapsed
        private void btn_Close2_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
            this.Width = 439;
            RefreshGrid();
            bIsInsertMode = false;
        } 
        #endregion
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            bIsInsertMode = false;
            lstReturn.Clear();
            
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtCompetitor_code, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCompetitorname, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtCountry, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtRemarks, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtCity, true, false, false);

            txtCity.Text = "";
            txtCompetitor_code.Text = "<Auto Generated>";
            txtCompetitorname.Text = "";
            txtCountry.Text = "";
            txtRemarks.Text = "";

            txtCountry.Tag = null;
            txtCity.Tag = null;
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_ttsMasCompetitor oDetail in tbl_ttsMasCompetitor.SelectAll().Where(p => p.IsCanceled != true && p.Competitor_Id!="default"))
                {
                    dgr_Main.dt.Rows.Add(oDetail.Competitor_Id, oDetail.Competitor_name, clsRef_Name.get_Country_Name(oDetail.Com_Country), oDetail.Remarks);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search
        private void txtCountry_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Country);
            if (RowDataSearch.DialogResult == true)
            {
                txtCountry.Tag = lstResult[0];
                txtCountry.Text = lstResult[1];
            }
        }

        private void txtCity_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.City);
            if (RowDataSearch.DialogResult == true)
            {
                txtCity.Tag = lstResult[0];
                txtCity.Text = lstResult[1];
                txtCountry.Tag = lstResult[6];
                txtCountry.Text = lstResult[7];
            }
        }  
        #endregion

        #region CheckValidity
        private bool CheckValidity()
        {
            bool status = false;
            if (CheckEmptyFields())
                status = true;

            return status;
        }
        private bool CheckEmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;
            if (!clsValidation.Validate_EmptyValue(txtCompetitorname, ref strMessage))
                bStatus = false;

            if (bStatus == false)
            {
                SEACCMessageBox.Show("Information", "Please fill required field " + strMessage, MessageBoxButton.OK);
            }
            return bStatus;
        }
        #endregion

        private void txtCompetitorname_KeyUp(object sender, KeyEventArgs e)
        {
            if (txtCompetitorname.Text != "")
            {
                DataView dv = dgr_Main.dt.DefaultView;
                dv.RowFilter = "Competitor LIKE '%" + txtCompetitorname.Text + "%'";
                dgr_Main.grdMain.ItemsSource = dv;
            }
            else
                dgr_Main.dt.DefaultView.RowFilter = string.Empty;
            
        }
    }
}