using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using System.Text;
using System.Windows.Forms;
using DataTire;

namespace Digiteq
{
    public partial class frm_sasCustomerOrder_Edit : MettroForm
    {
        
        //to manage update and insert
  
        static bool bIsWeightCalculation = false;
        
        //for security handle

       
   

        #region Form Load
        public frm_sasCustomerOrder_Edit()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.CustomerOrderEdit);
            iFormID = clsSecurity.getFormID(FormName.CustomerOrderEdit);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_sasCustomerOrder_Edit_Load(object sender, EventArgs e)
        {
            //format Form
            clsFormatter.setFormatForm(this, "Customer Order Edit [COE]", 2, iFormID);
            CusDataGridViewFormat();

            ClearFields();
        }
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {

                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            #region Insert
                            //Customer Order Detail                                
                            foreach (DataGridViewRow row in dgvDetail.Rows)
                            {
                                string sItemCode = "", sItemSubCategoryID = "", sItemSubCategoryID2 = "", sItemSerialNo = "", sItemSerialNo2 = "", sRemarks = "", sInquriyID = "";
                                decimal dQty = 0, dWeight = 0, dQty_DO = 0, dWeight_DO = 0, dQty_Invoice = 0, dWeight_Invoice = 0, dQty_Edit = 0, dWeight_Edit = 0;


                                dQty = clsValidate.ValidateGridValue(dgvDetail, "Quantity", row.Index, decimal.Parse("0.00"));
                                dWeight = clsValidate.ValidateGridValue(dgvDetail, "Weight", row.Index, decimal.Parse("0.00"));
                                dQty_DO = clsValidate.ValidateGridValue(dgvDetail, "QuantityDO", row.Index, decimal.Parse("0.00"));
                                dWeight_DO = clsValidate.ValidateGridValue(dgvDetail, "WeightDO", row.Index, decimal.Parse("0.00"));
                                dQty_Invoice = clsValidate.ValidateGridValue(dgvDetail, "QuantityInvoice", row.Index, decimal.Parse("0.00"));
                                dWeight_Invoice = clsValidate.ValidateGridValue(dgvDetail, "WeightInvoice", row.Index, decimal.Parse("0.00"));
                                dQty_Edit = clsValidate.ValidateGridValue(dgvDetail, "EditQuantity", row.Index, decimal.Parse("0.00"));
                                dWeight_Edit = clsValidate.ValidateGridValue(dgvDetail, "EditWeight", row.Index, decimal.Parse("0.00"));

                                sItemCode = clsValidate.ValidateGridValue(dgvDetail, "ItemCode", row.Index, "");
                                sItemSubCategoryID = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID", row.Index, "default");
                                sItemSubCategoryID2 = clsValidate.ValidateGridTag(dgvDetail, "ItemSubCategoryID2", row.Index, "default");
                                sItemSerialNo = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo", row.Index, "0");
                                sItemSerialNo2 = clsValidate.ValidateGridValue(dgvDetail, "ItemSerialNo2", row.Index, "0");
                                sInquriyID = clsValidate.ValidateGridValue(dgvDetail, "InquiryID", row.Index, "default");
                                sRemarks = clsValidate.ValidateGridValue(dgvDetail, "Remarks", row.Index, "");

                                if (sItemCode.Length > 0)
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtCustomerOrderEditId.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    if (txtCustomerOrderEditId.TextLength > 0)
                                    {

                                        tbl_sasCustomerOrder_Detail coDetail = tbl_sasCustomerOrder_Detail.Select( 0,txtCustomerOrderID.Text.Trim(),
                                            sItemCode, sItemSubCategoryID, sItemSubCategoryID2, sItemSerialNo, sItemSerialNo2);
                                        if (coDetail != null)
                                        {
                                            if (coDetail.Qty - coDetail.QtySettle_DeliveryOrder >= dQty_Edit)
                                            {
                                                //insert Edit Record
                                                tbl_sasCustomerOrder_Edit detail = new tbl_sasCustomerOrder_Edit(txtCustomerOrderEditId.Text.Trim(), sRemarks, clsSecurity.getServerDateTime(), txtCustomerOrderID.Text.Trim(),
                                                   sItemCode, sItemSubCategoryID, sItemSubCategoryID2, sItemSerialNo, sItemSerialNo2, coDetail.Qty, dQty_Edit, coDetail.Weight, dWeight_Edit, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime());
                                                detail.Insert();

                                                //update Customer Order Detail
                                                coDetail.Qty += dQty_Edit;
                                                coDetail.Weight += dWeight_Edit;
                                                coDetail.Update();

                                                CheckBox chkUnitPricing = new CheckBox();
                                                chkUnitPricing.Checked = !coDetail.IsWeightCalculation;
                                                clsProcessMethods.SetSettle_CustomerOrderFrom_DeliveryOrder(txtCustomerOrderID.Text.Trim(), chkUnitPricing);
                                            }
                                        }
                                    }
                                }

                            }
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            #endregion
                        }
                        catch (Exception ex)
                        {
                            SEACCException.Show(ex);
                            clsValidate.WriteErrorLog("", iFormID,ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            tbl_sasCustomerOrder oldRecord = tbl_sasCustomerOrder.Select(txtCustomerOrderID.Text.Trim());
                            if (oldRecord != null)
                                FillDetails(txtCustomerOrderID.Text.Trim());
                        }
                    }
                }

            }
        }
        #endregion        

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 0)
                    {
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);                      
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion


        #region ClearFields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            lblCancelled.Visible = false;
            bIsWeightCalculation = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCustomerOrderID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblCustomerOrderID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtCustomerName,true);
            clsCommon.SetEnableDisable_NormalLabel(lblCustomerID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtSalesExecutiveID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblRep, true);

            clsCommon.SetEnableDisable_NormalLabel(lblRemark,true);
            clsCommon.SetEnableDisable_NormalTextbox(txtRemark,true);

            clsCommon.SetEnableDisable_NormalLabel(lblCustomerOrderDate,true);
            clsCommon.SetEnableDisable_NormalDateTimePicker(dtpCustomerOrderDate,true);
            clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo,true);
            clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo,true);
            clsCommon.SetEnableDisable_NormalLabel(lblPurchasedOrderNo,true);
            clsCommon.SetEnableDisable_NormalTextbox(txtPurchaseOrder,true);

            txtCustomerOrderID.Tag = null;
            txtCustomerOrderID.Text = "";
            txtCustomerName.Clear();
            txtSalesExecutiveID.Clear();
            txtRemark.Clear();
            dtpCustomerOrderDate.Value = clsSecurity.getServerDateTime();
            txtOrderRefNo.Clear();
            txtPurchaseOrder.Clear();

            dgvDetail.Rows.Clear();

            txtCustomerOrderID.Focus();
            txtCustomerOrderID.SelectAll();
        }
        #endregion        

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour, clsFormatter.colorDigiteqTheamColorSales1BackColour);
            
        }
        private void FormatGridView(bool bIsWeightCalculation)
        {
            if (bIsWeightCalculation)
            {
                dgvDetail.Columns["Quantity"].Visible = false;
                dgvDetail.Columns["Weight"].Visible = true;
                dgvDetail.Columns["QuantityDO"].Visible = false;
                dgvDetail.Columns["WeightDO"].Visible = true;
                dgvDetail.Columns["QuantityInvoice"].Visible = false;
                dgvDetail.Columns["WeightInvoice"].Visible = true;
                dgvDetail.Columns["EditQuantity"].Visible = false;
                dgvDetail.Columns["EditWeight"].Visible = true;
            }
            else
            {
                dgvDetail.Columns["Quantity"].Visible = true;
                dgvDetail.Columns["Weight"].Visible = false;
                dgvDetail.Columns["QuantityDO"].Visible = true;
                dgvDetail.Columns["WeightDO"].Visible = false;
                dgvDetail.Columns["QuantityInvoice"].Visible = true;
                dgvDetail.Columns["WeightInvoice"].Visible = false;
                dgvDetail.Columns["EditQuantity"].Visible = true;
                dgvDetail.Columns["EditWeight"].Visible = false;
            }

            clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour, clsFormatter.colorDigiteqTheamColorSales1BackColour);

        }
        #endregion
        
        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_sasCustomerOrder detail = tbl_sasCustomerOrder.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        if (detail.IsDeleted)
                            lblCancelled.Visible = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCustomerOrderID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblCustomerOrderID, false);
                        clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtCustomerName, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblCustomerID, false);
                        clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtSalesExecutiveID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblRep, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblRemark, false);
                        clsCommon.SetEnableDisable_NormalTextbox(txtRemark, false);

                        clsCommon.SetEnableDisable_NormalLabel(lblCustomerOrderDate, false);
                        clsCommon.SetEnableDisable_NormalDateTimePicker(dtpCustomerOrderDate, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblOrderRefNo, false);
                        clsCommon.SetEnableDisable_NormalTextbox(txtOrderRefNo, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblPurchasedOrderNo, false);
                        clsCommon.SetEnableDisable_NormalTextbox(txtPurchaseOrder, false);

                        //asign values
                        txtCustomerOrderID.Text = detail.CustomerOrder_ID;
                        txtCustomerName.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_Customer(detail.Customer_ID));
                        txtSalesExecutiveID.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_SalesRep(detail.Employee_ID));
                        txtRemark.Text = detail.Remark;
                        dtpCustomerOrderDate.Value=detail.CustomerOrderDate;
                        txtOrderRefNo.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_OrderRefNo(detail.OrderRefNo_ID));//detail.OrderRefNo_ID;
                        txtPurchaseOrder.Text = detail.PurchaseOrder_ID;
                        bIsWeightCalculation = detail.IsWeightCalculation;

                        FormatGridView(detail.IsWeightCalculation);
                        RefreshGrid(sID);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh
        private void RefreshGrid(string sID)
        {
            try
            {
                int iRow;
                decimal dDOQty = 0, dDOWeight = 0, dInvoiceQty = 0, dInvoiceWeight = 0;                
                dgvDetail.Rows.Clear();
                tbl_sasCustomerOrder cOrder = tbl_sasCustomerOrder.Select(sID);
                if (cOrder != null)
                {

                    List<tbl_sasCustomerOrder_Detail> details = tbl_sasCustomerOrder_Detail.SelectAllByCustomerOrder_ID(sID);
                    foreach (tbl_sasCustomerOrder_Detail detail in details)
                    {
                        //tbl_sasDeliveryOrder_Detail DO = tbl_sasDeliveryOrder_Detail.SelectAllByItem_ID(detail.Item_ID);

                        if (detail.CustomerOrder_ID.Trim() != "default")
                        {
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            dgvDetail["ItemCode", iRow].Value = detail.Item_ID;
                            dgvDetail["ItemName", iRow].Value = clsGenaralName.getName_Item(detail.Item_ID);
                            dgvDetail["ItemSubCategoryID", iRow].Tag = detail.ItemSubCategory_ID;
                            dgvDetail["ItemSubCategoryID2", iRow].Tag = detail.ItemSubCategory2_ID;
                            dgvDetail["ItemSubCategoryID", iRow].Value = detail.ItemSubCategory_ID;
                            dgvDetail["ItemSubCategoryID2", iRow].Value = detail.ItemSubCategory2_ID;
                            dgvDetail["ItemSerialNo", iRow].Value = detail.ItemSerialNo;
                            dgvDetail["ItemSerialNo2", iRow].Value = detail.ItemSerialNo2;
                            dgvDetail["InquiryID", iRow].Value = detail.Inquiry_ID;
                            dgvDetail["Remarks", iRow].Value = detail.Remark;
                            dgvDetail["UOM", iRow].Value = clsGenaralName.getName_ItemUOM(detail.Item_ID);
                            dgvDetail["Quantity", iRow].Value = clsFormatter.FormatToNumberNoDecimal(detail.Qty);
                            dgvDetail["Weight", iRow].Value = clsFormatter.FormatToNumberNoDecimal(detail.Weight);

                            dDOQty = getDeliveryOrder_Qty(sID, detail.Item_ID, detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2);
                            dDOWeight = getDeliveryOrder_Weight(sID, detail.Item_ID, detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2);
                            dInvoiceQty = getInvoice_Qty(sID, detail.Item_ID, detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2);
                            dInvoiceWeight = getInvoice_Weight(sID, detail.Item_ID, detail.ItemSubCategory_ID, detail.ItemSubCategory2_ID, detail.ItemSerialNo, detail.ItemSerialNo2);
                            dgvDetail["QuantityDO", iRow].Value = clsFormatter.FormatToNumberNoDecimal(dDOQty);
                            dgvDetail["WeightDO", iRow].Value = clsFormatter.FormatToNumberNoDecimal(dDOWeight);
                            dgvDetail["QuantityInvoice", iRow].Value = clsFormatter.FormatToNumberNoDecimal(dInvoiceQty);
                            dgvDetail["WeightInvoice", iRow].Value = clsFormatter.FormatToNumberNoDecimal(dInvoiceWeight);
                            if (cOrder.IsWeightCalculation)
                            {
                                dgvDetail["EditWeight", iRow].Value = clsFormatter.FormatToNumberNoDecimal(getEditValue(detail.Weight, dDOWeight, dInvoiceWeight));
                                dgvDetail["EditQuantity", iRow].Value = 0;                                
                            }
                            else
                            {
                                dgvDetail["EditQuantity", iRow].Value = clsFormatter.FormatToNumberNoDecimal(getEditValue(detail.Qty, dDOQty, dInvoiceQty));
                                dgvDetail["EditWeight", iRow].Value = 0;
                            }
                        }
                    }
                }                
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion        

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtCustomerOrderID.TextLength == 0)
            {
                strMessage += "\n" + "Customer Order ";
                bStatus = false;
            }           
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }





        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {
                
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }


        #endregion
       


        #region Event DoubleClick
        private void txtCustomerOrderID_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_TransactionCustomerOrder_Direct(ref txtCustomerOrderID, true);
            if (txtCustomerOrderID.Tag != null && txtCustomerOrderID.Tag.ToString().Trim().Length > 0)
                FillDetails(txtCustomerOrderID.Tag.ToString());

           
        }                
        #endregion    
    
        #region Search Methods
        private void Search_CustomerID()
        {
            
        }
        #endregion    
    
        #region Get Qty/Weight Methods
        private decimal getDeliveryOrder_Qty(string sCustomerOrderID, string sItemID, string sSubCategory1, string sSubCateogry2, string sSerial1, string sSerial2)
        {
            decimal dQty = 0;
            try
            {
                List<tbl_sasDeliveryOrder_Detail> details = tbl_sasDeliveryOrder_Detail.SelectAllByCustomerOrder_ID(sCustomerOrderID);
                foreach (tbl_sasDeliveryOrder_Detail detail in details)
                {
                    if (detail.Item_ID == sItemID && detail.ItemSubCategory_ID == sSubCategory1 && detail.ItemSubCategory2_ID == sSubCateogry2 && detail.ItemSerialNo == sSerial1 && detail.ItemSerialNo2 == sSerial2)
                    {
                        dQty += detail.Qty;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return dQty;
        }
        private decimal getDeliveryOrder_Weight(string sCustomerOrderID, string sItemID, string sSubCategory1, string sSubCateogry2, string sSerial1, string sSerial2)
        {
            decimal dWeight = 0;
            try
            {
                List<tbl_sasDeliveryOrder_Detail> details = tbl_sasDeliveryOrder_Detail.SelectAllByCustomerOrder_ID(sCustomerOrderID);
                foreach (tbl_sasDeliveryOrder_Detail detail in details)
                {
                    if (detail.Item_ID == sItemID && detail.ItemSubCategory_ID == sSubCategory1 && detail.ItemSubCategory2_ID == sSubCateogry2 && detail.ItemSerialNo == sSerial1 && detail.ItemSerialNo2 == sSerial2)
                    {
                        dWeight += detail.Weight;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return dWeight;
        }
        private decimal getInvoice_Qty(string sCustomerOrderID, string sItemID, string sSubCategory1, string sSubCateogry2, string sSerial1, string sSerial2)
        {
            decimal dQty = 0;
            try
            {
                List<tbl_sasDeliveryOrder_Detail> details = tbl_sasDeliveryOrder_Detail.SelectAllByCustomerOrder_ID(sCustomerOrderID);
                foreach (tbl_sasDeliveryOrder_Detail detail in details)
                {
                    List<tbl_sasInvoice_Detail> invDetails = tbl_sasInvoice_Detail.SelectAllByDeliveryOrder_ID(detail.DeliveryOrder_ID);
                    foreach (tbl_sasInvoice_Detail invDetail in invDetails)
                    {
                        if (invDetail.Item_ID == sItemID && invDetail.ItemSubCategory_ID == sSubCategory1 && invDetail.ItemSubCategory2_ID == sSubCateogry2 && invDetail.ItemSerialNo == sSerial1 && invDetail.ItemSerialNo2 == sSerial2)
                        {
                            dQty += detail.Qty;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return dQty;
        }
        private decimal getInvoice_Weight(string sCustomerOrderID, string sItemID, string sSubCategory1, string sSubCateogry2, string sSerial1, string sSerial2)
        {
            decimal dWeight = 0;
            try
            {
                List<tbl_sasDeliveryOrder_Detail> details = tbl_sasDeliveryOrder_Detail.SelectAllByCustomerOrder_ID(sCustomerOrderID);
                foreach (tbl_sasDeliveryOrder_Detail detail in details)
                {
                    List<tbl_sasInvoice_Detail> invDetails = tbl_sasInvoice_Detail.SelectAllByDeliveryOrder_ID(detail.DeliveryOrder_ID);
                    foreach (tbl_sasInvoice_Detail invDetail in invDetails)
                    {
                        if (invDetail.Item_ID == sItemID && invDetail.ItemSubCategory_ID == sSubCategory1 && invDetail.ItemSubCategory2_ID == sSubCateogry2 && invDetail.ItemSerialNo == sSerial1 && invDetail.ItemSerialNo2 == sSerial2)
                        {
                            dWeight += detail.Weight;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return dWeight;
        }
        private decimal getEditValue(decimal dCoValue, decimal dDOValue, decimal dInvoiceValue)
        {
            decimal dEditValue = 0;
            try
            {
                if (dDOValue >= dInvoiceValue)
                    dEditValue = dDOValue - dCoValue;
                else
                    dEditValue = dInvoiceValue - dCoValue;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return dEditValue;
        }
        #endregion
    }
}
