exports.up = async function(knex) {
  const tenant  = await knex('sec_tenants').where({ tenantName: 'demo' }).first();
  const company = await knex('sec_companies').where({ tenantId: tenant.tenantId, companyName: 'Demo Company' }).first();
  const base = { tenantId: tenant.tenantId, companyId: company.companyId };

  return knex('ref_category').insert([







{ ...base,id: 1,  categoryType:2107, value:'AF', description:'Afghanistan', ref1:'AFG', ref2:'004', parentId:'1',               isActive:1 },
{ ...base,id: 2,  categoryType:2107, value:'AL', description:'Albania',     ref1:'ALB', ref2:'008', parentId:'2',            isActive:1 },
{ ...base,id: 3,  categoryType:2107, value:'DZ', description:'Algeria',     ref1:'DZA', ref2:'012', parentId:'3',            isActive:1 },
{ ...base,id: 4,  categoryType:2107, value:'AD', description:'Andorra',     ref1:'AND', ref2:'020', parentId:'4',            isActive:1 },
{ ...base,id: 5,  categoryType:2107, value:'AO', description:'Angola',      ref1:'AGO', ref2:'024', parentId:'5',         isActive:1 },
{ ...base,id: 6,  categoryType:2107, value:'AG', description:'Antigua and Barbuda', ref1:'ATG', ref2:'028', parentId:'6',       isActive:1 },
{ ...base,id: 7,  categoryType:2107, value:'AR', description:'Argentina',   ref1:'ARG', ref2:'032', parentId:'7',              isActive:1 },
{ ...base,id: 8,  categoryType:2107, value:'AM', description:'Armenia',     ref1:'ARM', ref2:'051', parentId:'8',               isActive:1 },
{ ...base,id: 9,  categoryType:2107, value:'AU', description:'Australia',   ref1:'AUS', ref2:'036', parentId:'9',  isActive:1 },
{ ...base,id:10,  categoryType:2107, value:'AT', description:'Austria',     ref1:'AUT', ref2:'040', parentId:'10',             isActive:1 },
{ ...base,id:11,  categoryType:2107, value:'AZ', description:'Azerbaijan',  ref1:'AZE', ref2:'031', parentId:'11',               isActive:1 },
{ ...base,id:12,  categoryType:2107, value:'BS', description:'Bahamas',     ref1:'BHS', ref2:'044', parentId:'12',                  isActive:1 },
{ ...base,id:13,  categoryType:2107, value:'BH', description:'Bahrain',     ref1:'BHR', ref2:'048', parentId:'13',               isActive:1 },
{ ...base,id:14,  categoryType:2107, value:'BD', description:'Bangladesh',  ref1:'BGD', ref2:'050', parentId:'14',              isActive:1 },
{ ...base,id:15,  categoryType:2107, value:'BB', description:'Barbados',    ref1:'BRB', ref2:'052', parentId:'15',                  isActive:1 },
{ ...base,id:16,  categoryType:2107, value:'BY', description:'Belarus',     ref1:'BLR', ref2:'112', parentId:'16',             isActive:1 },
{ ...base,id:17,  categoryType:2107, value:'BE', description:'Belgium',     ref1:'BEL', ref2:'056', parentId:'17',             isActive:1 },
{ ...base,id:18,  categoryType:2107, value:'BZ', description:'Belize',      ref1:'BLZ', ref2:'084', parentId:'18',            isActive:1 },
{ ...base,id:19,  categoryType:2107, value:'BJ', description:'Benin',       ref1:'BEN', ref2:'204', parentId:'19',         isActive:1 },
{ ...base,id:20,  categoryType:2107, value:'BT', description:'Bhutan',      ref1:'BTN', ref2:'064', parentId:'20',              isActive:1 },
{ ...base,id:21,  categoryType:2107, value:'BO', description:'Bolivia, Plurinational State of', ref1:'BOL', ref2:'068', parentId:'21', isActive:1 },
{ ...base,id:22,  categoryType:2107, value:'BA', description:'Bosnia and Herzegovina', ref1:'BIH', ref2:'070', parentId:'22', isActive:1 },
{ ...base,id:23,  categoryType:2107, value:'BW', description:'Botswana',    ref1:'BWA', ref2:'072', parentId:'23',         isActive:1 },
{ ...base,id:24,  categoryType:2107, value:'BR', description:'Brazil',      ref1:'BRA', ref2:'076', parentId:'24',              isActive:1 },
{ ...base,id:25,  categoryType:2107, value:'BN', description:'Brunei Darussalam', ref1:'BRN', ref2:'096', parentId:'25',   isActive:1 },
{ ...base,id:26,  categoryType:2107, value:'BG', description:'Bulgaria',    ref1:'BGR', ref2:'100', parentId:'10',             isActive:1 },
{ ...base,id:27,  categoryType:2107, value:'BF', description:'Burkina Faso',ref1:'BFA', ref2:'854', parentId:'4',         isActive:1 },
{ ...base,id:28,  categoryType:2107, value:'BI', description:'Burundi',     ref1:'BDI', ref2:'108', parentId:'4',         isActive:1 },
{ ...base,id:29,  categoryType:2107, value:'CV', description:'Cabo Verde',  ref1:'CPV', ref2:'132', parentId:'4',         isActive:1 },
{ ...base,id:30,  categoryType:2107, value:'KH', description:'Cambodia',    ref1:'KHM', ref2:'116', parentId:'12',         isActive:1 },
{ ...base,id:31,  categoryType:2107, value:'CM', description:'Cameroon',    ref1:'CMR', ref2:'120', parentId:'4',         isActive:1 },
{ ...base,id:32,  categoryType:2107, value:'CA', description:'Canada',      ref1:'CAN', ref2:'124', parentId:'13',           isActive:1 },
{ ...base,id:33,  categoryType:2107, value:'CF', description:'Central African Republic', ref1:'CAF', ref2:'140', parentId:'4', isActive:1 },
{ ...base,id:34,  categoryType:2107, value:'TD', description:'Chad',        ref1:'TCD', ref2:'148', parentId:'4',         isActive:1 },
{ ...base,id:35,  categoryType:2107, value:'CL', description:'Chile',       ref1:'CHL', ref2:'152', parentId:'6',              isActive:1 },
{ ...base,id:36,  categoryType:2107, value:'CN', description:'China',       ref1:'CHN', ref2:'156', parentId:'14',               isActive:1 },
{ ...base,id:37,  categoryType:2107, value:'CO', description:'Colombia',    ref1:'COL', ref2:'170', parentId:'6',              isActive:1 },
{ ...base,id:38,  categoryType:2107, value:'KM', description:'Comoros',     ref1:'COM', ref2:'174', parentId:'4',         isActive:1 },
{ ...base,id:39,  categoryType:2107, value:'CG', description:'Congo',       ref1:'COG', ref2:'178', parentId:'4',         isActive:1 },
{ ...base,id:40,  categoryType:2107, value:'CD', description:'Congo, Democratic Republic of the', ref1:'COD', ref2:'180', parentId:'4', isActive:1 },
{ ...base,id:41,  categoryType:2107, value:'CR', description:'Costa Rica',  ref1:'CRI', ref2:'188', parentId:'11',            isActive:1 },
{ ...base,id:42,  categoryType:2107, value:'CI', description:"Côte d'Ivoire", ref1:'CIV', ref2:'384', parentId:'4',     isActive:1 },
{ ...base,id:43,  categoryType:2107, value:'HR', description:'Croatia',     ref1:'HRV', ref2:'191', parentId:'2',            isActive:1 },
{ ...base,id:44,  categoryType:2107, value:'CU', description:'Cuba',        ref1:'CUB', ref2:'192', parentId:'5',                  isActive:1 },
{ ...base,id:45,  categoryType:2107, value:'CY', description:'Cyprus',      ref1:'CYP', ref2:'196', parentId:'7',               isActive:1 },
{ ...base,id:46,  categoryType:2107, value:'CZ', description:'Czechia',     ref1:'CZE', ref2:'203', parentId:'10',             isActive:1 },
{ ...base,id:47,  categoryType:2107, value:'DK', description:'Denmark',     ref1:'DNK', ref2:'208', parentId:'15',            isActive:1 },
{ ...base,id:48,  categoryType:2107, value:'DJ', description:'Djibouti',    ref1:'DJI', ref2:'262', parentId:'4',         isActive:1 },
{ ...base,id:49,  categoryType:2107, value:'DM', description:'Dominica',    ref1:'DMA', ref2:'212', parentId:'5',                  isActive:1 },
{ ...base,id:50,  categoryType:2107, value:'DO', description:'Dominican Republic', ref1:'DOM', ref2:'214', parentId:'5',         isActive:1 },
{ ...base,id:51,  categoryType:2107, value:'EC', description:'Ecuador',     ref1:'ECU', ref2:'218', parentId:'6',              isActive:1 },
{ ...base,id:52,  categoryType:2107, value:'EG', description:'Egypt',       ref1:'EGY', ref2:'818', parentId:'3',            isActive:1 },
{ ...base,id:53,  categoryType:2107, value:'SV', description:'El Salvador', ref1:'SLV', ref2:'222', parentId:'11',            isActive:1 },
{ ...base,id:54,  categoryType:2107, value:'GQ', description:'Equatorial Guinea', ref1:'GNQ', ref2:'226', parentId:'4',  isActive:1 },
{ ...base,id:55,  categoryType:2107, value:'ER', description:'Eritrea',     ref1:'ERI', ref2:'232', parentId:'4',         isActive:1 },
{ ...base,id:56,  categoryType:2107, value:'EE', description:'Estonia',     ref1:'EST', ref2:'233', parentId:'15',            isActive:1 },
{ ...base,id:57,  categoryType:2107, value:'SZ', description:'Eswatini',    ref1:'SWZ', ref2:'748', parentId:'4',         isActive:1 },
{ ...base,id:58,  categoryType:2107, value:'ET', description:'Ethiopia',    ref1:'ETH', ref2:'231', parentId:'4',         isActive:1 },
{ ...base,id:59,  categoryType:2107, value:'FJ', description:'Fiji',        ref1:'FJI', ref2:'242', parentId:'16',                  isActive:1 },
{ ...base,id:60,  categoryType:2107, value:'FI', description:'Finland',     ref1:'FIN', ref2:'246', parentId:'15',            isActive:1 },
{ ...base,id:61,  categoryType:2107, value:'FR', description:'France',      ref1:'FRA', ref2:'250', parentId:'9',             isActive:1 },
{ ...base,id:62,  categoryType:2107, value:'GA', description:'Gabon',       ref1:'GAB', ref2:'266', parentId:'4',         isActive:1 },
{ ...base,id:63,  categoryType:2107, value:'GM', description:'Gambia',      ref1:'GMB', ref2:'270', parentId:'4',         isActive:1 },
{ ...base,id:64,  categoryType:2107, value:'GE', description:'Georgia',     ref1:'GEO', ref2:'268', parentId:'7',               isActive:1 },
{ ...base,id:65,  categoryType:2107, value:'DE', description:'Germany',     ref1:'DEU', ref2:'276', parentId:'9',             isActive:1 },
{ ...base,id:66,  categoryType:2107, value:'GH', description:'Ghana',       ref1:'GHA', ref2:'288', parentId:'4',         isActive:1 },
{ ...base,id:67,  categoryType:2107, value:'GR', description:'Greece',      ref1:'GRC', ref2:'300', parentId:'2',            isActive:1 },
{ ...base,id:68,  categoryType:2107, value:'GD', description:'Grenada',     ref1:'GRD', ref2:'308', parentId:'5',                  isActive:1 },
{ ...base,id:69,  categoryType:2107, value:'GT', description:'Guatemala',   ref1:'GTM', ref2:'320', parentId:'11',            isActive:1 },
{ ...base,id:70,  categoryType:2107, value:'GN', description:'Guinea',      ref1:'GIN', ref2:'324', parentId:'4',         isActive:1 },
{ ...base,id:71,  categoryType:2107, value:'GW', description:'Guinea-Bissau', ref1:'GNB', ref2:'624', parentId:'4',     isActive:1 },
{ ...base,id:72,  categoryType:2107, value:'GY', description:'Guyana',      ref1:'GUY', ref2:'328', parentId:'6',              isActive:1 },
{ ...base,id:73,  categoryType:2107, value:'HT', description:'Haiti',       ref1:'HTI', ref2:'332', parentId:'5',                  isActive:1 },
{ ...base,id:74,  categoryType:2107, value:'HN', description:'Honduras',    ref1:'HND', ref2:'340', parentId:'11',            isActive:1 },
{ ...base,id:75,  categoryType:2107, value:'HU', description:'Hungary',     ref1:'HUN', ref2:'348', parentId:'10',             isActive:1 },
{ ...base,id:76,  categoryType:2107, value:'IS', description:'Iceland',     ref1:'ISL', ref2:'352', parentId:'15',            isActive:1 },
{ ...base,id:77,  categoryType:2107, value:'IN', description:'India',       ref1:'IND', ref2:'356', parentId:'1',              isActive:1 },
{ ...base,id:78,  categoryType:2107, value:'ID', description:'Indonesia',   ref1:'IDN', ref2:'360', parentId:'12',         isActive:1 },
{ ...base,id:79,  categoryType:2107, value:'IR', description:'Iran, Islamic Republic of', ref1:'IRN', ref2:'364', parentId:'1', isActive:1 },
{ ...base,id:80,  categoryType:2107, value:'IQ', description:'Iraq',        ref1:'IRQ', ref2:'368', parentId:'7',               isActive:1 },
{ ...base,id:81,  categoryType:2107, value:'IE', description:'Ireland',     ref1:'IRL', ref2:'372', parentId:'15',            isActive:1 },
{ ...base,id:82,  categoryType:2107, value:'IL', description:'Israel',      ref1:'ISR', ref2:'376', parentId:'7',               isActive:1 },
{ ...base,id:83,  categoryType:2107, value:'IT', description:'Italy',       ref1:'ITA', ref2:'380', parentId:'2',            isActive:1 },
{ ...base,id:84,  categoryType:2107, value:'JM', description:'Jamaica',     ref1:'JAM', ref2:'388', parentId:'5',                  isActive:1 },
{ ...base,id:85,  categoryType:2107, value:'JP', description:'Japan',       ref1:'JPN', ref2:'392', parentId:'14',               isActive:1 },
{ ...base,id:86,  categoryType:2107, value:'JO', description:'Jordan',      ref1:'JOR', ref2:'400', parentId:'7',               isActive:1 },
{ ...base,id:87,  categoryType:2107, value:'KZ', description:'Kazakhstan',  ref1:'KAZ', ref2:'398', parentId:'17',               isActive:1 },
{ ...base,id:88,  categoryType:2107, value:'KE', description:'Kenya',       ref1:'KEN', ref2:'404', parentId:'4',         isActive:1 },
{ ...base,id:89,  categoryType:2107, value:'KI', description:'Kiribati',    ref1:'KIR', ref2:'296', parentId:'18',                 isActive:1 },
{ ...base,id:90,  categoryType:2107, value:'KP', description:"Korea, Democratic People's Republic of", ref1:'PRK', ref2:'408', parentId:'14', isActive:1 },
{ ...base,id:91,  categoryType:2107, value:'KR', description:'Korea, Republic of', ref1:'KOR', ref2:'410', parentId:'14',     isActive:1 },
{ ...base,id:92,  categoryType:2107, value:'KW', description:'Kuwait',      ref1:'KWT', ref2:'414', parentId:'7',               isActive:1 },
{ ...base,id:93,  categoryType:2107, value:'KG', description:'Kyrgyzstan',  ref1:'KGZ', ref2:'417', parentId:'17',               isActive:1 },
{ ...base,id:94,  categoryType:2107, value:'LA', description:"Lao People's Democratic Republic", ref1:'LAO', ref2:'418', parentId:'12', isActive:1 },
{ ...base,id:95,  categoryType:2107, value:'LV', description:'Latvia',      ref1:'LVA', ref2:'428', parentId:'15',            isActive:1 },
{ ...base,id:96,  categoryType:2107, value:'LB', description:'Lebanon',     ref1:'LBN', ref2:'422', parentId:'7',               isActive:1 },
{ ...base,id:97,  categoryType:2107, value:'LS', description:'Lesotho',     ref1:'LSO', ref2:'426', parentId:'4',         isActive:1 },
{ ...base,id:98,  categoryType:2107, value:'LR', description:'Liberia',     ref1:'LBR', ref2:'430', parentId:'4',         isActive:1 },
{ ...base,id:99,  categoryType:2107, value:'LY', description:'Libya',       ref1:'LBY', ref2:'434', parentId:'3',            isActive:1 },
{ ...base,id:100, categoryType:2107, value:'LI', description:'Liechtenstein', ref1:'LIE', ref2:'438', parentId:'9',          isActive:1 },
{ ...base,id:101, categoryType:2107, value:'LT', description:'Lithuania',   ref1:'LTU', ref2:'440', parentId:'15',            isActive:1 },
{ ...base,id:102, categoryType:2107, value:'LU', description:'Luxembourg',  ref1:'LUX', ref2:'442', parentId:'9',             isActive:1 },
{ ...base,id:103, categoryType:2107, value:'MG', description:'Madagascar',  ref1:'MDG', ref2:'450', parentId:'4',         isActive:1 },
{ ...base,id:104, categoryType:2107, value:'MW', description:'Malawi',      ref1:'MWI', ref2:'454', parentId:'4',         isActive:1 },
{ ...base,id:105, categoryType:2107, value:'MY', description:'Malaysia',    ref1:'MYS', ref2:'458', parentId:'12',         isActive:1 },
{ ...base,id:106, categoryType:2107, value:'MV', description:'Maldives',    ref1:'MDV', ref2:'462', parentId:'1',              isActive:1 },
{ ...base,id:107, categoryType:2107, value:'ML', description:'Mali',        ref1:'MLI', ref2:'466', parentId:'4',         isActive:1 },
{ ...base,id:108, categoryType:2107, value:'MT', description:'Malta',       ref1:'MLT', ref2:'470', parentId:'2',            isActive:1 },
{ ...base,id:109, categoryType:2107, value:'MH', description:'Marshall Islands', ref1:'MHL', ref2:'584', parentId:'18',          isActive:1 },
{ ...base,id:110, categoryType:2107, value:'MR', description:'Mauritania',  ref1:'MRT', ref2:'478', parentId:'4',         isActive:1 },
{ ...base,id:111, categoryType:2107, value:'MU', description:'Mauritius',   ref1:'MUS', ref2:'480', parentId:'4',         isActive:1 },
{ ...base,id:112, categoryType:2107, value:'MX', description:'Mexico',      ref1:'MEX', ref2:'484', parentId:'11',            isActive:1 },
{ ...base,id:113, categoryType:2107, value:'FM', description:'18, Federated States of', ref1:'FSM', ref2:'583', parentId:'18', isActive:1 },
{ ...base,id:114, categoryType:2107, value:'MD', description:'Moldova, Republic of', ref1:'MDA', ref2:'498', parentId:'10',  isActive:1 },
{ ...base,id:115, categoryType:2107, value:'MC', description:'Monaco',      ref1:'MCO', ref2:'492', parentId:'9',             isActive:1 },
{ ...base,id:116, categoryType:2107, value:'MN', description:'Mongolia',    ref1:'MNG', ref2:'496', parentId:'14',               isActive:1 },
{ ...base,id:117, categoryType:2107, value:'ME', description:'Montenegro',  ref1:'MNE', ref2:'499', parentId:'2',            isActive:1 },
{ ...base,id:118, categoryType:2107, value:'MA', description:'Morocco',     ref1:'MAR', ref2:'504', parentId:'3',            isActive:1 },
{ ...base,id:119, categoryType:2107, value:'MZ', description:'Mozambique',  ref1:'MOZ', ref2:'508', parentId:'4',         isActive:1 },
{ ...base,id:120, categoryType:2107, value:'MM', description:'Myanmar',     ref1:'MMR', ref2:'104', parentId:'12',         isActive:1 },
{ ...base,id:121, categoryType:2107, value:'NA', description:'Namibia',     ref1:'NAM', ref2:'516', parentId:'4',         isActive:1 },
{ ...base,id:122, categoryType:2107, value:'NR', description:'Nauru',       ref1:'NRU', ref2:'520', parentId:'18',                 isActive:1 },
{ ...base,id:123, categoryType:2107, value:'NP', description:'Nepal',       ref1:'NPL', ref2:'524', parentId:'1',              isActive:1 },
{ ...base,id:124, categoryType:2107, value:'NL', description:'Netherlands', ref1:'NLD', ref2:'528', parentId:'9',             isActive:1 },
{ ...base,id:125, categoryType:2107, value:'NZ', description:'New Zealand', ref1:'NZL', ref2:'554', parentId:'8',  isActive:1 },
{ ...base,id:126, categoryType:2107, value:'NI', description:'Nicaragua',   ref1:'NIC', ref2:'558', parentId:'11',            isActive:1 },
{ ...base,id:127, categoryType:2107, value:'NE', description:'Niger',       ref1:'NER', ref2:'562', parentId:'4',         isActive:1 },
{ ...base,id:128, categoryType:2107, value:'NG', description:'Nigeria',     ref1:'NGA', ref2:'566', parentId:'4',         isActive:1 },
{ ...base,id:129, categoryType:2107, value:'MK', description:'North Macedonia', ref1:'MKD', ref2:'807', parentId:'2',      isActive:1 },
{ ...base,id:130, categoryType:2107, value:'NO', description:'Norway',      ref1:'NOR', ref2:'578', parentId:'15',            isActive:1 },
{ ...base,id:131, categoryType:2107, value:'OM', description:'Oman',        ref1:'OMN', ref2:'512', parentId:'7',               isActive:1 },
{ ...base,id:132, categoryType:2107, value:'PK', description:'Pakistan',    ref1:'PAK', ref2:'586', parentId:'1',              isActive:1 },
{ ...base,id:133, categoryType:2107, value:'PW', description:'Palau',       ref1:'PLW', ref2:'585', parentId:'18',                 isActive:1 },
{ ...base,id:134, categoryType:2107, value:'PA', description:'Panama',      ref1:'PAN', ref2:'591', parentId:'11',            isActive:1 },
{ ...base,id:135, categoryType:2107, value:'PG', description:'Papua New Guinea', ref1:'PNG', ref2:'598', parentId:'16',           isActive:1 },
{ ...base,id:136, categoryType:2107, value:'PY', description:'Paraguay',    ref1:'PRY', ref2:'600', parentId:'6',              isActive:1 },
{ ...base,id:137, categoryType:2107, value:'PE', description:'Peru',        ref1:'PER', ref2:'604', parentId:'6',              isActive:1 },
{ ...base,id:138, categoryType:2107, value:'PH', description:'Philippines', ref1:'PHL', ref2:'608', parentId:'12',         isActive:1 },
{ ...base,id:139, categoryType:2107, value:'PL', description:'Poland',      ref1:'POL', ref2:'616', parentId:'10',             isActive:1 },
{ ...base,id:140, categoryType:2107, value:'PT', description:'Portugal',    ref1:'PRT', ref2:'620', parentId:'2',            isActive:1 },
{ ...base,id:141, categoryType:2107, value:'QA', description:'Qatar',       ref1:'QAT', ref2:'634', parentId:'7',               isActive:1 },
{ ...base,id:142, categoryType:2107, value:'RO', description:'Romania',     ref1:'ROU', ref2:'642', parentId:'10',             isActive:1 },
{ ...base,id:143, categoryType:2107, value:'RU', description:'Russian Federation', ref1:'RUS', ref2:'643', parentId:'10',  isActive:1 },
{ ...base,id:144, categoryType:2107, value:'RW', description:'Rwanda',      ref1:'RWA', ref2:'646', parentId:'4',         isActive:1 },
{ ...base,id:145, categoryType:2107, value:'KN', description:'Saint Kitts and Nevis', ref1:'KNA', ref2:'659', parentId:'5',     isActive:1 },
{ ...base,id:146, categoryType:2107, value:'LC', description:'Saint Lucia', ref1:'LCA', ref2:'662', parentId:'5',                  isActive:1 },
{ ...base,id:147, categoryType:2107, value:'VC', description:'Saint Vincent and the Grenadines', ref1:'VCT', ref2:'670', parentId:'5', isActive:1 },
{ ...base,id:148, categoryType:2107, value:'WS', description:'Samoa',       ref1:'WSM', ref2:'882', parentId:'19',                  isActive:1 },
{ ...base,id:149, categoryType:2107, value:'SM', description:'San Marino',  ref1:'SMR', ref2:'674', parentId:'2',            isActive:1 },
{ ...base,id:150, categoryType:2107, value:'ST', description:'Sao Tome and Principe', ref1:'STP', ref2:'678', parentId:'4', isActive:1 },
{ ...base,id:151, categoryType:2107, value:'SA', description:'Saudi Arabia', ref1:'SAU', ref2:'682', parentId:'7',              isActive:1 },
{ ...base,id:152, categoryType:2107, value:'SN', description:'Senegal',     ref1:'SEN', ref2:'686', parentId:'4',         isActive:1 },
{ ...base,id:153, categoryType:2107, value:'RS', description:'Serbia',      ref1:'SRB', ref2:'688', parentId:'2',            isActive:1 },
{ ...base,id:154, categoryType:2107, value:'SC', description:'Seychelles',  ref1:'SYC', ref2:'690', parentId:'4',         isActive:1 },
{ ...base,id:155, categoryType:2107, value:'SL', description:'Sierra Leone', ref1:'SLE', ref2:'694', parentId:'4',        isActive:1 },
{ ...base,id:156, categoryType:2107, value:'SG', description:'Singapore',   ref1:'SGP', ref2:'702', parentId:'12',         isActive:1 },
{ ...base,id:157, categoryType:2107, value:'SK', description:'Slovakia',    ref1:'SVK', ref2:'703', parentId:'10',             isActive:1 },
{ ...base,id:158, categoryType:2107, value:'SI', description:'Slovenia',    ref1:'SVN', ref2:'705', parentId:'2',            isActive:1 },
{ ...base,id:159, categoryType:2107, value:'SB', description:'Solomon Islands', ref1:'SLB', ref2:'090', parentId:'16',            isActive:1 },
{ ...base,id:160, categoryType:2107, value:'SO', description:'Somalia',     ref1:'SOM', ref2:'706', parentId:'4',         isActive:1 },
{ ...base,id:161, categoryType:2107, value:'ZA', description:'South Africa', ref1:'ZAF', ref2:'710', parentId:'4',        isActive:1 },
{ ...base,id:162, categoryType:2107, value:'SS', description:'South Sudan', ref1:'SSD', ref2:'728', parentId:'4',         isActive:1 },
{ ...base,id:163, categoryType:2107, value:'ES', description:'Spain',       ref1:'ESP', ref2:'724', parentId:'2',            isActive:1 },
{ ...base,id:164, categoryType:2107, value:'LK', description:'Sri Lanka',   ref1:'LKA', ref2:'144', parentId:'1',              isActive:1 },
{ ...base,id:165, categoryType:2107, value:'SD', description:'Sudan',       ref1:'SDN', ref2:'729', parentId:'3',            isActive:1 },
{ ...base,id:166, categoryType:2107, value:'SR', description:'Suriname',    ref1:'SUR', ref2:'740', parentId:'6',              isActive:1 },
{ ...base,id:167, categoryType:2107, value:'SE', description:'Sweden',      ref1:'SWE', ref2:'752', parentId:'15',            isActive:1 },
{ ...base,id:168, categoryType:2107, value:'CH', description:'Switzerland', ref1:'CHE', ref2:'756', parentId:'9',             isActive:1 },
{ ...base,id:169, categoryType:2107, value:'SY', description:'Syrian Arab Republic', ref1:'SYR', ref2:'760', parentId:'7',    isActive:1 },
{ ...base,id:170, categoryType:2107, value:'TJ', description:'Tajikistan',  ref1:'TJK', ref2:'762', parentId:'17',               isActive:1 },
{ ...base,id:171, categoryType:2107, value:'TZ', description:'Tanzania, United Republic of', ref1:'TZA', ref2:'834', parentId:'4', isActive:1 },
{ ...base,id:172, categoryType:2107, value:'TH', description:'Thailand',    ref1:'THA', ref2:'764', parentId:'12',         isActive:1 },
{ ...base,id:173, categoryType:2107, value:'TL', description:'Timor-Leste', ref1:'TLS', ref2:'626', parentId:'12',         isActive:1 },
{ ...base,id:174, categoryType:2107, value:'TG', description:'Togo',        ref1:'TGO', ref2:'768', parentId:'4',         isActive:1 },
{ ...base,id:175, categoryType:2107, value:'TO', description:'Tonga',       ref1:'TON', ref2:'776', parentId:'19',                  isActive:1 },
{ ...base,id:176, categoryType:2107, value:'TT', description:'Trinidad and Tobago', ref1:'TTO', ref2:'780', parentId:'5',        isActive:1 },
{ ...base,id:177, categoryType:2107, value:'TN', description:'Tunisia',     ref1:'TUN', ref2:'788', parentId:'3',            isActive:1 },
{ ...base,id:178, categoryType:2107, value:'TR', description:'Türkiye',     ref1:'TUR', ref2:'792', parentId:'7',               isActive:1 },
{ ...base,id:179, categoryType:2107, value:'TM', description:'Turkmenistan',ref1:'TKM', ref2:'795', parentId:'17',               isActive:1 },
{ ...base,id:180, categoryType:2107, value:'TV', description:'Tuvalu',      ref1:'TUV', ref2:'798', parentId:'19',                  isActive:1 },
{ ...base,id:181, categoryType:2107, value:'UG', description:'Uganda',      ref1:'UGA', ref2:'800', parentId:'4',         isActive:1 },
{ ...base,id:182, categoryType:2107, value:'UA', description:'Ukraine',     ref1:'UKR', ref2:'804', parentId:'10',             isActive:1 },
{ ...base,id:183, categoryType:2107, value:'AE', description:'United Arab Emirates', ref1:'ARE', ref2:'784', parentId:'7',    isActive:1 },
{ ...base,id:184, categoryType:2107, value:'GB', description:'United Kingdom of Great Britain and Northern Ireland', ref1:'GBR', ref2:'826', parentId:'15', isActive:1 },
{ ...base,id:185, categoryType:2107, value:'US', description:'United States of America', ref1:'USA', ref2:'840', parentId:'13', isActive:1 },
{ ...base,id:186, categoryType:2107, value:'UY', description:'Uruguay',     ref1:'URY', ref2:'858', parentId:'6',              isActive:1 },
{ ...base,id:187, categoryType:2107, value:'UZ', description:'Uzbekistan',  ref1:'UZB', ref2:'860', parentId:'17',               isActive:1 },
{ ...base,id:188, categoryType:2107, value:'VU', description:'Vanuatu',     ref1:'VUT', ref2:'548', parentId:'16',                  isActive:1 },
{ ...base,id:189, categoryType:2107, value:'VE', description:'Venezuela, Bolivarian Republic of', ref1:'VEN', ref2:'862', parentId:'6', isActive:1 },
{ ...base,id:190, categoryType:2107, value:'VN', description:'Viet Nam',    ref1:'VNM', ref2:'704', parentId:'12',         isActive:1 },
{ ...base,id:191, categoryType:2107, value:'YE', description:'Yemen',       ref1:'YEM', ref2:'887', parentId:'7',               isActive:1 },
{ ...base,id:192, categoryType:2107, value:'ZM', description:'Zambia',      ref1:'ZMB', ref2:'894', parentId:'4',         isActive:1 },
{ ...base,id:193, categoryType:2107, value:'ZW', description:'Zimbabwe',    ref1:'ZWE', ref2:'716', parentId:'4',         isActive:1 },
{ ...base,id:194, categoryType:2107, value:'VA', description:'Holy See',    ref1:'VAT', ref2:'336', parentId:'2',            isActive:1 },
{ ...base,id:195, categoryType:2107, value:'PS', description:'Palestine, State of', ref1:'PSE', ref2:'275', parentId:'7',      isActive:1 },



  ]);

};
exports.down = function(knex) {
      return knex('ref_category')
        .whereIn('categoryType', [2107])
        .del();
};