// Rename "Permission Groups" → "Roles" in the menu and remove the old
// "Roles" menu row.  This follows the ref_roles collapse migration
// (20270721000001_collapse_roles_into_permission_groups.js).
//
// - sec_menu id 351 ("Permission Groups") → displayName "Roles"
// - sec_menu id 352 ("Roles") → isActive = false
// - sec_userMenu grants for id 352 are removed everywhere.
// - sec_userMenu grants for id 351 are kept as-is (it's the same screen).
//
// Idempotent — safe to re-run.

exports.up = async function (knex) {
  const now = new Date();

  // 1. Rename "Permission Groups" → "Roles" (id 351) for every tenant
  await knex('sec_menu')
    .where({ id: 351 })
    .update({ displayName: 'Roles', updatedAt: now });

  // 2. Hide the old "Roles" item (id 352) for every tenant
  await knex('sec_menu')
    .where({ id: 352 })
    .update({ isActive: false, updatedAt: now });

  // 3. Remove all sec_userMenu grants for id 352
  await knex('sec_userMenu').where({ id: 352 }).del();
};

exports.down = async function (knex) {
  const now = new Date();

  // 1. Restore original name "Permission Groups" on id 351
  await knex('sec_menu')
    .where({ id: 351 })
    .update({ displayName: 'Permission Groups', updatedAt: now });

  // 2. Reactivate the old "Roles" item (id 352)
  await knex('sec_menu')
    .where({ id: 352 })
    .update({ isActive: true, updatedAt: now });

  // Note: down() does not restore sec_userMenu grants for id 352.
  // Those are regenerated by re-running the seed migration
  // 20270706000001_reorganize_main_menu.js.
};
