const ICONS = [
  'bi bi-grid-1x2', 'bi bi-speedometer2', 'bi bi-bar-chart', 'bi bi-graph-up', 'bi bi-table',
  'bi bi-journal-text', 'bi bi-journal-plus', 'bi bi-list-columns', 'bi bi-diagram-3',
  'bi bi-building', 'bi bi-people', 'bi bi-person', 'bi bi-shield-lock', 'bi bi-key',
  'bi bi-gear', 'bi bi-sliders', 'bi bi-tools', 'bi bi-wrench',
  'bi bi-cash-stack', 'bi bi-cash', 'bi bi-currency-exchange', 'bi bi-calculator',
  'bi bi-file-earmark-text', 'bi bi-file-earmark-plus', 'bi bi-files',
  'bi bi-inbox', 'bi bi-send', 'bi bi-envelope', 'bi bi-chat-dots',
  'bi bi-cart', 'bi bi-truck', 'bi bi-box-seam', 'bi bi-shop',
  'bi bi-printer', 'bi bi-download', 'bi bi-upload', 'bi bi-cloud-arrow-up',
  'bi bi-bookmarks', 'bi bi-bookmark-star', 'bi bi-star', 'bi bi-heart',
  'bi bi-calendar3', 'bi bi-clock', 'bi bi-alarm',
  'bi bi-pie-chart', 'bi bi-bar-chart-steps', 'bi bi-graph-up-arrow',
  'bi bi-layout-split', 'bi bi-layout-text-window', 'bi bi-window',
  'bi bi-clipboard-check', 'bi bi-clipboard-data', 'bi bi-card-checklist',
  'bi bi-bell', 'bi bi-flag', 'bi bi-tag', 'bi bi-tags',
  'bi bi-search', 'bi bi-funnel', 'bi bi-filter',
  'bi bi-plus-circle', 'bi bi-dash-circle', 'bi bi-x-circle', 'bi bi-check-circle',
  'bi bi-question-circle', 'bi bi-info-circle', 'bi bi-exclamation-triangle',
  'bi bi-dot', 'bi bi-circle', 'bi bi-record-circle',
  // --- extended ---
  'bi bi-house', 'bi bi-house-door', 'bi bi-house-fill',
  'bi bi-archive', 'bi bi-archive-fill', 'bi bi-folder', 'bi bi-folder2-open',
  'bi bi-receipt', 'bi bi-receipt-cutoff',
  'bi bi-wallet2', 'bi bi-credit-card', 'bi bi-piggy-bank', 'bi bi-bank',
  'bi bi-graph-down', 'bi bi-graph-down-arrow', 'bi bi-bar-chart-fill',
  'bi bi-kanban', 'bi bi-columns-gap', 'bi bi-grid-3x2-gap',
  'bi bi-list-ul', 'bi bi-list-ol', 'bi bi-list-check', 'bi bi-list-task',
  'bi bi-menu-button', 'bi bi-menu-button-wide', 'bi bi-menu-app',
  'bi bi-pencil', 'bi bi-pencil-square', 'bi bi-pen', 'bi bi-eraser',
  'bi bi-trash', 'bi bi-trash3', 'bi bi-archive',
  'bi bi-eye', 'bi bi-eye-slash', 'bi bi-eye-fill',
  'bi bi-lock', 'bi bi-lock-fill', 'bi bi-unlock', 'bi bi-unlock-fill',
  'bi bi-shield-check', 'bi bi-shield-exclamation', 'bi bi-shield-fill',
  'bi bi-person-plus', 'bi bi-person-dash', 'bi bi-person-check',
  'bi bi-people-fill', 'bi bi-person-badge', 'bi bi-person-lines-fill',
  'bi bi-telephone', 'bi bi-telephone-fill', 'bi bi-phone', 'bi bi-phone-fill',
  'bi bi-geo-alt', 'bi bi-geo-alt-fill', 'bi bi-pin-map', 'bi bi-map',
  'bi bi-globe', 'bi bi-globe2',
  'bi bi-link', 'bi bi-link-45deg', 'bi bi-box-arrow-up-right',
  'bi bi-chat', 'bi bi-chat-left', 'bi bi-chat-left-text',
  'bi bi-megaphone', 'bi bi-megaphone-fill',
  'bi bi-book', 'bi bi-book-half', 'bi bi-journal', 'bi bi-journal-bookmark',
  'bi bi-newspaper', 'bi bi-layout-text-sidebar',
  'bi bi-file-earmark', 'bi bi-file-earmark-arrow-down', 'bi bi-file-earmark-arrow-up',
  'bi bi-file-earmark-check', 'bi bi-file-earmark-x', 'bi bi-file-earmark-medical',
  'bi bi-box', 'bi bi-boxes', 'bi bi-package',
  'bi bi-database', 'bi bi-database-fill', 'bi bi-server',
  'bi bi-hdd', 'bi bi-hdd-stack', 'bi bi-hard-drive',
  'bi bi-laptop', 'bi bi-display', 'bi bi-display-fill', 'bi bi-phone-flip',
  'bi bi-camera', 'bi bi-camera-fill', 'bi bi-image', 'bi bi-images',
  'bi bi-lightbulb', 'bi bi-lightbulb-fill', 'bi bi-lightning', 'bi bi-lightning-fill',
  'bi bi-award', 'bi bi-trophy', 'bi bi-gem',
  'bi bi-magic', 'bi bi-stars', 'bi bi-palette',
  'bi bi-arrow-left-right', 'bi bi-arrow-down-up', 'bi bi-shuffle',
  'bi bi-arrow-repeat', 'bi bi-arrow-return-left', 'bi bi-arrow-return-right',
  'bi bi-sort-down', 'bi bi-sort-up', 'bi bi-sort-alpha-down', 'bi bi-sort-alpha-up',
  'bi bi-chevron-bar-expand', 'bi bi-chevron-bar-contract',
  'bi bi-fullscreen', 'bi bi-fullscreen-exit',
  'bi bi-zoom-in', 'bi bi-zoom-out',
  'bi bi-power', 'bi bi-toggle-on', 'bi bi-toggle-off',
  'bi bi-sun', 'bi bi-moon', 'bi bi-moon-stars',
  'bi bi-cloud', 'bi bi-cloud-fill', 'bi bi-cloud-download', 'bi bi-cloud-upload',
  'bi bi-wifi', 'bi bi-wifi-off', 'bi bi-signal',
  'bi bi-bluetooth', 'bi bi-battery-charging', 'bi bi-battery-full',
  'bi bi-cpu', 'bi bi-motherboard', 'bi bi-memory',
  'bi bi-inboxes', 'bi bi-inboxes-fill',
  'bi bi-currency-dollar', 'bi bi-currency-euro', 'bi bi-currency-pound',
  'bi bi-currency-rupee', 'bi bi-currency-yen', 'bi bi-currency-bitcoin',
  'bi bi-hourglass', 'bi bi-hourglass-split', 'bi bi-hourglass-bottom',
  'bi bi-ticket', 'bi bi-ticket-perforated', 'bi bi-ticket-detailed',
  'bi bi-cart-plus', 'bi bi-cart-dash', 'bi bi-cart-x',
  'bi bi-basket', 'bi bi-basket2', 'bi bi-basket3',
  'bi bi-keyboard', 'bi bi-mouse', 'bi bi-headphones',
  'bi bi-stickies', 'bi bi-stickies-fill', 'bi bi-sticky', 'bi bi-sticky-fill',
  'bi bi-envelope-open', 'bi bi-envelope-paper', 'bi bi-envelope-check',
  'bi bi-envelope-exclamation', 'bi bi-envelope-x', 'bi bi-envelope-plus',
  'bi bi-chat-square', 'bi bi-chat-square-text', 'bi bi-chat-square-dots',
  'bi bi-patch-check', 'bi bi-patch-exclamation', 'bi bi-patch-question', 'bi bi-patch-minus',
  'bi bi-briefcase', 'bi bi-briefcase-fill', 'bi bi-backpack', 'bi bi-backpack2',
  'bi bi-toggle2-on', 'bi bi-toggle2-off',
  'bi bi-list-stars', 'bi bi-clipboard-plus', 'bi bi-clipboard-minus',
  'bi bi-diagram-2', 'bi bi-diagram-2-fill', 'bi bi-diagram-3-fill',
  'bi bi-dice-1', 'bi bi-dice-2', 'bi bi-dice-3', 'bi bi-dice-4', 'bi bi-dice-5', 'bi bi-dice-6',
  'bi bi-puzzle', 'bi bi-puzzle-fill',
  'bi bi-toggles', 'bi bi-toggles2',
  'bi bi-mic', 'bi bi-mic-fill', 'bi bi-mic-mute', 'bi bi-mic-mute-fill',
  'bi bi-camera-video', 'bi bi-camera-video-fill', 'bi bi-camera-video-off', 'bi bi-camera-video-off-fill',
];

export default ICONS;
