import * as Yup from "yup";

export const getFieldsQualifications = (uiDataFiltered) => ({
  headingEducation: {
    name: "headingEducation",
    type: "heading",
    label: "Education Qualifications",
    className: "col-12",
  },
  skillsQualifications: {
    name: "skillsQualifications",
    type: "textarea",
    placeholder: "Skills & Qualifications",
    initialValue: "",
    label: "Skills & Qualifications",
    className: "col-12",
  },

  headingMemberships: {
    name: "headingMemberships",
    type: "heading",
    label: "Memberships & Licenses",
    className: "col-12",
  },
  professionalMemberships: {
    name: "professionalMemberships",
    type: "textarea",
    placeholder: "Professional Memberships",
    initialValue: "",
    label: "Professional Memberships",
    className: "col-12",
  },

  headingSkills: {
    name: "headingSkills",
    type: "heading",
    label: "Skills",
    className: "col-12",
  },
  technicalSoftSkills: {
    name: "technicalSoftSkills",
    type: "textarea",
    placeholder: "Technical & Soft Skills",
    initialValue: "",
    label: "Technical & Soft Skills",
    className: "col-12",
  },
});

export const getFieldsFinancial = (uiDataFiltered) => ({
  headingPayroll: {
    name: "headingPayroll",
    type: "heading",
    label: "Payroll Information",
    className: "col-12",
  },
  payrollGroup: {
    name: "payrollGroup",
    type: "select",
    placeholder: "Payroll Group",
    dataBinding: {
      data: uiDataFiltered.PayrollGroup,
      keyField: "id",
      valueField: "value",
    },
    label: "Payroll Group",
    className: "col-md-4 col-12",
  },
  paymentMethod: {
    name: "paymentMethod",
    type: "select",
    placeholder: "Payment Method",
    dataBinding: {
      data: uiDataFiltered.PaymentMethod,
      keyField: "id",
      valueField: "value",
    },
    label: "Payment Method",
    className: "col-md-4 col-12",
  },
  joinDate: {
    name: "joinDate",
    type: "date",
    placeholder: "Date Joined",
    initialValue: "",
    label: "Date Joined",
    className: "col-md-4 col-12",
  },
  confirmationDate: {
    name: "confirmationDate",
    type: "date",
    placeholder: "Date of Confirmation",
    initialValue: "",
    label: "Date of Confirmation",
    className: "col-md-4 col-12",
  },
  retirementDate: {
    name: "retirementDate",
    type: "date",
    placeholder: "Date of Retirement",
    initialValue: "",
    label: "Date of Retirement",
    className: "col-md-4 col-12",
  },
  lastWorkingDate: {
    name: "lastWorkingDate",
    type: "date",
    placeholder: "Last Working Date",
    initialValue: "",
    label: "Last Working Date",
    className: "col-md-4 col-12",
  },

  headingStatutory: {
    name: "headingStatutory",
    type: "heading",
    label: "Statutory Processing",
    className: "col-12",
  },
  timeAttendance: {
    name: "timeAttendance",
    type: "checkbox",
    placeholder: "Time Attendance",
    initialValue: true,
    label: "Time Attendance",
    className: "col-md-3 col-6",
  },
  payrollProcess: {
    name: "payrollProcess",
    type: "checkbox",
    placeholder: "Payroll Process",
    initialValue: true,
    label: "Payroll Process",
    className: "col-md-3 col-6",
  },
  payslipPrint: {
    name: "payslipPrint",
    type: "checkbox",
    placeholder: "Payslip Print",
    initialValue: true,
    label: "Payslip Print",
    className: "col-md-3 col-6",
  },
  epfEtfProcess: {
    name: "epfEtfProcess",
    type: "checkbox",
    placeholder: "EPF/ETF Process",
    initialValue: true,
    label: "EPF/ETF Process",
    className: "col-md-3 col-6",
  },

  headingBanking: {
    name: "headingBanking",
    type: "heading",
    label: "Banking Details",
    className: "col-12",
  },
  bank: {
    name: "bank",
    type: "select",
    placeholder: "Bank",
    initialValue: "",
    dataBinding: {
      data: uiDataFiltered.Bank,
      keyField: "id",
      valueField: "value",
    },
    label: "Bank",
    className: "col-md-4 col-12",
  },
  branch: {
    name: "branch",
    type: "select",
    placeholder: "Branch",
    initialValue: "",
    dataBinding: {
      data: uiDataFiltered.BankBranch,
      keyField: "id",
      valueField: "value",
    },
    label: "Branch",
    className: "col-md-4 col-12",
  },
  accountNo: {
    name: "accountNo",
    type: "text",
    placeholder: "Account No.",
    initialValue: "",
    label: "Account No.",
    className: "col-md-4 col-12",
  },
  accountName: {
    name: "accountName",
    type: "text",
    placeholder: "Account Name",
    initialValue: "",
    label: "Account Name",
    className: "col-md-4 col-12",
  },
});

export const getFieldsDocumentation = (uiDataFiltered) => ({
  /* OFFICIAL TAB */
  headingClassification: {
    name: "headingClassification",
    type: "heading",
    label: "Classification",
    className: "col-12",
  },
  division: {
    name: "division",
    type: "select",
    placeholder: "Division",
    dataBinding: {
      data: uiDataFiltered.Division,
      keyField: "id",
      valueField: "value",
    },
    label: "Division",
    className: "col-md-4 col-12",
  },
  department: {
    name: "department",
    type: "select",
    placeholder: "Department",
    dataBinding: {
      data: uiDataFiltered.Department,
      keyField: "id",
      valueField: "value",
    },
    label: "Department",
    className: "col-md-4 col-12",
  },
  section: {
    name: "section",
    type: "select",
    placeholder: "Section",
    dataBinding: {
      data: uiDataFiltered.Section,
      keyField: "id",
      valueField: "value",
    },
    label: "Section",
    className: "col-md-4 col-12",
  },
  subSection: {
    name: "subSection",
    type: "select",
    placeholder: "Sub Section",
    dataBinding: {
      data: uiDataFiltered.SubSection,
      keyField: "id",
      valueField: "value",
    },
    label: "Sub Section",
    className: "col-md-4 col-12",
  },

  headingOrgStructure: {
    name: "headingOrgStructure",
    type: "heading",
    label: "Organizational Structure",
    className: "col-12",
  },
  designation: {
    name: "designation",
    type: "select",
    placeholder: "Designation",
    dataBinding: {
      data: uiDataFiltered.Designation,
      keyField: "id",
      valueField: "value",
    },
    label: "Designation",
    className: "col-md-4 col-12",
  },
  recruitmentType: {
    name: "recruitmentType",
    type: "select",
    placeholder: "Recruitment Type",
    dataBinding: {
      data: uiDataFiltered.RecruitmentType,
      keyField: "id",
      valueField: "value",
    },
    label: "Recruitment Type",
    className: "col-md-4 col-12",
  },
  employmentStatus: {
    name: "employmentStatus",
    type: "select",
    placeholder: "Employment Status",
    dataBinding: {
      data: uiDataFiltered.EmploymentStatus,
      keyField: "id",
      valueField: "value",
    },
    label: "Employment Status",
    className: "col-md-4 col-12",
  },

  headingReporting: {
    name: "headingReporting",
    type: "heading",
    label: "Reporting Lines",
    className: "col-12",
  },
  supervisor: {
    name: "supervisor",
    type: "text",
    placeholder: "Search Supervisor ID...",
    initialValue: "",
    label: "Direct Supervisor",
    className: "col-md-6 col-12",
  },
  manager: {
    name: "manager",
    type: "text",
    placeholder: "Search Manager ID...",
    initialValue: "",
    label: "Manager",
    className: "col-md-6 col-12",
  },
});

export const getFieldsMovement = (uiDataFiltered) => ({});

export const getFieldsPersonal = (uiDataFiltered) => ({
  /* PERSONAL TAB */
  headingIdentification: {
    name: "headingIdentification",
    type: "heading",
    label: "Identification",
    className: "col-12",
  },
  employeeNo: {
    name: "employeeNo",
    type: "text",
    placeholder: "Employee No.",
    initialValue: "",
    label: "Employee No.",
    className: "col-md-4 col-12",
  },
  epfNo: {
    name: "epfNo",
    type: "text",
    placeholder: "EPF No.",
    initialValue: "",
    label: "EPF No.",
    className: "col-md-4 col-12",
  },
  deviceEmpNo: {
    name: "deviceEmpNo",
    type: "text",
    placeholder: "Device EMP. No.",
    initialValue: "",
    label: "Device EMP. No.",
    className: "col-md-4 col-12",
  },
  nicNo: {
    name: "nicNo",
    type: "text",
    placeholder: "NIC No.",
    initialValue: "",
    label: "NIC No.",
    className: "col-md-4 col-12",
  },
  nicExpiryDate: {
    name: "nicExpiryDate",
    type: "date",
    placeholder: "NIC Expiry Date",
    initialValue: "",
    label: "NIC Expiry Date",
    className: "col-md-4 col-12",
  },
  br1: {
    type: "br",
  },
  passportNo: {
    name: "passportNo",
    type: "text",
    placeholder: "Passport No.",
    initialValue: "",
    label: "Passport No.",
    className: "col-md-4 col-12",
  },
  passportExpiry: {
    name: "passportExpiry",
    type: "date",
    placeholder: "Passport Expiry",
    initialValue: "",
    label: "Passport Expiry",
    className: "col-md-4 col-12",
  },
  br2: {
    type: "br",
  },
  drivingLicNo: {
    name: "drivingLicNo",
    type: "text",
    placeholder: "Driving Lic. No.",
    initialValue: "",
    label: "Driving Lic. No.",
    className: "col-md-4 col-12",
  },
  licenseExpiry: {
    name: "licenseExpiry",
    type: "date",
    placeholder: "License Expiry",
    initialValue: "",
    label: "License Expiry",
    className: "col-md-4 col-12",
  },
  br3: {
    type: "br",
  },
  visaNo: {
    name: "visaNo",
    type: "text",
    placeholder: "Visa No.",
    initialValue: "",
    label: "Visa No.",
    className: "col-md-4 col-12",
  },
  visaExpiry: {
    name: "visaExpiry",
    type: "date",
    placeholder: "Visa Expiry",
    initialValue: "",
    label: "Visa Expiry",
    className: "col-md-4 col-12",
  },
  br4: {
    type: "br",
  },
  status: {
    name: "status",
    type: "select",
    placeholder: "Status",
    initialValue: "",
    label: "Status",
    dataBinding: {
      data: uiDataFiltered.Status,
      keyField: "id",
      valueField: "value",
    },
    className: "col-md-4 col-12",
    validation: Yup.number().required("Status is required"),
  },
  br5: {
    type: "br",
  },
  headingNameProfile: {
    name: "headingNameProfile",
    type: "heading",
    label: "Name & Profile",
    className: "col-12",
  },
  title: {
    name: "title",
    type: "select",
    placeholder: "Title",
    initialValue: "Mr.",
    dataBinding: {
      data: uiDataFiltered.Title,
      keyField: "id",
      valueField: "value",
    },
    label: "Title",
    className: "col-md-4 col-12",
  },
  firstName: {
    name: "firstName",
    type: "text",
    placeholder: "First Name",
    initialValue: "",
    label: "First Name",
    className: "col-md-4 col-12",
  },
  middleName: {
    name: "middleName",
    type: "text",
    placeholder: "Middle Name",
    initialValue: "",
    label: "Middle Name",
    className: "col-md-4 col-12",
  },
  lastName: {
    name: "lastName",
    type: "text",
    placeholder: "Last Name",
    initialValue: "",
    label: "Last Name",
    className: "col-md-4 col-12",
  },
  initials: {
    name: "initials",
    type: "text",
    placeholder: "Initials",
    initialValue: "",
    label: "Initials",
    className: "col-md-4 col-12",
  },
  fullName: {
    name: "fullName",
    type: "text",
    placeholder: "Full Name",
    initialValue: "",
    label: "Full Name",
    className: "col-md-8 col-12", // Span 2
  },
  preferredName: {
    name: "preferredName",
    type: "text",
    placeholder: "Preferred Name",
    initialValue: "",
    label: "Preferred Name",
    className: "col-md-4 col-12",
  },

  headingDemographics: {
    name: "headingDemographics",
    type: "heading",
    label: "Demographics",
    className: "col-12",
  },
  dob: {
    name: "dob",
    type: "date",
    placeholder: "Date of Birth",
    initialValue: "",
    label: "Date of Birth",
    className: "col-md-4 col-12",
  },
  gender: {
    name: "gender",
    type: "select",
    placeholder: "Gender",
    // initialValue: 'Male',
    dataBinding: {
      data: uiDataFiltered.Gender,
      keyField: "id",
      valueField: "value",
    },
    label: "Gender",
    className: "col-md-4 col-12",
  },
  maritalStatus: {
    name: "maritalStatus",
    type: "select",
    placeholder: "Marital Status",
    // initialValue: 'Single',
    dataBinding: {
      data: uiDataFiltered.MaritalStatus,
      keyField: "id",
      valueField: "value",
    },
    label: "Marital Status",
    className: "col-md-4 col-12",
  },
  nationality: {
    name: "nationality",
    type: "select",
    placeholder: "Nationality",
    //  initialValue: 'Sri Lankan',
    dataBinding: {
      data: uiDataFiltered.Nationality,
      keyField: "id",
      valueField: "value",
    },
    label: "Nationality",
    className: "col-md-4 col-12",
  },
  religion: {
    name: "religion",
    type: "select",
    placeholder: "Religion",
    dataBinding: {
      data: uiDataFiltered.Religion,
      keyField: "id",
      valueField: "value",
    },
    label: "Religion",
    className: "col-md-4 col-12",
  },
  bloodGroup: {
    name: "bloodGroup",
    type: "select",
    placeholder: "Blood Group",
    dataBinding: {
      data: uiDataFiltered.BloodGroup,
      keyField: "id",
      valueField: "value",
    },
    label: "Blood Group",
    className: "col-md-4 col-12",
  },

  headingFamily: {
    name: "headingFamily",
    type: "heading",
    label: "Family Information",
    className: "col-12",
  },
  spouseName: {
    name: "spouseName",
    type: "text",
    placeholder: "Spouse Name",
    initialValue: "",
    label: "Spouse Name",
    className: "col-md-4 col-12",
  },
  spouseContact: {
    name: "spouseContact",
    type: "tel",
    placeholder: "Spouse Contact",
    initialValue: "",
    label: "Spouse Contact",
    className: "col-md-4 col-12",
  },

  headingAddress: {
    name: "headingAddress",
    type: "heading",
    label: "Permanent Address",
    className: "col-12",
  },
  addressLine1: {
    name: "addressLine1",
    type: "text",
    placeholder: "Address Line 1",
    initialValue: "",
    label: "Address Line 1",
    className: "col-md-8 col-12", // Span 2
  },
  addressLine2: {
    name: "addressLine2",
    type: "text",
    placeholder: "Address Line 2",
    initialValue: "",
    label: "Address Line 2",
    className: "col-md-8 col-12", // Span 2
  },
  addressLine3: {
    name: "addressLine3",
    type: "text",
    placeholder: "Address Line 3",
    initialValue: "",
    label: "Address Line 3",
    className: "col-md-8 col-12", // Span 2
  },
  city: {
    name: "city",
    type: "select",
    placeholder: "City",
    dataBinding: {
      data: uiDataFiltered.City,
      keyField: "id",
      valueField: "value",
    },
    label: "City",
    className: "col-md-4 col-12",
  },
  district: {
    name: "district",
    type: "select",
    placeholder: "District",
    dataBinding: {
      data: uiDataFiltered.District,
      keyField: "id",
      valueField: "value",
    },
    label: "District",
    className: "col-md-4 col-12",
  },
  province: {
    name: "province",
    type: "select",
    placeholder: "Province",
    dataBinding: {
      data: uiDataFiltered.Province,
      keyField: "id",
      valueField: "value",
    },
    label: "Province",
    className: "col-md-4 col-12",
  },
  country: {
    name: "country",
    type: "select",
    placeholder: "Country",
    dataBinding: {
      data: uiDataFiltered.Country,
      keyField: "id",
      valueField: "value",
    },
    label: "Country",
    className: "col-md-4 col-12",
  },
  postalCode: {
    name: "postalCode",
    type: "text",
    placeholder: "Postal Code",
    initialValue: "",
    label: "Postal Code",
    className: "col-md-4 col-12",
  },

  headingContact: {
    name: "headingContact",
    type: "heading",
    label: "Contact Information",
    className: "col-12",
  },
  emailPersonal: {
    name: "emailPersonal",
    type: "email",
    placeholder: "Email (Personal)",
    initialValue: "",
    label: "Email (Personal)",
    className: "col-md-4 col-12",
  },
  emailOffice: {
    name: "emailOffice",
    type: "email",
    placeholder: "Email (Office)",
    initialValue: "",
    label: "Email (Office)",
    className: "col-md-4 col-12",
  },
  mobile1: {
    name: "mobile1",
    type: "tel",
    placeholder: "Mobile 1",
    initialValue: "",
    label: "Mobile 1",
    className: "col-md-4 col-12",
  },
  mobile2: {
    name: "mobile2",
    type: "tel",
    placeholder: "Mobile 2",
    initialValue: "",
    label: "Mobile 2",
    className: "col-md-4 col-12",
  },
  officeMobile: {
    name: "officeMobile",
    type: "tel",
    placeholder: "Office Mobile",
    initialValue: "",
    label: "Office Mobile",
    className: "col-md-4 col-12",
  },
  telephoneHome: {
    name: "telephoneHome",
    type: "tel",
    placeholder: "Telephone (Home)",
    initialValue: "",
    label: "Telephone (Home)",
    className: "col-md-4 col-12",
  },
  telephoneOffice: {
    name: "telephoneOffice",
    type: "tel",
    placeholder: "Telephone (Office)",
    initialValue: "",
    label: "Telephone (Office)",
    className: "col-md-4 col-12",
  },
  officeExt: {
    name: "officeExt",
    type: "text",
    placeholder: "Office Ext.",
    initialValue: "",
    label: "Office Ext.",
    className: "col-md-4 col-12",
  },

  headingEmergency: {
    name: "headingEmergency",
    type: "heading",
    label: "Emergency Contact",
    className: "col-12",
  },
  emergencyPerson1: {
    name: "emergencyPerson1",
    type: "text",
    placeholder: "Contact Person 1",
    initialValue: "",
    label: "Contact Person 1",
    className: "col-md-4 col-12",
  },
  emergencyContact1: {
    name: "emergencyContact1",
    type: "tel",
    placeholder: "Contact Number 1",
    initialValue: "",
    label: "Contact Number 1",
    className: "col-md-4 col-12",
  },
  emergencyPerson2: {
    name: "emergencyPerson2",
    type: "text",
    placeholder: "Contact Person 2",
    initialValue: "",
    label: "Contact Person 2",
    className: "col-md-4 col-12",
  },
  emergencyContact2: {
    name: "emergencyContact2",
    type: "tel",
    placeholder: "Contact Number 2",
    initialValue: "",
    label: "Contact Number 2",
    className: "col-md-4 col-12",
  },
});
