using DataTire;
using ZION.PCB.Search;
using Digiteq_Logic;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace ZION.PCB
{
    /// <summary>
    /// Interaction logic for UC_IncomeType.xaml
    /// </summary>
    public partial class UC_IncomeType : UserControl
    {
        #region Form Load
        public UC_IncomeType()
        {
            #region User Control Initialization
            InitializeComponent();
            SEACC_Form.enmFormName = FormName.PCB_IncomeType;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("IncomeTypeID");
            dgr_Main.dt.Columns.Add("IncomeTypeName");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, false, false, true);
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            //this.SEACC_Form.btn_Print.Click += btn_Print_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("Type ID", "IncomeTypeID", 90);
            dgr_Main.Add_DatagridColoumn("Type Name", "IncomeTypeName", 250);
            #endregion

            ClearFields();
            RefreshGrid();
        }
        #endregion

        #region Form Responsiveness
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 850)
                coloumnA.Width = new GridLength(210);
            else
                coloumnA.Width = new GridLength(670);
        }
        #endregion

        #region Action Buttons
        private void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
            RefreshGrid();
        }

        private void btn_Print_Click(object sender, RoutedEventArgs e)
        {
 

        }

        private void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    #region Update
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermission_ToSave(true))
                        {
                            tbl_pcbRefIncomeType oOldType = tbl_pcbRefIncomeType.Select(txtIncomeTypeID.Tag.ToString());
                            if (oOldType != null)
                            {
                                if (!oOldType.IsCanceled)
                                {
                                    tbl_pcbRefIncomeType oType = new tbl_pcbRefIncomeType(txtIncomeTypeID.Tag.ToString(), txtIncomeTypeName.Text, oOldType.IsCanceled, oOldType.CreateUser_ID, clsSecurity.UserIDLoged, oOldType.CanceldUser_ID, oOldType.DateCreate, clsSecurity.getServerDateTime(), oOldType.DateCanceled, oOldType.CreateUserTerminal_ID, clsSecurity.TerminalID, oOldType.CanceledUserTerminal_ID);
                                    oType.Update();
                                    SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                                }
                                else
                                    SEACCMessageBox.Show("Can not Update..", "This Expenditure is already cancelled", MessageBoxButton.OK);
                            }
                        }
                    }
                    #endregion

                    #region Insert
                    else
                    {
                        if (SEACC_Form.CheckPermission_ToSave(false))
                        {
                            if (SEACC_Form.isAutoGenaratedCode)
                                txtIncomeTypeID.Tag = SEACC_Form.getAutoGeneratedCode();

                            tbl_pcbRefIncomeType oNewType = new tbl_pcbRefIncomeType(txtIncomeTypeID.Tag.ToString(), txtIncomeTypeName.Text, false, clsSecurity.UserIDLoged, "default", "default", clsSecurity.getServerDateTime(), clsValidation.defaultDateTime, clsValidation.defaultDateTime, clsSecurity.TerminalID, "default", "default");
                            oNewType.Insert();
                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                        }
                    }
                    #endregion
                }
                catch (Exception ex)
                {
                    clsValidate.WriteErrorLog("", clsSecurity.getFormID(SEACC_Form.enmFormName), ex);
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        private void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    if (txtIncomeTypeID.Tag != null)
                    {
                        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);

                        if (bMessegeBoxResult)
                        {
                            tbl_pcbRefIncomeType Details = tbl_pcbRefIncomeType.Select(txtIncomeTypeID.Tag.ToString());
                            if (Details != null)
                            {
                                Details.IsCanceled = true;
                                Details.DateCanceled = clsSecurity.getServerDateTime();
                                Details.CanceldUser_ID = clsSecurity.UserIDLoged;
                                Details.CanceledUserTerminal_ID = clsSecurity.TerminalID;
                                Details.Update();

                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                                ClearFields();
                                RefreshGrid();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", clsSecurity.getFormID(SEACC_Form.enmFormName), ex);
                SEACCExeption.Show(ex);
            }
        }

        #endregion

        #region Check validity

        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                //if (CheckValidity_DuplicateFiled())
                //{
                //    if (ChekValidity_DuplicateNames())
                        bStatus = true;
                //}
            }
            return bStatus;
        }

        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtIncomeTypeName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                //if (SEACC_Form.isAutoGenaratedCode)
                //{
                //    txtDepartmentID.Tag = SEACC_Form.getAutoGeneratedCode();
                //    txtDepartmentID.Text = txtDepartmentID.Tag.ToString();
                //}

                //tbl_genDepartmentMaster oDept = tbl_genDepartmentMaster.Select(txtDepartmentID.Text);
                //if (oDept != null)
                //{
                //    bStatus = false;
                //    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                //}
            }
            return bStatus;
        }

        public bool ChekValidity_DuplicateNames()
        {
            bool bStatus = true;
            //foreach (tbl_genDepartmentMaster oDept in tbl_genDepartmentMaster.SelectAll().Where(p => p.DepartmentName == txtDeptName.Text && p.Department_ID != txtDepartmentID.Text))
            //{
            //    bStatus = false;
            //    SEACCMessageBox.Show(MessegeBoxType.FieldAlreadyExist);
            //    break;
            //}
            return bStatus;
        }

        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtIncomeTypeID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtIncomeTypeName, true, false, false);

            txtIncomeTypeID.Tag = null;

            txtIncomeTypeID.Text = "";
            txtIncomeTypeName.Text = "";

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtIncomeTypeID.setReadOnlyStatus(true);
                txtIncomeTypeID.Text = "<Auto Generate>";
            }
            else
                txtIncomeTypeID.setReadOnlyStatus(false);            

        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_pcbRefIncomeType detail in tbl_pcbRefIncomeType.SelectAll().Where(p => p.PcbIncomeType_ID != "default" && !p.IsCanceled))
                {
                    dgr_Main.dt.Rows.Add(detail.PcbIncomeType_ID, detail.PcbIncomeTypeName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", clsSecurity.getFormID(SEACC_Form.enmFormName), ex);
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region FillDetails
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_pcbRefIncomeType detail = tbl_pcbRefIncomeType.Select(sID);
                    if (detail != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtIncomeTypeID, false, false, false);

                        txtIncomeTypeID.Text = detail.PcbIncomeType_ID;
                        txtIncomeTypeID.Tag = detail.PcbIncomeType_ID;
                        txtIncomeTypeName.Text = detail.PcbIncomeTypeName;                        
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", clsSecurity.getFormID(SEACC_Form.enmFormName), ex);
                SEACCExeption.Show(ex);
            }
        }
        #endregion        

        #region Search Events
        private void txtIncomeTypeID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frm_search RowDataSearch = new frm_search(false);
            RowDataSearch.WindowStartupLocation = WindowStartupLocation.CenterScreen;
            List<string> lstResult = RowDataSearch.Show(Digiteq_Logic.Search.PCB_IncomeType);

            if (RowDataSearch.DialogResult == true)
                fillDetails(lstResult[0]);

        }
        #endregion

        #region Grid Events
        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", clsSecurity.getFormID(SEACC_Form.enmFormName), ex);
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        private void SEACC_Form_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.F5)
            {
                btn_New_Click(sender, e);
            }
        }
    }
}
