using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;

namespace Digiteq
{
    public partial class frm_toolRecordPurge : Form
    {
        
        //to manage update and insert
        static bool IsUpdate = false;

        //for security handle
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        public bool bHasChecked;
        public bool bHasApproved;
        DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        DateTime glbCheckedDate = clsSecurity.getServerDateTime();


        #region Form Load
        public frm_toolRecordPurge()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.PurgeTool);
            iFormID = clsSecurity.getFormID(FormName.PurgeTool);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frmItemMaster_Load(object sender, EventArgs e)
        {
            clsFormatter.setFormatForm(this, "Data Purge Tool", 1, iFormID);
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtPurgeID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {

                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 1)
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtPurgeID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordUpdateIsBlock), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtPurgeID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    if (txtPurgeID.TextLength > 0)
                                    {
                                        //Purge Header
                                        tbl_securityPurge detail = new tbl_securityPurge(txtPurgeID.Text.Trim(), dtpPurgeDate.Value, txtRemark.Text.Trim(), clsAutocode.GetProcessNoteID(ProcessNote.Invoice),
                                            clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, txtCheckedBy.Text.ToString(), txtApprovedBy.Text.ToString(), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                            clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                            glbCheckedDate, glbApprovedDate, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), bHasChecked, bHasApproved, false, false, false, false, false);
                                        detail.Insert();

                                        //Purge Detaile                                       
                                        foreach (DataGridViewRow row in dgvDetail.Rows)
                                        {
                                            try
                                            {
                                                string sCustomerID = clsValidate.ValidateGridValue(dgvDetail, "CustomerID", row.Index, "default");
                                                string sTransactionId = clsValidate.ValidateGridValue(dgvDetail, "TransactionID", row.Index, "default");
                                                int iProsesnoteId = Convert.ToInt16(clsValidate.ValidateGridTag(dgvDetail, "TransactionName", row.Index, int.Parse("0")));
                                                DateTime dtpTransactionDate = clsSecurity.getServerDateTime();
                                                try
                                                {
                                                    dtpTransactionDate = DateTime.Parse(clsValidate.ValidateGridValue(dgvDetail, "TransactionDate", row.Index, "1999-01-01"));
                                                }
                                                catch (Exception ) { }

                                                tbl_securityPurge_Detail oPurgeDetail = new tbl_securityPurge_Detail(detail.Purge_ID, sTransactionId, dtpTransactionDate, sCustomerID, iProsesnoteId, false);
                                                oPurgeDetail.Insert();
                                            }
                                            catch (Exception ex)
                                            {
                                                clsValidate.WriteErrorLog("", iFormID,ex);
                                                SEACCException.Show(ex);
                                            }
                                        }
                                    }
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Alert " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            tbl_securityPurge oldRecord = tbl_securityPurge.Select(txtPurgeID.Text.Trim());
                            if (oldRecord != null)
                                FillDetails(txtPurgeID.Text.Trim());
                        }
                    }
                }
            }
        }
        #endregion

        #region Btn Purge
        private void btn_PurgeApprove_Click(object sender, EventArgs e)
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                frmSetApproved login = new frmSetApproved();
                login.iFormID = iFormID;
                login.ShowDialog();
                if (frmSetApproved.bChecked)
                {
                    bHasApproved = true;
                    glbApprovedDate = clsSecurity.getServerDateTime();
                    dtpDateApprovedBy.Value = clsSecurity.getServerDateTime();
                    dtpTimeApprovedBy.Value = clsSecurity.getServerDateTime();
                    txtApprovedBy.Text = frmSetApproved.sApprovedUserName;
                    txtApprovedBy.Tag = frmSetApproved.sApprovedUserID;
                    clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, false);
                    clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, false);

                    //Before Delete documents Call below method
                    //clsHelpMethods.RemoveSattlements

                    foreach (tbl_genCustomerMaster oCustomerMaster in tbl_genCustomerMaster.SelectAll().Where(p=> p.Customer_ID != "default")) 
                    {
                        decimal dTotalDues_Old = clsHelpMethods_Local.GetCustomerTotalDues_All(oCustomerMaster.Customer_ID);
                        foreach (tbl_securityPurge_Detail oPurgeDetail in tbl_securityPurge_Detail.SelectAllByCustomer_ID(oCustomerMaster.Customer_ID).Where(p=> p.Transaction_ID != "default" && p.Purge_ID == txtPurgeID.Text.Trim()))
                        {
                            #region Cheque
                            if (oPurgeDetail.ProcessNote_ID == clsAutocode.GetProcessNoteID(ProcessNote.Cheque))
                            {
                                if (DeleteCheque(oPurgeDetail.Transaction_ID))
                                {
                                    oPurgeDetail.IsPurgeEnd = true;
                                    oPurgeDetail.Update();
                                }
                            }
                            #endregion

                            #region Recipt
                            else if (oPurgeDetail.ProcessNote_ID == clsAutocode.GetProcessNoteID(ProcessNote.Receipt))
                            {
                                //Remove all cheque from this receipt
                                foreach (tbl_bpsChequeRegister oCheque in tbl_bpsChequeRegister.SelectAllByReceipt_ID(oPurgeDetail.Transaction_ID).Where(p => p.ChequeRegister_ID != "default"))
                                    DeleteCheque(oCheque.ChequeRegister_ID);

                                clsHelpMethods_Local.RemoveSattlementsFrom_ReceiptID_OnlyCash(oPurgeDetail.Transaction_ID);
                                foreach (tbl_bpsReceipt_Invoice Detail in tbl_bpsReceipt_Invoice.SelectAllByReceipt_ID(oPurgeDetail.Transaction_ID))
                                {
                                    if (Detail != null)
                                        Detail.Delete();
                                }
                                tbl_bpsReceipt orecipt = tbl_bpsReceipt.Select(oPurgeDetail.Transaction_ID);
                                if (orecipt != null)
                                    orecipt.Delete();

                                oPurgeDetail.IsPurgeEnd = true;
                                oPurgeDetail.Update();
                            }
                            #endregion

                            #region CreditNote
                            else if (oPurgeDetail.ProcessNote_ID == clsAutocode.GetProcessNoteID(ProcessNote.CreditNote))
                            {
                           //     clsHelpMethods_Local.RemoveSattlementsFrom_CreditNoteID(oPurgeDetail.Transaction_ID);
                                foreach (tbl_bpsCreditNote_Detail Detail in tbl_bpsCreditNote_Detail.SelectAllByCreditNote_ID(oPurgeDetail.Transaction_ID).Where(p => p.CreditNote_ID != "default"))
                                {
                                    if (Detail != null)
                                        Detail.Delete();
                                }
                                tbl_bpsCreditNote ocr = tbl_bpsCreditNote.Select(oPurgeDetail.Transaction_ID);
                                if (ocr != null)
                                    ocr.Delete();

                                oPurgeDetail.IsPurgeEnd = true;
                                oPurgeDetail.Update();
                            }
                            #endregion
                        }

                        #region Invoice
                        foreach (tbl_securityPurge_Detail oPurgeDetail in tbl_securityPurge_Detail.SelectAllByCustomer_ID(oCustomerMaster.Customer_ID).Where(p => p.ProcessNote_ID == clsAutocode.GetProcessNoteID(ProcessNote.Invoice) && p.Transaction_ID != "default" && p.Purge_ID == txtPurgeID.Text.Trim()))
                        {
                            clsHelpMethods_Local.RemoveSattlementsFrom_InvoiceID(oPurgeDetail.Transaction_ID);
                            List<string> sDOID = new List<string>();
                            if (oPurgeDetail != null)
                            {
                                foreach (tbl_bpsReceipt_Invoice oInv in tbl_bpsReceipt_Invoice.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                {
                                    if (oInv != null)
                                        oInv.Delete();
                                }
                                //foreach (tbl_sasInvoice_Detail_FIFO oInv in tbl_sasInvoice_Detail_FIFO.SelectAll().Where(p => p.Invoice_ID == oPurgeDetail.Transaction_ID))
                                //{
                                //    if (oInv != null)
                                //        oInv.Delete();
                                //}
                                foreach (tbl_sasInvoice_Detail Detail in tbl_sasInvoice_Detail.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                {
                                    if (Detail != null)
                                    {
                                        sDOID.Add(Detail.DeliveryOrder_ID);
                                        Detail.Delete();
                                    }
                                }
                                foreach (tbl_audTransactioin_Invoice Detail in tbl_audTransactioin_Invoice.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                {
                                    if (Detail != null)
                                    {                                        
                                        Detail.Delete();
                                    }
                                }
                                foreach (tbl_bpsDebitNote Detail in tbl_bpsDebitNote.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                {
                                    if (Detail != null)
                                    {
                                        foreach (tbl_bpsDebitNote_Detail oInv in tbl_bpsDebitNote_Detail.SelectAllByDebitNote_ID(Detail.DebitNote_ID))
                                        {
                                            if (oInv != null)
                                                oInv.Delete();
                                        }
                                        Detail.Delete();
                                    }
                                }
                                foreach (tbl_sasSalesReturnedNote oSRN in tbl_sasSalesReturnedNote.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID).Where(p => p.SalesReturnedNote_ID != "default"))
                                {
                                    foreach (tbl_sasSalesReturnedNote_Detail oSRNDetail in tbl_sasSalesReturnedNote_Detail.SelectAllBySalesReturnedNote_ID(oSRN.SalesReturnedNote_ID))
                                        oSRNDetail.Delete();
                                    oSRN.Delete();
                                }  
                                foreach (tbl_bpsCreditNote Detail in tbl_bpsCreditNote.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                {
                                 //   clsHelpMethods_Local.RemoveSattlementsFrom_CreditNoteID(Detail.CreditNote_ID);
                                    foreach (tbl_bpsCreditNote_Detail CrDetail in tbl_bpsCreditNote_Detail.SelectAllByCreditNote_ID(Detail.CreditNote_ID).Where(p => p.CreditNote_ID != "default"))
                                    {
                                        if (CrDetail != null)
                                            CrDetail.Delete();
                                    }                                   

                                    tbl_bpsCreditNote ocr = tbl_bpsCreditNote.Select(Detail.CreditNote_ID);
                                    if (ocr != null)
                                        ocr.Delete();
                                }
                                foreach (tbl_bpsReceipt Detail in tbl_bpsReceipt.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID).Where(p => p.Receipt_ID != "default"))
                                {
                                    foreach (tbl_bpsChequeRegister oCheque in tbl_bpsChequeRegister.SelectAllByReceipt_ID(Detail.Receipt_ID).Where(p => p.ChequeRegister_ID != "default"))
                                        DeleteCheque(oCheque.ChequeRegister_ID);

                                    clsHelpMethods_Local.RemoveSattlementsFrom_ReceiptID_OnlyCash(Detail.Receipt_ID);
                                    foreach (tbl_bpsReceipt_Invoice oReceiptInvoice in tbl_bpsReceipt_Invoice.SelectAllByReceipt_ID(Detail.Receipt_ID))
                                    {
                                        if (oReceiptInvoice != null)
                                            oReceiptInvoice.Delete();
                                    }
                                    tbl_bpsReceipt orecipt = tbl_bpsReceipt.Select(Detail.Receipt_ID);
                                    if (orecipt != null)
                                        orecipt.Delete();

                                    oPurgeDetail.IsPurgeEnd = true;
                                    oPurgeDetail.Update();
                                }

                                //Sales Returned
                                foreach (tbl_sasSalesReturnedNote oSRN in tbl_sasSalesReturnedNote.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID).Where(p => p.SalesReturnedNote_ID != "default"))
                                {
                                    foreach (tbl_sasSalesReturnedNote_Detail oSRNDetail in tbl_sasSalesReturnedNote_Detail.SelectAllBySalesReturnedNote_ID(oSRN.SalesReturnedNote_ID))
                                        oSRNDetail.Delete();
                                    oSRN.Delete();
                                }   
                                ////Pls Check IT
                                //foreach (tbl_bpsReceipt oRcp in tbl_bpsReceipt.SelectAllByInvoice_ID(oPurgeDetail.Transaction_ID))
                                //{
                                //    if (oRcp != null)
                                //    {
                                //        oRcp.Receipt_ID = "default";
                                //        oRcp.Update();
                                //    }
                                //}
                                    

                                tbl_sasInvoice oinvoice = tbl_sasInvoice.Select(oPurgeDetail.Transaction_ID);
                                if (oinvoice != null)
                                    oinvoice.Delete();                                

                                oPurgeDetail.IsPurgeEnd = true;
                                oPurgeDetail.Update();

                                //Delivery Delivery Orders
                                foreach (string sDeliveryOrderID in sDOID)
                                {
                                    if (sDeliveryOrderID != "default")
                                    {
                                        foreach (tbl_sasDeliveryOrder_Detail oDO in tbl_sasDeliveryOrder_Detail.SelectAllByDeliveryOrder_ID(sDeliveryOrderID))
                                        {
                                            foreach (tbl_sasDeliveryOrder_DetailBreakdown oDODetail in tbl_sasDeliveryOrder_DetailBreakdown.SelectAllByDeliveryOrder_ID_Item_ID_ItemSubCategory_ID_ItemSubCategory2_ID_ItemSerialNo_ItemSerialNo2(oDO.DeliveryOrder_ID, oDO.Item_ID, oDO.ItemSubCategory_ID, oDO.ItemSubCategory2_ID, oDO.ItemSerialNo, oDO.ItemSerialNo2))
                                            {
                                                oDODetail.Delete();
                                            }
                                            oDO.Delete();
                                        }
                                    }
                                }

                                                            
                            }
                        }                        
                        #endregion

                        #region Create Credit/Debit Note for Balance
                        decimal dTotalDues_New = clsHelpMethods_Local.GetCustomerTotalDues_All(oCustomerMaster.Customer_ID);
                        bool bIsCredit = dTotalDues_Old <= dTotalDues_New ? true : false;
                        decimal dBalance = bIsCredit ? dTotalDues_New - dTotalDues_Old : dTotalDues_Old - dTotalDues_New;
                        if (dBalance != 0)
                        {
                            string sFormConfigCodeCR = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.bssCreditNote));

                            tbl_bpsCreditNote cNote = new tbl_bpsCreditNote(sFormConfigCodeCR, clsSecurity.getServerDateTime(), "Purge Tool", "default", "default", oCustomerMaster.Customer_ID, "default", 
                                "default", "default", clsAutocode.getCreditNoteTypeID(CreditNoteType.InvoiceAdjustment), "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction),
                                clsSecurity.FinancialYearID,  clsConfig.sLocalCurrencyCode, "default", 1, 0, 0, 0, 0, dBalance, 0, 0, 0, 0, dBalance, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID,
                                clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                false, false, false, false, false, false, 0, false, 0,clsSecurity.CompanyID,clsSecurity.BranchID, false, (-1), (-1));
                            cNote.Insert();
                        } 
                        #endregion
                    }
                    //MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PurgeDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    






                    
                }                
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
                Cursor = Cursors.Default;
            }
            Cursor = Cursors.Default;
        }
        private bool DeleteCheque(string sChequeRegisterID)
        {
            bool bValue = true;
            try
            {                
                clsHelpMethods_Local.RemoveSattlementsFrom_ChequeID(sChequeRegisterID);

                //tbl_bpsChequeReconciliation_Detail
                foreach (tbl_bpsChequeReconciliation_Detail oChqReq in tbl_bpsChequeReconciliation_Detail.SelectAllByChequeRegister_ID(sChequeRegisterID))
                {
                    if (oChqReq != null)
                        oChqReq.Delete();
                }
                //tbl_bpsChequeDeposit_Detail
                foreach (tbl_bpsChequeDeposit_Detail oChqDep in tbl_bpsChequeDeposit_Detail.SelectAllByChequeRegister_ID(sChequeRegisterID))
                {
                    if (oChqDep != null)
                        oChqDep.Delete();
                }

                //tbl_bpsChequeReIssue_Detail
                foreach (tbl_bpsChequeReIssue_Detail oChqReIss in tbl_bpsChequeReIssue_Detail.SelectAllByChequeRegister_ID(sChequeRegisterID))
                {
                    if (oChqReIss != null)
                        oChqReIss.Delete();
                }

                //tbl_bpsChequeRegister
                tbl_bpsChequeRegister oChqRegister = tbl_bpsChequeRegister.Select(sChequeRegisterID);
                if (oChqRegister != null && oChqRegister.ChequeRegister_ID != "default")
                    oChqRegister.Delete();               
            }
            catch (Exception ex)
            {
                bValue = false;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return bValue;
        }
        #endregion

        #region Btn Fill
        private void btnFill_Click(object sender, EventArgs e)
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                List<string> sInvoices = new List<string>();

                List<tbl_sasInvoice> oInvoices = tbl_sasInvoice.SelectAll().Where(p => p.InvoiceDate.Date < dtpPurgeDate.Value.Date && p.Invoice_ID != "default").ToList();
                foreach (tbl_sasInvoice oInvoice in oInvoices)
                {
                    sInvoices.Add(oInvoice.Invoice_ID);
                }

                foreach (string sInvoiceID in sInvoices)
                {
                    List<string> sTmpInvoice = new List<string>();
                    List<string> sTmpCheque = new List<string>();
                    List<string> sTmpReceipt = new List<string>();
                    List<string> sTmpCreditNote = new List<string>();
                    List<string> sTmpSRN = new List<string>();
                    List<string> sTmpDO = new List<string>();

                    bool bIsInvoicePass = true;
                    foreach (tbl_sasInvoice_Sattled oTag in tbl_sasInvoice_Sattled.SelectAllByInvoice_ID(sInvoiceID))
                    {
                        #region Cheque
                        if (oTag.Invoice_ID != "default" && oTag.ChequeRegister_ID != "default" && oTag.Receipt_ID != "default")
                            sTmpCheque.Add(oTag.ChequeRegister_ID);

                        if (bIsInvoicePass && oTag.Invoice_ID != "default" && oTag.ChequeRegister_ID == "default" && oTag.Receipt_ID != "default")
                            sTmpReceipt.Add(oTag.Receipt_ID);

                        if (bIsInvoicePass && oTag.Invoice_ID != "default" && oTag.CreditNote_ID != "default")
                            sTmpCreditNote.Add(oTag.CreditNote_ID);

                        #endregion
                    }

                    tbl_sasInvoice oInvoice = tbl_sasInvoice.Select(sInvoiceID);
                    if (oInvoice != null)
                    {
                        int iRow;
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        int iProcessNoteID_Invoice = clsAutocode.GetProcessNoteID(ProcessNote.Invoice);
                        string sProcessNoteName_Invoice = clsGenaralName.getName_ProcessNote(iProcessNoteID_Invoice);
                        string sCustomerID = oInvoice.Customer_ID;
                        Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_Invoice, iProcessNoteID_Invoice.ToString(), sInvoiceID, clsFormatter.FormatDate_Short(oInvoice.InvoiceDate), false, false, sCustomerID);

                        #region Cheques
                        int iProcessNoteID_Cheque = clsAutocode.GetProcessNoteID(ProcessNote.Cheque);
                        string sProcessNoteName_Cheque = clsGenaralName.getName_ProcessNote(iProcessNoteID_Cheque);
                        foreach (string sCheque in sTmpCheque)
                        {
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_Cheque, iProcessNoteID_Cheque.ToString(), sCheque, "", false, false, sCustomerID);
                        }
                        #endregion

                        #region Receipt
                        int iProcessNoteID_Receipt = clsAutocode.GetProcessNoteID(ProcessNote.Receipt);
                        string sProcessNoteName_Receipt = clsGenaralName.getName_ProcessNote(iProcessNoteID_Receipt);
                        foreach (string sReceipt in sTmpReceipt)
                        {
                            string sTransactionName = clsGenaralName.getName_ProcessNote(clsAutocode.GetProcessNoteID(ProcessNote.Receipt));
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_Receipt, iProcessNoteID_Receipt.ToString(), sReceipt, "", false, false, sCustomerID);
                        }
                        #endregion

                        #region Credit Note
                        int iProcessNoteID_CreditNote = clsAutocode.GetProcessNoteID(ProcessNote.CreditNote);
                        string sProcessNoteName_CreditNote = clsGenaralName.getName_ProcessNote(iProcessNoteID_CreditNote);
                        foreach (string sCreditNote in sTmpCreditNote)
                        {                            
                            string sTransactionName = clsGenaralName.getName_ProcessNote(clsAutocode.GetProcessNoteID(ProcessNote.CreditNote));                            
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_CreditNote, iProcessNoteID_CreditNote.ToString(), sCreditNote, "", false, false, sCustomerID);
                        }
                        #endregion

                        #region Sales Returned Note
                        int iProcessNoteID_SRN = clsAutocode.GetProcessNoteID(ProcessNote.SalesReturned);
                        string sProcessNoteName_SRN = clsGenaralName.getName_ProcessNote(iProcessNoteID_SRN);
                        foreach (string sSRN in sTmpSRN)
                        {
                            string sTransactionName = clsGenaralName.getName_ProcessNote(clsAutocode.GetProcessNoteID(ProcessNote.SalesReturned));
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_SRN, iProcessNoteID_SRN.ToString(), sSRN, "", false, false, sCustomerID);
                        }
                        #endregion

                        #region Delivery Order
                        int iProcessNoteID_DO = clsAutocode.GetProcessNoteID(ProcessNote.DeliveryOrder);
                        string sProcessNoteName_DO = clsGenaralName.getName_ProcessNote(iProcessNoteID_DO);
                        foreach (string sDO in sTmpSRN)
                        {
                            string sTransactionName = clsGenaralName.getName_ProcessNote(clsAutocode.GetProcessNoteID(ProcessNote.DeliveryOrder));
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            Fill_Datagrid(iRow, iRow + 1, sProcessNoteName_DO, iProcessNoteID_DO.ToString(), sDO, "", false, false, sCustomerID);
                        }
                        #endregion
                    }

                    sTmpInvoice.Clear();
                    sTmpCheque.Clear();
                    sTmpReceipt.Clear();
                    sTmpCreditNote.Clear();
                    sTmpSRN.Clear();
                    sTmpDO.Clear();

                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail, clsFormatter.colorDigiteqTheamColorAdminHeaderColour, clsFormatter.colorDigiteqTheamColorAdminForColour);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtPurgeID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblAlertID, true);

            clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, true);

            txtPreparedBy.Tag = null;
            txtCheckedBy.Tag = null;
            txtApprovedBy.Tag = null;

            txtApprovedBy.Clear();
            txtCheckedBy.Clear();
            txtPreparedBy.Clear();
            txtRemark.Clear();
            dtpPurgeDate.Value = clsSecurity.getServerDateTime();
            dgvDetail.Rows.Clear();

            bHasApproved = false;
            bHasChecked = false;


            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtPurgeID.Text = "<Auto Generate>";
            else
                txtPurgeID.Clear();
            if (txtPurgeID.Enabled)
            {
                txtPurgeID.SelectAll();
                txtPurgeID.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid(string sPurgeID)
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                tbl_securityPurge oPurge = tbl_securityPurge.Select(sPurgeID);
                if (oPurge != null && oPurge.Purge_ID != "default")
                {
                    List<tbl_securityPurge_Detail> details = tbl_securityPurge_Detail.SelectAllByPurge_ID(oPurge.Purge_ID);
                    foreach (tbl_securityPurge_Detail detail in details)
                    {
                        if (detail.Purge_ID.Trim() != "default")
                        {
                            dgvDetail.Rows.Add();
                            iRow = dgvDetail.Rows.Count - 1;
                            dgvDetail["LineNo", iRow].Value = detail.Line_No.ToString();
                            dgvDetail["TransactionName", iRow].Value = clsGenaralName.getName_ProcessNote(detail.ProcessNote_ID);
                            dgvDetail["TransactionID", iRow].Value = detail.Transaction_ID;
                            dgvDetail["IsPurged", iRow].Value = detail.IsPurgeEnd;
                            dgvDetail["IsPurged", iRow].Value = detail.IsPurgeEnd;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_securityPurge detail = tbl_securityPurge.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtPurgeID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblAlertID, false);

                        //asign values
                        txtPurgeID.Text = detail.Purge_ID;
                        txtRemark.Text = detail.Remark;
                        dtpPurgeDate.Value = detail.PurgeDate;


                        //User Security
                        txtPreparedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.CreateUser_ID));
                        dtpDatePreparedBy.Value = detail.DateCreate;
                        dtpTimePreparedBy.Value = detail.DateCreate;

                        if (detail.IsApproved)
                        {
                            bHasApproved = true;
                            glbApprovedDate = detail.DateApproved;
                            dtpDateApprovedBy.Value = detail.DateApproved;
                            dtpTimeApprovedBy.Value = detail.DateApproved;
                            clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, false);
                            clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, false);
                            txtApprovedBy.Tag = detail.ApprovedUser_ID;
                            txtApprovedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.ApprovedUser_ID));
                        }
                        if (detail.IsChecked)
                        {
                            bHasChecked = true;
                            glbCheckedDate = detail.DateChecked;
                            dtpDateCheckedBy.Value = detail.DateChecked;
                            dtpTimeCheckedBy.Value = detail.DateChecked;
                            clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, false);
                            clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, false);
                            txtCheckedBy.Tag = detail.CheckedUser_ID;
                            txtCheckedBy.Text = clsCommon.GetForeignKeyValue(clsGenaralName.getName_User(detail.CheckedUser_ID));
                        }

                        RefreshGrid(detail.Purge_ID);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion



        #region Events KeyDown
        private void txtAlertID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_PurgeID();
            }
        }

        private void frm_mtrAlert_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtAlertID_DoubleClick(object sender, EventArgs e)
        {
            Search_PurgeID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {

                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion



        #region Search Methods
        private void Search_PurgeID()
        {
            try
            {
                clsSearch.Search_MasterPurge(ref txtPurgeID);
                if (txtPurgeID.Text.Length > 0 && txtPurgeID.Text.Trim() != "<Auto Generate>")
                    FillDetails(txtPurgeID.Text.Trim());
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        private void FindAndFillRecords(DateTime dtpTillDate)
        {

        }

        #region Fill Datagrid
        private void Fill_Datagrid(int iRow, int iLineNo, string sProcessNote, string sProcessNoteID, string sTransactionID, string sTransactionDate, bool bIsBackup, bool bIsPurge, string sCustomerID)
        {
            try
            {
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    string sTmpTransactionID = "", sTmpTransactionName = "";
                    sTmpTransactionName = clsValidate.ValidateGridValue(dgvDetail, "TransactionName", row.Index, "default");
                    sTmpTransactionID = clsValidate.ValidateGridTag(dgvDetail, "TransactionID", row.Index, "default");
                    if (sTmpTransactionID == sTransactionID && sTmpTransactionName == sProcessNote)
                    {
                        dgvDetail.Rows.RemoveAt(iRow);
                    }
                }

                dgvDetail["LineNo", iRow].Value = iLineNo.ToString();
                dgvDetail["TransactionName", iRow].Value = sProcessNote;
                dgvDetail["TransactionName", iRow].Tag = sProcessNoteID;
                dgvDetail["TransactionID", iRow].Value = sTransactionID;
                dgvDetail["TransactionDate", iRow].Value = sTransactionDate;
                dgvDetail["IsBackUp", iRow].Value = bIsBackup;
                dgvDetail["IsPurged", iRow].Value = bIsPurge;
                dgvDetail["CustomerID", iRow].Value = sCustomerID;

            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        private void UpdatePurgeDetail(int sPurgeDetaillineNo, bool isPurgeDone)
        {
            tbl_securityPurge_Detail detail = tbl_securityPurge_Detail.Select(sPurgeDetaillineNo);
            if (detail != null)
            {
                detail.IsPurgeEnd = true;
                detail.Update();
            }

        }
    }
}
