using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_masEmployeeMasterViewer : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;
        string s_FileName;
        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_masEmployeeMasterViewer()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.EmployeeMaster);
            iFormID = clsSecurity.getFormID(FormName.EmployeeMaster);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_mtrEmplioyeeMaster_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        #endregion

        #region Btn new
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }

        #endregion

        #region Btn Delet
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtEmployeeID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_genEmployeeMaster detail = tbl_genEmployeeMaster.Select(txtEmployeeID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                   
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtEmployeeID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_genEmployeeMaster oldRecord = tbl_genEmployeeMaster.Select(txtEmployeeID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_genEmployeeMaster detail = new tbl_genEmployeeMaster(txtEmployeeID.Text.Trim(), txtEmployeeName.Text.Trim(), txtDesignationName.Text.Trim(), txtNicNo.Text.Trim(), tetEmployeeCode.Text.Trim(), txtTelephone.Text.Trim(), txtMoible.Text.Trim(), txtFax.Text.Trim(), txtEmail.Text.Trim(), oldRecord.Gl_ID, dtpDateOfBirth.Value, chkSalesManager.Checked, chkAreaManager.Checked, chkSelesRep.Checked, chkSalesExecutive.Checked, chkDrive.Checked, chkAssistant.Checked, oldRecord.IsDelete, oldRecord.EmployeeCostPerHour, oldRecord.IsOperator,decimal.Parse( txtSalesTarget.Text.Trim()),0,0,0);
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtEmployeeID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_genEmployeeMaster detail = new tbl_genEmployeeMaster(txtEmployeeID.Text.Trim(), txtEmployeeName.Text.Trim(), txtDesignationName.Text.Trim(), txtNicNo.Text.Trim(), tetEmployeeCode.Text.Trim(), txtTelephone.Text.Trim(), txtMoible.Text.Trim(), txtFax.Text.Trim(), txtEmail.Text.Trim(), "default", dtpDateOfBirth.Value, chkSalesManager.Checked, chkAreaManager.Checked, chkSelesRep.Checked, chkSalesExecutive.Checked, chkDrive.Checked, chkAssistant.Checked, false, 0, chkOperator.Checked, decimal.Parse(txtSalesTarget.Text.Trim()), 0, 0,0);                                       
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Employee " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }                    
                }
            }
        }

        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail, clsFormatter.colorDigiteqTheamColorMaster, clsFormatter.colorDigiteqTheamColorMaster);            
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtEmployeeID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblEmployeeID, true);

            txtEmployeeName.Clear();
            txtEmployeeID.Clear();
            txtDesignationName.Clear();
            txtNicNo.Clear();
            tetEmployeeCode.Clear();
            txtTelephone.Clear();
            txtMoible.Clear();
            txtFax.Clear();
            txtEmail.Clear();
            txtSalesTarget.Clear();
            chkSalesManager.Checked = false;
            chkAreaManager.Checked = false;
            chkSelesRep.Checked = false;
            chkSalesExecutive.Checked = false;
            chkDrive.Checked = false;
            chkAssistant.Checked = false;

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtEmployeeID.Text = "<Auto Generate>";
            else
                txtEmployeeID.Clear();

            txtDesignationName.Clear();
            if (txtEmployeeID.Enabled)
            {
                txtEmployeeID.SelectAll();
                txtEmployeeID.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();

            List<tbl_genEmployeeMaster> details = tbl_genEmployeeMaster.SelectAll();
            foreach (tbl_genEmployeeMaster detail in details)
            {
                dgvDetail.Rows.Add();
                iRow = dgvDetail.Rows.Count - 1;
                dgvDetail["EmployeeID", iRow].Value = detail.Employee_ID;
                dgvDetail["EmployeeName", iRow].Value = detail.EmployeeName;
                dgvDetail["designation", iRow].Value = detail.Designation;
                dgvDetail["EmployeeCode", iRow].Value = detail.Employee_ID;
                dgvDetail["designation", iRow].Value = detail.EmployeeName;
                dgvDetail["Nic", iRow].Value = detail.Designation;
                dgvDetail["Mobile", iRow].Value = detail.Employee_ID;
                dgvDetail["Telephone", iRow].Value = detail.EmployeeName;
                dgvDetail["Email", iRow].Value = detail.Designation;
            }
            dgvDetail.Rows.Add();
        }
        #endregion     

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID.Length > 0)
            {
                tbl_genEmployeeMaster detail = tbl_genEmployeeMaster.Select(sID);
                if (detail != null)
                {
                    //set the update flag and Locked
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtEmployeeID, false);
                    clsCommon.SetEnableDisable_NormalLabel(lblEmployeeID, false);

                    //asign values
                    txtEmployeeID.Text = detail.Employee_ID;
                    txtEmployeeName.Text = detail.EmployeeName;
                    txtDesignationName.Text = detail.Designation;
                    txtEmployeeName.Text = detail.EmployeeName;
                    txtEmployeeID.Text = detail.Employee_ID;
                    txtDesignationName.Text = detail.Designation;
                    txtNicNo.Text = detail.NicNo;
                    tetEmployeeCode.Text = detail.EmployeCode;
                    txtTelephone.Text = detail.Telephone;
                    txtMoible.Text = detail.Mobile;
                    txtFax.Text = detail.Fax;
                    txtEmail.Text = detail.Email;
                    chkSalesManager.Checked = detail.IsSalesManager;
                    chkAreaManager.Checked = detail.IsAreaManager;
                    chkSelesRep.Checked = detail.IsSelesRep;
                    chkSalesExecutive.Checked = detail.IsSalesExecutive;
                    chkDrive.Checked = detail.IsDriver;
                    chkAssistant.Checked = detail.IsAssistant;
                }
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtEmployeeName.TextLength == 0)
            {
                strMessage += "\n" + "Employee Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events Key down
        private void txtEmployeeID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_EmployeeID();
            }
        }

        private void frm_masEmployeeMaster_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events Double Click
        private void txtEmployeeID_DoubleClick(object sender, EventArgs e)
        {
            Search_EmployeeID();
        }
        
        #endregion

        #region Events Datagrid

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                string sID = dgvDetail["EmployeeID", e.RowIndex].Value.ToString();
                if (sID.Length > 0)
                {
                    //fills the values to controls
                    FillDetails(sID.Trim());
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellContentClick(sender,e);
        }
        
        #endregion

        #region Events KeyPress
        private void txtSalesTarget_KeyPress(object sender, KeyPressEventArgs e)
        {
            clsValidate.AllowDecimalWithLength(txtSalesTarget, e, 15, 2);
        }
        #endregion

        #region Search Methods
        private void Search_EmployeeID()
        {
            Form frmhelpsearch = new frmSearchMaster();
            clsSearch.passValue_Employee();
            frmhelpsearch.ShowDialog();

            if (frmSearchMaster.s_SearchID.Length > 0)
            {
                txtEmployeeID.Text = frmSearchMaster.s_SearchID;
                FillDetails(frmSearchMaster.s_SearchID);
            }
        }
        #endregion

        #region Btn Image
        private void btnLoadImage_Click(object sender, EventArgs e)
        {
            FileDialog filedialog = new OpenFileDialog();

            filedialog.Filter = "JPG Files|*.Jpg|" + "JPEG Files|*.Jpeg";
            filedialog.ShowDialog();
            s_FileName = filedialog.FileName;
            pbxImage.ImageLocation = s_FileName;
        } 
        #endregion

    }
}
