using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Printing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_masPrinterMaster : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;

        //Filter Data
        private BindingSource source = new BindingSource();
        public DataTable dtAllRecodes = new DataTable();
        #endregion

        #region Form Load
        public frm_masPrinterMaster()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.PrinterMaster);

            iFormID = clsSecurity.getFormID(FormName.PrinterMaster);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        

        private void frm_masPrinterMaster_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            CusDataGridViewFormat();
            ClearFields();
            RefreshGrid();

            FillComboBox();
        }
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    //if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    //{
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtPrinterID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_zPrinterMaster oldRecord = tbl_zPrinterMaster.Select(txtPrinterID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_zPrinterMaster detail = new tbl_zPrinterMaster(txtPrinterID.Text.Trim(), txtPrinterName.Text.Trim(), txtPrinterPort.Text.Trim(), txtRemark.Text.Trim(), chkDefaultPrinter.Checked);
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtPrinterID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_zPrinterMaster detail = new tbl_zPrinterMaster(txtPrinterID.Text.Trim(), txtPrinterName.Text.Trim(), txtPrinterPort.Text.Trim(), txtRemark.Text.Trim(), chkDefaultPrinter.Checked);
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Printer Master " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    //}
                }
            }
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtPrinterID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zCountry detail = tbl_zCountry.Select(txtPrinterID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                   
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            try
            {
                if (dgvDetail.SelectedCells.Count != 0)
                {
                    if (dgvDetail.Rows.Count > 1)
                        dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity        
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtPrinterName.Text.Length == 0)
            {
                strMessage += "\n" + "Printer Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion


        #region ClearFields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;

            //txtItemID.Enabled = true;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtPrinterID, true);
            //clsCommon.SetEnableDisable_NormalTextbox(txtPrinterName,true);
            //clsCommon.SetEnableDisable_NormalTextbox(txtPrinterPort, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtRemark, true);
            clsCommon.SetEnableDisable_NormalCheckBox(chkDefaultPrinter, true);

            txtPrinterID.Clear();
            txtPrinterName.Text = "";
            txtPrinterPort.Text = "";
            txtRemark.Clear();
            chkDefaultPrinter.Checked = false;
           

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtPrinterID.Text = "<Auto Generate>";
            else
                txtPrinterID.Clear();
            if (txtPrinterID.Enabled)
            {
                txtPrinterID.SelectAll();
                txtPrinterID.Focus();
            } 
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();

                List<tbl_zPrinterMaster> details = tbl_zPrinterMaster.SelectAll();
                foreach (tbl_zPrinterMaster detail in details)
                {                    
                     dgvDetail.Rows.Add();
                     iRow = dgvDetail.Rows.Count - 1;
                     dgvDetail["printerID", iRow].Value = detail.Printer_ID;
                     dgvDetail["printerName", iRow].Value = detail.PrinterName;
                     dgvDetail["printerPort", iRow].Value = detail.PrinterPort;
                     dgvDetail["remark", iRow].Value = detail.Remark;
                     dgvDetail["defaultPrinter", iRow].Value = detail.IsDefaultPrinter;
                    
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion

        #region  Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail, clsFormatter.colorDigiteqTheamColorMaster, clsFormatter.colorDigiteqTheamColorMaster);
        }
        #endregion

        #region Fill Details
        private void FillDetails(string pID)
        {
            try
            {
                if (pID.Length > 0)
                {
                    tbl_zPrinterMaster detail = tbl_zPrinterMaster.Select(pID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtPrinterID, false);
                       // clsCommon.SetEnableDisable_NormalTextbox(txtPrinterName, true);
                       // clsCommon.SetEnableDisable_NormalTextbox(txtPrinterPort, true);
                        clsCommon.SetEnableDisable_NormalTextbox(txtRemark, true);
                        clsCommon.SetEnableDisable_NormalCheckBox(chkDefaultPrinter, true);

                        //asign values
                        txtPrinterID.Text = detail.Printer_ID;
                        txtPrinterName.Text = detail.PrinterName;
                        txtPrinterPort.Text = detail.PrinterPort;
                        txtRemark.Text = detail.Remark;
                        chkDefaultPrinter.Checked = detail.IsDefaultPrinter;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        private void FillComboBox()
        {
            //ports
            txtPrinterPort.Items.Clear();
            foreach (string port in System.IO.Ports.SerialPort.GetPortNames())
            {
                txtPrinterPort.Items.Add(port);
            }

            //printers
            txtPrinterName.Items.Clear();
            foreach (string printerName in PrinterSettings.InstalledPrinters)
            {
                txtPrinterName.Items.Add(printerName);
                txtPrinterName.Items.Add(printerName);
            }
        }
        

        #region Events KeyDown
        private void txtPrinterID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CountryID();
            }
        }

        private void frm_masPrinterMaster_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion
              
        #region Events DoubleClick
        private void txtPrinterID_DoubleClick(object sender, EventArgs e)
        {
            Search_CountryID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["printerID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion


        #region Search
        private void Search_CountryID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_PrinterID();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtPrinterID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion                
    }
}
