using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using DataTire;

namespace Digiteq
{
    public partial class frm_bpsCashDeposit : SEACC_Form
    {
        bool bActiveDateValidation = false;

        
        public DataTable dtCashDeposite = new DataTable();
 

        #region Form load
        public frm_bpsCashDeposit()
        {
            InitializeComponent();
        }
        public frm_bpsCashDeposit(FormName _enmForm)
        {
            enmForm = _enmForm;
            InitializeComponent();
            Initialize();
        }

        private void frm_bpsCashDeposit_Load(object sender, EventArgs e)
        {
            SetVisibility_ActionButons(true, false, false, true, false, false, false, false, false);
            Refresh_BranchCmb();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void frm_bpsCashDeposit_SF_newButton_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Save
        private void frm_bpsCashDeposit_SF_saveButton_Click(object sender, EventArgs e)
        {
            if (CheckValidityCashDeposit_EmptyField())
            {
                if (CheckSelectedChequeCount())
                {
                    if (clsMethods_GL.CheckValidity_FinancialYear(dtpCashDepositeDate.Value.Date))
                    {
                        if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                        {
                            if (CheckValidity_CashDepositPosting())
                            {
                                try
                                {
                                    Cursor = Cursors.WaitCursor;
                                    ValidateEmptyForeignKeyDeposit();

                                    try
                                    {
                                        txtCashDepositeID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                        if (clsValidate.CheckValidity_TransactionCodeLength(txtCashDepositeID.Text)) //if (txtCashDepositeID.TextLength > 0)
                                        {
                                            int iCompanyAccount_ID = clsGenaralName.getName_CompanyAccount_IDByAccountNo(txtCashDepositeAccountNo.Tag.ToString());

                                            //tbl_bpsCashDeposit detail = new tbl_bpsCashDeposit(txtCashDepositeID.Text.Trim(), txtCashDepositeRemarks.Text.Trim(), dtpCashDepositeDate.Value, decimal.Parse(txtCountCheques.Text.Trim()), decimal.Parse(txtAmountChequeSelected.Text.Trim()),
                                            //     txtCashDepositeAccountNo.Text.Trim(), txtCashDepositeBankName.Tag.ToString(), txtCashDepositeBranchName.Tag.ToString(), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime(),
                                            //    clsSecurity.getServerDateTime(), clsSecurity.CompanyID, ((ComboBoxItem)cmbComBranch.SelectedItem).Value);
                                            //detail.Insert();
                                            tbl_bpsCashDeposit detail = new tbl_bpsCashDeposit(txtCashDepositeID.Text.Trim(), txtCashDepositeRemarks.Text.Trim(), dtpCashDepositeDate.Value, decimal.Parse(txtCountChequeSelected.Text.Trim()), decimal.Parse(txtTotDepAmount.Text.Trim()), decimal.Parse(txtTotDepAmount.Text.Trim()),
                                                 txtCashDepositeAccountNo.Text.Trim(), lblCashDepositeBankName.Tag.ToString(), lblCashDepositeBranchName.Tag.ToString(), clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime(),
                                                clsSecurity.getServerDateTime(), false, clsSecurity.CompanyID, ((ComboBoxItem)cmbComBranch.SelectedItem).Value, iCompanyAccount_ID, -1, clsSecurity.getServerDateTime());
                                            detail.Insert();

                                            foreach (DataGridViewRow row in dgvDetail.Rows)
                                            {
                                                if (!bool.Parse(dgvDetail["IsSelected", row.Index].Value.ToString()))
                                                    continue;

                                                string ReceiptID = "";

                                                ReceiptID = dgvDetail["ReceiptID", row.Index].Value.ToString();
                                                if (ReceiptID.Length > 0)
                                                {
                                                    decimal dAmount = 0;
                                                    decimal dDepCashAount = decimal.Parse(dgvDetail["DepositedAmount", row.Index].Value.ToString());

                                                    tbl_bpsCashDeposit_Detail Ddetial = new tbl_bpsCashDeposit_Detail(row.Index, txtCashDepositeID.Text.Trim(), ReceiptID.Trim(), "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), dDepCashAount);
                                                    Ddetial.Insert();

                                                    #region Sales Receipt 
                                                    List<tbl_bpsChequeRegister> oChqList = tbl_bpsChequeRegister.SelectAllByReceipt_ID(ReceiptID).ToList();
                                                    foreach (tbl_bpsChequeRegister oDetail in oChqList.Where(p => p.PaymentMethod_ID == (int)PaymentMethod.Cash))
                                                    {
                                                        if (oDetail != null && oDetail.Receipt_ID != "default")
                                                        {
                                                            oDetail.DepositedCashAmount += dDepCashAount;
                                                            if (oDetail.Amount == oDetail.DepositedCashAmount)
                                                                oDetail.IsDepositted = true;

                                                            oDetail.DateDeposited = dtpCashDepositeDate.Value;
                                                            oDetail.PostingStatus_ID2 = clsAutocode.getGLPostingStatusID(GLPostingStatus.Posted);
                                                            oDetail.Update();

                                                            dAmount = oDetail.DepositedCashAmount;
                                                        }
                                                    }
                                                    #endregion

                                                    #region POS Receipt 
                                                    List<tbl_bpsChequeRegister> oPOSChqList = tbl_bpsChequeRegister.SelectAllByPosReceipt_ID(ReceiptID).ToList();
                                                    //(+) Amount
                                                    foreach (tbl_bpsChequeRegister oDetail in oPOSChqList.Where(p => !p.IsDeleted && p.Amount >= 0 && p.PaymentMethod_ID == (int)PaymentMethod.Cash))
                                                    {
                                                        if (oDetail != null && oDetail.PosReceipt_ID != "default")
                                                        {
                                                            oDetail.DepositedCashAmount += dDepCashAount;
                                                            if (oDetail.Amount == oDetail.DepositedCashAmount)
                                                                oDetail.IsDepositted = true;

                                                            oDetail.DateDeposited = dtpCashDepositeDate.Value;
                                                            oDetail.PostingStatus_ID2 = clsAutocode.getGLPostingStatusID(GLPostingStatus.Posted);
                                                            oDetail.Update();

                                                            dAmount = oDetail.DepositedCashAmount;
                                                        }
                                                    }

                                                    //(-) Amount
                                                    foreach (tbl_bpsChequeRegister oDetail in oPOSChqList.Where(p => !p.IsDeleted && p.Amount < 0 && p.PaymentMethod_ID == (int)PaymentMethod.Cash))
                                                    {
                                                        if (oDetail != null && oDetail.PosReceipt_ID != "default")
                                                        {
                                                            dAmount += oDetail.DepositedCashAmount;
                                                        }
                                                    }
                                                    #endregion

                                                    #region Account Receipt
                                                    List<tbl_bpsChequeRegister> oARChqList = tbl_bpsChequeRegister.SelectAllByAccountReceipt_ID(ReceiptID).ToList();
                                                    foreach (tbl_bpsChequeRegister oDetail in oARChqList.Where(p => p.PaymentMethod_ID == (int)PaymentMethod.Cash))
                                                    {
                                                        if (oDetail != null && oDetail.AccountReceipt_ID != "default")
                                                        {
                                                            oDetail.DepositedCashAmount += Ddetial.DepositedAmount;
                                                            if (oDetail.Amount == oDetail.DepositedCashAmount)
                                                                oDetail.IsDepositted = true;

                                                            oDetail.DateDeposited = dtpCashDepositeDate.Value;
                                                            oDetail.Update();

                                                            dAmount = Ddetial.DepositedAmount;
                                                        }
                                                    }

                                                    tbl_accAccountReceipt ARdetail = tbl_accAccountReceipt.Select(ReceiptID);
                                                    if (ARdetail != null && ARdetail.AccountReceipt_ID != "default")
                                                    {
                                                        //dAmount = ARdetail.CashAmount;

                                                        ARdetail.DepositedCashAmount += dDepCashAount;
                                                        if (ARdetail.CashAmount == ARdetail.DepositedCashAmount)
                                                            ARdetail.IsCashDeposited = true;
                                                        ARdetail.DateDeposited = dtpCashDepositeDate.Value;
                                                        ARdetail.Update();

                                                        dAmount = ARdetail.DepositedCashAmount;
                                                    }
                                                    #endregion

                                                    clsMethods_GL.PostTransaction_cashDeposit(ReceiptID, txtCashDepositeID.Text.Trim(), dtpCashDepositeDate.Value, dAmount, txtCashDepositeAccountNo.Text);
                                                }
                                            }
                                            MessageBox.Show("Record Saved Successfully....\nPlease Write Down The Deposit Reference Number In Your Bank Slip \n\nCHEQUE DEPOSIT REF NO : " + txtCashDepositeID.Text.Trim(), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                        }
                                    }
                                    catch (Exception ex)
                                    {
                                        clsValidate.WriteErrorLog("", iFormID, ex);
                                        SEACCException.Show(ex);
                                    }
                                }
                                catch (Exception ex)
                                {
                                    clsValidate.WriteErrorLog("", iFormID, ex);
                                    SEACCException.Show(ex);
                                }
                                finally
                                {
                                    Cursor = Cursors.Default;
                                    ClearFields();
                                }
                            }
                        }
                    }
                }
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            lblCashDepositeBankName.Tag = null;
            lblCashDepositeBranchName.Tag = null;

            txtCashDepositeAccountNo.Clear();
            lblCashDepositeBankName.Text = "";
            lblCashDepositeBranchName.Text = "";
            txtCashDepositeRemarks.Clear();

            dtpCashDepositeDate.Value = clsSecurity.getServerDateTime();

            txtCountChequeSelected.Text = "0";
            txtAmountChequeSelected.Text = "0.00";

            if (clsConfig.bAdvanceCashDepositeEnable)
            {
                txtTotDepAmount.Visible = true;
                lblTotDepAmount.Visible = true;
            }

            clsCommon.SetEnableDisable_NormalTextbox(txtTotDepAmount, false);
            txtTotDepAmount.Text = "0.00";

            clsCommon.SetEnableDisable_NormalTextbox(txtFillter, true);

            RefreshGridAllCashDeposite();
            CalculateCashDeposaiteTotal();
        }

        #endregion

        #region Refresh Grid
        private void RefreshGridAllCashDeposite()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dgvDetail.Columns["CSdate"].ValueType = typeof(DateTime);
                dtCashDeposite.Rows.Clear();
                if (clsConfig.bAdvanceCashDepositeEnable)
                    dgvDetail.Columns["DepositedAmount"].Visible = true;

                dtCashDeposite.Merge(DBHandling.ExecQuery("exec sp_ChequeRegister_ToBeDeposit_Cash '" + clsSecurity.CompanyID + "','" + ((ComboBoxItem)cmbComBranch.SelectedItem).Value + "'").Tables[0]);

                if (clsConfig.bDisplayBankManagemnet_CashDeposit_Account)
                    dtCashDeposite.Merge(DBHandling.ExecQuery("exec sp_AccountReceipt_ToBeDeposit_Cash '" + clsSecurity.CompanyID + "','" + ((ComboBoxItem)cmbComBranch.SelectedItem).Value + "'").Tables[0]);

                dgvDetail.DataSource = dtCashDeposite;
                dgvDetail.Sort(this.dgvDetail.Columns["CSdate"], ListSortDirection.Ascending);

                //CalculateCheque();

            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
            finally { Cursor = Cursors.Default; }
        }

        #endregion

        private void CalculateSelectedCashDeposites()
        {
            try
            {
                int iCount = 0;
                decimal dAmount = 0;
                decimal dDepCashAmount = 0;
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    try
                    {
                        if (dgvDetail["IsSelected", row.Index].Value != null && dgvDetail["IsSelected", row.Index].Value.ToString().Length > 0)
                        {
                            if (bool.Parse(dgvDetail["IsSelected", row.Index].Value.ToString()) == true)
                            {
                                iCount++;
                                if (dgvDetail["Amount", row.Index].Value != null && dgvDetail["Amount", row.Index].Value.ToString().Length > 0 && clsCommon.isCurrency(dgvDetail["Amount", row.Index].Value.ToString()))
                                    dAmount += decimal.Parse(dgvDetail["Amount", row.Index].Value.ToString());

                                if (dgvDetail["DepositedAmount", row.Index].Value != null && dgvDetail["DepositedAmount", row.Index].Value.ToString().Length > 0 && clsCommon.isCurrency(dgvDetail["DepositedAmount", row.Index].Value.ToString()))
                                    dDepCashAmount += decimal.Parse(dgvDetail["DepositedAmount", row.Index].Value.ToString());
                                else
                                    dgvDetail["DepositedAmount", row.Index].Value = dgvDetail["Amount", row.Index].Value;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID, ex);
                        SEACCException.Show(ex);
                    }
                }

                //txtAmountChequeSelected.Text = clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                txtAmountChequeSelected.Text = clsFormatter.FormatToCurrecyWithThousendSep(dDepCashAmount);
                txtCountChequeSelected.Text = iCount.ToString();

                txtTotDepAmount.Text = clsFormatter.FormatToCurrecyWithThousendSep(dDepCashAmount);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }

        private void CalculateCashDeposaiteTotal()
        {
            try
            {
                int iCount = 0;
                decimal dAmount = 0;
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    try
                    {
                        iCount++;
                        dAmount += decimal.Parse(dgvDetail["Amount", row.Index].Value.ToString());
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID, ex);
                        SEACCException.Show(ex);
                    }
                }
                txtAmountCheques.Text = clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                txtCountCheques.Text = iCount.ToString();
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }
        private void Refresh_BranchCmb()
        {
            cmbComBranch.Items.Clear();
            cmbComBranch.DisplayMember = "Value";
            cmbComBranch.ValueMember = "Text";

            foreach (tbl_genCompanyBranchMaster oDetail in tbl_genCompanyBranchMaster.SelectAll())
            {
                if (oDetail.CompanyBranch_ID != "default")
                    cmbComBranch.Items.Add(new ComboBoxItem(oDetail.CompanyBranch_ID, oDetail.BranchName));
            }
            if (cmbComBranch.Items.Count > 0)
                cmbComBranch.SelectedIndex = cmbComBranch.FindStringExact(clsSecurity.BranchName);
        }

        #region Selected Chques Count
        private bool CheckSelectedChequeCount()
        {
            bool bStatus = true, bSelected = false;
            DateTime Recieptdate = DateTime.MinValue;
            int ValiedRowCount = 0;
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {     
                bSelected = clsValidate.ValidateGridValue(dgvDetail, "IsSelected", row.Index, bSelected);   
                if (bSelected)
                {
                    Recieptdate = clsValidate.ValidateGridValue(dgvDetail, "ReceiptDate2", row.Index, Recieptdate);

                    if (bActiveDateValidation)
                    {
                        if (dtpCashDepositeDate.Value.Date >= Recieptdate.Date)
                        { ValiedRowCount++; }
                        else
                        {
                            MessageBox.Show("Deposit date Should be greater than receipt date", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                            return false;
                        }
                    }
                    else
                        ValiedRowCount++;
                }
            }
            if (ValiedRowCount == 0)
                bStatus = false;

            return bStatus;
        }
        private bool CheckValidity_CashDepositPosting()
        {
            bool bStatus = false;
            if (clsConfig.bAutoPostingEnable)
            {
                bool bSlotStatus_Bank = clsMethods_GL.CheckAccountLink_Bank(txtCashDepositeAccountNo.Text);
                bool bSlotStatus_Cash = clsMethods_GL.CheckAccountLink(AccSlot.CashDeposit, true);

                if (bSlotStatus_Bank && bSlotStatus_Cash)
                    bStatus = true;
            }
            else
                bStatus = true;
            return bStatus;
        }

        #endregion

        #region Check Validity        
        private bool CheckValidityCashDeposit_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtCashDepositeAccountNo, "Account Number"))
            {
                //if (clsValidate.ValidateTextBox_EmptyValue(lblCashDepositeBankName, "Bank Name"))
                bStatus = true;
            }
            return bStatus;
        }

        private bool CheckNumberValidityDeposit()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {
                if (!clsCommon.isCurrency(txtCountChequeSelected.Text.Trim()))
                {
                    strMessage += "\n Selected Cheque Count";
                    bStatus = false;
                }
                if (!clsCommon.isCurrency(txtAmountChequeSelected.Text.Trim()))
                {
                    strMessage += "\n Selected Cheque Amount";
                    bStatus = false;
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }

            if (bStatus == false)
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

            return bStatus;
        }
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKeyDeposit()
        {
            clsCommon.ValidateForeignKey(ref lblCashDepositeBankName);
            clsCommon.ValidateForeignKey(ref lblCashDepositeBranchName);
            //clsCommon.ValidateForeignKey(ref txtCheckedBy);
            //clsCommon.ValidateForeignKey(ref txtApprovedBy);
        }
        #endregion

        private void txtCashDepositeAccountNo_DoubleClick(object sender, EventArgs e)
        {
            Search_AccountForDeposit(txtCashDepositeAccountNo, lblCashDepositeBankName, lblCashDepositeBranchName);
        }

        private void Search_AccountForDeposit(TextBox myTextBox, Label DepositBankName, Label DepositBranchName)
        {
            try
            {
                clsSearch.SearchMaster_CompanyAccount(ref myTextBox, "", "");
                if (myTextBox.Tag != null)
                    FillBankAndBranch(myTextBox.Tag.ToString(), DepositBankName, DepositBranchName);
            }

            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);

            }
        }

        private void FillBankAndBranch(string sAccountNo, Label DepositBankName, Label DepositBranchName)
        {
            try
            {
                tbl_genCompanyAccount Adetail = tbl_genCompanyAccount.Select(sAccountNo);

                tbl_zBank detail = tbl_zBank.Select(Adetail.Bank_ID);
                if (detail != null)
                {
                    DepositBankName.Text = detail.BankName;
                    DepositBankName.Tag = detail.Bank_ID;
                }
                tbl_zBankBranches details = tbl_zBankBranches.Select(Adetail.Branch_ID);
                if (detail != null)
                {
                    DepositBranchName.Text = details.BranchName;
                    DepositBranchName.Tag = details.Branch_ID;
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
        }

        private void dgvDetail_CellMouseClick(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                if (e.ColumnIndex >= 0)
                    sColName = dgvDetail.Columns[e.ColumnIndex].Name;

                //if (sColName == "RegisterCode" || sColName == "RTSRegisterCode")
                //{
                //    string sRegisterID = dgvDetail[e.ColumnIndex, e.RowIndex].Value.ToString();
                //    tbl_bpsChequeRegister detail = tbl_bpsChequeRegister.Select(sRegisterID);
                //    if (detail != null)
                //    {
                //        frm_bpsChequeViewer cheque = new frm_bpsChequeViewer();
                //        cheque.glbChequeRegisterID = detail.ChequeRegister_ID;
                //        cheque.ShowDialog();
                //    }
                //}

                //else
                if (sColName == "ReceiptID" || sColName == "RTSReceiptID")
                {
                    string sReceiptID = dgvDetail[e.ColumnIndex, e.RowIndex].Value.ToString();
                    tbl_bpsReceipt detail = tbl_bpsReceipt.Select(sReceiptID);
                    tbl_accAccountReceipt detailAR = tbl_accAccountReceipt.Select(sReceiptID);
                    if (detail != null)
                    {
                        if (detail.IsSalesReceipt)
                        {
                            UC_bpsReceiptSales frm = new UC_bpsReceiptSales(FormName.UCReceipt);
                            frm.glbReceiptID = detail.Receipt_ID;
                            clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, (this.Parent as Form).MdiParent);
                        }
                        else
                        {
                            UC_bpsReceiptSales frm = new UC_bpsReceiptSales(FormName.InterimReceipt);
                            frm.glbReceiptID = detail.Receipt_ID;
                            clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorBills, (this.Parent as Form).MdiParent);
                        }
                    }
                    else if (detailAR != null)
                    {
                        frm_accAccountReceipt frm = new frm_accAccountReceipt(FormName.accReceiptVoucher);
                        frm.glbAccReceiptID = detailAR.AccountReceipt_ID;
                        clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorAccounts, (this.Parent as Form).MdiParent);
                    }
                }
                else if (sColName == "IsSelected")
                {
                    bool bstatus = clsValidate.ValidateGridValue(dgvDetail, "IsSelected", e.RowIndex, false);
                    // if (bstatus)
                    dgvDetail[e.ColumnIndex, e.RowIndex].Value = !bstatus;

                    CalculateSelectedCashDeposites();
                }
            }
        }

        private void txtFillter_KeyUp(object sender, KeyEventArgs e)
        {
            try
            {
                StringBuilder sFilter = new StringBuilder();

                string sFilteredValue = clsHelpMethods.CheckValue(txtFillter.Text.Trim());

                //sFilter.Append("ReceiptDate LIKE '%" + txtFillter.Text.Trim() + "%' ");
                //sFilter.Append("OR CustomerName LIKE '%" + txtFillter.Text.Trim() + "%' ");
                //sFilter.Append("OR receiptID LIKE '%" + txtFillter.Text.Trim() + "%' ");
                //sFilter.Append("OR invoiceList LIKE '%" + txtFillter.Text.Trim() + "%' ");
                //sFilter.Append("OR Amount LIKE '%" + txtFillter.Text.Trim() + "%' ");

                sFilter.Append("ReceiptDate LIKE '%" + sFilteredValue + "%' ");
                sFilter.Append("OR CustomerName LIKE '%" + sFilteredValue + "%' ");
                sFilter.Append("OR receiptID LIKE '%" + sFilteredValue + "%' ");
                sFilter.Append("OR invoiceList LIKE '%" + sFilteredValue + "%' ");
                sFilter.Append("OR Amount LIKE '%" + sFilteredValue + "%' ");
                dtCashDeposite.DefaultView.RowFilter = sFilter.ToString();
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }


            //string sCheckedValue = clsHelpMethods.CheckValue(value);
        }

        private void dgvDetail_CellMouseLeave(object sender, DataGridViewCellEventArgs e)
        {
            Cursor = Cursors.Default;
        }

        private void dgvDetail_CellMouseMove(object sender, DataGridViewCellMouseEventArgs e)
        {
            string sColName = "";
            DataGridView dgv = (DataGridView)sender;
            if (e.ColumnIndex >= 0)
                sColName = dgv.Columns[e.ColumnIndex].Name;


            //if (sColName == "RegisterCode" || sColName == "RTSRegisterCode" || sColName == "ReceiptID")
            if (sColName == "ReceiptID")
                Cursor = Cursors.Hand;
        }

        private void cmbComBranch_SelectedIndexChanged(object sender, EventArgs e)
        {
            ClearFields();
        }

        private void dgvDetail_CurrentCellDirtyStateChanged(object sender, EventArgs e)
        {
            CalculateSelectedCashDeposites();
        }
    }
}