using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using DataTire;
using SEACC.DATA.Data.BSS;
using SEACC.DATA.Domain.BSS;

namespace Digiteq
{
    public partial class frm_bpsReturnCheque : Form
    {
        bool bIsInwordCheque, bIsCancel = false;
        string sTxnID, sChequeRegisterID, sStatusID, sTxnType;
        public frm_bpsReturnCheque()
        {
            InitializeComponent();
        }

        private void btnCancle_Click(object sender, EventArgs e)
        {
            this.Close();
            bIsCancel = true;
        }

        private void frm_bpsReturnCheque_FormClosing(object sender, FormClosingEventArgs e)
        {
            this.DialogResult = DialogResult.Abort;
        }

        public bool Show(bool isInwordCheque, string TxnID, string ChequeRegisterID, string StatusID, string TxnType)
        {
            bIsInwordCheque = isInwordCheque;
            sTxnID = TxnID;
            sChequeRegisterID = ChequeRegisterID;
            sStatusID = StatusID;
            sTxnType = TxnType;
            this.ShowDialog();

            return bIsCancel;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            try
            {
                #region BPS Cheque
                if (sTxnType == "CHQ")
                {
                    string sFormConfigReturnedCheque = clsAutocode.getFormConfigCode(FormName.RetruendChequeDebitInvoice);
                    string sSalesNoteType = "";
                    bool bSlotStatus_Debter = false, bSlotStatus_Bank = false, bSlotStatus_Cheque = false;

                    tbl_bpsChequeRegister oCheque = tbl_bpsChequeRegister.Select(sChequeRegisterID);
                    if (oCheque != null)
                    {
                        if (clsConfig.bAutoPostingEnable)
                        {
                            bSlotStatus_Debter = clsMethods_GL.CheckAccountLink_Customer(oCheque.Customer_ID);
                            bSlotStatus_Bank = clsMethods_GL.CheckAccountLink_Bank(oCheque.DepositedAccountNumber);
                            bSlotStatus_Cheque = clsMethods_GL.CheckAccountLink(AccSlot.ChequeReturned, false);
                        }

                        if (bSlotStatus_Debter && bSlotStatus_Bank && bSlotStatus_Cheque)
                        {
                            Cursor = Cursors.WaitCursor;
                            DialogResult msgResult = MessageBox.Show("Do you want to return this cheque?", clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                            if (msgResult == DialogResult.Yes)
                            {
                                string sAccChequeReconciliationID = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.ChequeReconsiliation));
                                if (sAccChequeReconciliationID.Length > 0)
                                {
                                    #region Reconciliation Header
                                    tbl_bpsChequeReconciliation detail = new tbl_bpsChequeReconciliation(sAccChequeReconciliationID, "", dtmReturnDate.Value.Date,
                                                                    1, oCheque.Amount, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                                                        clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), false, false, false, false, false, clsSecurity.CompanyID, clsSecurity.BranchID);
                                    detail.Insert();
                                    #endregion

                                    tbl_bpsChequeReconciliation_Detail items = new tbl_bpsChequeReconciliation_Detail(sAccChequeReconciliationID, sChequeRegisterID, 0, sStatusID, "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), dtmReturnDate.Value.Date, clsGenaralName.getName_CompanyAccount_IDByAccountNo(oCheque.DepositedAccountNumber), 1, "default");
                                    items.Insert();

                                    #region Returned
                                    if (sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_C) || sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_O) || sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_R))
                                    {
                                        tbl_bpsReceipt oReceipt = tbl_bpsReceipt.Select(oCheque.Receipt_ID);
                                        if (oReceipt != null)
                                            sSalesNoteType = oReceipt.SalesNoteType_ID;

                                        #region Retern Cheque - Debit Note
                                        oCheque.IsReturned = true;
                                        string sDebitNoteID = "";

                                        #region RC inv
                                        sDebitNoteID = clsAutocode.getAutoGeneratedCode(sFormConfigReturnedCheque);

                                        ChequeData oData = new ChequeData();
                                        ReturnedCheque oRC = new ReturnedCheque();

                                        oRC.Txn_ID = sDebitNoteID;
                                        oRC.Txn_Date = dtmReturnDate.Value.Date;
                                        oRC.Customer_ID = oCheque.Customer_ID;
                                        oRC.employee_ID = clsHelpMethods.getEmployeeIDFromReceiptID(oCheque.Receipt_ID);
                                        oRC.OrderRefNo_ID = oCheque.OrderRefNo_ID;
                                        oRC.ChequeRegister_ID = oCheque.ChequeRegister_ID;
                                        oRC.CurrencyCode = clsConfig.sLocalCurrencyCode;
                                        oRC.FinancialYearID = clsSecurity.FinancialYearID;
                                        oRC.SalesNoteType_ID = sSalesNoteType;
                                        oRC.Amount = oCheque.Amount;
                                        oRC.UserID = clsSecurity.UserIDLoged;
                                        oRC.TerminalID = clsSecurity.TerminalID;
                                        oRC.CompanyID = oCheque.CompanyID;
                                        oRC.CompanyBranch_ID = oCheque.CompanyBranch_ID;
                                        oRC.chequeStatus_ID = sStatusID;

                                        var result = oData.Save_DebitNoteForRC(oRC);
                                        if (!result.IsSuccess)
                                            MessageBox.Show(result.OutMsg); 
                                        #endregion

                                    //    clsDB.update_CustomerReturnedCheques(oCheque.Customer_ID, oCheque.Amount, oCheque.AccountNumber);
                                     //   clsDB.update_CustomerDeposittedChequesFromReturns(oCheque.Customer_ID, oCheque.Amount, oCheque.AccountNumber);
                                        #endregion

                                        oCheque.DateReconcilied = dtmReturnDate.Value.Date;
                                        oCheque.IsReconcilied = true;
                                        oCheque.IsLocked = true;
                                        oCheque.ChequeStatus_ID = sStatusID;
                                        oCheque.Update();

                                        bool bChequeReturnedAutoPostingStatus = clsMethods_GL.PostTransaction_chequeReturned(sAccChequeReconciliationID, sChequeRegisterID, dtmReturnDate.Value.Date, oCheque.Amount);

                                        #region BPS Cheque
                                        tbl_bpsChequeDeposit_Detail oChequeDepositeDetail = tbl_bpsChequeDeposit_Detail.Select(sTxnID, sChequeRegisterID);
                                        if (oChequeDepositeDetail != null)
                                        {
                                            oChequeDepositeDetail.ChequeStatus_ID = sStatusID;
                                            oChequeDepositeDetail.DateReconciliation= dtmReturnDate.Value.Date;
                                            oChequeDepositeDetail.RecSerialNo = -1;
                                            oChequeDepositeDetail.Update();
                                        }
                                        #endregion

                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                        this.DialogResult = DialogResult.Yes;
                                    }
                                    #endregion
                                }
                            }
                            else
                            {
                                this.DialogResult = DialogResult.Abort;
                                bIsCancel = true;
                            }
                        }
                    }
                    else
                    {
                        MessageBox.Show("selected cheque is not found...!");
                        this.DialogResult = DialogResult.Abort;
                        bIsCancel = true;
                    }
                }
                #endregion

                #region PV Cheque
                else if (sTxnType == "PV")
                {
                    string sFormConfigReturnedCheque = clsAutocode.getFormConfigCode(FormName.ChequeReconsiliation);
                    string sSalesNoteType = "";
                    //bool bSlotStatus_Debter = false, bSlotStatus_Bank = false, bSlotStatus_Cheque = false;

                    tbl_accChequeRegister oCheque = tbl_accChequeRegister.Select(sChequeRegisterID);
                    if (oCheque != null)
                    {
                        //if (clsConfig.bAutoPostingEnable)
                        //{
                        //    //bSlotStatus_Debter = clsMethods_GL.CheckAccountLink_Customer(oCheque.Customer_ID);
                        //    //bSlotStatus_Bank = clsMethods_GL.CheckAccountLink_Bank(oCheque.DepositedAccountNumber);
                        //    //bSlotStatus_Cheque = clsMethods_GL.CheckAccountLink(AccSlot.ChequeReturned, false);
                        //}

                        //if (bSlotStatus_Debter && bSlotStatus_Bank && bSlotStatus_Cheque)
                        //{
                        Cursor = Cursors.WaitCursor;
                        DialogResult msgResult = MessageBox.Show("Do you want to return this cheque?", clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                        if (msgResult == DialogResult.Yes)
                        {
                            string sAccChequeReconciliationID = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.ChequeReconsiliation));
                            if (sAccChequeReconciliationID.Length > 0)
                            {
                                #region Reconciliation Header                                   
                                tbl_accChequeReconciliation detail = new tbl_accChequeReconciliation(sAccChequeReconciliationID, "", dtmReturnDate.Value,
                                   1, oCheque.ChequeAmount, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                       clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                       false, false, false, false, false, -1, 1, clsSecurity.CompanyID, clsSecurity.BranchID);
                                detail.Insert();
                                #endregion

                                tbl_accChequeReconciliation_Detail items = new tbl_accChequeReconciliation_Detail(0, sAccChequeReconciliationID, sChequeRegisterID, 0, sStatusID, dtmReturnDate.Value, oCheque.CompanyAccount_ID, 1);
                                items.Insert();

                                //#region Returned
                                //if (sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_C) || sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_O) || sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_R))
                                //{
                                if (oCheque.PaymentVoucher_ID != null && oCheque.PaymentVoucher_ID != "default")
                                {
                                    tbl_accPaymentVoucher detailPV = tbl_accPaymentVoucher.Select(oCheque.PaymentVoucher_ID);
                                    if (detailPV != null)
                                    {
                                        #region Cheque Return
                                        if (sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Returned_R))
                                        {
                                            string sAPNID = "";
                                            sAPNID = clsAutocode.getAutoGeneratedCode(sFormConfigReturnedCheque);

                                            //APN Header                                                   
                                            tbl_accAccountPayableNote AccAPN = new tbl_accAccountPayableNote(sAPNID, dtmReturnDate.Value.Date, "", "", clsSecurity.getServerDateTime(), "default", "", "", "default", "default", "default",
                                                                "default", detailPV.Supplier_ID, "default", "default", "default", "default", "default".Trim(), "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), clsSecurity.FinancialYearID, clsConfig.sLocalCurrencyCode,
                                                                1, 0, 0, 0, 0, 0, oCheque.ChequeAmount, 0, 0, 0, 0, oCheque.ChequeAmount,
                                                                clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, "default", "default", clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                                clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID,
                                                                clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(),
                                                                true, false, false, false, false, false, false, false, false, 0, false,
                                                                oCheque.ChequeRegister_ID, true, 0, clsSecurity.CompanyID, clsSecurity.BranchID);
                                            AccAPN.Insert();

                                            //clsDB.update_CustomerReturnedCheques(oCheque.Customer_ID, oCheque.Amount, oCheque.AccountNumber);
                                            //clsDB.update_CustomerDeposittedChequesFromReturns(oCheque.Customer_ID, oCheque.Amount, oCheque.AccountNumber);

                                            oCheque.ReconcilationDate = dtmReturnDate.Value.Date;
                                            oCheque.PrintCount = 1;
                                            oCheque.IsLocked = true;
                                            oCheque.ChequeStatus_ID = sStatusID;
                                            oCheque.Update();

                                            clsMethods_GL.ReversePostTransaction_PV(detailPV.PaymentVoucher_ID, dtmReturnDate.Value, false);

                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                            this.DialogResult = DialogResult.Yes;
                                        }
                                        #endregion

                                        #region Cheque Cancel
                                        else if (sStatusID == clsAutocode.getChequeStatusID(ChequeStatus.Deleted))
                                        {
                                            clsMethods_GL.ReversePostTransaction_PV(detailPV.PaymentVoucher_ID, dtmReturnDate.Value.Date, true);

                                            #region tbl acc ChequeRegister Delete
                                            oCheque.IsDeleted = true;
                                            oCheque.DateModified = dtmReturnDate.Value.Date;
                                            oCheque.ModifiedUser_ID = clsSecurity.UserIDLoged;
                                            oCheque.Update();
                                            #endregion

                                            #region PV Cancel
                                            detailPV.IsDeleted = true;
                                            detailPV.IsSeattled = false;
                                            detailPV.SettledAmount = 0;
                                            detailPV.DateDeleted = dtmReturnDate.Value.Date;
                                            detailPV.DeletedUser_ID = clsSecurity.UserIDLoged;
                                            detailPV.DeletedTerminal_ID = clsSecurity.TerminalID;
                                            detailPV.Update();
                                            #endregion

                                            #region  Un Settle Account Payable Note
                                            clsHelpMethods.RemoveAPNSattlementsFrom_PaymentVoucherID(detailPV.PaymentVoucher_ID);
                                            #endregion

                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                            this.DialogResult = DialogResult.Yes;

                                        }
                                        #endregion
                                    }
                                }
                                //}
                                //#endregion
                            }
                        }
                        else
                        {
                            this.DialogResult = DialogResult.Abort;
                            bIsCancel = true;
                        }

                        //}
                    }
                    else
                    {
                        MessageBox.Show("selected cheque is not found...!");
                        this.DialogResult = DialogResult.Abort;
                        bIsCancel = true;
                    }
                }
                #endregion
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                this.DialogResult = DialogResult.Abort;
            }
        }
    }
}
