using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DataTire;
using Digiteq_Logic; using SEACC.WinFormControls.Forms;

namespace Digiteq
{
    public partial class frm_bpsChequeDeposit : SEACC_Form
    {
        bool bActiveDateValidation = false;

        
        public DataTable dtChequeDeposit = new DataTable();
 

        #region Form load
        public frm_bpsChequeDeposit()
        {
            InitializeComponent();
        }
        public frm_bpsChequeDeposit(FormName _enmForm)
        {
            enmForm = _enmForm;
            InitializeComponent();
            Initialize();
            dgvDetail.AutoGenerateColumns = false;
        }

        private void frm_bpsChequeDeposit_Load(object sender, EventArgs e)
        {
            SetVisibility_ActionButons(true, false, false, true, false, false, false, false, false);
            Refresh_BranchCmb();
            ClearFields();
        }
        #endregion

        #region Btn New
        private void frm_bpsChequeDeposit_SF_newButton_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Save
        private void frm_bpsChequeDeposit_SF_saveButton_Click(object sender, EventArgs e)
        {
            if (CheckValidityDeposit_EmptiField())
            {
                if (CheckNumberValidityDeposit())
                {
                    if (clsMethods_GL.CheckValidity_FinancialYear(dtpDepositDate.Value.Date))
                    {
                        if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                        {
                            if (CheckSelectedChequeCount())
                            {
                                if (CheckValidity_ChequeDepositPosting())
                                {
                                    try
                                    {
                                        Cursor = Cursors.WaitCursor;
                                        ValidateEmptyForeignKeyDeposit();

                                        txtDepositID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);
                                        if (clsValidate.CheckValidity_TransactionCodeLength(txtDepositID.Text)) //if (txtDepositID.TextLength > 0)
                                        {
                                            #region Deposit Header
                                            tbl_bpsChequeDeposit detail = new tbl_bpsChequeDeposit(txtDepositID.Text.Trim(), txtDepositRemark.Text.Trim(), dtpDepositDate.Value,
                                                                               decimal.Parse(txtCountChequeSelected.Text.Trim()), decimal.Parse(txtAmountChequeSelected.Text.Trim()), txtDepositAccountHolder.Text.Trim(),
                                                                               txtDepositAccountNo.Text.Trim(), lblDepositBankName.Tag.ToString(), lblDepositBranchName.Tag.ToString(), clsSecurity.UserIDLoged,
                                                                               clsSecurity.UserIDLoged, clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), false, false, clsSecurity.CompanyID, ((ComboBoxItem)cmbComBranch.SelectedItem).Value, false);
                                            detail.Insert();
                                            #endregion

                                            #region Cheque Deposit Detail
                                            foreach (DataGridViewRow row in dgvDetail.Rows)
                                            {
                                                try
                                                {
                                                    // decimal dChequeAmount = 0;

                                                    //  bool bIsSelected = false;
                                                    bool bIsSelected = clsValidate.ValidateGridValue(dgvDetail, "IsSelected", row.Index, false);
                                                    // try
                                                    // {
                                                    //     bIsSelected = bool.Parse(dgvDetail["IsSelected", row.Index].Value.ToString());
                                                    //    }
                                                    //   catch (Exception) { }

                                                    if (!bIsSelected)
                                                        continue;

                                                    //    string sRegisterCode = "";
                                                    //     if (dgvDetail["RegisterCode", row.Index].Value != null)
                                                    //         sRegisterCode = dgvDetail["RegisterCode", row.Index].Value.ToString();
                                                    string sRegisterCode = clsValidate.ValidateGridValue(dgvDetail, "RegisterCode", row.Index, "");
                                                    if (sRegisterCode.Length > 0)
                                                    {
                                                        int iChequeStatus = clsValidate.ValidateGridValue(dgvDetail, "chequeStatus_ID", row.Index, 0);
                                                        int iCompanyAccount_ID = clsGenaralName.getName_CompanyAccount_IDByAccountNo(txtDepositAccountNo.Tag.ToString());
                                                    
                                                        tbl_bpsChequeDeposit_Detail items = new tbl_bpsChequeDeposit_Detail(txtDepositID.Text.Trim(), sRegisterCode, dtpDepositDate.Value,
                                                            "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), clsSecurity.FinancialYearID, clsSecurity.CompanyID, (iChequeStatus == 0 ? false : true), "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), clsAutocode.getChequeStatusID((iChequeStatus == 0 ? ChequeStatus.Deposited : ChequeStatus.ReDeposited)), "default", "default", clsSecurity.getServerDateTime(), iCompanyAccount_ID, 1);
                                                        items.Insert();

                                                        //update Cheque Register

                                                        tbl_bpsChequeRegister register = tbl_bpsChequeRegister.Select(sRegisterCode);
                                                        if (register != null)
                                                        {
                                                            register.IsDepositted = true;
                                                            register.DateDeposited = dtpDepositDate.Value;
                                                            register.DepositedBank_ID = lblDepositBankName.Tag.ToString();
                                                            register.DepositedBranch_ID = lblDepositBranchName.Tag.ToString();
                                                            register.DepositedAccountNumber = txtDepositAccountNo.Text.Trim();
                                                            register.CompanyAccount_ID = iCompanyAccount_ID;
                                                            register.IsLocked = true;
                                                            register.DepositCount += 1;
                                                            register.ChequeStatus_ID = clsAutocode.getChequeStatusID((iChequeStatus == 0 ? ChequeStatus.Deposited : ChequeStatus.ReDeposited));//clsAutocode.getChequeStatusID(ChequeStatus.Deposited);
                                                            register.PostingStatus_ID2 = clsAutocode.getGLPostingStatusID(GLPostingStatus.Posted);
                                                          //  clsDB.update_CustomerDeposittedCheques(register.Customer_ID, register.Amount, register.AccountNumber);
                                                            register.Update();

                                                            if (iChequeStatus == 4)
                                                            {
                                                                #region Credit Note Creatation
                                                                string sCRN_ID = clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.bssCreditNote));

                                                                //   tbl_bpsCreditNote oldCreditNote = tbl_bpsCreditNote.Select(sCRN_ID);
                                                                //  if (oldCreditNote == null)
                                                                //   {
                                                                tbl_bpsCreditNote cNote = new tbl_bpsCreditNote(sCRN_ID, clsSecurity.getServerDateTime(), "", "default",
                                                                "default", register.Customer_ID, "default", register.OrderRefNo_ID, register.ChequeRegister_ID, clsAutocode.getCreditNoteTypeID(CreditNoteType.ReturnedChequeDeposit),
                                                                "default", clsAutocode.getGLPostingStatusID(GLPostingStatus.NewTransaction), clsSecurity.FinancialYearID, clsConfig.sLocalCurrencyCode, "default", 1,
                                                                0, 0, 0, 0, register.Amount, 0, 0, 0, 0, register.Amount, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, clsSecurity.UserIDLoged,
                                                                clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID, clsSecurity.TerminalID,
                                                                clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), false, false, false, false, false, false, 0, false, 0, clsSecurity.CompanyID, clsSecurity.BranchID, false, (-1), (-1));
                                                                cNote.Insert();


                                                                foreach (tbl_sasInvoice oInvoice in tbl_sasInvoice.SelectAllByChequeRegister_ID(register.ChequeRegister_ID).Where(p => p.Invoice_ID != "default" && p.SeattleAmount == 0 && !p.IsDeleted && !p.IsSeattled && p.IsReturnedCheque))
                                                                {
                                                                    decimal dAllocatedAmmount = oInvoice.GrandTotal;
                                                                    string sFormConfigCode1 = clsAutocode.getFormConfigCode(FormName.CreditNoteAllocation);
                                                                    string sAllocationID = clsAutocode.getAutoGeneratedCode(sFormConfigCode1);

                                                                    dAllocatedAmmount = dAllocatedAmmount > 0 ? dAllocatedAmmount : 0;
                                                                    dAllocatedAmmount = clsHelpMethods.AutoSettledInvoiceWithCreditNote(oInvoice.Invoice_ID, sCRN_ID, dAllocatedAmmount, sAllocationID, false, false);

                                                                    tbl_bpsCreditNote_Invoice oCrnInv = tbl_bpsCreditNote_Invoice.Select(sCRN_ID, row.Index);
                                                                    if (oCrnInv != null)
                                                                    {
                                                                        oCrnInv.AlocatedAmount = dAllocatedAmmount;
                                                                        oCrnInv.Update();
                                                                    }
                                                                }
                                                                // }
                                                                // else
                                                                //      MessageBox.Show("Credit Note No is Already Taken......!", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
                                                                #endregion
                                                                clsMethods_GL.PostTransaction_chequeReDeposit(txtDepositID.Text.Trim(), sRegisterCode, dtpDepositDate.Value, register.Amount, txtDepositAccountNo.Text);
                                                            }
                                                            else
                                                            {
                                                                clsMethods_GL.PostTransaction_chequeDeposit(txtDepositID.Text.Trim(), sRegisterCode, dtpDepositDate.Value, register.Amount, txtDepositAccountNo.Text);
                                                                //    dChequeAmount = register.Amount;
                                                            }
                                                        }
                                                    }


                                                }
                                                catch (Exception ex)
                                                {
                                                    SEACCException.Show(ex);
                                                    clsValidate.WriteErrorLog("", iFormID, ex);
                                                }
                                            }
                                            #endregion
                                            MessageBox.Show("Record Saved Successfully....\nPlease Write Down The Deposit Reference Number In Your Bank Slip \n\nCHEQUE DEPOSIT REF NO : " + txtDepositID.Text.Trim(), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                        }
                                        //else
                                        //    MessageBox.Show("Cheque Deposit " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                    catch (Exception ex)
                                    {
                                        clsValidate.WriteErrorLog("", iFormID, ex);
                                        SEACCException.Show(ex);
                                    }
                                    finally
                                    {
                                        Cursor = Cursors.Default;
                                        ClearFields();
                                    }
                                }
                            }
                            else
                                MessageBox.Show("please Select the Cheques");
                        }
                    }
                }
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            lblDepositBankName.Tag = null;
            lblDepositBranchName.Tag = null;
            txtDepositAccountNo.Tag = null;

            txtDepositAccountHolder.Clear();
            txtDepositAccountNo.Clear();
            lblDepositBankName.Text = "";
            lblDepositBranchName.Text = "";
            txtDepositRemark.Clear();

            dtpDepositDate.Value = clsSecurity.getServerDateTime();

            txtCountChequeSelected.Text = "0";
            txtAmountChequeSelected.Text = "0.00";

            clsCommon.SetEnableDisable_NormalTextbox(txtFillter, true);

            RefreshGridAllForChequeDeposit();
        }
        #endregion
        private void RefreshGridAllForChequeDeposit()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dgvDetail.Columns["Sdate"].ValueType = typeof(DateTime);
                dtChequeDeposit.Rows.Clear();

                dtChequeDeposit.Merge(DBHandling.ExecQuery("exec sp_PReg_ChequesToBeDeposit '" + clsSecurity.CompanyID + "','" + ((ComboBoxItem)cmbComBranch.SelectedItem).Value + "','"+ clsSecurity.UserIDLoged+"'").Tables[0]);
                dgvDetail.DataSource = dtChequeDeposit;

                dgvDetail.Sort(this.dgvDetail.Columns["Sdate"], ListSortDirection.Ascending);
                //MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToRead), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                CalculateCheque();
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
            finally { Cursor = Cursors.Default; }

        }
        private void CalculateCheque()
        {
            try
            {
                int iCount = 0;
                decimal dAmount = 0;
                foreach (DataGridViewRow row in dgvDetail.Rows)
                {
                    try
                    {
                        if (dgvDetail["RegisterCode", row.Index].Value != null && dgvDetail["RegisterCode", row.Index].Value.ToString().Length > 0)
                        {
                            iCount++;
                            if (dgvDetail["Amount", row.Index].Value != null && dgvDetail["Amount", row.Index].Value.ToString().Length > 0 && clsCommon.isCurrency(dgvDetail["Amount", row.Index].Value.ToString()))
                                dAmount += decimal.Parse(dgvDetail["Amount", row.Index].Value.ToString());
                        }
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID, ex);
                        SEACCException.Show(ex);
                    }
                }
                txtAmountCheques.Text = clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
                txtCountCheques.Text = iCount.ToString();
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }

        }

        private void Refresh_BranchCmb()
        {
            cmbComBranch.Items.Clear();
            cmbComBranch.DisplayMember = "Value";
            cmbComBranch.ValueMember = "Text";

            foreach (tbl_genCompanyBranchMaster oDetail in tbl_genCompanyBranchMaster.SelectAll())
            {
                if (oDetail.CompanyBranch_ID != "default")
                    cmbComBranch.Items.Add(new ComboBoxItem(oDetail.CompanyBranch_ID, oDetail.BranchName));
            }
            if (cmbComBranch.Items.Count > 0)
                cmbComBranch.SelectedIndex = cmbComBranch.FindStringExact(clsSecurity.BranchName);
        }


        private void dgvDetail_CellMouseMove(object sender, DataGridViewCellMouseEventArgs e)
        {
            string sColName = "";
            DataGridView dgv = (DataGridView)sender;
            if (e.ColumnIndex >= 0)
                sColName = dgv.Columns[e.ColumnIndex].Name;


            if (sColName == "RegisterCode" || sColName == "RTSRegisterCode" || sColName == "ReceiptID")
                Cursor = Cursors.Hand;
        }


        private void dgvDetail_CellMouseLeave(object sender, DataGridViewCellEventArgs e)
        {
            Cursor = Cursors.Default;
        }

        private void dgvDetail_CellMouseClick(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                if (e.ColumnIndex >= 0)
                    sColName = dgvDetail.Columns[e.ColumnIndex].Name;

                if (sColName == "RegisterCode" || sColName == "RTSRegisterCode")
                {
                    string sRegisterID = dgvDetail[e.ColumnIndex, e.RowIndex].Value.ToString();
                    tbl_bpsChequeRegister detail = tbl_bpsChequeRegister.Select(sRegisterID);
                    if (detail != null)
                    {
                        frm_bpsChequeViewer cheque = new frm_bpsChequeViewer();
                        cheque.glbChequeRegisterID = detail.ChequeRegister_ID;
                        cheque.ShowDialog();
                    }
                }

                else if (sColName == "ReceiptID" || sColName == "RTSReceiptID")
                {
                    string sReceiptID = dgvDetail[e.ColumnIndex, e.RowIndex].Value.ToString();
                    tbl_bpsReceipt detail = tbl_bpsReceipt.Select(sReceiptID);
                    if (detail != null)
                    {
                        if (detail.IsSalesReceipt)
                        {
                            UC_bpsReceiptSales cheque = new UC_bpsReceiptSales(FormName.UCReceipt);
                          
                            cheque.glbReceiptID = detail.Receipt_ID;
                            clsHelpMethods_Local.DisplayForm(cheque, clsFormatter.colorBills, (this.Parent as Form).MdiParent);
                            //cheque.ShowDialog();
                        }
                        else
                        {
                            // frm_bpsReceipt_Interim cheque = new frm_bpsReceipt_Interim();
                            // cheque.gReceiptID = detail.Receipt_ID;
                            // cheque.ShowDialog();
                        }
                    }
                }
                else if (sColName == "IsSelected")
                {
                    bool bstatus = clsValidate.ValidateGridValue(dgvDetail, "IsSelected", e.RowIndex, false);
                    // if (bstatus)
                    dgvDetail[e.ColumnIndex, e.RowIndex].Value = !bstatus;

                    calculateSelectedCheques();
                }
            }
        }

        private void calculateSelectedCheques()
        {

            int iCount = 0;
            decimal dAmount = 0;
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                try
                {
                    if (dgvDetail["IsSelected", row.Index].Value != null && dgvDetail["IsSelected", row.Index].Value.ToString().Length > 0)
                    {
                        if (bool.Parse(dgvDetail["IsSelected", row.Index].Value.ToString()) == true)
                        {
                            iCount++;
                            if (dgvDetail["Amount", row.Index].Value != null && dgvDetail["Amount", row.Index].Value.ToString().Length > 0 && clsCommon.isCurrency(dgvDetail["Amount", row.Index].Value.ToString()))
                                dAmount += decimal.Parse(dgvDetail["Amount", row.Index].Value.ToString());
                        }
                    }
                }
                catch (Exception ex)
                {
                    clsValidate.WriteErrorLog("", iFormID, ex);
                    SEACCException.Show(ex);
                }
            }
            txtAmountChequeSelected.Text = clsFormatter.FormatToCurrecyWithThousendSep(dAmount);
            txtCountChequeSelected.Text = iCount.ToString();
        }

        #region Selected Chques Count
        private bool CheckSelectedChequeCount()
        {
            bool bStatus = true, bSelected = false;
            int ValiedRowCount = 0;

            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                DateTime sTxnDate = clsValidate.ValidateGridValue(dgvDetail, "dateCheque", row.Index, DateTime.Now);
                 bSelected = clsValidate.ValidateGridValue(dgvDetail, "IsSelected", row.Index, false);
                if (bSelected)
                {
                    if (bActiveDateValidation)
                    {
                        if (sTxnDate.Date <= dtpDepositDate.Value.Date)
                        {
                            ValiedRowCount++;
                        }
                        else
                        {
                            MessageBox.Show("Invalied Deposit     date......!", "Validation Error");
                            return false;
                        }
                    }
                    else
                        ValiedRowCount++;
                }
                if (ValiedRowCount == 0)
                    bStatus = false;

            }
            return bStatus;
        }
        #endregion



        #region Check Validity
        private bool CheckValidityDeposit_EmptiField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtDepositAccountNo, "Account Number"))
            {
                //if (clsValidate.ValidateTextBox_EmptyValue(lblDepositBankName, "Bank Name"))
                bStatus = true;
            }
            return bStatus;
        }
        private bool CheckNumberValidityDeposit()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {
                if (!clsCommon.isCurrency(txtCountChequeSelected.Text.Trim()))
                {
                    strMessage += "\n Selected Cheque Count";
                    bStatus = false;
                }
                if (!clsCommon.isCurrency(txtAmountChequeSelected.Text.Trim()))
                {
                    strMessage += "\n Selected Cheque Amount";
                    bStatus = false;
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }

            if (bStatus == false)
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

            return bStatus;
        }
        private bool CheckValidity_ChequeDepositPosting()
        {
            bool bStatus = false;
            if (clsConfig.bAutoPostingEnable)
            {
                bool bSlotStatus_Bank = clsMethods_GL.CheckAccountLink_Bank(txtDepositAccountNo.Text);
                bool bSlotStatus_ChequeDeposit = clsMethods_GL.CheckAccountLink(AccSlot.ChequeDeposit, true);
                bool bSlotStatus_ChequeREDeposit = clsMethods_GL.CheckAccountLink(AccSlot.ChequeReDeposit, true);

                if (bSlotStatus_Bank && bSlotStatus_ChequeDeposit && bSlotStatus_ChequeREDeposit)
                    bStatus = true;
            }
            else
                bStatus = true;
            return bStatus;
        }

        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKeyDeposit()
        {
            clsCommon.ValidateForeignKey(ref lblDepositBankName);
            clsCommon.ValidateForeignKey(ref lblDepositBranchName);
            //clsCommon.ValidateForeignKey(ref txtCheckedBy);
            //clsCommon.ValidateForeignKey(ref txtApprovedBy);
        }
        #endregion

        private void txtDepositAccountNo_DoubleClick(object sender, EventArgs e)
        {
            Search_AccountForDeposit(txtDepositAccountNo, lblDepositBankName, lblDepositBranchName);
        }

        private void Search_AccountForDeposit(TextBox myTextBox, Label DepositBankName, Label DepositBranchName)
        {
            try
            {
                //Form frmhelpsearch = new frmSearchTransaction();

                //clsSearch.passValue_CompanyAccount();

                //frmhelpsearch.ShowDialog();
                //if (frmSearchTransaction.s_SearchID.Length > 0)
                //{
                //    if (frmSearchTransaction.s_SearchText.Length > 0)
                //        myTextBox.Text = frmSearchTransaction.s_SearchID;
                //    if (frmSearchTransaction.s_SearchID.Length > 0)
                //        myTextBox.Tag = frmSearchTransaction.s_SearchID;

                //    FillBankAndBranch(myTextBox.Tag.ToString(), DepositBankName, DepositBranchName);
                //}

                clsSearch.SearchMaster_CompanyAccount(ref myTextBox, "", "");
                if (myTextBox.Tag != null)
                    FillBankAndBranch(myTextBox.Tag.ToString(), DepositBankName, DepositBranchName);

            }

            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID, ex);
                SEACCException.Show(ex);
            }
        }

        private void FillBankAndBranch(string sAccountNo, Label DepositBankName, Label DepositBranchName)
        {
            try
            {
                tbl_genCompanyAccount Adetail = tbl_genCompanyAccount.Select(sAccountNo);

                tbl_zBank detail = tbl_zBank.Select(Adetail.Bank_ID);
                if (detail != null)
                {
                    DepositBankName.Text = detail.BankName;
                    DepositBankName.Tag = detail.Bank_ID;
                }
                tbl_zBankBranches details = tbl_zBankBranches.Select(Adetail.Branch_ID);
                if (detail != null)
                {
                    DepositBranchName.Text = details.BranchName;
                    DepositBranchName.Tag = details.Branch_ID;
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID, ex);
            }
        }

        private void txtGenChequeNo_KeyUp(object sender, KeyEventArgs e)
        {
            StringBuilder sFilter = new StringBuilder();
            sFilter.Append("ChequeNo Like '%" + txtFillter.Text.Trim() + "%' ");
            sFilter.Append("OR ChequeDate LIKE '%" + txtFillter.Text.Trim() + "%' ");
            sFilter.Append("OR CustomerName LIKE '%" + txtFillter.Text.Trim() + "%' ");
            sFilter.Append("OR ReceiptID LIKE '%" + txtFillter.Text.Trim() + "%' ");
            sFilter.Append("OR Amount LIKE '%" + txtFillter.Text.Trim() + "%' ");
            //   sTemp = " ChequeDate LIKE '%" + txtChequeDate.Text.Trim() + "%'";
            //   sTemp = " CustomerName LIKE '%" + txtCustomerID.Text.Trim() + "%'";
            //    sTemp = " ReceiptID LIKE '%" + txtReceiptID.Text.Trim() + "%'";
            // sTemp = " Amount LIKE '%" + txtAmount.Text.Trim() + "%'";
            dtChequeDeposit.DefaultView.RowFilter = sFilter.ToString();
        }

        private void cmbComBranch_SelectedIndexChanged(object sender, EventArgs e)
        {
            ClearFields();
        }
    }
}