//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Express.SAP.Reversal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="getPaymentReversal", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class zdocrevpost : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZzbapiAccDocumentRevPostOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public zdocrevpost() {
            this.Url = global::Express.SAP.Properties.Settings.Default.Express_SAP_Reversal_zdocrevpost;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZzbapiAccDocumentRevPostCompletedEventHandler ZzbapiAccDocumentRevPostCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZDOCREVPOST:ZzbapiAccDocumentRev" +
            "PostRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZzbapiAccDocumentRevPostResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZzbapiAccDocumentRevPostResponse ZzbapiAccDocumentRevPost([System.Xml.Serialization.XmlElementAttribute("ZzbapiAccDocumentRevPost", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZzbapiAccDocumentRevPost ZzbapiAccDocumentRevPost1) {
            object[] results = this.Invoke("ZzbapiAccDocumentRevPost", new object[] {
                        ZzbapiAccDocumentRevPost1});
            return ((ZzbapiAccDocumentRevPostResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZzbapiAccDocumentRevPostAsync(ZzbapiAccDocumentRevPost ZzbapiAccDocumentRevPost1) {
            this.ZzbapiAccDocumentRevPostAsync(ZzbapiAccDocumentRevPost1, null);
        }
        
        /// <remarks/>
        public void ZzbapiAccDocumentRevPostAsync(ZzbapiAccDocumentRevPost ZzbapiAccDocumentRevPost1, object userState) {
            if ((this.ZzbapiAccDocumentRevPostOperationCompleted == null)) {
                this.ZzbapiAccDocumentRevPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZzbapiAccDocumentRevPostOperationCompleted);
            }
            this.InvokeAsync("ZzbapiAccDocumentRevPost", new object[] {
                        ZzbapiAccDocumentRevPost1}, this.ZzbapiAccDocumentRevPostOperationCompleted, userState);
        }
        
        private void OnZzbapiAccDocumentRevPostOperationCompleted(object arg) {
            if ((this.ZzbapiAccDocumentRevPostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZzbapiAccDocumentRevPostCompleted(this, new ZzbapiAccDocumentRevPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZzbapiAccDocumentRevPost {
        
        private string compCodeField;
        
        private string docNoField;
        
        private string fisPeriodField;
        
        private string fiscalYearField;
        
        private ZfiReturn1[] itReturnField;
        
        private string pstngDateField;
        
        private string revReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompCode {
            get {
                return this.compCodeField;
            }
            set {
                this.compCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FisPeriod {
            get {
                return this.fisPeriodField;
            }
            set {
                this.fisPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FiscalYear {
            get {
                return this.fiscalYearField;
            }
            set {
                this.fiscalYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZfiReturn1[] ItReturn {
            get {
                return this.itReturnField;
            }
            set {
                this.itReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PstngDate {
            get {
                return this.pstngDateField;
            }
            set {
                this.pstngDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RevReason {
            get {
                return this.revReasonField;
            }
            set {
                this.revReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiReturn1 {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZzbapiAccDocumentRevPostResponse {
        
        private ZfiReturn1[] itReturnField;
        
        private string objKeyField;
        
        private string objSysField;
        
        private string objTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZfiReturn1[] ItReturn {
            get {
                return this.itReturnField;
            }
            set {
                this.itReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObjKey {
            get {
                return this.objKeyField;
            }
            set {
                this.objKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObjSys {
            get {
                return this.objSysField;
            }
            set {
                this.objSysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObjType {
            get {
                return this.objTypeField;
            }
            set {
                this.objTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ZzbapiAccDocumentRevPostCompletedEventHandler(object sender, ZzbapiAccDocumentRevPostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZzbapiAccDocumentRevPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZzbapiAccDocumentRevPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZzbapiAccDocumentRevPostResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZzbapiAccDocumentRevPostResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591