exports.up = function (knex) {
  const data = [
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2100,
      parentCategoryType: 0,
      categoryTypeName: "Status",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Status",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Status is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 10,
    },

    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2101,
      parentCategoryType: 0,
      categoryTypeName: "Title",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Title",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Title is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 20,
    },

    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2102,
      parentCategoryType: 0,
      categoryTypeName: "Gender",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Gender",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Gender is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 30,
    },

    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2103,
      parentCategoryType: 0,
      categoryTypeName: "Marital Status",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Marital Status",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Marital Status is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 40,
    },

    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2104,
      parentCategoryType: 0,
      categoryTypeName: "Nationality",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Nationality",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Nationality is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 50,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2105,
      parentCategoryType: 0,
      categoryTypeName: "Religion",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Religion",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Religion is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 60,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2106,
      parentCategoryType: 0,
      categoryTypeName: "Blood Group",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Blood Group",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Blood Group is required" },
      },
      metaDesc: {
        name: "Description",
        type: "textarea",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        // isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 70,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2120,
      parentCategoryType: 0,
      categoryTypeName: "Region",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Region",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Region is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 79,
    },

    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2107,
      parentCategoryType: 2120,
      categoryTypeName: "Country",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "ISO‑2",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "ISO‑2 is required" },
      },
      metaDesc: {
        name: "Country",
        type: "text",
        placeholder: "Country",
        initialValue: "",
        className: "col-12",
      },
      ref1: {
        name: "ISO‑3",
        type: "text",
        placeholder: "ISO‑3",
        initialValue: "",
        className: "col-md-6 col-12",
      },
      ref2: {
        name: "numeric",
        type: "text",
        placeholder: "numeric",
        initialValue: "",
        className: "col-md-6 col-12",
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 80,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2108,
      parentCategoryType: 0,
      categoryTypeName: "Province",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Province",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Province is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 90,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2109,
      parentCategoryType: 2108,
      categoryTypeName: "District",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "District",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "District is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 100,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2110,
      parentCategoryType: 2109,
      categoryTypeName: "City",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "City",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "City is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 110,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2111,
      parentCategoryType: 0,
      categoryTypeName: "Division",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Division",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Division is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 120,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2112,
      parentCategoryType: 0,
      categoryTypeName: "Department",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Department",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Department is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 130,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2113,
      parentCategoryType: 0,
      categoryTypeName: "Section",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Section",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Section is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 140,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2114,
      parentCategoryType: 0,
      categoryTypeName: "Sub Section",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Sub Section",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Sub Section is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 150,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2115,
      parentCategoryType: 0,
      categoryTypeName: "Designation",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Designation",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Designation is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 160,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2116,
      parentCategoryType: 0,
      categoryTypeName: "Recruitment Type",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Recruitment Type",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Recruitment Type is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 170,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2117,
      parentCategoryType: 0,
      categoryTypeName: "Payment Method",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Payment Method",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Payment Method is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 180,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2118,
      parentCategoryType: 0,
      categoryTypeName: "Bank",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Bank",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Bank is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 190,
    },
    {
      tenantId: 1,
      companyId: 1,
      categoryType: 2119,
      parentCategoryType: 2118,
      categoryTypeName: "Bank Branch",
      serialNo: 0,
      metaValue: {
        name: "value",
        type: "text",
        placeholder: "Bank Branch",
        initialValue: "",
        className: "col-md-9 col-sm-6 col-12",
        validation: { required: true, message: "Bank Branch is required" },
      },
      metaDesc: {
        name: "Description",
        type: "text",
        placeholder: "Description",
        initialValue: "",
        className: "col-12",
        isVisible: false,
      },
      Active: true,
      menuParentId: 160,
      icon: "",
      order: 200,
    },
  ];

  const mappedData = data.map(({ Active, ...item }) => ({
    ...item,
    isActive: Active
  }));

  return knex("conf_category").insert(mappedData);
};
exports.down = function (knex) {
  return knex("conf_category")
    .whereIn(
      "categoryType",
      [
        2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111,
        2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120,
      ],
    )
    .del();
};
