using DataTire;
using Digiteq_Logic;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Digiteq
{
    public partial class frmCompanyBankAccount : MettroForm
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //form manage
        string sFormConfigCode;
        public int iFormID;

        //for security handle
        public bool bNoAccess;

        public string sComID = "";
        #endregion

        #region Form Load
        public frmCompanyBankAccount()
        {
            iFormID = clsSecurity.getFormID(FormName.CompanyBankAcc);
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.CompanyBankAcc);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
                bNoAccess = true;

            InitializeComponent();
        }

        private void frmCompanyBankAccount_Load(object sender, EventArgs e)
        {
            clsFormatter.setFormatForm(this, "Company Bank Account", 1, iFormID);
            cusFormat();

            //string compnayID = clsSecurity.getRegDBComapanyName();
            //FillDetails(compnayID);
            RefreshGrid_Account();
            ClearFiled();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            try
            {
                Cursor = Cursors.Arrow;
                if (CheckValidity_EmptyField())
                {
                    if (CheckValidity_AccNoLength())
                    {
                        clsCommon.ValidateForeignKey(ref txtChequeFormat, -1);

                        string sAccountNo = txtAccountNo.Text;
                        string sBank = clsGenaralName.getShortName_Bank(txtBankID.Tag.ToString());

                        if (IsUpdate)
                        {
                            tbl_genCompanyAccount oAccount = tbl_genCompanyAccount.Select(int.Parse(txtAccountNo.Tag.ToString()));
                            if (oAccount != null)
                            {
                                tbl_genCompanyAccount account = new tbl_genCompanyAccount(int.Parse(txtAccountNo.Tag.ToString()), clsSecurity.CompanyID, sAccountNo, txtBankID.Tag.ToString(), txtBankBranchID.Tag.ToString(), 0, txtControlAccID.Tag.ToString(), txtPrefix.Text.Trim(), oAccount.Counter, oAccount.BankReconcilationCounter, int.Parse(txtChequeFormat.Tag.ToString()));
                                account.Update();

                                tbl_accGLMaster_Bank oBank = tbl_accGLMaster_Bank.Select(account.AccountNumber);
                                if (oBank != null)
                                {
                                    oBank.Delete();
                                }

                                tbl_accGLMaster_Bank oBank_GL = new tbl_accGLMaster_Bank(txtControlAccID.Tag.ToString(), sAccountNo, true);
                                oBank_GL.Insert();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtAccountNo.Text, TxnActivity.Update);
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        else
                        {
                            if (CheckValidityDuplicate_ControlAccount(sAccountNo))
                            {
                                if (CheckValidity_DuplicateAccountNo(sAccountNo))
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtAccountNo.Tag = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    if (sBank != null && txtPrefix.Text.Length == 0)
                                        txtPrefix.Text = sBank.Substring(0, 3) + sAccountNo.Substring(sAccountNo.Length - 4) + "/";

                                    tbl_genCompanyAccount account = new tbl_genCompanyAccount(int.Parse(txtAccountNo.Tag.ToString()), clsSecurity.CompanyID, sAccountNo, txtBankID.Tag.ToString(), txtBankBranchID.Tag.ToString(), 0, txtControlAccID.Tag.ToString(), txtPrefix.Text.Trim(), 1, 1, int.Parse(txtChequeFormat.Tag.ToString()));
                                    account.Insert();

                                    tbl_accGLMaster_Bank oBank = new tbl_accGLMaster_Bank(txtControlAccID.Tag.ToString(), sAccountNo, true);
                                    oBank.Insert();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtAccountNo.Text, TxnActivity.Insert);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                        }

                        #region MyRegion
                        //if (IsUpdate)
                        //{
                        //    tbl_accGLMaster_Bank oOldBank = tbl_accGLMaster_Bank.Select(sAccountNo);
                        //    tbl_genCompanyAccount oOldCom = tbl_genCompanyAccount.Select(int.Parse(txtAccountNo.Tag.ToString()));
                        //    if (oOldCom != null && oOldBank != null)
                        //    {
                        //        tbl_accGLMaster_Bank oBank = new tbl_accGLMaster_Bank(txtControlAccID.Tag.ToString(), sAccountNo, true);
                        //        oBank.Update();

                        //        tbl_genCompanyAccount account = new tbl_genCompanyAccount(int.Parse(txtAccountNo.Tag.ToString()), clsSecurity.CompanyID, sAccountNo, txtBankID.Tag.ToString(), txtBankBranchID.Tag.ToString(), 0, txtControlAccID.Tag.ToString(), txtPrefix.Text.Trim(), oOldCom.Counter);
                        //        account.Update();
                        //        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        //    }
                        //}
                        //else
                        //{
                        //    if (CheckValidity_DuplicateAccountNo(sAccountNo))
                        //    {
                        //        if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                        //            txtAccountNo.Tag = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                        //        if (sBank != null)
                        //            txtPrefix.Text = sBank.Substring(0, 3) + sAccountNo.Substring(sAccountNo.Length - 4) + "/";

                        //        tbl_accGLMaster_Bank oBank = new tbl_accGLMaster_Bank(txtControlAccID.Tag.ToString(), sAccountNo, true);
                        //        oBank.Insert();

                        //        tbl_genCompanyAccount account = new tbl_genCompanyAccount(int.Parse(txtAccountNo.Tag.ToString()), clsSecurity.CompanyID, sAccountNo, txtBankID.Tag.ToString(), txtBankBranchID.Tag.ToString(), 0, txtControlAccID.Tag.ToString(), txtPrefix.Text.Trim(), 1);
                        //        account.Insert();

                        //        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        //    }
                        //} 
                        #endregion

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
                RefreshGrid_Account();
                FillDetails(txtAccountNo.Text);
            }

        }
        #endregion

        #region Btn Cancel
        private void btnCancel_Click(object sender, EventArgs e)
        {
            try
            {
                if (CheckValidity_SelectBankAcc_Transaction())
                {
                    DialogResult msgResult = MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.AskForDelete, txtAccountNo.Text.Trim()), clsFormatter.GetMessageCaption(), MessageBoxButtons.YesNo, MessageBoxIcon.Stop);
                    if (msgResult == DialogResult.Yes)
                    {
                        tbl_genCompanyAccount detail = tbl_genCompanyAccount.Select(txtAccountNo.Text.ToString());
                        tbl_accGLMaster_Bank oBank = tbl_accGLMaster_Bank.Select(txtAccountNo.Text.ToString());
                        if (detail != null && oBank != null)
                        {
                            oBank.Delete();
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtAccountNo.Text, TxnActivity.Cancel);
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCException.Show(ex);
                clsValidate.WriteErrorLog("", iFormID,ex);
            }
            finally
            {
                RefreshGrid_Account();
                ClearFiled();
            }

        }


        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            RefreshGrid_Account();
            ClearFiled();
        }
        #endregion

        #region Datagrid Format
        private void cusFormat()
        {
            clsFormatter.ApplyGridFormat_New(dgvAccounts);
        }
        #endregion

        #region Clear Field
        private void ClearFiled()
        {
            IsUpdate = false;

            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtAccountNo, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtBankBranchID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtBankID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtControlAccID, true);

            clsCommon.SetEnableDisable_NormalTextbox(txtPrefix, true);

            txtAccountNo.Text = "";
            txtBankBranchID.Text = "";
            txtBankID.Text = "";
            txtControlAccID.Text = "";
            txtPrefix.Text = "";
            txtChequeFormat.Text = "";

            txtAccountNo.Tag = null;
            txtBankBranchID.Tag = null;
            txtBankID.Tag = null;
            txtControlAccID.Tag = null;
            txtPrefix.Tag = null;
            txtChequeFormat.Tag = null;

            if (clsConfig.bEnable_AutomatedChequePrint)
            {
                txtChequeFormat.Visible = true;
                lblChequeFormat.Visible = true;
            }
            else
            {
                txtChequeFormat.Visible = false;
                lblChequeFormat.Visible = false;

            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid_Account()
        {
            int iRow;
            dgvAccounts.Rows.Clear();

            foreach (tbl_genCompanyAccount oCompany in tbl_genCompanyAccount.SelectAll().Where(p => p.CompanyAccount_ID != -1))
            {
                string sGLID = "default";
                tbl_accGLMaster_Bank detail = tbl_accGLMaster_Bank.Select(oCompany.AccountNumber);
                if (detail != null && detail.Gl_ID != "default")
                {
                    sGLID = detail.Gl_ID;
                }

                dgvAccounts.Rows.Add();
                iRow = dgvAccounts.Rows.Count - 1;
                dgvAccounts["BankName", iRow].Value = clsGenaralName.getName_Bank(oCompany.Bank_ID);
                dgvAccounts["BranchName", iRow].Value = clsGenaralName.getName_BankBranch(oCompany.Branch_ID);
                dgvAccounts["AccountID", iRow].Value = oCompany.CompanyAccount_ID;
                dgvAccounts["AccountNo", iRow].Value = oCompany.AccountNumber;
                dgvAccounts["GLCode", iRow].Value = clsCommon.GetForeignKeyValue(clsGenaralName.getName_AccountName(sGLID));
                dgvAccounts["GLCode", iRow].Tag = clsCommon.GetForeignKeyValue(sGLID);
            }


            // List<tbl_accGLMaster_Bank> details = tbl_accGLMaster_Bank.SelectAll().Where(p => p.Gl_ID != "default").ToList();
            //foreach (tbl_accGLMaster_Bank detail in tbl_accGLMaster_Bank.SelectAll().Where(p => p.Gl_ID != "default"))
            //{
            //    tbl_genCompanyAccount oCompany = tbl_genCompanyAccount.Select( detail.AccountNumber);
            //    if (oCompany != null)
            //    {
            //        dgvAccounts.Rows.Add();
            //        iRow = dgvAccounts.Rows.Count - 1;
            //        dgvAccounts["BankName", iRow].Value = clsGenaralName.getName_Bank(oCompany.Bank_ID);
            //        dgvAccounts["BranchName", iRow].Value = clsGenaralName.getName_BankBranch(oCompany.Branch_ID);
            //        dgvAccounts["AccountID", iRow].Value = oCompany.CompanyAccount_ID;
            //        dgvAccounts["AccountNo", iRow].Value = detail.AccountNumber;
            //        dgvAccounts["GLCode", iRow].Value = clsCommon.GetForeignKeyValue(clsGenaralName.getName_AccountName(detail.Gl_ID));
            //        dgvAccounts["GLCode", iRow].Tag = clsCommon.GetForeignKeyValue(detail.Gl_ID);
            //    }
            //}            
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sAccountID)
        {
            txtControlAccID.Tag = null;
            txtControlAccID.Clear();

            if (sAccountID.Length > 0)
            {
                tbl_genCompanyAccount oCompany = tbl_genCompanyAccount.Select(sAccountID);
                if (oCompany != null)
                {
                    IsUpdate = true;
                    clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtAccountNo, false);

                    txtAccountNo.Tag = oCompany.CompanyAccount_ID;
                    txtAccountNo.Text = oCompany.AccountNumber;

                    txtBankBranchID.Tag = oCompany.Branch_ID;
                    txtBankBranchID.Text = clsGenaralName.getName_BankBranch(oCompany.Branch_ID);
                    txtBankID.Tag = oCompany.Bank_ID;
                    txtBankID.Text = clsGenaralName.getName_Bank(oCompany.Bank_ID);
                    txtPrefix.Tag = oCompany.Prefix;
                    txtPrefix.Text = oCompany.Prefix;

                    txtChequeFormat.Tag = oCompany.ChequeFormat_ID;
                    txtChequeFormat.Text = clsGenaralName.getChequeFormat_Code(oCompany.ChequeFormat_ID);

                    tbl_accGLMaster_Bank oBank = tbl_accGLMaster_Bank.Select(sAccountID);
                    if (oBank != null)
                    {
                        txtControlAccID.Tag = oBank.Gl_ID;
                        txtControlAccID.Text = clsGenaralName.getName_AccountName(oBank.Gl_ID);
                    }
                }
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtAccountNo, "Company Bank Account"))
                if (clsValidate.ValidateTextBox_EmptyValue(txtBankID, "Bank"))
                    if (clsValidate.ValidateTextBox_EmptyValue(txtBankBranchID, "Bank Branch"))
                        if (clsValidate.ValidateTextBox_EmptyValue(txtControlAccID, "Controll Account"))
                            bStatus = true;

            return bStatus;
        }

        private bool CheckValidity_AccNoLength()
        {
            bool bStatus = true;
            if (txtAccountNo.Text.Length < 4)
            {
                bStatus = false;
                MessageBox.Show("Please check Account No. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;
        }
        private bool CheckValidity_DuplicateAccountNo(string sAccountNo)
        {
            bool bStatus = true;

            tbl_accGLMaster_Bank oOldBank = tbl_accGLMaster_Bank.Select(sAccountNo);
            tbl_genCompanyAccount oOldCom = tbl_genCompanyAccount.Select(sAccountNo);
            //foreach (tbl_genCompanyAccount oOldCom in tbl_genCompanyAccount.SelectAll().Where(p => p.AccountNumber == sAccountNo))
            //{
            //    bStatus = false;
            //} 

            if (oOldCom != null || oOldBank != null)
                bStatus = false;

            if (bStatus == false)
                MessageBox.Show("This Account No. is already added. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

            return bStatus;
        }

        private bool CheckValidityDuplicate_ControlAccount(string sAccountNo)
        {
            bool bStatus = true;

            if (txtControlAccID.Tag.ToString() == "default")
            {
                bStatus = false;
                MessageBox.Show("Please add a Control Account .. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            else
            {
                List<tbl_accGLMaster_Bank> oBanks = tbl_accGLMaster_Bank.SelectAllByGl_ID(txtControlAccID.Tag.ToString()).ToList();
                if (oBanks.Count >= 1)
                {
                    bStatus = false;
                    MessageBox.Show("This Control Account is already added. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }

            return bStatus;
        }
        private bool CheckValidity_SelectBankAcc_Transaction()
        {
            bool bStatus = true;
            int iAccountNo = int.Parse(txtAccountNo.Tag.ToString());

            if (iAccountNo != null)
            {
                List<tbl_accChequeRegister> oAccCheq = tbl_accChequeRegister.SelectAll().Where(p => p.CompanyAccount_ID == iAccountNo).ToList();
                if (oAccCheq.Count > 0)
                    bStatus = false;

                List<tbl_bpsChequeRegister> oBpsCheq = tbl_bpsChequeRegister.SelectAll().Where(p => p.DepositedAccountNumber == txtAccountNo.Text.ToString()).ToList();
                if (oBpsCheq.Count > 0)
                    bStatus = false;

                if (bStatus == false)
                    MessageBox.Show("Already traded with this account. ", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;
        }
        #endregion

        #region Events Datagrid
        private void dgvAccounts_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0)
            {
                string sColName = "";
                if (e.ColumnIndex >= 0)
                    sColName = dgvAccounts.Columns[e.ColumnIndex].Name;

                if (sColName == "AccountNo" || sColName == "BankName" || sColName == "BranchName" || sColName == "GLCode")
                {
                    string sAccountNo = clsValidate.ValidateGridValue(dgvAccounts, "AccountNo", e.RowIndex, "");
                    if (sAccountNo != null)
                    {
                        FillDetails(sAccountNo);
                    }
                }
            }
        }
        #endregion

        #region Events Double Click
        private void txtAccountNo_DoubleClick(object sender, EventArgs e)
        {
            Search_CompanyAccount();
        }

        private void txtBankID_DoubleClick(object sender, EventArgs e)
        {
            Search_Bank();
        }

        private void txtBankBranchID_DoubleClick(object sender, EventArgs e)
        {
            Search_Branch(txtBankID.Tag.ToString());
        }

        private void txtControlAccID_DoubleClick(object sender, EventArgs e)
        {
            SearchAccountCode();
        }

        private void txtChequeFormat_DoubleClick(object sender, EventArgs e)
        {
            Search_ChequeFormat();
        }
        #endregion

        #region Events Key Down
        private void txtAccountNo_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
                Search_CompanyAccount();
        }

        private void txtBankID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
                Search_Bank();
        }

        private void txtBankBranchID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
                Search_Branch(txtBankID.Tag.ToString());
        }

        private void txtControlAccID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
                SearchAccountCode();
        }

        private void txtChequeFormat_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
                Search_ChequeFormat();
        }
        #endregion

        #region Search Methods
        private void Search_CompanyAccount()
        {
            clsSearch.SearchMaster_CompanyAccount(ref txtAccountNo, "", "");
            if (txtAccountNo.Text.Length > 0)
            {
                FillDetails(txtAccountNo.Tag.ToString());
            }
        }
        private void Search_Bank()
        {
            clsSearch.Search_Bank(ref txtBankID);
        }
        private void Search_Branch(string sBankID)
        {
            if (sBankID.Length <= 0)
                MessageBox.Show("Please Select the Bank Name First", clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            else
                clsSearch.Search_BankBranch(ref txtBankBranchID, sBankID);
        }
        private void SearchAccountCode()
        {
            try
            {
                clsSearch.Search_MasterAccountGLCode(ref txtControlAccID, "", clsAutocode.getControlAccount_Types(enum_ControlAccountType.Bank));
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_ChequeFormat()
        {
            clsSearch.Search_ChequeFormat(ref txtChequeFormat);
        }
        #endregion
    }
}