using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic; using SEACC.WinFormControls.Forms;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;


namespace Digiteq
{
    public partial class frmGroupApproval : Form
    {

        
        //to manage update and insert
        static bool IsUpdate = false;        
      
        //to keep form detail       
           public int iFormID;
        string sFormConfigCode;
        
        //for security handle
        public bool bNoAccess;
        public bool bHasChecked;
        public bool bHasApproved;
        DateTime glbApprovedDate = clsSecurity.getServerDateTime();
        DateTime glbCheckedDate = clsSecurity.getServerDateTime(); 

        public DataTable dtAllRecodes = new DataTable();
        private BindingSource source = new BindingSource();
        private string sFilteQuary = "";


        #region Form Load
        public frmGroupApproval()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.GroupApproval);
            iFormID = clsSecurity.getFormID(FormName.GroupApproval);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frmGroupApproval_Load(object sender, EventArgs e)
        {
            clsFormatter.setFormatForm(this, "Batch Approval ", 2, iFormID);
            ClearFields();
            FillDetailNotes();
            dgvDetail.DataSource = source;
            CusDataGridViewFormat();
            CreateDataTable();
        }
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
            FillDetailNotes();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {

               if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                {
                    try
                    {
                        Cursor = Cursors.WaitCursor;
                        ValidateEmptyForeignKey();
                        if (IsUpdate)  //update records
                        {

                        }
                        else  //insert records
                        {
                            #region Insert
                            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                txtCustomerOrderID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);                          

                            if (txtCustomerOrderID.TextLength > 0)
                            {
                                //Customer Order Header
                                tbl_sasBatchApproval detail = new tbl_sasBatchApproval(txtCustomerOrderID.Text.Trim(), dtpDatePreparedBy.Value, "",
                                     clsSecurity.UserIDLoged, clsSecurity.UserIDLoged, txtCheckedBy.Tag.ToString(), txtApprovedBy.Tag.ToString(), clsSecurity.getServerDateTime(),
                                    clsSecurity.getServerDateTime(), glbCheckedDate, glbApprovedDate, bHasChecked, bHasApproved, false, false, false);                               
                                detail.Insert();
                                //Customer Order Detail                                
                                foreach (DataGridViewRow row in dgvDetail.Rows)
                                {
                                    try
                                    {
                                        string sNoteID = "", sApprovalStatusID = "", sApprovalName = "";
                                        bool bApproved = false;
                                        if (dgvDetail["Approve", row.Index].Value != null)
                                            bApproved = bool.Parse(dgvDetail["Approve", row.Index].Value.ToString());

                                        sNoteID = clsValidate.ValidateGridValue(dgvDetail, "NoteNumber", row.Index, "default");
                                        sApprovalStatusID = clsValidate.ValidateGridValue(dgvDetail, "ApprovalStatusID", row.Index, "default");
                                        sApprovalName = clsValidate.ValidateGridValue(dgvDetail, "ApprovalStatus", row.Index, "default");


                                        if (sNoteID.Length > 0)
                                        {
                                            if (bApproved)
                                            {
                                                tbl_sasBatchApproval_Detail note = new tbl_sasBatchApproval_Detail(txtCustomerOrderID.Text.Trim(), sNoteID, sApprovalStatusID, bApproved);
                                                note.Insert();

                                                //update Notes
                                                if (chkInquiry.Checked && bApproved)
                                                    clsHelpMethods_Local.UpdateApprovalInquiry(sNoteID, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime());
                                                else if (chkCustomerOrder.Checked && bApproved)
                                                    clsHelpMethods_Local.UpdateApprovalCustomerOrder(sNoteID, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime());
                                                else if (chkDeliveryOrder.Checked && bApproved)
                                                    clsHelpMethods_Local.UpdateApprovalDeliveryOrder(sNoteID, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime());
                                                else if (chkInvoice.Checked && bApproved)
                                                    clsHelpMethods_Local.UpdateApprovalInvoice(sNoteID, clsSecurity.UserIDLoged, clsSecurity.getServerDateTime());
                                            }
                                        }
                                    }
                                    catch (Exception ex)
                                    {
                                        clsValidate.WriteErrorLog("", iFormID,ex);
                                        SEACCException.Show(ex);
                                    }//error may come because last row of the grid may not have information
                                }
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                            else
                            {
                                MessageBox.Show("Approval Note " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                            #endregion
                        }

                    }
                    catch (Exception ex)
                    {
                        SEACCException.Show(ex);
                        clsValidate.WriteErrorLog("", iFormID,ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Default;
                        ClearFields();
                        FillDetailNotes();
                    }
                }
            }

        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormatModify(dgvDetail, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour, clsFormatter.colorDigiteqTheamColorSales1BackColour);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCustomerOrderID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblCustomerOrderID, true);
            

            clsCommon.SetVisible_PermissionTextBox(txtDateApprovedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtTimeApprovedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtDateCheckedBy, true);
            clsCommon.SetVisible_PermissionTextBox(txtTimeCheckedBy, true);


            chkCustomerOrder.ForeColor = Color.Gray;
            chkDeliveryOrder.ForeColor = Color.Gray;
            chkInquiry.ForeColor = Color.Gray;
            chkInvoice.ForeColor = Color.Gray;
            chkQutation.ForeColor = Color.Gray;
            chkCheque.ForeColor = Color.Gray;
            chkReceipt.ForeColor = Color.Gray;
            chkSalesReturn.ForeColor = Color.Gray;
            chkCreditNote.ForeColor = Color.Gray;
            chkDebitNote.ForeColor = Color.Gray;

            chkCustomerOrder.Text = "Customer Order (0)";
            chkDeliveryOrder.Text = "Delivery Order (0)";
            chkQutation.Text = "Qutation (0)";
            chkInquiry.Text = "Inquiry (0)";
            chkInvoice.Text = "Invoice (0)";
            chkCheque.Text = "Cheque (0)";
            chkReceipt.Text = "Receipt (0)";
            chkSalesReturn.Text = "SalesReturn (0)";
            chkCreditNote.Text = "CreditNote (0)";
            chkDebitNote.Text = "DebitNote (0)";
            dtAllRecodes.Clear();

            txtApprovedBy.Clear();
            txtCheckedBy.Clear();
            txtPreparedBy.Clear();
            bHasApproved = false;
            bHasChecked = false;

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtCustomerOrderID.Text = "<Auto Generate>";
            else
                txtCustomerOrderID.Clear();
            if (txtCustomerOrderID.Enabled)
            {
                txtCustomerOrderID.SelectAll();
                txtCustomerOrderID.Focus();
            }
        }
        #endregion

        #region Fill Detail Note
        private void FillDetailNotes()
        {
            ClearFields();
            int InquiryCount = 0, CustomerOrderCount = 0, DeliveryOrderCount = 0, InvoiceCount = 0;

            InquiryCount = GetInquiryCount();
            CustomerOrderCount = GetCustomerOrderCount();
            DeliveryOrderCount = GetDeliveryOrderCount();
            InvoiceCount = GetInvoiceCount();

            if (InquiryCount > 0)
            {
                chkInquiry.ForeColor = Color.Red;
                chkInquiry.Text = "Inquiry  (" + InquiryCount + ")";
            }
            if (CustomerOrderCount > 0)
            {
                chkCustomerOrder.ForeColor = Color.Red;
                chkCustomerOrder.Text = "Customer Order (" + CustomerOrderCount + ")";
            }
            if (DeliveryOrderCount > 0)
            {
                chkDeliveryOrder.ForeColor = Color.Red;
                chkDeliveryOrder.Text = "Delivery Order (" + DeliveryOrderCount + ")";
            }
            if (InvoiceCount > 0)
            {
                chkInvoice.ForeColor = Color.Red;
                chkInvoice.Text = "Invoice (" + InvoiceCount + ")";
            }
        }
        #endregion

        #region Fill Datagrid
        private void Fill_Datagrid(int iRow, string CustomerID, string NoteNumber, decimal Amount)
        {
            try
            {
                dgvDetail["CustomerName", iRow].Value = clsGenaralName.getName_Customer(CustomerID);
                dgvDetail["PDCheques", iRow].Value = clsHelpMethods_Local.GetCustomerChequesInHand(CustomerID);
                dgvDetail["CrediteBalance", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerCreditBalance(CustomerID));
                dgvDetail["RCOutstandings", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_ReturnedCheque(CustomerID));
                dgvDetail["NoteNumber", iRow].Value = NoteNumber.ToString();
                dgvDetail["Amount", iRow].Value = clsFormatter.FormatToCurrecyWithThousendSep(Amount);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGridInquiry()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dtAllRecodes.Clear();                
                dgvDetail.Columns["CustomerName"].Width = 225;
                List<tbl_sasInquiry> details = tbl_sasInquiry.SelectAll();
                foreach (tbl_sasInquiry detail in details)
                {
                    if (detail.Inquiry_ID != "default" && detail.IsApproved == false && detail.IsDeleted != true)
                    {
                        string sCustomerID,sCustomerName, sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount;

                        sCustomerID = detail.Customer_ID;
                        sCustomerName = clsGenaralName.getName_Customer(detail.Customer_ID);
                        sPDCheques = clsHelpMethods_Local.GetCustomerChequesInHand(detail.Customer_ID).ToString();
                        sCrediteBalance = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_All(detail.Customer_ID));
                        sRCOutstandings = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_ReturnedCheque(detail.Customer_ID));
                        sNoteNumber = detail.Inquiry_ID;
                        sAmount = clsFormatter.FormatToCurrecyWithThousendSep(detail.GrandTotal);
                        
                        dtAllRecodes.Rows.Add(sCustomerID,sCustomerName, sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount);
                    }
                }
                source.DataSource = dtAllRecodes;
                if (source.Count > 19)
                    dgvDetail.Columns["CustomerName"].Width -= 17;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        private void RefreshGridCustomerOrder()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dtAllRecodes.Clear();               
                dgvDetail.Columns["CustomerName"].Width = 225;              
                List<tbl_sasCustomerOrder> details = tbl_sasCustomerOrder.SelectAll();
                foreach (tbl_sasCustomerOrder detail in details)
                {
                    if (detail.CustomerOrder_ID != "default" && detail.IsApproved == false && detail.IsDeleted != true)
                    {
                        string sCustomerID,sCustomerName,sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount;

                        sCustomerID = detail.Customer_ID;
                        sCustomerName = clsGenaralName.getName_Customer(detail.Customer_ID);                        
                        sPDCheques = clsHelpMethods_Local.GetCustomerChequesInHand(detail.Customer_ID).ToString();
                        sCrediteBalance = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_All(detail.Customer_ID));
                        sRCOutstandings = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_ReturnedCheque(detail.Customer_ID));
                        sNoteNumber = detail.CustomerOrder_ID;
                        sAmount = clsFormatter.FormatToCurrecyWithThousendSep(detail.GrandTotal);

                        dtAllRecodes.Rows.Add(sCustomerID,sCustomerName,sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount);
                    }
                }
                source.DataSource = dtAllRecodes;
                if (source.Count > 19)
                    dgvDetail.Columns["CustomerName"].Width -= 17;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        private void RefreshGridDeliveryOrder()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dtAllRecodes.Clear();             
                dgvDetail.Columns["CustomerName"].Width = 225;
                List<tbl_sasDeliveryOrder> details = tbl_sasDeliveryOrder.SelectAll();
                foreach (tbl_sasDeliveryOrder detail in details)
                {
                    if (detail.DeliveryOrder_ID != "default" && detail.IsApproved == false && detail.IsDeleted != true)
                    {
                        string sCustomerID, sCustomerName, sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount;

                        sCustomerID = detail.Customer_ID;
                        sCustomerName = clsGenaralName.getName_Customer(detail.Customer_ID);
                        sPDCheques = clsHelpMethods_Local.GetCustomerChequesInHand(detail.Customer_ID).ToString();
                        sCrediteBalance = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_All(detail.Customer_ID));
                        sRCOutstandings = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_ReturnedCheque(detail.Customer_ID));
                        sNoteNumber = detail.DeliveryOrder_ID;
                        sAmount = clsFormatter.FormatToCurrecyWithThousendSep(detail.GrandTotal);

                        dtAllRecodes.Rows.Add(sCustomerID,sCustomerName,sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount);
                    }
                }

                source.DataSource = dtAllRecodes;
                if (source.Count > 19)
                    dgvDetail.Columns["CustomerName"].Width -= 17;

            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        private void RefreshGridInvoice()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                dtAllRecodes.Clear();          
                dgvDetail.Columns["CustomerName"].Width = 225;
                List<tbl_sasInvoice> details = tbl_sasInvoice.SelectAll();
                foreach (tbl_sasInvoice detail in details)
                {
                    if (detail.Invoice_ID != "default" && detail.IsApproved == false && detail.IsDeleted != true)
                    {
                        string sCustomerID, sCustomerName, sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount;

                        sCustomerID = detail.Customer_ID;
                        sCustomerName = clsGenaralName.getName_Customer(detail.Customer_ID);
                        sPDCheques = clsHelpMethods_Local.GetCustomerChequesInHand(detail.Customer_ID).ToString();
                        sCrediteBalance = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_All(detail.Customer_ID));
                        sRCOutstandings = clsFormatter.FormatToCurrecyWithThousendSep(clsHelpMethods_Local.GetCustomerTotalDues_ReturnedCheque(detail.Customer_ID));
                        sNoteNumber = detail.Invoice_ID;
                        sAmount = clsFormatter.FormatToCurrecyWithThousendSep(detail.GrandTotal);
                        dtAllRecodes.Rows.Add(sCustomerID, sCustomerName, sPDCheques, sCrediteBalance, sRCOutstandings, sNoteNumber, sAmount);
                    }
                }
                source.DataSource = dtAllRecodes;
                if (source.Count > 19)
                    dgvDetail.Columns["CustomerName"].Width -= 17;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }
        private void CreateDataTable()
        {
            dtAllRecodes.Columns.Clear();
            dtAllRecodes.Columns.Add("CustomerID", typeof(string));
            dtAllRecodes.Columns.Add("CustomerName", typeof(string));
            dtAllRecodes.Columns.Add("PDCheques", typeof(string));
            dtAllRecodes.Columns.Add("CrediteBalance", typeof(string));
            dtAllRecodes.Columns.Add("RCOutstandings", typeof(string));
            dtAllRecodes.Columns.Add("NoteNumber", typeof(string));
            dtAllRecodes.Columns.Add("Amount", typeof(string));
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

           
          
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion


        #region Pending Approved Count
        private int GetInquiryCount()
        {
            int Count = 0;
            try
            {
                List<tbl_sasInquiry> details = tbl_sasInquiry.SelectAll();
                foreach (tbl_sasInquiry detail in details)
                {
                    if (detail.IsApproved == false && detail.IsDeleted == false && detail.Inquiry_ID != "default")
                    {
                        Count++;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return Count;
        }
        private int GetCustomerOrderCount()
        {
            int Count = 0;
            try
            {
                List<tbl_sasCustomerOrder> details = tbl_sasCustomerOrder.SelectAll();
                foreach (tbl_sasCustomerOrder detail in details)
                {
                    if (detail.IsApproved == false && detail.IsDeleted == false && detail.CustomerOrder_ID != "default")
                    {
                        Count++;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return Count;
        }
        private int GetDeliveryOrderCount()
        {
            int Count = 0;
            try
            {
                List<tbl_sasDeliveryOrder> details = tbl_sasDeliveryOrder.SelectAll();
                foreach (tbl_sasDeliveryOrder detail in details)
                {
                    if (detail.IsApproved == false && detail.IsDeleted == false && detail.DeliveryOrder_ID != "default")
                    {
                        Count++;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return Count;
        }
        private int GetInvoiceCount()
        {
            int Count = 0;
            try
            {
                List<tbl_sasInvoice> details = tbl_sasInvoice.SelectAll();
                foreach (tbl_sasInvoice detail in details)
                {
                    if (detail.IsApproved == false && detail.IsDeleted == false && detail.Invoice_ID != "default")
                    {
                        Count++;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            return Count;
        } 
        #endregion


        #region Events CheckedChanged
        private void chkInquiry_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            RefreshGridInquiry();
        }
        private void chkQutation_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }
        private void chkCustomerOrder_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            RefreshGridCustomerOrder();
        }
        private void chkDeliveryOrder_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            RefreshGridDeliveryOrder();
        }
        private void chkInvoice_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            RefreshGridInvoice();
        }
        private void chkCheque_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }
        private void chkReceipt_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }
        private void chkSalesReturn_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }
        private void chkCreditNote_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }
        private void chkDebitNote_CheckedChanged(object sender, EventArgs e)
        {
            FormatForcusedCheckBox(((Control)sender).Name.ToString().Trim());
            ClearFields();
            FillDetailNotes();
        }

        private void chkCustomerName_CheckedChanged(object sender, EventArgs e)
        {
            if (chkCustomerName.Checked)
            {
                txtCustomerID.Enabled = false;
            }
            else
            {
                txtCustomerID.Enabled = true;
                txtCustomerID.Text = "";
                sFilteQuary = "";
                createFilterQuary(txtCustomerID);
            }
        }
        private void chkAmount_CheckedChanged(object sender, EventArgs e)
        {
            if (chkAmount.Checked)
            {
                txtAmount.Enabled = false;
            }
            else
            {
                txtAmount.Enabled = true;
                txtAmount.Text = "";
                sFilteQuary = "";
                createFilterQuary(txtAmount);
            }
        }
        private void chkNoteID_CheckedChanged(object sender, EventArgs e)
        {
            if (chkNoteID.Checked)
            {
                txtNoteID.Enabled = false;
            }
            else
            {
                txtNoteID.Enabled = true;
                txtNoteID.Text = "";
                sFilteQuary = "";
                createFilterQuary(txtNoteID);
            }
        } 
        #endregion

        #region BindingSource Filtering
        private void createFilterQuary(TextBox argText)
        {
            string sTemp = "";
            string sFinalQuary = "";
            //iGridCount = 1;

            if (chkCustomerName.Checked && argText.Name != "txtCustomerID")
            {
                if (sFilteQuary.Trim().Length > 0)
                    sFilteQuary += " AND CustomerName LIKE '%" + txtCustomerID.Text.Trim() + "%'";
                else
                    sFilteQuary = " CustomerName LIKE '%" + txtCustomerID.Text.Trim() + "%'";
            }
            if (chkNoteID.Checked && argText.Name != "txtNoteID")
            {
                if (sFilteQuary.Trim().Length > 0)
                    sFilteQuary += " AND NoteNumber LIKE '%" + txtNoteID.Text.Trim() + "%'";
                else
                    sFilteQuary = " NoteNumber LIKE '%" + txtNoteID.Text.Trim() + "%'";
            }
            if (chkAmount.Checked && argText.Name != "txtAmount")
            {
                if (sFilteQuary.Trim().Length > 0)
                    sFilteQuary += " AND Amount LIKE '%" + txtAmount.Text.Trim() + "%'";
                else
                    sFilteQuary = " Amount LIKE '%" + txtAmount.Text.Trim() + "%'";
            }

            if (argText.Name == "txtCustomerID")
                sTemp = " CustomerName LIKE '%" + txtCustomerID.Text.Trim() + "%'";
            if (argText.Name == "txtNoteID")
                sTemp = " NoteNumber LIKE '%" + txtNoteID.Text.Trim() + "%'";
            if (argText.Name == "txtAmount")
                sTemp = " Amount LIKE '%" + txtAmount.Text.Trim() + "%'";


            if (sTemp.Trim().Length > 0)
            {
                if (sFilteQuary.Trim().Length > 0)
                {
                    sFinalQuary = sFilteQuary + " AND " + sTemp;
                }
                else
                {
                    sFinalQuary = sTemp;
                }
            }
            source.Filter = "";
            if (sFinalQuary.Trim().Length > 0)
                source.Filter = sFinalQuary;
            else
                source.Filter = sTemp;
        }
        #endregion

        #region Event Key Up
        private void txtCustomerID_KeyUp(object sender, KeyEventArgs e)
        {
            createFilterQuary(txtCustomerID);
        }
        private void txtInvoiceID_KeyUp(object sender, KeyEventArgs e)
        {
            createFilterQuary(txtNoteID);
        }
        private void txtAmount_KeyUp(object sender, KeyEventArgs e)
        {
            createFilterQuary(txtAmount);
        } 
        #endregion

        #region Cell Double Click
        private void dgvDetail_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            string sColName = "";
            if (e.ColumnIndex >= 0)
                sColName = dgvDetail.Columns[e.ColumnIndex].Name;

            if (sColName == "CustomerName" || sColName == "PDCheques" || sColName == "CrediteBalance" || sColName == "RCOutstandings")
            {
                frm_sasViewerCustomer frm = new frm_sasViewerCustomer();
                frm.glbCustomerID = dgvDetail["CustomerID", e.RowIndex].Value.ToString();
                frm.ShowDialog();
            }
            else if (sColName == "NoteNumber" || sColName == "Amount")
            {
               DisplayNoteView(dgvDetail["NoteNumber", e.RowIndex].Value.ToString());
            }
            else if (sColName == "ApprovalStatus")
            {
                Form frmhelpsearch = new frmSearchMaster();
                //clsSearch.passValue_Section();
                frmSearchMaster.s_TableName = "tbl_zBatchApprovalStatus";
                frmSearchMaster.s_Columns = " batchApprovalStatus_ID Status_ID, batchApprovalStatus StatusName ";
                frmSearchMaster.i_ColumnWidth = new int[] { 100, 250 };
                frmSearchMaster.s_Criteria = "batchApprovalStatus_ID != 'default'";

                frmhelpsearch.ShowDialog();
                if (frmSearchMaster.s_SearchText.Length > 0)
                    dgvDetail["ApprovalStatus", e.RowIndex].Value = frmSearchMaster.s_SearchText;
                if (frmSearchMaster.s_SearchID.Length > 0)
                    dgvDetail["ApprovalStatusID", e.RowIndex].Tag = frmSearchMaster.s_SearchID;
            }
        }
        #endregion

        #region Format Forcused CheckBox
        private void FormatForcusedCheckBox(string radioButtonName)
        {
            Color cSelectedColor = Color.FromArgb(215, 215, 0), cUnSelectedColor = Color.FromArgb(250, 244, 133);            
            foreach (Control con in flpNotes.Controls)
            {
                if (con is RadioButton)
                {
                    if (con.Name == radioButtonName)
                        con.BackColor = cSelectedColor;
                    else
                        con.BackColor = cUnSelectedColor;
                }
            }
        } 
        #endregion

        #region Validate Empty Foreignkey
        private void ValidateEmptyForeignKey()
        {
            try
            {
                clsCommon.ValidateForeignKey(ref txtCheckedBy);
                clsCommon.ValidateForeignKey(ref txtApprovedBy);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion        

        #region Display Note View
        private void DisplayNoteView(string NoteID)
        {
            if (chkInquiry.Checked)
            {
                tbl_sasInquiry detail = tbl_sasInquiry.Select(NoteID);
                if (detail != null)
                {
                    frm_sasInquiry frm = new frm_sasInquiry(FormName.sasInquiry);
                    frm.glbInquiryID = detail.Inquiry_ID;
                    clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, this.MdiParent);
                }
            }
            else if (chkCustomerOrder.Checked)
            {
                tbl_sasCustomerOrder detail = tbl_sasCustomerOrder.Select(NoteID);
                if (detail != null)
                {
                    frm_sasCustomerOrder frm = new frm_sasCustomerOrder(FormName.CustomerOrder);
                    frm.glbCustomerOrderID = detail.CustomerOrder_ID;
                    clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, this.MdiParent);
                }
            }
            else if (chkDeliveryOrder.Checked)
            {
                tbl_sasDeliveryOrder detail = tbl_sasDeliveryOrder.Select(NoteID);
                if (detail != null)
                {
                    if (clsConfig.sSoftwareModel.Trim() == SoftwareModel_Sales.idealWheels.ToString())
                    {
                        frm_sasDeliveryOrder frm = new frm_sasDeliveryOrder(FormName.CusDeliveryOrder);
                        frm.glbDeliveryOrderID = detail.DeliveryOrder_ID;
                        clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, this.MdiParent);
                    }
                    else
                    {
                        frm_sasDeliveryOrder frm = new frm_sasDeliveryOrder(FormName.CusDeliveryOrder);
                        frm.glbDeliveryOrderID = detail.DeliveryOrder_ID;
                        clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, this.MdiParent);
                    }
                }
            }
            else if (chkInvoice.Checked)
            {
                tbl_sasInvoice detail = tbl_sasInvoice.Select(NoteID);
                if (detail != null)
                {
                    frm_sasInvoice frm = new frm_sasInvoice(FormName.VATInvoice);
                    frm.glbInvoiceID = detail.Invoice_ID;
                    clsHelpMethods_Local.DisplayForm(frm, clsFormatter.colorSales, this.MdiParent);
                }
            }
        } 
        #endregion
       
    }

}
