using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Digiteq_Logic;
using DataTire;
using Digiteq_Logic;
using SEACC_WPFControls;
using System.Data;

namespace Digiteq
{
    public partial class UC_WebLinks : UserControl
    {
        #region Class Variables
        DataTable dtMain = new DataTable();
        #endregion

        #region Form Load
        public UC_WebLinks()
        {
            #region Initialize Usercontrol
            InitializeComponent(); 

            SEACC_Form.enmFormName = FormName.Web_Links;
            grd_PopUp.Visibility = Visibility.Hidden;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("wb_ID");
            dgr_Main.dt.Columns.Add("LinkName");
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "wb_ID", 0);
            dgr_Main.Add_DatagridColoumn("Links", "LinkName", 250);
            #endregion

            ClearFields();
            RefreshGrid();  
        }
        #endregion

        #region Action Button
        private void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        private void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    #region Update
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_cfgWebLinks oldRecord = tbl_cfgWebLinks.Select(txtLinkCode.Text.Trim());
                            if (oldRecord != null)
                            {
                                tbl_cfgWebLinks detail = new tbl_cfgWebLinks(txtLinkCode.Text.Trim(), txtName.Text, txtDescription.Text, txtURL.Text, oldRecord.IsCancled, oldRecord.UserID_Created, clsSecurity.UserIDLoged, oldRecord.UserID_Canceled, oldRecord.TerminalID_Created, clsSecurity.TerminalID, oldRecord.TerminalID_Canceled, oldRecord.Date_Created, clsSecurity.getServerDateTime(), oldRecord.Date_Canceled);
                                detail.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    #endregion

                    #region Insert
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtLinkCode.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_cfgWebLinks detail = new tbl_cfgWebLinks(txtLinkCode.Text.Trim(), txtName.Text, txtDescription.Text, txtURL.Text, false, clsSecurity.UserIDLoged, "Default", "Default", clsSecurity.TerminalID, "Default", "Default", clsSecurity.getServerDateTime(), clsConfig.defaultDateTime, clsConfig.defaultDateTime);
                        detail.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                    #endregion
                }
                catch (Exception ex)
                {
                    SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        private void btn_Edit_Click(object sender, RoutedEventArgs e)
        {

        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    if (txtLinkCode.Tag != null)
                    {
                        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                        if (bMessegeBoxResult)
                        {
                            tbl_cfgWebLinks detail = tbl_cfgWebLinks.Select(txtLinkCode.Text.Trim());
                            if (detail != null)
                            {
                                detail.IsCancled = true;
                                detail.Date_Canceled = clsSecurity.getServerDateTime();
                                detail.TerminalID_Canceled = clsSecurity.TerminalID;
                                detail.UserID_Canceled = clsSecurity.UserIDLoged;
                                detail.Update();

                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                                ClearFields();
                                RefreshGrid();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region PopUp Buttons
        private void btn_popupClose_Click(object sender, RoutedEventArgs e)
        {
            if (grd_PopUp.Visibility == Visibility.Visible)
                grd_PopUp.Visibility = Visibility.Hidden;
            else
                grd_PopUp.Visibility = Visibility.Visible;
        }

        private void btn_Addnew_Click(object sender, RoutedEventArgs e)
        {
            if (grd_PopUp.Visibility == Visibility.Visible)
                grd_PopUp.Visibility = Visibility.Hidden;
            else
                grd_PopUp.Visibility = Visibility.Visible;
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_SEACCNormalTextbox(txtLinkCode, true, false,false);
            cls_Formater.SetEnableDisable_SEACCNormalTextbox(txtName, true, false, false);
            cls_Formater.SetEnableDisable_SEACCNormalTextbox(txtWbDescription, true, false, false);
            cls_Formater.SetEnableDisable_SEACCNormalTextbox(txtURL, true, false, false);

            txtLinkCode.Text = "";
            txtLinkCode.Tag = null;
            txtName.Text = "";
            txtWbDescription.Text = "";
            txtURL.Text = "";

            #region Set Auto Genarate Key fields
            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtLinkCode.setReadOnlyStatus(true);
                txtLinkCode.Text = "<Auto Generate>";
            }
            else
                txtLinkCode.setReadOnlyStatus(false);
            #endregion
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_cfgWebLinks detail in tbl_cfgWebLinks.SelectAll().Where(p => p.IsCancled == false))
                {
                    dgr_Main.dt.Rows.Add(detail.Wb_ID, detail.Wb_Name);
                }

                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
                if (!ChekValidity_DuplicateNames())
                    bStatus = false;
            }
            return bStatus;
        }

        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!SEACC_Form.IsUpdateMode)
            {
                if (!clsValidation.Validate_SEACCTextBox_EmptyValue(txtLinkCode))
                    bStatus = false;
                if (!clsValidation.Validate_SEACCTextBox_EmptyValue(txtName))
                    bStatus = false;
                if (!clsValidation.Validate_SEACCTextBox_EmptyValue(txtURL))
                    bStatus = false;
            }

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_cfgWebLinks detail = tbl_cfgWebLinks.Select(txtLinkCode.Text);
                if (detail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }

        public bool ChekValidity_DuplicateNames()
        {
            bool bStatus = true;
            foreach (tbl_cfgWebLinks detail1 in tbl_cfgWebLinks.SelectAll().Where(p => p.Wb_Name == txtName.Text && p.IsCancled == false && p.Wb_ID != txtLinkCode.Text))
            {
                if (detail1 != null)
                {
                    SEACCMessageBox.Show(MessegeBoxType.FieldAlreadyExist, "Link Name");
                    bStatus = false;
                    break;
                }
            }
            return bStatus;
        }
        #endregion

        #region Grid Event
        private void grd_WebLinks_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    tbl_cfgWebLinks detail = tbl_cfgWebLinks.Select(GridID);
                    if (detail != null)
                    {
                        SEACC_Form.IsUpdateMode = true;

txtLinkCode.Text = detail.Wb_ID;
                        txtLinkCode.Tag = detail.Wb_ID;
                        txtName.Text = detail.Wb_Name;
                        txtWbDescription.Text = detail.Wb_description;
                        txtURL.Text = detail.Wb_link;

                        txtWebAddress.Text = detail.Wb_link;
                        txtDescription.Text = detail.Wb_description;
                        System.Diagnostics.Process.Start(detail.Wb_link);

                        
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion 
    }
}