import { useEffect, useState } from "react";
import * as Yup from "yup";
import { useParams, useNavigate } from "react-router-dom";
import { useFormikBuilder, FieldsRenderer } from "../../../../helpers/formikBuilder";
import MeridianPage from "../../MeridianPage";
import groupService from "./service";
import tenantService from "../Tenants/service";
import currencyService from "../Currency/service";
import MessageBoxService from "../../../../services/MessageBoxService";

import config from "../../../../config/config";

export default function AddGroup() {
  const { id }   = useParams();
  const navigate = useNavigate();
  const isEdit   = Boolean(id);

  const [tenants,    setTenants]    = useState([]);
  const [currencies, setCurrencies] = useState([]);

  useEffect(() => {
    tenantService.getAll().then(({ success, data }) => {
      if (success) setTenants(data ?? []);
    });
    currencyService.getAll().then(({ success, data }) => {
      if (success) setCurrencies(data ?? []);
    });
  }, []);

  useEffect(() => {
    if (!isEdit) return;
    groupService.get(id).then(({ success, data }) => {
      if (success && data) formik.setValues({ ...data });
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSubmit = async (values, { resetForm }) => {
    const param = {
      ...values,
      groupId:  id ?? null,
      isUpdate: isEdit,
    };
    const response = await groupService.update(param);
    const { success, data } = response;
    if (success) {
      MessageBoxService.show({
        message: isEdit ? "Group updated successfully!" : "Group created successfully!",
        type: "success",
        onClose: () => {
          if (config.features.returnToListAfterSave) {
            navigate("/settings/groups");
          } else if (!id && data?.groupId) {
            navigate(`/settings/groups/edit/${data.groupId}`);
          } else if (!id) {
            resetForm();
          }
        },
      });
    }
  };

  const fields = {
    groupId: {
      name: "groupId",
      type: "text",
      placeholder: "Group ID",
      initialValue: "<Auto-generated>",
      className: "col-md-4",
      disabled: true,
    },
    groupName: {
      name: "groupName",
      type: "text",
      placeholder: "Group Name",
      initialValue: "",
      className: "col-md-8",
      validation: Yup.string().required("Group Name is required"),
    },
    tenantId: {
      name: "tenantId",
      type: "select",
      placeholder: "Tenant",
      initialValue: "",
      className: "col-md-6",
      validation: Yup.string().required("Tenant is required"),
      dataBinding: { data: tenants, keyField: "tenantId", valueField: "tenantName" },
    },
    baseCurrencyCode: {
      name: "baseCurrencyCode",
      type: "select",
      placeholder: "Base Currency",
      initialValue: "",
      className: "col-md-6",
      dataBinding: { data: currencies, keyField: "currencyCode", valueField: "currencyCode" },
    },
  };

  const formik = useFormikBuilder(fields, handleSubmit);

  const handleDelete = async () => {
    if (!isEdit) return;
    const confirmed = await MessageBoxService.confirmAsync({
      message: "Delete this group? This cannot be undone.",
      type: "danger",
      confirmText: "Delete",
      cancelText: "Cancel",
    });
    if (!confirmed) return;
    const response = await groupService.delete(id);
    if (response.success) {
      MessageBoxService.show({
        message: "Group deleted.",
        type: "success",
        onClose: () => navigate("/settings/groups"),
      });
    }
  };

  return (
    <MeridianPage
      title={isEdit ? "Edit Group" : "New Group"}
      backTo="/settings/groups"
      cardClass="ml-form-card"
      actions={
        <>
          {isEdit && (
            <button
              type="button"
              className="ml-btn-ghost ml-btn-danger-ghost ml-fab-1"
              onClick={handleDelete}
            >
              <i className="bi bi-trash" aria-hidden="true" />
              Delete
            </button>
          )}
          <button
            type="submit"
            form="group-form"
            className="ml-btn-action ml-fab"
            disabled={formik.isSubmitting}
          >
            {formik.isSubmitting
              ? <span className="ml-spinner" aria-hidden="true" />
              : <i className="bi bi-check-lg" aria-hidden="true" />}
            {isEdit ? "Save Changes" : "Create Group"}
          </button>
        </>
      }
    >
      <form id="group-form" onSubmit={formik.handleSubmit}>
        <div className="ml-form-section">
          <div className="ml-form-section-label">Group Details</div>
          <div className="row g-3">
            <FieldsRenderer fields={fields} formik={formik} />
          </div>
        </div>
      </form>
    </MeridianPage>
  );
}
