using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;

namespace SEACC_Tender
{
    /// <summary>
    /// Interaction logic for UC_AcceptanceLetter.xaml
    /// </summary>
    public partial class UC_ttsTxnAcceptanceLetter : UserControl
    {
        #region Class Variables
        DataTable dt = new DataTable();
        bool bIsItemChanged = false;
        public int iFormID;
        #endregion

        #region Form Load
        public UC_ttsTxnAcceptanceLetter()
        {
            InitializeComponent();

            #region Form Initialize
            SEACC_Form.enmFormName = FormName.AcceptanceLetter;
            iFormID = clsSecurity.getFormID(FormName.AcceptanceLetter);
            SEACC_Form.Initialize();
            #endregion

            #region data Initialize
            dgr_Main.dt.Columns.Add("AcceptanceNo");
            dgr_Main.dt.Columns.Add("TenderID");
            dgr_Main.dt.Columns.Add("TenderNo");
            dgr_Main.dt.Columns.Add("NoticeDate");
            dgr_Main.dt.Columns.Add("LetterDate");
            #endregion

            #region gridview initialize
            dgr_Main.Add_DatagridColoumn("Acceptance No", "AcceptanceNo", 100);
            dgr_Main.Add_DatagridColoumn("Tender ID", "TenderID", 50, false);
            dgr_Main.Add_DatagridColoumn("Tender No", "TenderNo", 100);
            dgr_Main.Add_DatagridColoumn("Notice Date", "NoticeDate", 120);
            dgr_Main.Add_DatagridColoumn("Letter Date", "LetterDate", 100);
            #endregion

            #region Action Button Initialize
            SEACC_Form.SetVisibility_ActionButons(true, true, true, true);
            this.SEACC_Form.btn_New.Click += Btn_New_Click;
            this.SEACC_Form.btn_Cancel.Click += Btn_Cancel_Click;
            //this.SEACC_Form.btn_Print.Click += Btn_Print_Click;
            this.SEACC_Form.btn_Save.Click += Btn_Save_Click;
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Form Responsive
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 880)
                ColumnA.Width = new GridLength(200);
            else
                ColumnA.Width = new GridLength(310);
        }
        #endregion

        #region Actions Buttons
        private void Btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.CheckPermisshion_ToSave(SEACC_Form.IsUpdateMode))
            {
                string sLetterID = "";
                try
                {
                    #region Update
                    if (SEACC_Form.IsUpdateMode)
                    {
                        
                        tbl_ttsAcceptanceLetter oldDetail = tbl_ttsAcceptanceLetter.Select(txtAcceptanceNo.Tag.ToString());
                        if (oldDetail != null)
                        {
                            tbl_ttsAcceptanceLetter oDetails = new tbl_ttsAcceptanceLetter(txtAcceptanceNo.Tag.ToString(), txtTenderID.Tag.ToString(), dtpLetterDate.GetDateTime(), txtLetterRef.Text, false);
                            oDetails.Update();

                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                        }

                    }
                    #endregion

                    #region Insert
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtAcceptanceNo.Tag = SEACC_Form.getAutoGeneratedCode();

                        tbl_ttsAcceptanceLetter oDetail = new tbl_ttsAcceptanceLetter(txtAcceptanceNo.Tag.ToString(), txtTenderID.Tag.ToString(), dtpLetterDate.GetDateTime(), txtLetterRef.Text, false);
                        oDetail.Insert();

                        Attachments.Insert(txtAcceptanceNo.Tag.ToString());

                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                    #endregion
                }
                catch (Exception Ex)
                {
                    SEACCExeption.Show(Ex);
                }

                finally
                {
                    sLetterID = txtAcceptanceNo.Tag.ToString();
                    ClearFields();
                    RefreshGrid();
                    FillDetails(sLetterID);
                }
            }
            
        }

        private void Btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.IsUpdateMode)
            {
                bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                if (bMessegeBoxResult)
                {
                    tbl_ttsAcceptanceLetter Detail = tbl_ttsAcceptanceLetter.Select(txtAcceptanceNo.Tag.ToString());
                    if (Detail != null)
                    {
                        Detail.IsCanceled = true;
                        Detail.Update();

                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                        ClearFields();
                        RefreshGrid();
                    }
                }
            }
        }

        private void Btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }
        #endregion      

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            Attachments.Clear(SEACC_Form.Function_ID);

            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtAcceptanceNo, true, false, false);
            cls_Formater.SetEnableDisable_LableTimePicker(dtpLetterDate, true, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtLetterRef, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtTenderID, true, false, false);

            txtAcceptanceNo.Text = "<Auto generated>";
            txtTenderID.Text = "";
            txtLetterRef.Text = "";

            txtTenderID.Tag = null;
            txtAcceptanceNo.Tag = null;

            dtpLetterDate.SetTime(DateTime.Now);
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_ttsAcceptanceLetter oDetail in tbl_ttsAcceptanceLetter.SelectAll().Where(p => p.IsCanceled != true).OrderBy(p => p.Acceptance_ID))
                {
                    DateTime dDate = DateTime.Parse(clsRef_Name.get_Notice_Date(oDetail.Tender_ID));
                    dgr_Main.dt.Rows.Add(oDetail.Acceptance_ID, oDetail.Tender_ID, clsRef_Name.get_Bid_No(oDetail.Tender_ID), dDate.ToString(cls_Formater.Format_Date2), oDetail.AcceptanceLetterDate.ToString(cls_Formater.Format_Date2));
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sId)
        {
            if (sId != null)
            {
                SEACC_Form.IsUpdateMode = true;

                tbl_ttsAcceptanceLetter oDetail = tbl_ttsAcceptanceLetter.Select(sId);
                if (sId != null)
                {
                    txtAcceptanceNo.Text = oDetail.Acceptance_ID;
                    txtAcceptanceNo.Tag = oDetail.Acceptance_ID;
                    txtTenderID.Text = oDetail.Tender_ID.ToString();
                    txtTenderID.Tag = oDetail.Tender_ID.ToString();
                    txtLetterRef.Text = oDetail.AcceptanceLetterRefNo;
                    dtpLetterDate.SetTime(oDetail.AcceptanceLetterDate);

                    Attachments.FillDetails(oDetail.Acceptance_ID);
                }
            }
        } 
        #endregion

        #region Search
        private void txtTenderID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Tender);
            if (RowDataSearch.DialogResult == true)
            {
                txtTenderID.Tag = lstResult[0];
                txtTenderID.Text = lstResult[1];
            }
        }
        private void txtAcceptanceNo_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Ten_AcceptanceLetter);
            if (RowDataSearch.DialogResult == true)
            {
                FillDetails(lstResult[0]);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyFields())
            {
                bStatus = true;
            }
            return bStatus;
        }

        private bool CheckValidity_EmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtTenderID, ref strMessage))
                bStatus = false;

            if (bStatus == false)
                SEACCMessageBox.Show("Fields cannot be Empty", strMessage, MessageBoxButton.OK);

            return bStatus;
        }
        #endregion

        #region Grid Event
        private void dgr_Main_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object oItem = dgr_Main.grdMain.SelectedItem;
                if (oItem != null)
                {
                    string sId = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text;
                    FillDetails(sId);
                }
            }
            catch (Exception ex)
            {

                SEACCExeption.Show(ex);
            }
        }
        #endregion
 
    }
}
