using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;
using System.IO;


namespace SEACC_Tender
{
    public partial class UC_ttsTxnDocumentRenewal : UserControl
    {
        #region Class Variables
        DataTable dt = new DataTable();
       public int iFormID;
        #endregion

        #region Form Load
        public UC_ttsTxnDocumentRenewal()
        {
            InitializeComponent();

            #region Initialize Form
            SEACC_Form.enmFormName = FormName.DocumentLicenceRenewal;
            iFormID = clsSecurity.getFormID(FormName.DocumentLicenceRenewal);
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dt.Columns.Add("DocRenewalID");
            dt.Columns.Add("DocumentID");
            dt.Columns.Add("DocumentCode");
            dt.Columns.Add("DocumentName");
            dt.Columns.Add("RenewalType");
            dt.Columns.Add("ExpiryDate");
            dgr_Documents.ItemsSource = dt.DefaultView;
            #endregion

            #region Action Button Initialize
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_New.Click += Btn_New_Click;
            this.SEACC_Form.btn_Cancel.Click += Btn_Cancel_Click;
            //this.SEACC_Form.btn_Print.Click += Btn_Print_Click;
            this.SEACC_Form.btn_Save.Click += Btn_Save_Click;
            #endregion

            ClearFields();
        }
        #endregion

        #region Action Button
        private void Btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.CheckPermisshion_ToSave(SEACC_Form.IsUpdateMode))
            {
                if (CheckValidity())
                {
                    string sDocID = "";
                    try
                    {
                        if (SEACC_Form.IsUpdateMode)
                        {
                            #region Update
                            tbl_ttsTenderDocumentRenewals oldDetail = tbl_ttsTenderDocumentRenewals.Select(txtDocRenewalID.Text);
                            if (oldDetail != null)
                            {
                                tbl_ttsTenderDocumentRenewals oDetails = new tbl_ttsTenderDocumentRenewals(txtDocRenewalID.Text, txtItemCode.Tag.ToString(), txtDocCode.Tag.ToString(), int.Parse(txtRenewalType1.Tag.ToString()), 0, dtpExpiryDate.GetDateTime().Date, txtRemarks.Text, int.Parse(txtReminderDays.Text), cmbFrequence.GetSelectedIndex(), dtpTime.GetDateTime().Date, true, false);
                                oDetails.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                            #endregion
                        }
                        else
                        {
                            #region Insert
                            if (SEACC_Form.isAutoGenaratedCode)
                                sDocID = txtDocRenewalID.Text = SEACC_Form.getAutoGeneratedCode();

                            tbl_ttsTenderDocumentRenewals oDetail = new tbl_ttsTenderDocumentRenewals(txtDocRenewalID.Text, txtItemCode.Tag.ToString(), txtDocCode.Tag.ToString(), int.Parse(txtRenewalType1.Tag.ToString()), 0, dtpExpiryDate.GetDateTime().Date, txtRemarks.Text, int.Parse(txtReminderDays.Text), cmbFrequence.GetSelectedIndex(), dtpTime.GetDateTime(), true, false);
                            oDetail.Insert();
                            Attachments.Insert(txtDocRenewalID.Text);
                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                            #endregion
                        }
                    }
                    catch (Exception Ex)
                    {
                        SEACCExeption.Show(Ex);
                    }
                    finally
                    {
                        sDocID = txtDocRenewalID.Text;
                        ClearFields();
                        FillDetails(sDocID);
                    }
                }

            }
        }

        private void Btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.IsUpdateMode)
            {
                bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                if (bMessegeBoxResult)
                {
                    tbl_ttsTenderDocumentRenewals Detail = tbl_ttsTenderDocumentRenewals.Select(txtDocRenewalID.Tag.ToString());
                    if (Detail != null)
                    {
                        Detail.IsCanceled = true;
                        Detail.IsActive = false;
                        Detail.Update();

                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                        string sItemCode = Detail.Item_ID.ToString();
                        ClearFields();
                        FillDetails_Item(Detail.Item_ID);
                    }
                }
            }
        }

        private void Btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            dt.Clear();
            Attachments.Clear(SEACC_Form.Function_ID);

            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtDocRenewalID, false, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtRemarks, true, false, true);
            cls_Formater.SetEnableDisable_LableTextbox(txtReminderDays, true, true, false);
            cls_Formater.SetEnableDisable_LableTimePicker(dtpTime, true, false);
            cls_Formater.SetEnableDisable_LableTimePicker(dtpExpiryDate, true, false);

            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtItemCode, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtItemCode, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtDocCode, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtRenewalType1, true, false, true);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtTenderNo, true, false, false);

            rdoGCertification.IsChecked = false;
            rdoPBCertification.IsChecked = true;

            stackGeneralandProduct.Visibility = Visibility.Collapsed;

            txtCategory.Text = "";
            txtDocCode.Text = "";
            txtDocDescription.Text = "";
            txtDocRenewalID.Text = "";
            txtDocType.Text = "";
            txtItemCode.Text = "";
            txtRemarks.Text = "";
            txtReminderDays.Text = "0";
            txtRenewalType1.Text = "";
            txtType.Text = "";

            txtItemCode.Tag = null;
            txtDocRenewalID.Tag = null;
            txtDocCode.Tag = null;
            txtRenewalType1.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
                txtDocRenewalID.Text = "<Auto Generated>";

            cmbFrequence.comboBox.ItemsSource = Common.clsHelpMethods.GetEnumDescription(typeof(Frequence));
            cmbFrequence.SetSelectedIndex(0);
        }
        #endregion

        #region Refresh Grid
        //private void RefreshGrids(string sItemID)
        //{
        //    dt.Clear();
        //    foreach (tbl_tenderItemMasterDocument oDetail in tbl_tenderItemMasterDocument.SelectAllByItem_ID(sItemID).Where(p => p.IsCanceled != true))
        //    {
        //        string sDocumentCode = "", sDocumentTypes = "", sRenwalType = "";
        //        foreach (tbl_tenderDocumentMaster oDocuments in tbl_tenderDocumentMaster.SelectAll().Where(p => p.Doc_ID == oDetail.Doc_ID))
        //        {
        //            sDocumentCode += oDocuments.Doc_Code;
        //            sDocumentTypes += (Common.clsHelpMethods.GetEnumDescription(typeof(DocumentType)))[oDocuments.Doc_Type];
        //        }
        //        foreach (tbl_tenderRenewalType oTypes in tbl_tenderRenewalType.SelectAll().Where(t => t.Renewal_ID == oDetail.Renewal_ID))
        //        {
        //            sRenwalType += oTypes.Renewal_Name;
        //        }
        //        dt.Rows.Add(oDetail.Doc_Renewal_ID, oDetail.Doc_ID, sDocumentCode, sDocumentTypes, sRenwalType, oDetail.ExpiryDate.ToShortDateString());
        //    }
        //} 

        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            if (sID != null)
            {
                ClearFields();
                SEACC_Form.IsUpdateMode = true;

                tbl_ttsTenderDocumentRenewals oDetails = tbl_ttsTenderDocumentRenewals.Select(sID);             
                if (oDetails != null)
                {
                    txtDocRenewalID.Text = oDetails.Doc_Renewal_ID;
                    txtDocRenewalID.Tag = oDetails.Doc_Renewal_ID.ToString();
                    
                    txtRenewalType1.Text = clsRef_Name.get_Renewal_Types(oDetails.Renewal_Type1_ID.ToString());
                    txtRenewalType1.Tag = oDetails.Renewal_Type1_ID.ToString();
                    dtpExpiryDate.SetTime(oDetails.ExpiryDate);
                    txtRemarks.Text = oDetails.Remarks.ToString();

                    txtReminderDays.Text = oDetails.ReminderDays.ToString();
                    dtpTime.SetTime(oDetails.ReminderTime);
                    cmbFrequence.SetSelectedIndex(oDetails.ReminderFrequence);

                    tbl_ttsTenderDocumentMaster oDocument = tbl_ttsTenderDocumentMaster.Select(oDetails.Doc_ID);
                    if (oDocument != null)
                    {
                        txtDocCode.Tag = oDetails.Doc_ID.ToString();
                        txtDocCode.Text = oDocument.Doc_Code.ToString();
                        txtDocDescription.Text = oDocument.Doc_Description.ToString();
                        int sDocType = int.Parse(oDocument.Doc_Type.ToString());
                        txtDocType.Text = (Common.clsHelpMethods.GetEnumDescription(typeof(DocumentType)))[sDocType];
                    }
                    Attachments.FillDetails(oDetails.Doc_Renewal_ID);
                    //foreach (tbl_ttsAttachments oAttachments in tbl_ttsAttachments.SelectAll().Where(p => p.Transaction_ID == oDetails.Doc_Renewal_ID))
                    //{
                    //    dt2.Rows.Add(oAttachments.DipsplayName,@"Attachments\"+ oAttachments.Attachment, false, false,oAttachments.Attachment_ID , null);
                    //}
                    FillDetails_Item(oDetails.Item_ID.ToString());
                }
            }
        }

        private void FillDetails_Item(string sItemID)
        {
            if (sItemID != null)
            {
                try
                {
                    tbl_genItemMaster oItem = tbl_genItemMaster.Select(sItemID);
                    if (oItem != null)
                    {
                        string sItemFullName = sItemID + " - " + clsRef_Name.get_Item_Name(sItemID);

                        txtCategory.Tag = oItem.ItemCategory_ID;
                        txtCategory.Text = clsRef_Name.get_Item_Category(oItem.ItemCategory_ID);
                        txtType.Tag = oItem.ItemType_ID;
                        txtType.Text = clsRef_Name.get_Item_Type(oItem.ItemType_ID);

                        txtItemCode.Tag = sItemID;
                        txtItemCode.Text = sItemFullName.ToString();

                        dt.Clear();
                        foreach (tbl_ttsTenderDocumentRenewals oDetails in tbl_ttsTenderDocumentRenewals.SelectAllByItem_ID(sItemID).Where(p => p.IsCanceled != true).OrderByDescending(p => p.ExpiryDate))
                        {
                            string sDocumentTypes = "";
                            tbl_ttsTenderDocumentMaster oDocument = tbl_ttsTenderDocumentMaster.Select(oDetails.Doc_ID);
                            if (oDocument != null)
                            {
                                sDocumentTypes = (Common.clsHelpMethods.GetEnumDescription(typeof(DocumentType)))[oDocument.Doc_Type];

                                dt.Rows.Add(oDetails.Doc_Renewal_ID, oDetails.Doc_ID, oDocument.Doc_Code, sDocumentTypes, clsRef_Name.get_Renewal_Types(oDetails.Renewal_Type1_ID.ToString()), oDetails.ExpiryDate.ToString(cls_Formater.Format_Date2));
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
            }
        }
        #endregion

        #region Search
        private void txtDocCode_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch DataRowSearch = new Search_Forms.frmSearch();
            List<string> lstResult = DataRowSearch.Show(Search.Ten_Document);
            if (DataRowSearch.DialogResult == true)
            {
                bool bItemOk = true;
                foreach (DataRow row in dt.Rows)
                {
                    string sDocID = row["DocumentID"].ToString();
                    if (sDocID == lstResult[0])
                    {
                        SEACCMessageBox.Show("Sorry", "This document is allready Renewed", MessageBoxButton.OK);
                        bItemOk = false;
                    }
                }
                if (bItemOk)
                {
                    txtDocCode.Tag = lstResult[0];
                    txtDocCode.Text = lstResult[1];

                    int iTypeId = int.Parse(lstResult[2]);
                    string sVal = (Common.clsHelpMethods.GetEnumDescription(typeof(DocumentType)))[iTypeId];
                    txtDocType.Text = sVal;

                    txtDocDescription.Text = lstResult[3];
                }
            }
        }

        private void txtItemCode_MouseDoubleClick_1(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Items);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                FillDetails_Item(lstResult[0]);
            }
        }

        private void txtTenderNo_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Tender);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                FillDetails_Item(lstResult[0]);
            }
        }    

        private void txtRenewalType1_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch DataRowSearch = new Search_Forms.frmSearch();
            List<string> lstResult = DataRowSearch.Show(Search.Ten_RenewalTypes);
            if (DataRowSearch.DialogResult == true)
            {
                txtRenewalType1.Text = lstResult[1];
                txtRenewalType1.Tag = lstResult[0];
            }
        }

        private void txtDocRenewalID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Ten_DocumentRenewal);
            if (RowDataSearch.DialogResult == true)
            {
                FillDetails(lstResult[0]);
            }
        }

        #endregion

        #region Grid Event
        private void dgr_Documents_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object oItem = dgr_Documents.SelectedItem;
                if (oItem != null)
                {
                    string sId = (dgr_Documents.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text;
                    FillDetails(sId);
                }
            }
            catch (Exception ex)
            {

                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyFields())
            {
                if (CheckGridvalidity())
                {
                //    if (CheckValidity_DuplicateKey())
                //    {
                //        if (CheckValidity_GrossAmount())
                bStatus = true;
                //    }
                }
            }
            return bStatus;
        }

        private bool CheckValidity_EmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtItemCode, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(txtDocCode, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(txtRenewalType1, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(cmbFrequence))
                bStatus = false;

            if (bStatus == false)
                SEACCMessageBox.Show("Fields cannot be Empty", strMessage, MessageBoxButton.OK);

            return bStatus;
        }
        private bool CheckGridvalidity()
        {
            bool bStatus = true;
            if (Attachments.dt2.Rows.Count <= 0)
            {
                SEACCMessageBox.Show("Please select file to upload..", "Upload files", MessageBoxButton.OK);
                bStatus = false;
            }
            return bStatus;
        }
        #endregion

        #region Radio Button Events
        private void rdoGCertification_Click(object sender, RoutedEventArgs e)
        {
            txtItemCode.Visibility = Visibility.Collapsed;
        }

        private void rdoPBCertification_Click(object sender, RoutedEventArgs e)
        {
            txtItemCode.Visibility = Visibility.Visible;
        }
        #endregion
    }
}