using System;
using System.Windows;
using System.Collections.Generic;
using System.IO;
using System.Data;
using DataTire;
using System.Windows.Media.Imaging;
using SEACC_WPFControls;
using System.Linq;
using System.ComponentModel;

namespace Digiteq_Logic
{
    public class clsCommon : Window
    {
        public static void Set_UserIndicator(ref SEACC_UserIndicator_Small userIndicator, string UserID)
        {
            try
            {
                if (UserID != "default")
                {
                    tbl_genMasEmployee oEmployee = tbl_genMasEmployee.Select(UserID, clsSecurity.CompanyID, clsSecurity.BranchID);
                    if (oEmployee.Employee_ID != null)
                        userIndicator.Set(UserID, oEmployee.FullName, clsCommon.Convert_ByteToBitMap(oEmployee.Employee_Image));
                }
            }
            catch (Exception)
            {
            }
        }
        public static BitmapImage Convert_ByteToBitMap(byte[] ByteImage)
        {
            BitmapImage bitmap = new BitmapImage();
            try
            {
                if (ByteImage != null)
                    if (ByteImage.Length > 0)
                    {
                        using (var stream = new MemoryStream(ByteImage))
                        {
                            bitmap.BeginInit();
                            bitmap.StreamSource = stream;
                            bitmap.CacheOption = BitmapCacheOption.OnLoad;
                            bitmap.EndInit();
                            bitmap.Freeze();
                        }
                    }
            }
            catch (Exception)
            {
            }
            return bitmap;
        }

        public static string getAutoGeneratedCode(FormName enmFormName)
        {
            string sCode = "";

            tbl_securityFunctionMaster_Form detail = tbl_securityFunctionMaster_Form.Select((int)enmFormName);
            if (detail != null)
            {
                if (detail.Prefix1 != null && detail.Prefix1.Length > 0)
                    sCode += detail.Prefix1;

                sCode += detail.Counter.ToString(getWidthFormat(detail.Length));
                detail.Counter++;
                detail.Update();
            }
            return sCode;
        }

        public static string getWidthFormat(int Size)
        {
            string Zero = "";
            for (int x = 0; x < Size; x++)
            {
                Zero += "0";
            }
            return Zero;
        }

        #region General functions

        private static string regRegistryName = "Software\\52465123-sys\\456465465461312313111321";// + "1212";

        public static string RegRegistryName
        {
            get { return clsCommon.regRegistryName; }
            set { clsCommon.regRegistryName = value; }
        }


        #region Get Company Details
        public static byte[] getCompanyImage()
        {
            byte[] sCompanyImage = null;
            tbl_genCompanyImage comI = tbl_genCompanyImage.Select(clsSecurity.CompanyID);

            if (comI != null)
                sCompanyImage = comI.MainLogo;

            return sCompanyImage;
        }
        public static string getCompanyName()
        {
            string sCompanyName = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
                sCompanyName = com.CompanyName;

            return sCompanyName;
        }
        public static string getCompanyAddress1()
        {
            string sAddress1 = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
                sAddress1 = com.Address;

            return sAddress1;
        }
        public static string getCompanyAddress2()
        {
            string sAddress2 = "";
            tbl_genCompanyInfo com = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
            if (com != null)
            {
                if (com.Telephone1.Length > 0)
                    sAddress2 = "Tel:" + com.Telephone1;
                if (com.Telephone2.Length > 0)
                    sAddress2 += "," + com.Telephone2;
                if (com.Fax.Length > 0)
                    sAddress2 += "," + " FAX:" + com.Fax;
            }
            return sAddress2;
        }


        public static CompanyDetails getCompanyDetail_FromDivision(string sDivisionID)
        {
            string sCompanyName = "";
            string sAddress1 = "";
            string sAddress2 = "";
            string sBusinessRegNo = "";
            string sVatRegisterNo = "";
            string sEPF_RegNo = "";
            string sETF_RegNo = "";
            string sPayee_RegNo = "";
            string sTax_IdentityNo = "";

            byte[] bCompanyImage = null;

            CompanyDetails strcutComDetails = new CompanyDetails();
            tbl_genMasDivision oDiv = tbl_genMasDivision.Select(clsSecurity.CompanyID, clsSecurity.BranchID, sDivisionID);

            if (oDiv != null && oDiv.Reg_ID != null && oDiv.Reg_ID != "default")
            {
                tbl_genRegistrationInfo oRegInfo = tbl_genRegistrationInfo.Select(clsSecurity.CompanyID, clsSecurity.BranchID, oDiv.Reg_ID);
                if (oRegInfo != null)
                {
                    #region Company Name
                    sCompanyName = oRegInfo.CompanyName;
                    strcutComDetails.sCompanyName = clsSecurity.decryptPassword(sCompanyName);
                    #endregion

                    #region Address 1
                    sAddress1 = oRegInfo.Address;
                    strcutComDetails.sAddress1 = clsSecurity.decryptPassword(sAddress1);
                    #endregion

                    #region Address 2
                    if (oRegInfo.Telephone1.Length > 0)
                        sAddress2 = "Tel:" + oRegInfo.Telephone1;
                    if (oRegInfo.Telephone2.Length > 0)
                        sAddress2 += "," + oRegInfo.Telephone2;
                    if (oRegInfo.Fax.Length > 0)
                        sAddress2 += "," + " FAX:" + oRegInfo.Fax;
                    strcutComDetails.sAddress2 = sAddress2;
                    #endregion

                    #region sBusinessRegNo
                    sBusinessRegNo = oRegInfo.BusinessRegisterNo;
                    strcutComDetails.sBusinessRegNo = sBusinessRegNo;
                    #endregion

                    #region sVatRegisterNo
                    sVatRegisterNo = oRegInfo.VatRegisterNo;
                    strcutComDetails.sVatRegisterNo = sVatRegisterNo;
                    #endregion

                    #region sEPF_RegNo
                    sEPF_RegNo = oRegInfo.Epf_RegNo;
                    strcutComDetails.sEPF_RegNo = sEPF_RegNo;
                    #endregion

                    #region sETF_RegNo
                    sETF_RegNo = oRegInfo.Etf_RegNo;
                    strcutComDetails.sETF_RegNo = sETF_RegNo;
                    #endregion

                    #region sPayee_RegNo
                    sPayee_RegNo = oRegInfo.Payee_RegNo;
                    strcutComDetails.sPayee_RegNo = sPayee_RegNo;
                    #endregion

                    #region sTax_IdentityNo
                    sTax_IdentityNo = oRegInfo.Tax_IdentityNo;
                    strcutComDetails.sTax_IdentityNo = sTax_IdentityNo;
                    #endregion

                    #region Company Image
                    bCompanyImage = oRegInfo.MainLogo;
                    strcutComDetails.bCompanyImage = bCompanyImage;
                    #endregion
                }
            }
            else
            {
                tbl_genCompanyInfo oCom = tbl_genCompanyInfo.Select(clsSecurity.CompanyID);
                if (oCom != null)
                {
                    #region Company Name
                    sCompanyName = oCom.CompanyName;
                    strcutComDetails.sCompanyName = clsSecurity.decryptPassword(sCompanyName);
                    #endregion

                    #region Address 1
                    sAddress1 = oCom.Address;
                    strcutComDetails.sAddress1 = clsSecurity.decryptPassword(sAddress1);
                    #endregion

                    #region Address 2
                    if (oCom.Telephone1.Length > 0)
                        sAddress2 = "Tel:" + oCom.Telephone1;
                    if (oCom.Telephone2.Length > 0)
                        sAddress2 += "," + oCom.Telephone2;
                    if (oCom.Fax.Length > 0)
                        sAddress2 += "," + " FAX:" + oCom.Fax;
                    strcutComDetails.sAddress2 = sAddress2;
                    #endregion

                    #region sBusinessRegNo
                    sBusinessRegNo = oCom.BusinessRegisterNo;
                    strcutComDetails.sBusinessRegNo = sBusinessRegNo;
                    #endregion

                    #region sVatRegisterNo
                    sVatRegisterNo = oCom.VatRegisterNo;
                    strcutComDetails.sVatRegisterNo = sVatRegisterNo;
                    #endregion

                    #region sEPF_RegNo
                    sEPF_RegNo = oCom.Epf_RegNo;
                    strcutComDetails.sEPF_RegNo = sEPF_RegNo;
                    #endregion

                    #region sETF_RegNo
                    sETF_RegNo = oCom.Etf_RegNo;
                    strcutComDetails.sETF_RegNo = sETF_RegNo;
                    #endregion

                    #region sPayee_RegNo
                    sPayee_RegNo = oCom.Payee_RegNo;
                    strcutComDetails.sPayee_RegNo = sPayee_RegNo;
                    #endregion

                    #region sTax_IdentityNo
                    sTax_IdentityNo = oCom.Tax_IdentityNo;
                    strcutComDetails.sTax_IdentityNo = sTax_IdentityNo;
                    #endregion

                    #region Company Image
                    bCompanyImage = getCompanyImage();
                    strcutComDetails.bCompanyImage = bCompanyImage;
                    #endregion
                }
            }

            return strcutComDetails;
        }

        #endregion

        #endregion

        #region Get Telephone Fax Customer/Supplier
        public static string getCustomerTelephoneAndFax(string CustomerID)
        {
            string sTelephoneFax = "";
            tbl_genCustomerMaster Cus = tbl_genCustomerMaster.Select(CustomerID);
            if (Cus != null)
            {
                if (Cus.Telephone.Trim().Length > 0 || Cus.Fax.Trim().Length > 0)
                {
                    sTelephoneFax = (Cus.Telephone.Trim().Length > 0) ? Cus.Telephone : "N/A";
                    sTelephoneFax += " / ";
                    sTelephoneFax += (Cus.Telephone.Trim().Length > 0) ? Cus.Telephone : "N/A";
                }
                else
                    sTelephoneFax = "N/A";
            }
            return sTelephoneFax;
        }

        public static string getSupplerTelephoneAndFax(string CustomerID)
        {
            string sTelephoneFax = "";
            tbl_genSupplierMaster Cus = tbl_genSupplierMaster.Select(CustomerID);
            if (Cus != null)
            {
                sTelephoneFax = Cus.Telephone + "  /  " + Cus.Fax;
            }
            return sTelephoneFax;
        }
        #endregion

        public static List<string> getCompanyDays(DateTime fromDate, DateTime toDate)
        {
            List<string> dtDayDescs = new List<string>();

            DataTable dtDBResult_Table = DBHandling.ExecQuery("SELECT HolidayCalander.holiday_Date, Holiday.holydayType_Name, HolidayCalander.holiday_Description FROM tbl_tasHolidayType AS Holiday RIGHT OUTER JOIN tbl_tasHolidayCalander AS HolidayCalander ON Holiday.holydayType_ID = HolidayCalander.holydayType_ID").Tables[0];

            for (DateTime date = fromDate; date.Date <= toDate.Date; date = date.AddDays(1))
            {
                dtDayDescs.Add(date.ToString("ddd"));

                DataRow[] result = dtDBResult_Table.Select("holiday_Date = #" + date.Date + "#");
                if (result != null)
                    if (result.Length > 0)
                    {
                        dtDayDescs[dtDayDescs.Count - 1] = result[0]["holydayType_Name"].ToString().Substring(0, 4);
                    }
            }
            return dtDayDescs;
        }

        public static string GetHRyear_ID(DateTime dtmDate)
        {
            string sValue = "default";
            sValue = DBHandling.ExecQuery_ReturnStringValue("SELECT year_ID FROM tbl_hrPeriod_Year WHERE (CONVERT(Date, year_startDate) <= '" + dtmDate.Date + "') AND (CONVERT(Date, year_endDate) >= '" + dtmDate.Date + "')");
            //sValue = DBHandling.ExecQuery_ReturnStringValue("select [year_ID] from [dbo].[tbl_hrPeriod_Year] where [year_startDate]< '" + dtmDate.Date + "' AND [year_endDate]> '" + dtmDate.Date + "'");
            return sValue;
        }

        public static List<string> GetEnumDescription(Type enumType)
        {
            List<string> lPeriod = new List<string>();

            foreach (var record in Enum.GetValues(enumType).Cast<Enum>().Select(value => new
            {
                (Attribute.GetCustomAttribute(value.GetType().GetField(value.ToString()), typeof(DescriptionAttribute)) as DescriptionAttribute).Description,
                value
            })
        .OrderBy(item => item.value)
        .ToList())
            {
                lPeriod.Add(record.Description);
            }

            return lPeriod;
        }
    }

    public struct CompanyDetails
    {
        public string sCompanyName { get; set; }
        public string sAddress1 { get; set; }
        public string sAddress2 { get; set; }
        public string sBusinessRegNo { get; set; }
        public string sVatRegisterNo { get; set; }
        public string sEPF_RegNo { get; set; }
        public string sETF_RegNo { get; set; }
        public string sPayee_RegNo { get; set; }
        public string sTax_IdentityNo { get; set; }

        public byte[] bCompanyImage { get; set; }
    }
}
