using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;

namespace SEACC_Tender
{
    /// <summary>
    /// Create by Janith Srimal
    /// 2017-05-08
    /// </summary>
    public partial class UC_ttsMasProjectSponsor : UserControl
    {
        #region Class Variabels
        DataTable dt = new DataTable(); 
        #endregion

        #region Form Load
        public UC_ttsMasProjectSponsor()
        {
            InitializeComponent();

            #region Form Initialize
            SEACC_Form.enmFormName = FormName.ProjectSponsor;
            SEACC_Form.Initialize();
            #endregion

            #region data Initialize
            dgr_Main.dt.Columns.Add("SponsorID");
            dgr_Main.dt.Columns.Add("SponsorName");
            dgr_Main.dt.Columns.Add("SponsorEmail");
            dgr_Main.dt.Columns.Add("SponsorTpNo");
            #endregion

            #region gridview initialize
            dgr_Main.Add_DatagridColoumn("Sponsor ID", "SponsorID", 50, false);
            dgr_Main.Add_DatagridColoumn("Sponsor", "SponsorName", 150);
            dgr_Main.Add_DatagridColoumn("Email", "SponsorEmail", 120);
            dgr_Main.Add_DatagridColoumn("Mob#", "SponsorTpNo", 100);
            #endregion

            #region Action Button Initialize
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_New.Click += Btn_New_Click;
            this.SEACC_Form.btn_Cancel.Click += Btn_Cancel_Click;
            //this.SEACC_Form.btn_Print.Click += Btn_Print_Click;
            this.SEACC_Form.btn_Save.Click += Btn_Save_Click;
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Form Responsive
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 880)
                ColumnA.Width = new GridLength(200);
            else
                ColumnA.Width = new GridLength(410);
        } 
        #endregion

        #region Action Buttons
        private void Btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.CheckPermisshion_ToSave(SEACC_Form.IsUpdateMode))
            {
                string sDocID = "";
                try
                {
                    sDocID = txtSponsorID.Text;
                    if (SEACC_Form.IsUpdateMode)
                    {
                        #region Update
                        tbl_ttsTenderSponsor oldDetail = tbl_ttsTenderSponsor.Select(sDocID);
                        if (oldDetail != null)
                        {
                            tbl_ttsTenderSponsor oDetails = new tbl_ttsTenderSponsor(sDocID, txtSponsorOrganization.Text, txtSponsorEmail.Text, int.Parse(txtSponsorTpNo.Text), false);
                            oDetails.Update();

                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                        }
                        #endregion
                    }
                    else
                    {
                        #region Insert
                        if (SEACC_Form.isAutoGenaratedCode)
                            sDocID = txtSponsorID.Text = SEACC_Form.getAutoGeneratedCode();

                        tbl_ttsTenderSponsor oDetail = new tbl_ttsTenderSponsor(sDocID, txtSponsorOrganization.Text, txtSponsorEmail.Text, int.Parse(txtSponsorTpNo.Text), false);
                        oDetail.Insert();

                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                        #endregion
                    }
                }
                catch (Exception Ex)
                {
                    SEACCExeption.Show(Ex);
                }

                finally
                {
                    ClearFields();
                    RefreshGrid();
                    FillDetails(sDocID);
                }
            }
        }

        private void Btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.IsUpdateMode)
            {
                bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                if (bMessegeBoxResult)
                {
                    tbl_ttsTenderSponsor Detail = tbl_ttsTenderSponsor.Select(txtSponsorID.Tag.ToString());
                    if (Detail != null)
                    {
                        Detail.IsCanceled = true;
                        Detail.Update();

                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                        ClearFields();
                        RefreshGrid();
                    }
                }
            }
        }

        private void Btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        } 
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_LableTextbox(txtSponsorCode, true, false, false);
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtSponsorID, false, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtSponsorOrganization, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtSponsorEmail, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtSponsorTpNo, true, false, false);

            txtSponsorCode.Text = "";
            txtSponsorEmail.Text = "";
            txtSponsorID.Text = "<Auto generated>";
            txtSponsorOrganization.Text = "";
            txtSponsorTpNo.Text = "";

            txtSponsorID.Tag = null;
            txtSponsorCode.Tag = null;
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_ttsTenderSponsor oDetail in tbl_ttsTenderSponsor.SelectAll().Where(p => p.IsCanceled != true && p.Sponsor_ID != "default").OrderBy(p => p.Sponsor_ID))
                {
                    dgr_Main.dt.Rows.Add(oDetail.Sponsor_ID, oDetail.Sponsor_Name, oDetail.Sponsor_Email, oDetail.Sponsor_Mobile);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion

        #region Fill Details
        private void FillDetails(string sId)
        {
            if (sId != null)
            {
                SEACC_Form.IsUpdateMode = true;

                tbl_ttsTenderSponsor oDetail = tbl_ttsTenderSponsor.Select(sId);
                if (sId != null)
                {
                    txtSponsorID.Text = oDetail.Sponsor_ID.ToString();
                    txtSponsorID.Tag = oDetail.Sponsor_ID.ToString();
                    txtSponsorOrganization.Text = oDetail.Sponsor_Name.ToString();
                    txtSponsorEmail.Text = oDetail.Sponsor_Email.ToString();
                    txtSponsorTpNo.Text = oDetail.Sponsor_Mobile.ToString();
                }  
            }
        } 
        #endregion

        #region Search 
        private void txtSponsorID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Ten_ProjectSponsor);
            if (RowDataSearch.DialogResult == true)
            {
                FillDetails(lstResult[0]);
            }
        } 
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyFields())
            {
                bStatus = true;
            }
            return bStatus;
        }

        private bool CheckValidity_EmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtSponsorID, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(txtSponsorOrganization, ref strMessage))
                bStatus = false;

            if (bStatus == false)
                SEACCMessageBox.Show("Fields cannot be Empty", strMessage, MessageBoxButton.OK);

            return bStatus;
        }
        #endregion

        #region Grid Event
        private void dgr_Main_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object oItem = dgr_Main.grdMain.SelectedItem;
                if (oItem != null)
                {
                    string sId = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text;
                    FillDetails(sId);
                }
            }
            catch (Exception ex)
            {

                SEACCExeption.Show(ex);
            }
        } 
        #endregion
   
    }
}
