using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using SEACC_WPFControls;
using DataTire;
using SEACC_Tender.UserControls;
using System.Data;
using Digiteq_Logic;
using SEACC_Tender.Search_Forms;

namespace SEACC_Tender
{
    /// <summary>
    /// Create by Janith Srimal
    /// 2017-05-17 - 2017-05-18
    /// </summary>
    public partial class UC_ttsMasCompetitor : UserControl
    {
        #region Class Variables
        DataTable dt = new DataTable(); 
        #endregion

        #region Form Load
        public UC_ttsMasCompetitor()
        {
            InitializeComponent();

            #region Form Initialize
            SEACC_Form.enmFormName = FormName.Competitors;
            SEACC_Form.Initialize();
            #endregion

            #region Data Table Initialize
            dgr_Main.dt.Columns.Add("CompetitorID");
            dgr_Main.dt.Columns.Add("Competitor");
            dgr_Main.dt.Columns.Add("Description");
            dgr_Main.dt.Columns.Add("Country");
            dgr_Main.dt.Columns.Add("City");
            #endregion

            #region Datagrid Column Initialize
            dgr_Main.Add_DatagridColoumn("CompetitorID", "CompetitorID", 100, false);
            dgr_Main.Add_DatagridColoumn("Competitor", "Competitor", 100);
            dgr_Main.Add_DatagridColoumn("Description", "Description", 100);
            dgr_Main.Add_DatagridColoumn("Country", "Country", 100);
            dgr_Main.Add_DatagridColoumn("City", "City", 100);
            #endregion

            #region Action Button Initialize
            SEACC_Form.SetVisibility_ActionButons(true, true, true, true);
            this.SEACC_Form.btn_New.Click += Btn_New_Click;
            this.SEACC_Form.btn_Cancel.Click += Btn_Cancel_Click;
            //this.SEACC_Form.btn_Print.Click += Btn_Print_Click;
            this.SEACC_Form.btn_Save.Click += Btn_Save_Click;
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Form Responsive
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 880)
                ColumnA.Width = new GridLength(200);
            else
                ColumnA.Width = new GridLength(310);
        } 
        #endregion

        #region Action Button
        private void Btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.CheckPermisshion_ToSave(SEACC_Form.IsUpdateMode))
            {
                if (CheckValidity())
                {
                    Cursor = Cursors.Wait;
                    string sCompetitorID = "";
                    try
                    {
                        sCompetitorID = txtCompetitorID.Text;
                        #region Update
                        if (SEACC_Form.IsUpdateMode)
                        {
                            tbl_ttsMasCompetitor oldDetail = tbl_ttsMasCompetitor.Select(txtCompetitorID.Text);
                            if (oldDetail != null)
                            {
                                tbl_ttsMasCompetitor oDetails = new tbl_ttsMasCompetitor(txtCompetitorID.Text, txtCompetitorCompany.Text, txtDescription.Text,
                                    txtCountry.Tag.ToString(), txtCity.Tag.ToString(), txtRemarks.Text, false);
                                oDetails.Update();

                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                        #endregion

                        #region Insert
                        else
                        {
                            if (SEACC_Form.isAutoGenaratedCode)
                                sCompetitorID = txtCompetitorID.Text = SEACC_Form.getAutoGeneratedCode();

                            tbl_ttsMasCompetitor oDetails = new tbl_ttsMasCompetitor(txtCompetitorID.Text, txtCompetitorCompany.Text, txtDescription.Text,
                                    txtCountry.Tag.ToString(), txtCity.Tag.ToString(), txtRemarks.Text, false);
                            oDetails.Insert();

                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                        }
                        #endregion

                    }
                    catch (Exception ex)
                    {
                        SEACCExeption.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Arrow;
                        ClearFields();
                        RefreshGrid();
                        FillDetails(sCompetitorID);
                    }
                }
            }
        }

        private void Btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                    if (bMessegeBoxResult)
                    {
                        tbl_ttsMasCompetitor oDetail = tbl_ttsMasCompetitor.Select(txtCompetitorID.Text);
                        if (oDetail != null)
                        {
                            oDetail.IsCanceled = true;
                            oDetail.Update();

                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }

        private void Btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        } 
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtCompetitorID, false, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtDescription, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCompetitorCompany, true, false, false);
           // cls_Formater.SetEnableDisable_LableTextbox(txtCompetitorDesignation, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtCity, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtCountry, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtRemarks, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCompetitorCode, true, false, false);

            txtCity.Text = "";
            txtCompetitorCompany.Text = "";
            //txtCompetitorDesignation.Text = "";
            txtCompetitorID.Text = "<Auto generated>";
            //txtCompetitorName.Text = "";
            txtCountry.Text = "Srilanka";
            txtRemarks.Text = "";
            txtDescription.Text = "";

            txtCountry.Tag = 94;
            txtCity.Tag = null;
            txtCompetitorID.Tag = null;

        } 
        #endregion

        #region Fill Details
        private void FillDetails(string sCompetitorID)
        {
            if (sCompetitorID != null)
            {
                SEACC_Form.IsUpdateMode = true;

                tbl_ttsMasCompetitor oCompetitor = tbl_ttsMasCompetitor.Select(sCompetitorID);

                if (oCompetitor != null)
                {
                    txtCompetitorID.Tag = oCompetitor.Competitor_Id;
                    txtCompetitorID.Text = oCompetitor.Competitor_Id;
                    txtCompetitorCompany.Text = oCompetitor.Competitor_name;
                    txtDescription.Text = oCompetitor.Competitor_Desc;
                    //txtCompetitorName.Text = oCompetitor.Competitor_Name;
                    //txtCompetitorDesignation.Text = oCompetitor.Com_Designation;
                    txtCity.Tag = oCompetitor.Com_City;
                    txtCity.Text = clsRef_Name.get_City_Name(oCompetitor.Com_City);
                    txtCountry.Tag = oCompetitor.Com_Country;
                    txtCountry.Text = clsRef_Name.get_Country_Name(oCompetitor.Com_Country);
                    txtRemarks.Text = oCompetitor.Remarks;
                }
            }
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_ttsMasCompetitor oDetail in tbl_ttsMasCompetitor.SelectAll().Where(p => p.IsCanceled != true && p.Competitor_Id != "default").OrderBy(p => p.Competitor_Id))
                {
                    dgr_Main.dt.Rows.Add(oDetail.Competitor_Id, oDetail.Competitor_name, oDetail.Competitor_Desc, clsRef_Name.get_Country_Name(oDetail.Com_Country), clsRef_Name.get_City_Name(oDetail.Com_City));
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion

        #region Search Event
        private void txtCompetitorID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Ten_Competitors);
            if (RowDataSearch.DialogResult == true)
            {
                FillDetails(lstResult[0]);
            }
        }
        private void txtCountry_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Country);
            if (RowDataSearch.DialogResult == true)
            {
                txtCountry.Tag = lstResult[0];
                txtCountry.Text = lstResult[1];

            }
        }

        private void txtCity_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            Search_Forms.frmSearch RowDataSearch = new Search_Forms.frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.City);
            if (RowDataSearch.DialogResult == true)
            {
                txtCity.Tag = lstResult[0];
                txtCity.Text = lstResult[1];
                txtCountry.Tag = lstResult[6];
                txtCountry.Text = lstResult[7];
            }
        } 
        #endregion

        #region CheckValidity
        private bool CheckValidity()
        {
            bool status = false;
            if (CheckEmptyFields())
                status = true;

            return status;
        }
        private bool CheckEmptyFields()
        {
            string strMessage = "";
            bool bStatus = true;
            if (!clsValidation.Validate_EmptyValue(txtCompetitorCompany, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(txtCountry, ref strMessage))
                bStatus = false;
            else if (!clsValidation.Validate_EmptyValue(txtCity, ref strMessage))
                bStatus = false;

            if (bStatus == false)
            {
                SEACCMessageBox.Show("Information", "Please fill the " + strMessage + " field", MessageBoxButton.OK);
            }
            return bStatus;
        } 
        #endregion

        #region DataGrid Event
        private void dgr_Main_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object oItem = dgr_Main.grdMain.SelectedItem;
                if (oItem != null)
                {
                    string sId = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(oItem) as TextBlock).Text;
                    FillDetails(sId);
                }
            }
            catch (Exception ex)
            {

                SEACCExeption.Show(ex);
            }
        } 
        #endregion

    }
}
