using DataTire;
using Digiteq_Logic;
using SEACC_PRODUCTION_APPAREL.Search;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace SEACC_PRODUCTION_APPAREL.Masters
{
    /// <summary>
    /// Interaction logic for UC_ProductionSections.xaml
    /// </summary>
    public partial class UC_Section : UserControl
    {
        #region Initialize Form
        public UC_Section()
        {
            #region Initialize Usercontrol
            InitializeComponent();
            SEACC_Form.enmFormName = FormName.CompanySectionMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("SectionID");
            dgr_Main.dt.Columns.Add("SectionName");
            dgr_Main.dt.Columns.Add("HOD");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, false, false, false);
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            //this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("Section ID", "SectionID", 75, false);
            dgr_Main.Add_DatagridColoumn("Section Name", "SectionName", 150);
            dgr_Main.Add_DatagridColoumn("Head of Section", "HOD", 300);
            #endregion

            ClearFields();
            RefreshGrid();
        }
        #endregion

        #region Form Responsiveness
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 850)
                coloumnA.Width = new GridLength(210);
            else
                coloumnA.Width = new GridLength(670);
        }
        #endregion

        #region Action Buttons
        private void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
            RefreshGrid();
        }

        private void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    #region Update
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermission_ToSave(true))
                        {
                            tbl_genSectionMaster oOldSection = tbl_genSectionMaster.Select(txtSectionID.Tag.ToString());
                            if (oOldSection != null)
                            {
                                tbl_genStoreMaster oOldStore = tbl_genStoreMaster.Select(oOldSection.Store_ID);
                                if (oOldStore != null)
                                {
                                    tbl_genStoreMaster oStore = new tbl_genStoreMaster(oOldStore.Line_No, oOldStore.Store_ID, txtSectionName.Text, txtAddress.Text, txtTelephone.Text, txtFax.Text, txtHOD.Text, oOldStore.IsDamagedStore, oOldStore.IsSingleItemStockStore, oOldStore.IsMainStore, oOldStore.IsTradingStore, oOldStore.IsSalesRepStore, oOldStore.IsShowRoom, oOldStore.IsDepartment, oOldStore.IsDeleted, clsSecurity.CompanyID, clsSecurity.BranchID,oOldStore.IsAllowMinusStock, oOldStore.IsSubContractorStore );
                                    oStore.Update();
                                }

                                tbl_genSectionMaster oSection = new tbl_genSectionMaster(oOldSection.Line_No, txtSectionID.Tag.ToString(), txtSectionName.Text, txtDepartment.Tag != null ? txtDepartment.Tag.ToString() : "default", txtAddress.Text, txtTelephone.Text, txtFax.Text, txtHOD.Text, oOldSection.SectionCost, oOldSection.OverheadRate, oOldSection.Sectioncapacity, oOldSection.Remark, oOldSection.IsExtrusion, oOldSection.IsBinSection, oOldSection.IsDeleted , oOldSection.Store_ID);
                                oSection.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    #endregion

                    #region Insert
                    else
                    {
                        if (SEACC_Form.CheckPermission_ToSave(false))
                        {
                            string sStore_Section_ID = clsAutocode.getAutoGeneratedCode("CON/073");//Store Master Next Item ID
                            tbl_genStoreMaster oStore = new tbl_genStoreMaster(1, sStore_Section_ID, txtSectionName.Text, txtAddress.Text, txtTelephone.Text, txtFax.Text, txtHOD.Text, false, false, false, false, false, false, false, false, clsSecurity.CompanyID, clsSecurity.BranchID,false , false);
                            oStore.Insert();

                            tbl_genSectionMaster oSection = new tbl_genSectionMaster(1, txtSectionID.Tag.ToString(), txtSectionName.Text, txtDepartment.Tag != null ? txtDepartment.Tag.ToString() : "default", txtAddress.Text, txtTelephone.Text, txtFax.Text, txtHOD.Text, 0, 0, 0, "", false, false, false, oStore.Store_ID);
                            oSection.Insert();

                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                        }
                    }
                    #endregion
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtSectionID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtSectionName, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtDepartment, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtAddress, true, false, true);
            cls_Formater.SetEnableDisable_LableTextbox(txtTelephone, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtFax, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtHOD, true, false, false);

            txtSectionID.Tag = null;
            txtDepartment.Tag = null;

            txtSectionID.Text = "";
            txtSectionName.Text = "";
            txtDepartment.Text = "";
            txtAddress.Text = "";
            txtTelephone.Text = "";
            txtFax.Text = "";
            txtHOD.Text = "";

            #region Auto Generate
            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtSectionID.setReadOnlyStatus(true);
                txtSectionID.Text = "<Auto Generate>";
            }
            else
                txtSectionID.setReadOnlyStatus(false);
            #endregion
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_genSectionMaster oSection in tbl_genSectionMaster.SelectAll().Where(p => p.Section_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(oSection.Section_ID, oSection.SectionName, oSection.ContactPerson);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Check validity

        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                {
                    if (ChekValidity_DuplicateNames())
                        bStatus = true;
                }
            }

            return bStatus;
        }

        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtSectionID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtSectionName))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtDepartment))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                if (SEACC_Form.isAutoGenaratedCode)
                {
                    txtSectionID.Tag = SEACC_Form.getAutoGeneratedCode();
                    txtSectionID.Text = txtSectionID.Tag.ToString();
                }

                tbl_genSectionMaster oSection = tbl_genSectionMaster.Select(txtSectionID.Text);
                if (oSection != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }

        public bool ChekValidity_DuplicateNames()
        {
            bool bStatus = true;
            foreach (tbl_genSectionMaster osection in tbl_genSectionMaster.SelectAll().Where(p => p.SectionName == txtSectionName.Text && p.Section_ID != txtSectionID.Text))
            {
                bStatus = false;
                SEACCMessageBox.Show(MessegeBoxType.FieldAlreadyExist);
                break;
            }
            return bStatus;
        }

        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                tbl_genSectionMaster oSection = tbl_genSectionMaster.Select(sID);
                if (oSection != null)
                {
                    SEACC_Form.IsUpdateMode = true;

                    txtSectionID.Tag = oSection.Section_ID;
                    txtDepartment.Tag = oSection.Department_ID;

                    txtSectionID.Text = oSection.Section_ID;
                    txtSectionName.Text = oSection.SectionName;
                    txtDepartment.Text = clsGenaralName.getName_Department(oSection.Department_ID);
                    txtAddress.Text = oSection.Adress;
                    txtTelephone.Text = oSection.Telephone;
                    txtFax.Text = oSection.Fax;
                    txtHOD.Text = oSection.ContactPerson;
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }

        #endregion

        #region Grid Events
        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search Events
        private void txtSectionID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frm_search RowDataSearch = new frm_search();
            RowDataSearch.WindowStartupLocation = WindowStartupLocation.CenterScreen;
            List<string> lstResult = RowDataSearch.Show(Digiteq_Logic.Search.Prod_ProcductionSections);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                fillDetails(lstResult[0]);
            }
        }


        private void txtDepartment_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frm_search RowDataSearch = new frm_search();
            RowDataSearch.WindowStartupLocation = WindowStartupLocation.CenterScreen;
            List<string> lstResult = RowDataSearch.Show(Digiteq_Logic.Search.Prod_ProductionDepartment);
            if (RowDataSearch.DialogResult == true)
            {
                txtDepartment.Tag = lstResult[0];
                txtDepartment.Text = lstResult[1];
            }
        }

        #endregion

        #region Kye Press Events
        private void SEACC_Form_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.F5)
            {
                btn_New_Click(sender, e);
            }
        } 
        #endregion
    }
}
