using DataTire;
using Digiteq_Logic;
using SEACC_servii.Search_Forms;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_CustomerCategoryMaster.xaml
    /// </summary>
    public partial class UC_CustomerCategoryMaster : UserControl
    {
        public UC_CustomerCategoryMaster()
        {
            #region User Control Initialize
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.CustomerCategoryMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("CustomerCat_ID");
            dgr_Main.dt.Columns.Add("customerCatName");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "CustomerCat_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "customerCatName", 150);
            #endregion

            ClearFields();
            RefreshGrid();
        }


        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zCustomerCategory item in tbl_zCustomerCategory.SelectAll().Where(p => p.CustomerCategory_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.CustomerCategory_ID, item.CategoryName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtCustomerCatID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCustomerCatName, true, false, false);

            txtCustomerCatID.Text = "";
            txtCustomerCatName.Text = "";

            txtCustomerCatID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtCustomerCatID.setReadOnlyStatus(true);
                txtCustomerCatID.Text = "<Auto Generate>";
            }
            else
                txtCustomerCatID.setReadOnlyStatus(false);
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zCustomerCategory OldClass = tbl_zCustomerCategory.Select(txtCustomerCatID.Text);
                            if (OldClass != null)
                            {
                                tbl_zCustomerCategory oClass = new tbl_zCustomerCategory(txtCustomerCatID.Text, txtCustomerCatName.Text);
                                oClass.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtCustomerCatID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zCustomerCategory nClass = new tbl_zCustomerCategory(txtCustomerCatID.Text, txtCustomerCatName.Text);
                        nClass.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
        }

        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtCustomerCatID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtCustomerCatName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zCustomerCategory oDetail = tbl_zCustomerCategory.Select(txtCustomerCatID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zCustomerCategory FillDetails = tbl_zCustomerCategory.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtCustomerCatID.IsEnabled = false;

                        txtCustomerCatID.Text = FillDetails.CustomerCategory_ID;
                        txtCustomerCatName.Text = FillDetails.CategoryName;

                        txtCustomerCatID.Tag = FillDetails.CustomerCategory_ID;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event

        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        
        #endregion

        #region Search Event
        private void txtCustomerCatID_MouseDoubleClick_1(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.CustomerCategory);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtCustomerCatID.Text = lstResult[0];
                txtCustomerCatName.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        } 
        #endregion
    }
}
