using DataTire;
using Digiteq_Logic;
using SEACC_servii.Search_Forms;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_CustomerClassMater.xaml
    /// </summary>
    public partial class UC_CustomerClassMater : UserControl
    {
        #region From Load
        public UC_CustomerClassMater()
        {
            #region User Control Initialize
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.CustomerClassMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("CustomerClass_ID");
            dgr_Main.dt.Columns.Add("customerClassName");
            dgr_Main.dt.Columns.Add("Prefix");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "CustomerClass_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "customerClassName", 150);
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zCustomerClass item in tbl_zCustomerClass.SelectAll().Where(p => p.CustomerClass_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.CustomerClass_ID, item.ClassName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtCustomerClassID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCustomerClassName, true, false, false);

            txtCustomerClassID.Text = "";
            txtCustomerClassName.Text = "";

            txtCustomerClassID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtCustomerClassID.setReadOnlyStatus(true);
                txtCustomerClassID.Text = "<Auto Generate>";
            }
            else
                txtCustomerClassID.setReadOnlyStatus(false);
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zCustomerClass OldClass = tbl_zCustomerClass.Select(txtCustomerClassID.Text);
                            if (OldClass != null)
                            {
                                tbl_zCustomerClass oClass = new tbl_zCustomerClass(txtCustomerClassID.Text, txtCustomerClassName.Text);
                                oClass.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtCustomerClassID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zCustomerClass nClass = new tbl_zCustomerClass(txtCustomerClassID.Text, txtCustomerClassName.Text);
                        nClass.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            //if (SEACC_Form.IsUpdateMode)
            //{
            //    if (txtDistrictCode.Tag != null)
            //    {
            //        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);

            //        if (bMessegeBoxResult)
            //        {
            //            tbl_genMasDistrict oDistrict = tbl_genMasDistrict.Select(txtDistrictCode.Text.Trim());
            //            if (oDistrict != null)
            //            {
            //                oDistrict.IsCanceled = true;
            //                oDistrict.Date_Canceled = clsSecurity.getServerDateTime();
            //                oDistrict.TerminalID_Canceled = clsSecurity.TerminalID;
            //                oDistrict.Update();
            //                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
            //                ClearFields();
            //                RefreshGrid();
            //            }
            //        }
            //    }
            //}
        }

        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtCustomerClassID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtCustomerClassName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zCustomerClass oDetail = tbl_zCustomerClass.Select(txtCustomerClassID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zCustomerClass FillDetails = tbl_zCustomerClass.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtCustomerClassID.IsEnabled = false;

                        txtCustomerClassID.Text = FillDetails.CustomerClass_ID;
                        txtCustomerClassName.Text = FillDetails.ClassName;

                        txtCustomerClassID.Tag = FillDetails.CustomerClass_ID;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event

        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion

        #region Search Event
        private void txtCustomerClassID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.CustomerClass);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtCustomerClassID.Text = lstResult[0];
                txtCustomerClassID.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        } 
        #endregion
    }
}
