using DataTire;
using Digiteq_Logic;
using SEACC_servii.Search_Forms;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_CustomerTypeMaster.xaml
    /// </summary>
    public partial class UC_CustomerTypeMaster : UserControl
    {
        public UC_CustomerTypeMaster()
        {
            #region User Control Initialize
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.CustomerTypeMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("CustomeType_ID");
            dgr_Main.dt.Columns.Add("CustomerTypeName");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "CustomeType_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "CustomerTypeName", 150);
            #endregion

            ClearFields();
            RefreshGrid();
        }

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zCustomerType item in tbl_zCustomerType.SelectAll().Where(p => p.CustomerType_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.CustomerType_ID, item.TypeName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtCustomerTypeID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtCustomerTypeName, true, false, false);

            txtCustomerTypeID.Text = "";
            txtCustomerTypeName.Text = "";

            txtCustomerTypeID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtCustomerTypeID.setReadOnlyStatus(true);
                txtCustomerTypeID.Text = "<Auto Generate>";
            }
            else
                txtCustomerTypeID.setReadOnlyStatus(false);
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zCustomerType Oldtype = tbl_zCustomerType.Select(txtCustomerTypeID.Text);
                            if (Oldtype != null)
                            {
                                tbl_zCustomerType otype = new tbl_zCustomerType(txtCustomerTypeID.Text, txtCustomerTypeName.Text);
                                otype.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtCustomerTypeID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zCustomerType ntype = new tbl_zCustomerType(txtCustomerTypeID.Text, txtCustomerTypeName.Text);
                        ntype.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
        }

        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtCustomerTypeID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtCustomerTypeName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zCustomerType oDetail = tbl_zCustomerType.Select(txtCustomerTypeID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zCustomerType FillDetails = tbl_zCustomerType.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtCustomerTypeID.IsEnabled = false;

                        txtCustomerTypeID.Text = FillDetails.CustomerType_ID;
                        txtCustomerTypeName.Text = FillDetails.TypeName;

                        txtCustomerTypeID.Tag = FillDetails.CustomerType_ID;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Events
        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion


        #region Search Event
        private void txtCustomerTypeID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.CustomerType);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtCustomerTypeID.Text = lstResult[0];
                txtCustomerTypeID.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        } 
        #endregion
    }
}
