using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DataTire;
using SEACC_WPFControls;
using Digiteq_Logic;
using System.Data;
using SEACC_servii.Search_Forms;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_ItemClassMaster.xaml
    /// </summary>
    public partial class UC_ItemClassMaster : UserControl
    {
        #region Form Load
        public UC_ItemClassMaster()
        {
            #region User Control Initialize
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.ItemClassMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("ItemClass_ID");
            dgr_Main.dt.Columns.Add("ClassName");
            dgr_Main.dt.Columns.Add("Prefix");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "ItemClass_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "ClassName", 150);
            dgr_Main.Add_DatagridColoumn("Prefix", "Prefix", 80);
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zItemClass item in tbl_zItemClass.SelectAll().Where(p => p.ItemClass_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.ItemClass_ID, item.ClassName, item.Prefrix);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zItemClass OldDetails = tbl_zItemClass.Select(txtItemClassID.Text.Trim());
                            if (OldDetails != null)
                            {
                                tbl_zItemClass oClass = new tbl_zItemClass(txtItemClassID.Text, txtItemClassName.Text, txtItemClassPrefix.Text);
                                oClass.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtItemClassID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zItemClass nClass = new tbl_zItemClass(txtItemClassID.Text, txtItemClassName.Text, txtItemClassPrefix.Text);
                        nClass.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            //if (SEACC_Form.IsUpdateMode)
            //{
            //    if (txtDistrictCode.Tag != null)
            //    {
            //        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);

            //        if (bMessegeBoxResult)
            //        {
            //            tbl_genMasDistrict oDistrict = tbl_genMasDistrict.Select(txtDistrictCode.Text.Trim());
            //            if (oDistrict != null)
            //            {
            //                oDistrict.IsCanceled = true;
            //                oDistrict.Date_Canceled = clsSecurity.getServerDateTime();
            //                oDistrict.TerminalID_Canceled = clsSecurity.TerminalID;
            //                oDistrict.Update();
            //                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
            //                ClearFields();
            //                RefreshGrid();
            //            }
            //        }
            //    }
            //}
        }



        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtItemClassID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtItemClassName, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtItemClassPrefix, true, false, false);

            txtItemClassID.Text = "";
            txtItemClassName.Text = "";
            txtItemClassPrefix.Text = "";

            txtItemClassID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtItemClassID.setReadOnlyStatus(true);
                txtItemClassID.Text = "<Auto Generate>";
            }
            else
                txtItemClassID.setReadOnlyStatus(false);
        }
        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtItemClassID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtItemClassName))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtItemClassPrefix))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zItemClass oDetail = tbl_zItemClass.Select(txtItemClassID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zItemClass FillDetails = tbl_zItemClass.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtItemClassID.IsEnabled = false;
                        txtItemClassID.Text = FillDetails.ItemClass_ID;
                        txtItemClassID.Tag = FillDetails.ItemClass_ID;

                        txtItemClassName.Text = FillDetails.ClassName;
                        txtItemClassPrefix.Text = FillDetails.Prefrix;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event
        private void grd_ItemClass_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search Event
        private void txtItemClassID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ItemClass);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtItemClassID.Text = lstResult[0];
                txtItemClassID.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        }
        #endregion
    }
}
