using DataTire;
using Digiteq_Logic;
using SEACC_servii.Search_Forms;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_ItemBrandMaster.xaml
    /// </summary>
    public partial class UC_ItemBrandMaster : UserControl
    {
        public UC_ItemBrandMaster()
        {
            #region User Control Initialize
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.ItemBrandMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("Brand_ID");
            dgr_Main.dt.Columns.Add("BrandName");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "Brand_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "BrandName", 150);
            #endregion

            ClearFields();
            RefreshGrid();
        }

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zBrand OldDetails = tbl_zBrand.Select(txtBrandID.Text.Trim());
                            if (OldDetails != null)
                            {
                                tbl_zBrand oBrand = new tbl_zBrand(txtBrandID.Text, txtBrandName.Text);
                                oBrand.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtBrandID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zBrand nBrand = new tbl_zBrand(txtBrandID.Text, txtBrandName.Text);
                        nBrand.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {

        }



        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtBrandID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtBrandName, true, false, false);

            txtBrandID.Text = "";
            txtBrandName.Text = "";

            txtBrandID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtBrandID.setReadOnlyStatus(true);
                txtBrandID.Text = "<Auto Generate>";
            }
            else
                txtBrandID.setReadOnlyStatus(false);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zBrand item in tbl_zBrand.SelectAll().Where(p => p.Brand_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.Brand_ID, item.BrandName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtBrandID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtBrandName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zBrand oDetail = tbl_zBrand.Select(txtBrandID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zBrand FillDetails = tbl_zBrand.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtBrandID.IsEnabled = false;
                        txtBrandID.Text = FillDetails.Brand_ID;
                        txtBrandName.Text = FillDetails.BrandName;

                        txtBrandID.Tag = FillDetails.Brand_ID;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Events
        private void dgr_Main_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        } 
        #endregion

        #region Search Events
        private void txtBrandID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.ItemBrand);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtBrandID.Text = lstResult[0];
                txtBrandID.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        }       
        #endregion

    }
}
