using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DataTire;
using SEACC_WPFControls;
using Digiteq_Logic;
using System.Data;
using SEACC_servii.Search_Forms;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_TaxMaster.xaml
    /// </summary>
    public partial class UC_TaxMaster : UserControl
    {
        public UC_TaxMaster()
        {
            #region Initialize Usercontrol
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.TaxMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("TaxID");
            dgr_Main.dt.Columns.Add("TaxName");
            dgr_Main.dt.Columns.Add("TaxPesentage");
            dgr_Main.dt.Columns.Add("EffectiveFromDate");
            dgr_Main.dt.Columns.Add("EffectiveToDate");
            dgr_Main.dt.Columns.Add("IsActive", typeof(bool));
            dgr_Main.dt.Columns.Add("PayableGl_ID");
            dgr_Main.dt.Columns.Add("ReceivableGl_ID");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("Tax ID", "TaxID", 80);
            dgr_Main.Add_DatagridColoumn("Tax Name", "TaxName", 100);
            dgr_Main.Add_DatagridColoumn("Tax %.", "TaxPesentage", 80);
            dgr_Main.Add_DatagridColoumn("Effective From", "EffectiveFromDate", 90);
            dgr_Main.Add_DatagridColoumn( "Effective To", "EffectiveToDate", 90);
            dgr_Main.Add_DatagridColoumn("Is Active", "IsActive", 55);
            dgr_Main.Add_DatagridColoumn("Payable GL ID", "PayableGl_ID", 100, false);
            dgr_Main.Add_DatagridColoumn("Receivable GL ID", "ReceivableGl_ID", 100, false);
            #endregion

            ClearFields();
            RefreshGrid();
        }


        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zTax item in tbl_zTax.SelectAll().Where(p => p.Tax_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.Tax_ID, item.TaxName, item.TaxPesentage,"","",true, item.PayableGl_ID, item.ReceivableGl_ID);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zTax OldDetails = tbl_zTax.Select(txtTaxID.Text.Trim());
                            if (OldDetails != null)
                            {
                                tbl_zTax oDistrict = new tbl_zTax(txtTaxID.Text, txtTaxName.Text, decimal.Parse(txtTaxPecentage.Text) , txtPayableGL_ID.Text, txtReceibleGL_ID.Text);
                                oDistrict.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtTaxID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zTax oDistrict = new tbl_zTax(txtTaxID.Text, txtTaxName.Text, decimal.Parse(txtTaxPecentage.Text), txtPayableGL_ID.Text, txtReceibleGL_ID.Text);
                        oDistrict.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            if (SEACC_Form.IsUpdateMode)
            {
                if (txtTaxID.Tag != null)
                {
                    bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);

                    if (bMessegeBoxResult)
                    {
                        tbl_zTax oTax = tbl_zTax.Select(txtTaxID.Text.Trim());
                        if (oTax != null)
                        {
                            oTax.Delete();
                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }



        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtTaxID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtTaxName, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtTaxPecentage, true, true, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtPayableGL_ID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtReceibleGL_ID, true, false, false);

            txtTaxID.Text = "";
            txtTaxName.Text = "";
            txtTaxPecentage.Text = "";
            txtPayableGL_ID.Text = "";
            txtReceibleGL_ID.Text = "";

            txtTaxID.Tag = null;

            chkIsActiveTax.IsChecked = false;
            chkIsActiveTax.IsChecked = false;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtTaxID.setReadOnlyStatus(true);
                txtTaxID.Text = "<Auto Generate>";
            }
            else
                txtTaxID.setReadOnlyStatus(false);
        }
        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtTaxID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtTaxName))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtTaxPecentage))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtPayableGL_ID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtReceibleGL_ID))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zTax oDetail = tbl_zTax.Select(txtTaxName.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zTax FillDetails = tbl_zTax.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtTaxID.IsEnabled = false;
                        txtTaxID.Text = FillDetails.Tax_ID;
                        txtTaxID.Tag = FillDetails.Tax_ID;
                        txtTaxName.Text = FillDetails.TaxName;
                        txtTaxPecentage.Text = FillDetails.TaxPesentage.ToString();
                        txtPayableGL_ID.Text = FillDetails.PayableGl_ID;
                        txtReceibleGL_ID.Text = FillDetails.ReceivableGl_ID;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event
        private void grd_District_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search Event
        private void txtTaxID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Tax);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtTaxID.Text = lstResult[0];
                fillDetails(lstResult[0]);
            }

        }
        #endregion
    }
}
