using DataTire;
using Digiteq_Logic;
using SEACC_servii.Search_Forms;
using SEACC_WPFControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SEACC_servii.Master_Forms
{
    /// <summary>
    /// Interaction logic for UC_UomCategoryMaster.xaml
    /// </summary>
    public partial class UC_UomCategoryMaster : UserControl
    {
        #region Form Load
        public UC_UomCategoryMaster()
        {
            #region Initialize Usercontrol
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.CategoryOfUnitOfMeasureMaster;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("UoM_Catogory_ID");
            dgr_Main.dt.Columns.Add("UoM_Catogory_Name");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("ID", "UoM_Catogory_ID", 80);
            dgr_Main.Add_DatagridColoumn("Name", "UoM_Catogory_Name", 150);
            #endregion

            ClearFields();
            RefreshGrid();
        } 
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_zUomCategory item in tbl_zUomCategory.SelectAll().Where(p => p.UomCategory_ID != "default"))
                {
                    dgr_Main.dt.Rows.Add(item.UomCategory_ID, item.CategoryName);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Action Buttons
        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            tbl_zUomCategory OldDetails = tbl_zUomCategory.Select(txtUomCategoryID.Text.Trim());
                            if (OldDetails != null)
                            {
                                tbl_zUomCategory oClass = new tbl_zUomCategory(txtUomCategoryID.Text, txtUomCategoryName.Text);
                                oClass.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                        }
                    }
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtUomCategoryID.Text = SEACC_Form.getAutoGeneratedCode();
                        tbl_zUomCategory nClass = new tbl_zUomCategory(txtUomCategoryID.Text, txtUomCategoryName.Text);
                        nClass.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    ClearFields();
                    RefreshGrid();
                }
            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            cls_Formater.SetEnableDisable_PrimaryKeyLabelTextBox(txtUomCategoryID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtUomCategoryName, true, false, false);

            txtUomCategoryID.Text = "";
            txtUomCategoryName.Text = "";

            txtUomCategoryID.Tag = null;

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtUomCategoryID.setReadOnlyStatus(true);
                txtUomCategoryID.Text = "<Auto Generate>";
            }
            else
                txtUomCategoryID.setReadOnlyStatus(false);
        }
        #endregion

        #region Check validity
        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;

            if (!clsValidation.Validate_EmptyValue(txtUomCategoryID))
                bStatus = false;
            if (!clsValidation.Validate_EmptyValue(txtUomCategoryName))
                bStatus = false;

            return bStatus;
        }

        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_zUomCategory oDetail = tbl_zUomCategory.Select(txtUomCategoryID.Text);
                if (oDetail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }
            return bStatus;
        }
        #endregion

        #region Fill Details
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_zUomCategory FillDetails = tbl_zUomCategory.Select(sID);
                    if (FillDetails != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtUomCategoryID.IsEnabled = false;
                        txtUomCategoryID.Text = FillDetails.UomCategory_ID;
                        txtUomCategoryID.Tag = FillDetails.UomCategory_ID;

                        txtUomCategoryName.Text = FillDetails.CategoryName;
                        txtUomCategoryName.Text = FillDetails.CategoryName;
                    }
                }

            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Events
        private void grd_UOMCategory_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Search Events
        private void txtUomCategoryID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.UOM_Categories);
            if (RowDataSearch.DialogResult == true)
            {
                ClearFields();
                txtUomCategoryID.Text = lstResult[0];
                txtUomCategoryID.Tag = lstResult[0];
                fillDetails(lstResult[0]);
            }
        } 
        #endregion
    }
}
