using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Digiteq_Logic;
using DataTire;
using Digiteq_Logic;
using SEACC_WPFControls;
using System.Data;

namespace Digiteq
{
    /// <summary>
    /// Interaction logic for UC_RequestForLetter.xaml
    /// </summary>
    public partial class UC_RequestForLetter : UserControl
    {
        #region Class Variables
        DataTable dtMain = new DataTable();
        string sLetterID = string.Empty;
        #endregion

        #region Form Load
        public UC_RequestForLetter()
        {
            #region Initialize Usercontrol
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.Request_For_Letter;
            SEACC_Form.Initialize(); 
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("LetterID");
            dgr_Main.dt.Columns.Add("LetterName");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(false, false, false, false); 
            #endregion
            
            SEACC_Form.SetVisibility_HorizontalRule(false);

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("Letter ID", "LetterID", 0);
            dgr_Main.Add_DatagridColoumn("Letter Name", "LetterName", 220); 
            #endregion

            RefreshGrid();
        }
        #endregion

        #region Action Button
        private void btn_Addnew_Click(object sender, RoutedEventArgs e)
        {
            ClearFields();
        }

        private void btn_Edit_Click(object sender, RoutedEventArgs e)
        {
            if (ChekValidity())
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    if (SEACC_Form.CheckPermisshion_ToUpdate())
                    {
                        tbl_cfg_RequestLetter oldRecord = tbl_cfg_RequestLetter.Select(sLetterID);
                        if (oldRecord != null)
                        {
                            string sletterContect = new TextRange(txtLetterArea.Document.ContentStart, txtLetterArea.Document.ContentEnd).Text;
                            tbl_cfg_RequestLetter detail = new tbl_cfg_RequestLetter(sLetterID, oldRecord.Letter_Name, sletterContect, oldRecord.IsCanceled, oldRecord.UserID_Created, clsSecurity.UserIDLoged, oldRecord.UserID_Canceled, oldRecord.TerminalID_Created, clsSecurity.TerminalID, oldRecord.TerminalID_Canceled, oldRecord.Date_Created, clsSecurity.getServerDateTime(), oldRecord.Date_Canceled);
                            detail.Update();
                            SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                        }
                    }
                }
                else
                {
                    string sletterContect = new TextRange(txtLetterArea.Document.ContentStart, txtLetterArea.Document.ContentEnd).Text;
                    if (SEACC_Form.isAutoGenaratedCode)
                        sLetterID = SEACC_Form.getAutoGeneratedCode();

                    tbl_cfg_RequestLetter details = new tbl_cfg_RequestLetter(sLetterID, "Default", sletterContect, false, clsSecurity.UserIDLoged, "Default", "Default", clsSecurity.TerminalID, "Default", "Default", clsSecurity.getServerDateTime(), clsConfig.defaultDateTime, clsConfig.defaultDateTime);
                    details.Insert();
                    SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);
                }
            }
        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    if (sLetterID != null)
                    {
                        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                        if (bMessegeBoxResult)
                        {
                            tbl_cfg_RequestLetter detail = tbl_cfg_RequestLetter.Select(sLetterID);
                            if (detail != null)
                            {
                                detail.IsCanceled = true;
                                detail.Date_Canceled = clsSecurity.getServerDateTime();
                                detail.TerminalID_Canceled = clsSecurity.TerminalID;
                                detail.UserID_Canceled = clsSecurity.UserIDLoged;
                                detail.Update();

                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                                ClearFields();
                                RefreshGrid();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            SEACC_Form.IsUpdateMode = false;
            txtLetterArea.Document.Blocks.Clear();
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_cfg_RequestLetter detail in tbl_cfg_RequestLetter.SelectAll().Where(p => p.IsCanceled == false))
                {
                    dgr_Main.dt.Rows.Add(detail.Letter_ID, detail.Letter_Name);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool ChekValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyFields())
                bStatus = true;

            return bStatus;
        }

        private bool CheckValidity_EmptyFields()
        {
            bool bStatus = true;
            TextRange TextRange = new TextRange(txtLetterArea.Document.ContentStart, txtLetterArea.Document.ContentEnd);
            if (TextRange.Text == "")
            {
                bStatus = false;
            }

            return bStatus;
        }
        #endregion

        #region Grid Event
        private void grd_RequestLetter_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    if (GridID != null)
                    {
                        sLetterID = GridID;
                        SEACC_Form.IsUpdateMode = true;
                        tbl_cfg_RequestLetter detail = tbl_cfg_RequestLetter.Select(sLetterID);
                        if (detail != null)
                        {
                            TextRange TextRange = new TextRange(txtLetterArea.Document.ContentStart, txtLetterArea.Document.ContentEnd);
                            TextRange.Text = detail.Letter.ToString();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion
    }
}
