using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;

namespace Digiteq
{
    public partial class frm_mtrCurrency : MettroForm
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail  
        string sFormConfigCode; 
           public int iFormID;
        public bool bNoAccess; 
        #endregion

        #region Form Load
        public frm_mtrCurrency()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ZCurrency);
            iFormID = clsSecurity.getFormID(FormName.ZCurrency);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_mtrCurrency_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format            
            RefreshGrid();
            //RefreshGridHistory();
            CusDataGridViewFormat();

            ClearFields();
        }
        #endregion


        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {          
            ClearFields();            
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (tabControl1.SelectedTab == currencyMaster)
            {
                if (CheckValidity())
                {
                    if (CheckNumberValidity())
                    {
                        if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                        {
                            try
                            {
                                Cursor = Cursors.WaitCursor;
                                if (txtCurrencyID.TextLength > 0)
                                {
                                    if (IsUpdate)  //update records
                                    {
                                        tbl_zCurrency oldRecord = tbl_zCurrency.Select(txtCurrencyID.Text.Trim());
                                        if (oldRecord != null)
                                        {
                                            //Country Header
                                            tbl_zCurrency detail = new tbl_zCurrency(txtCurrencyID.Text.Trim(), txtCurrencyName.Text.Trim(), txtCurrencyCode.Text.Trim(), decimal.Parse(txtCurrencyRate.Text), decimal.Parse(txtBuyingRate.Text), clsSecurity.getServerDateTime());
                                            detail.Update();

                                            //insert histry record
                                            tbl_zCurrency_History detail2 = new tbl_zCurrency_History(clsHelpMethods.GetMaxzimumLineNoCurrencyMasterHistory(txtCurrencyID.Text.Trim()), txtCurrencyID.Text.Trim(), dtpCurrencyMasValiFrom.Value, clsSecurity.getServerDateTime(), decimal.Parse(txtCurrencyRate.Text), decimal.Parse(txtBuyingRate.Text), "", clsSecurity.UserIDLoged, clsSecurity.TerminalID, clsSecurity.getServerDateTime());
                                            detail2.Insert();
                                            clsHelpMethods.InsertTransactionHistory(iFormID, txtCurrencyID.Text, TxnActivity.Update);
                                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                        }
                                    }
                                    else  //insert records
                                    {
                                        if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                            txtCurrencyID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                        //Inquiry Header
                                        tbl_zCurrency detail = new tbl_zCurrency(txtCurrencyID.Text.Trim(), txtCurrencyName.Text.Trim(), txtCurrencyCode.Text.Trim(), decimal.Parse(txtCurrencyRate.Text), decimal.Parse(txtBuyingRate.Text), clsSecurity.getServerDateTime());
                                        detail.Insert();

                                        //insert histry record
                                        tbl_zCurrency_History detail2 = new tbl_zCurrency_History(clsHelpMethods.GetMaxzimumLineNoCurrencyMasterHistory(txtCurrencyID.Text.Trim()), txtCurrencyID.Text.Trim(), dtpCurrencyMasValiFrom.Value, clsSecurity.getServerDateTime(), decimal.Parse(txtCurrencyRate.Text), decimal.Parse(txtBuyingRate.Text), "default", clsSecurity.UserIDLoged, clsSecurity.TerminalID, clsSecurity.getServerDateTime());
                                        detail2.Insert();
                                        clsHelpMethods.InsertTransactionHistory(iFormID, txtCurrencyID.Text, TxnActivity.Insert);
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else
                                {
                                    MessageBox.Show("Currency " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            catch (Exception ex)
                            {
                                clsValidate.WriteErrorLog("", iFormID,ex);
                                SEACCException.Show(ex);
                            }
                            finally
                            {
                                Cursor = Cursors.Default;
                                ClearFields();
                                RefreshGrid();
                                //RefreshGridHistory();
                            }
                        }
                    }
                }

            }
        }


        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (tabControl1.SelectedTab == currencyMaster)
                {
                    if (txtCurrencyID.TextLength > 0)
                    {
                        if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                        {
                            //delete one record
                            Cursor = Cursors.WaitCursor;
                            tbl_zCurrency detail = tbl_zCurrency.Select(txtCurrencyID.Text.Trim());
                            if (detail != null)
                            {
                                detail.Delete();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtCurrencyID.Text, TxnActivity.Cancel);
                            }

                            Cursor = Cursors.Default;
                            MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            ClearFields();
                            RefreshGrid();
                        }
                       
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Remove
        private void btnRemove_Click(object sender, EventArgs e)
        {
            if (tabControl1.SelectedTab == currencyMaster)
            {
                try
                {
                    if (dgvDetail.SelectedCells.Count != 0)
                    {
                        if (dgvDetail.Rows.Count > 1)
                            dgvDetail.Rows.RemoveAt(dgvDetail.SelectedCells[0].RowIndex);
                    }
                }
                catch (Exception ex)
                {
                    clsValidate.WriteErrorLog("", iFormID,ex);
                    SEACCException.Show(ex);
                }
            }
        }
        #endregion
        
        
        #region Fill Details
        private void FillDetails(string cID)
        {
            try
            {
                if (cID.Length > 0)
                {
                    tbl_zCurrency detail = tbl_zCurrency.Select(cID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCurrencyID, false);
                        clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyName, true);
                        clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyCode, true);
                        clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyRate, true);

                        //asign values
                        txtCurrencyID.Text = detail.Currency_ID;
                        txtCurrencyName.Text = detail.CurrencyName;
                        txtCurrencyCode.Text = detail.CurrencyCode;
                        txtCurrencyRate.Text = detail.CurrencyRate.ToString();
                    }

                    RefreshGridHistoryByCurrencyID(cID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
            clsFormatter.ApplyGridFormat(dgvDetailHistory);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCurrencyID, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyName, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyCode, true);
            clsCommon.SetEnableDisable_NormalTextbox(txtCurrencyRate, true);

            txtCurrencyName.Clear();
            txtCurrencyCode.Clear();
            txtCurrencyRate.Clear();
            txtBuyingRate.Text = "0.00";

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtCurrencyID.Text = "<Auto Generate>";
            else
                txtCurrencyID.Clear();
            if (txtCurrencyID.Enabled)
            {
                txtCurrencyID.SelectAll();
                txtCurrencyID.Focus();
            }
            dgvDetailHistory.Rows.Clear();
        }
        #endregion

        #region Refresh
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<tbl_zCurrency> details = tbl_zCurrency.SelectAll();
                foreach (tbl_zCurrency detail in details)
                {
                    if (detail.Currency_ID.Trim() != "default")
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["CurrencyID", iRow].Value = detail.Currency_ID;
                        dgvDetail["CurrencyName", iRow].Value = detail.CurrencyName;
                        dgvDetail["currencyCode", iRow].Value = detail.CurrencyCode;
                        dgvDetail["currencyRate", iRow].Value = detail.CurrencyRate;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void RefreshGridHistory() 
        {
            try
            {
                int iRow;
                dgvDetailHistory.Rows.Clear();
                List<tbl_zCurrency_History> details = tbl_zCurrency_History.SelectAll();
                foreach (tbl_zCurrency_History detail in details)
                {
                    if (detail.Currency_ID.Trim() != "default")
                    {
                        dgvDetailHistory.Rows.Add();
                        iRow = dgvDetailHistory.Rows.Count - 1;
                        dgvDetailHistory["ValidateFrom", iRow].Value = clsFormatter.FormatDate_Short(detail.DateValidFrom);
                        dgvDetailHistory["ValidateTill", iRow].Value = clsFormatter.FormatDate_Short(detail.DateValidTill);
                        dgvDetailHistory["CRate", iRow].Value = detail.CurrencyRate;
                        dgvDetailHistory["ModifiedUser", iRow].Value = detail.CreateUser_ID;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void RefreshGridHistoryByCurrencyID(string sID)
        {
            try
            {
                int iRow;
                dgvDetailHistory.Rows.Clear();
                List<tbl_zCurrency_History> details = tbl_zCurrency_History.SelectAllByCurrency_ID(sID);
                foreach (tbl_zCurrency_History detail in details)
                {
                    if (detail.Currency_ID.Trim() != "default")
                    {
                        dgvDetailHistory.Rows.Add();
                        iRow = dgvDetailHistory.Rows.Count - 1;
                        dgvDetailHistory["ValidateFrom", iRow].Value = clsFormatter.FormatDate_Short(detail.DateValidFrom);
                        dgvDetailHistory["ValidateTill", iRow].Value = clsFormatter.FormatDate_Short(detail.DateValidTill);
                        dgvDetailHistory["CRate", iRow].Value = detail.CurrencyRate;
                        dgvDetailHistory["ModifiedUser", iRow].Value = detail.CreateUser_ID;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtCurrencyName.TextLength == 0)
            {
                strMessage += "\n" + "Currency Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {
                

            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion


        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string cID = dgvDetail["currencyID", e.RowIndex].Value.ToString();
                    if (cID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(cID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Events Events KeyDown
        private void txtCurrencyID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_CurrencyID();
            }
        }

        private void frm_mtrCurrency_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtCurrencyID_DoubleClick(object sender, EventArgs e)
        {
            Search_CurrencyID();
        }
        #endregion

        #region Events KeyPress
        private void txtCurrencyRate_KeyPress(object sender, KeyPressEventArgs e)
        {            
            clsValidate.AllowDecimal(txtCurrencyID.Text.Trim(), e);
        }
        private void txtBuyingRate_KeyPress(object sender, KeyPressEventArgs e)
        {
            clsValidate.AllowDecimal(txtBuyingRate.Text.Trim(), e);
        }
        #endregion

        #region Event TabIndexChanged
        private void tabControl1_TabIndexChanged(object sender, EventArgs e)
        {
            if (tabControl1.SelectedTab == CurrencyHistory)
            {
                RefreshGridHistoryByCurrencyID(txtCurrencyID.Tag.ToString());
            }
            else
            {
                dgvDetailHistory.Rows.Clear();
            }
        }
        #endregion

        #region Search Methods
        private void Search_CurrencyID()
        {
            try
            {

                clsSearch.Search_MasterCurrency(ref txtCurrencyID);
                if (txtCurrencyID.TextLength > 0)
                {
                    FillDetails(txtCurrencyID.Tag.ToString());
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion              

        
    }
}
