using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_mtrCostCenter4 : MettroForm
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_mtrCostCenter4()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.Cost_Center4);
            iFormID = clsSecurity.getFormID(FormName.Cost_Center4);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_mtrCostCenter4_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
            //lblCostCenterID.Text = clsConfig.sCostCenter4 + " ID"; ;
            //lblCostCenterName.Text = clsConfig.sCostCenter4;
            //this.Text = clsConfig.sCostCenter4;
            //dgvDetail.Columns["clmCostCenterID"].HeaderText = clsConfig.sCostCenter4 + " ID";
            //dgvDetail.Columns["clmCostCenterName"].HeaderText = clsConfig.sCostCenter4;
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (CheckValidity())
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                          tbl_zCost_Center4 detail =   tbl_zCost_Center4.Select(txtCostCenterID.Text.Trim());
                        if (detail != null)
                        {
                            detail.IsCanceled = true;
                            detail.Update();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtCostCenterID.Text, TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                   
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtCostCenterID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                      tbl_zCost_Center4 oldRecord =   tbl_zCost_Center4.Select(txtCostCenterID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_zCost_Center4 detail = new   tbl_zCost_Center4(txtCostCenterID.Text.Trim(), txtCostCenterName.Text.Trim(),oldRecord.IsCanceled);
                                        detail.Update();
                                        clsHelpMethods.InsertTransactionHistory(iFormID, txtCostCenterID.Text, TxnActivity.Update);
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtCostCenterID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                      tbl_zCost_Center4 detail = new   tbl_zCost_Center4(txtCostCenterID.Text.Trim(), txtCostCenterName.Text.Trim(),false);
                                    detail.Insert();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtCostCenterID.Text, TxnActivity.Insert);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Bank " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCostCenterID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblCostCenterID, true);

            txtCostCenterName.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtCostCenterID.Text = "<Auto Generate>";
            else
                txtCostCenterID.Clear();
            if (txtCostCenterID.Enabled)
            {
                txtCostCenterID.SelectAll();
                txtCostCenterID.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<  tbl_zCost_Center4> details =   tbl_zCost_Center4.SelectAll().Where(p=> !p.IsCanceled).ToList();
                foreach (  tbl_zCost_Center4 detail in details)
                {
                    if (detail.Cost_Center4_ID != "default")
                    {

                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["clmCostCenterID", iRow].Value = detail.Cost_Center4_ID;
                        dgvDetail["clmCostCenterName", iRow].Value = detail.Cost_Center4_Name;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                      tbl_zCost_Center4 detail =   tbl_zCost_Center4.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCostCenterID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblCostCenterID, false);

                        //asign values
                        txtCostCenterID.Text = detail.Cost_Center4_ID;
                        txtCostCenterName.Text = detail.Cost_Center4_Name;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            if (txtCostCenterName.TextLength == 0)
            {
                strMessage += "\n" + "Cost Center Name ";
                bStatus = false;
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtItemSubCategory_DoubleClick(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_MasterItemSubCategory(ref txtCostCenterID);
            }   
        }        
        private void frm_mtrBank_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtItemSubCategory_DoubleClick(object sender, EventArgs e)
        {
            Search_CostCenterID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["clmCostCenterID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods
        private void Search_CostCenterID()
        {
            clsSearch.Search_Cost4(ref txtCostCenterID);
            if (txtCostCenterID.Tag != null && txtCostCenterID.Text.Length > 0)
            {
                string sFontTypeID = txtCostCenterID.Tag.ToString();
                FillDetails(sFontTypeID);
            }
        }
        #endregion


    }
}
