using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;

namespace Digiteq.Master_Forms
{
    public partial class frm_securityConfigStatus : Form
    {

        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;
        public string glbUserID = "";
        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_securityConfigStatus()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.SecurityConfigType_Status);
            iFormID = clsSecurity.getFormID(FormName.SecurityConfigType_Status);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_securityConfigStatus_Load(object sender, EventArgs e)
        {
            //format Form
            RefreshGrid();
            CusDataGridViewFormat();

            ClearFields();
        } 
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        } 
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtStatusID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;

                        int iIdValue;
                        int.TryParse(txtStatusID.Text.Trim(), out iIdValue);

                        tbl_securityConfigStatus detail = tbl_securityConfigStatus.Select(iIdValue);
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        } 
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            int iIdValue;
                            int.TryParse(txtStatusID.Text.Trim(), out iIdValue);

                            if (txtStatusID.Text.Trim().Length > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_securityConfigStatus oldRecord = tbl_securityConfigStatus.Select(iIdValue);
                                    if (oldRecord != null)
                                    {
                                        tbl_securityConfigStatus detail = new tbl_securityConfigStatus(iIdValue, txtTypeStatusName.Text.Trim(),(rdbTrue.Checked) ? true : false, txtConfigTypeStatusID.Text.Trim());
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        iIdValue = clsAutocode.getAutoGeneratedCode_ForInteger(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_securityConfigStatus detail = new tbl_securityConfigStatus(iIdValue, txtTypeStatusName.Text.Trim(), (rdbTrue.Checked) ? true : false, txtConfigTypeStatusID.Text.Trim());
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }

                            }
                            else
                            {
                                MessageBox.Show("Status " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }

                        }

                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format

        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();

                List<tbl_securityConfigStatus> details = tbl_securityConfigStatus.SelectAll();
                foreach (tbl_securityConfigStatus detail in details)
                {
                    if (detail.ValueID != 0)
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["StatusID", iRow].Value = detail.ValueID;
                        dgvDetail["StatusName", iRow].Value = detail.ValueName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enable the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStatusID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, true);


            txtTypeStatusName.Clear();
            rdbFalse.Checked = false;
            rdbTrue.Checked = false;
            txtConfigTypeStatusID.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtStatusID.Text = "<Auto Generate>";
            else
                txtStatusID.Clear();
            if (txtStatusID.Enabled)
            {
                txtStatusID.SelectAll();
                txtStatusID.Focus();
            }
        }
        #endregion

        #region Fill Details

        private void FillDetails(string sID)
        {
            try
            {
                int iSID;
                if (sID.Length > 0)
                {
                    int.TryParse(sID,out iSID);
                    tbl_securityConfigStatus detail = tbl_securityConfigStatus.Select(iSID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStatusID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, false);

                        // Assign values
                        txtStatusID.Text =Convert.ToString( detail.ValueID);
                        txtConfigTypeStatusID.Text = detail.ConfigTypeStatus_ID;
                        txtTypeStatusName.Text = detail.ValueName;
                      
                        if (detail.ConfigValue)
                        {
                            rdbTrue.Checked = true;
                        }
                        else if(!detail.ConfigValue)
                        {
                            rdbFalse.Checked = true;
                        }
                       

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void FillDetails(int sID)
        {
            try
            {

                if (sID!=0 )
                {
                    tbl_securityConfigStatus detail = tbl_securityConfigStatus.Select(sID);
                    if (detail != null)
                    {
                        // Set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtStatusID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, false);

                        // Assign values
                        txtStatusID.Text = Convert.ToString(detail.ValueID);
                        txtConfigTypeStatusID.Text = detail.ConfigTypeStatus_ID;
                        txtTypeStatusName.Text = detail.ValueName;
                       
                        if (detail.ConfigValue)
                        {
                            rdbTrue.Checked = true;
                        }
                        else if (detail.ConfigValue)
                        {
                            rdbFalse.Checked = true;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion     

        
        #region Events KeyDown


        private void txtStatusID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityValueID();
            }
        }

        private void frm_securityConfigStatus_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        } 
        #endregion

        #region Events DoubleClick
        private void txtStatusID_DoubleClick(object sender, EventArgs e)
        {
            Search_SecurityValueID();
        } 
        #endregion

        #region key up
        private void txtConfigTypeStatusID_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityStatusID_Config();
            }  
        }
        #endregion


        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["StatusID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        } 
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMassage = "";
            bool bStatus = true;

            if (txtTypeStatusName.Text.Trim().Length == 0)
            {
                strMassage = strMassage + "\n " + "Type Status";
                //  string.Concat(strMassage, "\n ", "Type Status");
                bStatus = false;
            }

            if (!rdbTrue.Checked && !rdbFalse.Checked)
            {
                strMassage += "\n " + "status";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (txtConfigTypeStatusID.Text.Trim().Length == 0)
            {
                strMassage += "\n " + "configuration Status id";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (!bStatus)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMassage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;

        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Search Methods
        private void Search_SecurityStatusID_Config()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigStatusID();
                frmhelpsearch.ShowDialog();
                
                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtConfigTypeStatusID.Text = frmSearchMaster.s_SearchID;
                   // FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_SecurityValueID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigValueID_Status();//change it later ...TODO
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtStatusID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion






    }
}
