using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;


namespace Digiteq.Master_Forms
{
    public partial class frm_securityConfigTypeValue : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;
        public string glbUserID = "";
        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_securityConfigTypeValue()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.SecurityConfigTypeValue);
            iFormID = clsSecurity.getFormID(FormName.SecurityConfigTypeValue);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }

            InitializeComponent();
        }

        private void frm_securityConfigTypeValue_Load(object sender, EventArgs e)
        {
            //format Form
            RefreshGrid();
            CusDataGridViewFormat();

            ClearFields();
        } 
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        } 
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtTypeValueID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;

                        tbl_securityConfigType_Value detail = tbl_securityConfigType_Value.Select(txtTypeValueID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtTypeValueID.Text.Trim().Length > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_securityConfigType_Value oldRecord = tbl_securityConfigType_Value.Select(txtTypeValueID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        tbl_securityConfigType_Value detail = new tbl_securityConfigType_Value(txtTypeValueID.Text.Trim(),txtTypeValue.Text.Trim(), txtRemark.Text.Trim());
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtTypeValueID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_securityConfigType_Value detail = new tbl_securityConfigType_Value(txtTypeValueID.Text.Trim(), txtTypeValue.Text.Trim(), txtRemark.Text.Trim());
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }

                            }
                            else
                            {
                                MessageBox.Show("Status " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }

                        }

                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        } 
        #endregion


        #region Datagrid Format

        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();

                List<tbl_securityConfigType_Value> details = tbl_securityConfigType_Value.SelectAll();
                foreach (tbl_securityConfigType_Value detail in details)
                {
                    if (detail.ConfigTypeValue_ID.Trim() != "default")
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["TypeValueID", iRow].Value = detail.ConfigTypeValue_ID;
                        dgvDetail["TypeValue", iRow].Value = detail.ConfigTypeValue;
                        dgvDetail["Remark", iRow].Value = detail.Remark;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enable the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeValueID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, true);


            txtTypeValue.Clear();
            txtRemark.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtTypeValueID.Text = "<Auto Generate>";
            else
                txtTypeValueID.Clear();
            if (txtTypeValueID.Enabled)
            {
                txtTypeValueID.SelectAll();
                txtTypeValueID.Focus();
            }
        }
        #endregion

        #region Fill Details

        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_securityConfigType_Value detail = tbl_securityConfigType_Value.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeValueID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, false);

                        //asign values
                        txtTypeValueID.Text = detail.ConfigTypeValue_ID;
                        txtTypeValue.Text = detail.ConfigTypeValue;
                        txtRemark.Text = detail.Remark;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion


        #region Events KeyDown
        private void txtTypeValueID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityValueID();
            }
        }

        private void frm_securityConfigTypeValue_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick

        private void txtTypeValueID_DoubleClick(object sender, EventArgs e)
        {
            Search_SecurityValueID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["TypeValueID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }




        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMassage = "";
            bool bStatus = true;

            if (txtTypeValue.Text.Trim().Length == 0)
            {
                strMassage = strMassage + "\n " + "Type Value";
                //  string.Concat(strMassage, "\n ", "Type Status");
                bStatus = false;
            }

            if (txtRemark.Text.Trim().Length == 0)
            {
                strMassage += "\n " + "Remark";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (!bStatus)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMassage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;

        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Search Methods
        private void Search_SecurityValueID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigValueID();//change it later ...TODO
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtTypeValueID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion




    }
}
