using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frmDebitNoteTypeMaster :  MettroForm
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        # region Form Load
        public frmDebitNoteTypeMaster()
        {
            InitializeComponent();
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.DebitNoteType);
            iFormID = clsSecurity.getFormID(FormName.DebitNoteType);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }            
        }

        private void frmDebitNoteTypeMaster_Load(object sender, EventArgs e)
        {
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        # endregion

        # region btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
                ClearFields();
        }
        # endregion

        # region btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtDebitNoteTypeCode.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zDebitNoteType detail = tbl_zDebitNoteType.Select(txtDebitNoteTypeCode.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        # endregion

        # region btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                {
                    try
                    {
                        Cursor = Cursors.WaitCursor;
                        if (txtDebitNoteTypeCode.TextLength > 0)
                        {
                            if (IsUpdate)  //update records
                            {
                                tbl_zDebitNoteType oldRecord = tbl_zDebitNoteType.Select(txtDebitNoteTypeCode.Text.Trim());
                                if (oldRecord != null)
                                {

                                    tbl_zDebitNoteType detail = new tbl_zDebitNoteType(txtDebitNoteTypeCode.Text.Trim(), txtDebitNoteTypeName.Text.Trim(), "DN", 0, 1, "default");
                                    detail.Update();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Update);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else  //insert records
                            {
                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                    txtDebitNoteTypeCode.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                //Inquiry Header
                                tbl_zDebitNoteType detail = new tbl_zDebitNoteType(txtDebitNoteTypeCode.Text.Trim(), txtDebitNoteTypeName.Text.Trim(), "DN", 0, 1, "default");
                                detail.Insert();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Insert);
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        else
                        {
                            MessageBox.Show("Debit Note Type " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID,ex);
                        SEACCException.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Default;
                        ClearFields();
                        RefreshGrid();
                    }

                }
            }
        }
        #endregion



        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtDebitNoteTypeCode, true);
            clsCommon.SetEnableDisable_NormalLabel(lblDebitNoteTypeCode, true);

            txtDebitNoteTypeName.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtDebitNoteTypeCode.Text = "<Auto Generate>";
            else
                txtDebitNoteTypeCode.Clear();

            if (txtDebitNoteTypeCode.Enabled)
            {
                txtDebitNoteTypeCode.SelectAll();
                txtDebitNoteTypeCode.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zDebitNoteType> details = tbl_zDebitNoteType.SelectAll();
            foreach (tbl_zDebitNoteType detail in details)
            {
                if (detail.DebitNoteType_ID.Trim() != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["DebitNoteTypeCode", iRow].Value = detail.DebitNoteType_ID;
                    dgvDetail["DebitNoteTypeName", iRow].Value = detail.DebitNoteTypeName;
                }
            }
        }
        #endregion    

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_zDebitNoteType detail = tbl_zDebitNoteType.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtDebitNoteTypeCode, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblDebitNoteTypeCode, false);

                        //asign values
                        txtDebitNoteTypeCode.Text = detail.DebitNoteType_ID;
                        txtDebitNoteTypeName.Text = detail.DebitNoteTypeName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        # region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtDebitNoteTypeName, "Debit Note Type Name"))
            {
                bStatus = true;
            }
            return bStatus;
        }
        # endregion 

        

        #  region Events Key Down
        private void txtDebitNoteTypeCode_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_txtDebitNoteTypeCode();
            }
        }
        # endregion

        # region Events Double Click
        private void txtDebitNoteTypeCode_DoubleClick(object sender, EventArgs e)
        {
            Search_txtDebitNoteTypeCode();
        }
        # endregion

        # region Events data Grid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["DebitNoteTypeCode", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        # endregion

        #region Search Methods
        private void Search_txtDebitNoteTypeCode()
        {
            try
            {
                clsSearch.Search_MasterDebitNoteType_Direct(ref txtDebitNoteTypeCode);
                if (txtDebitNoteTypeCode.Tag != null && txtDebitNoteTypeCode.Tag.ToString().Trim().Length > 0)
                    FillDetails(txtDebitNoteTypeCode.Tag.ToString().Trim());
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion
    }
}
