using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic;

namespace Digiteq

{
    public partial class frm_mtrVehicle : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_mtrVehicle()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.ZVehicle);
            iFormID = clsSecurity.getFormID(FormName.ZVehicle);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }
        private void frm_mtrCustomerClass_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();         
        }
        #endregion
        
        #region Btn New
        private void btnNew_Click_1(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion
       
        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {

            try
            {
                if (txtVehicleID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;

                        tbl_zVehicle detail = tbl_zVehicle.Select(txtVehicleID.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }

        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            
       
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                   if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            if (txtVehicleID.TextLength > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_zVehicle oldRecord = tbl_zVehicle.Select(txtVehicleID.Text.Trim());
                                    if (oldRecord != null)
                                    {
                                        //Country Header
                                        tbl_zVehicle detail = new tbl_zVehicle(txtVehicleID.Text.Trim(), txtVehicleName.Text.Trim(), txtVehicleNumber.Text.Trim().ToUpper());
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);

                                    }
                                }
                                else  //insert records
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtVehicleID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_zVehicle detail = new tbl_zVehicle(txtVehicleID.Text.Trim(), txtVehicleName.Text.Trim(), txtVehicleNumber.Text.Trim().ToUpper());
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else
                            {
                                MessageBox.Show("Vehicle Class " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }


        }
        #endregion

        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {

            //set the flag and enble the id

            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtVehicleID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblClassID, true);

            txtVehicleName.Clear();
            txtVehicleNumber.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtVehicleID.Text = "<Auto Generate>";
            else
                txtVehicleID.Clear();

            if (txtVehicleID.Enabled)
            {
                txtVehicleID.SelectAll();
                txtVehicleID.Focus();
            }
            //txtClassID.Text = "ok";
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();
                List<tbl_zVehicle> details = tbl_zVehicle.SelectAll();
                foreach (tbl_zVehicle detail in details)
                {
                    if (detail.Vehicle_ID.Trim() != "default")
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["VehicleID", iRow].Value = detail.Vehicle_ID;
                        dgvDetail["VehicleName", iRow].Value = detail.VehicleName;
                        dgvDetail["VehicleNumber", iRow].Value = detail.VehicleNumber;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }

        }
        #endregion

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_zVehicle detail = tbl_zVehicle.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtVehicleID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblClassID, false);

                        //asign values
                        txtVehicleID.Text = detail.Vehicle_ID;
                        txtVehicleName.Text = detail.VehicleName;
                        txtVehicleNumber.Text = detail.VehicleNumber;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }

        }
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMessage = "";
            bool bStatus = true;
            if (txtVehicleName.TextLength == 0)
            {
                strMessage += "\n" + "Vehicle Name ";
                bStatus = false;
            }
            if (txtVehicleNumber.TextLength == 0)
            {
                strMessage += "\n" + "Vehicle number  ";
                bStatus = false;
            }
            foreach (DataGridViewRow row in dgvDetail.Rows)
            {
                if (clsValidate.ValidateGridValue(dgvDetail, "VehicleNumber", row.Index, "").ToString() == txtVehicleNumber.Text.ToUpper() && IsUpdate == false && txtVehicleNumber.TextLength != 0)
                {
                    strMessage += "\n" + " You Can't Enter Same Vehicle Number ";
                    bStatus = false;
                    break;
                }
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtClassID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_VehicleID();
            }   
        }
        private void frm_mtrCustomerclass_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtClassID_DoubleClick(object sender, EventArgs e)
        {
            Search_VehicleID();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {

                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["VehicleID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        #endregion

        #region Search Methods
        private void Search_VehicleID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_Vehicle();
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtVehicleID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }

        }
        #endregion


    }
}
