using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;
using Digiteq_Logic;

namespace Digiteq
{
    public partial class frm_CreditNoteTypeMaster : MettroForm
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        # region Form Load 
        public frm_CreditNoteTypeMaster()
        {
            InitializeComponent();
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.CreditNoteType);
            iFormID = clsSecurity.getFormID(FormName.CreditNoteType);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }            
        }

        private void frm_CreditNoteTypeMaster_Load(object sender, EventArgs e)
        {
            RefreshGrid();
            CusDataGridViewFormat();
            ClearFields();
        }
        # endregion

        # region btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        # endregion

        # region btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtCreditNoteTypeCode.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;
                        tbl_zCreditNoteType detail = tbl_zCreditNoteType.Select(txtCreditNoteTypeCode.Text.Trim());
                        if (detail != null)
                        {
                            detail.Delete();
                            clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Cancel);
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                   
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        # endregion

        # region btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                {
                    try
                    {
                        Cursor = Cursors.WaitCursor;
                        if (txtCreditNoteTypeCode.TextLength > 0)
                        {
                            if (IsUpdate)  //update records
                            {
                                tbl_zCreditNoteType oldRecord = tbl_zCreditNoteType.Select(txtCreditNoteTypeCode.Text.Trim());
                                if (oldRecord != null)
                                {

                                    tbl_zCreditNoteType detail = new tbl_zCreditNoteType(txtCreditNoteTypeCode.Text.Trim(), txtCreditNoteTypeName.Text.Trim());
                                    detail.Update();
                                    clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Update);
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                            else  //insert records
                            {
                                if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                    txtCreditNoteTypeCode.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                //Inquiry Header
                                tbl_zCreditNoteType detail = new tbl_zCreditNoteType(txtCreditNoteTypeCode.Text.Trim(), txtCreditNoteTypeName.Text.Trim());
                                detail.Insert();
                                clsHelpMethods.InsertTransactionHistory(iFormID, txtCreditNoteTypeCode.Text.ToString(), TxnActivity.Insert);
                                MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }
                        }
                        else
                        {
                            MessageBox.Show("Credit Note Type " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                    catch (Exception ex)
                    {
                        clsValidate.WriteErrorLog("", iFormID,ex);
                       SEACCException.Show(ex);
                    }
                    finally
                    {
                        Cursor = Cursors.Default;
                        ClearFields();
                        RefreshGrid();
                    }

                }
            }
        }
        #endregion



        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enble the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCreditNoteTypeCode, true);
            clsCommon.SetEnableDisable_NormalLabel(lblCreditNoteTypeCode, true);

            txtCreditNoteTypeName.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtCreditNoteTypeCode.Text = "<Auto Generate>";
            else
                txtCreditNoteTypeCode.Clear();

            if (txtCreditNoteTypeCode.Enabled)
            {
                txtCreditNoteTypeCode.SelectAll();
                txtCreditNoteTypeCode.Focus();
            }
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            int iRow;
            dgvDetail.Rows.Clear();
            List<tbl_zCreditNoteType> details = tbl_zCreditNoteType.SelectAll();
            foreach (tbl_zCreditNoteType detail in details)
            {
                if (detail.CreditNoteType_ID.Trim() != "default")
                {
                    dgvDetail.Rows.Add();
                    iRow = dgvDetail.Rows.Count - 1;
                    dgvDetail["CreditNoteTypeCode", iRow].Value = detail.CreditNoteType_ID;
                    dgvDetail["CreditNoteTypeName", iRow].Value = detail.CreditNoteTypeName;
                }
            }
        }
        #endregion       

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_zCreditNoteType detail = tbl_zCreditNoteType.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCreditNoteTypeCode, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblCreditNoteTypeCode, false);

                        //asign values
                        txtCreditNoteTypeCode.Text = detail.CreditNoteType_ID ;
                        txtCreditNoteTypeName.Text = detail.CreditNoteTypeName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        }
        #endregion

        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtCreditNoteTypeName, "Credit Note Type Name"))
            {
                bStatus = true;
            }
            return bStatus;
        }
        #endregion



        #region Events Key Down
        private void txtCreditNoteTypeCode_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_txtCreditNoteTypeCode();
            }
        }
        # endregion

        # region Events Double Click
        private void txtCreditNoteTypeCode_DoubleClick(object sender, EventArgs e)
        {
            Search_txtCreditNoteTypeCode();
        }
        # endregion

        # region Events data Grid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["CreditNoteTypeCode", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            dgvDetail_CellClick(sender, e);
        }
        # endregion

        #region Search Methods
        private void Search_txtCreditNoteTypeCode()
        {
            try
            {
                clsSearch.Search_MasterCreditNoteType_Direct(ref txtCreditNoteTypeCode);
                if (txtCreditNoteTypeCode.Tag != null && txtCreditNoteTypeCode.Tag.ToString().Trim().Length > 0)
                    FillDetails(txtCreditNoteTypeCode.Tag.ToString().Trim());
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
               SEACCException.Show(ex);
            }
        }
        #endregion
    }
}
