using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;

namespace Digiteq.Master_Forms
{
    public partial class frm_securityConfigValue : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;
        public string glbUserID = "";
        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        #endregion

        #region Form Load
        public frm_securityConfigValue()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.SecurityConfigStatus);
            iFormID = clsSecurity.getFormID(FormName.SecurityConfigStatus);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();
        }

        private void frm_securityConfigValue_Load(object sender, EventArgs e)
        {
            //format Form
            RefreshGrid();
            CusDataGridViewFormat();

            ClearFields();
        } 
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Delete
        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (txtTypeValueID.TextLength > 0)
                {
                    if (clsSecurity.PermissionToDelete(clsSecurity.UserIDLoged, iFormID))
                    {
                        //delete one record
                        Cursor = Cursors.WaitCursor;

                        int iIdValue;
                        int.TryParse(txtTypeValueID.Text.Trim(), out iIdValue);

                        tbl_securityConfigValue detail = tbl_securityConfigValue.Select(iIdValue);
                        if (detail != null)
                        {
                            detail.Delete();
                        }

                        Cursor = Cursors.Default;
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.DeleteDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        ClearFields();
                        RefreshGrid();
                    }
                    else //if no permission to delete
                    {
                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.PermissionToDelete), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                Cursor = Cursors.Default;
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity())
            {
                if (CheckNumberValidity())
                {
                    if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                    {
                        try
                        {
                            Cursor = Cursors.WaitCursor;
                            int iIdValue;
                            int.TryParse(txtTypeValueID.Text.Trim(), out iIdValue);

                            if (txtTypeValueID.Text.Trim().Length > 0)
                            {
                                if (IsUpdate)  //update records
                                {
                                    tbl_securityConfigValue oldRecord = tbl_securityConfigValue.Select(iIdValue);
                                    if (oldRecord != null)
                                    {
                                        tbl_securityConfigValue detail = new tbl_securityConfigValue(iIdValue, txtTypeValueName.Text.Trim(), txtValue.Text.Trim(), txtConfigTypeValueID.Text.Trim(), oldRecord.Form_ID);
                                        detail.Update();
                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.ModifyDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                }
                                else
                                {
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        iIdValue = clsAutocode.getAutoGeneratedCode_ForInteger(sFormConfigCode);

                                    //Inquiry Header
                                    tbl_securityConfigValue detail = new tbl_securityConfigValue(iIdValue, txtTypeValueName.Text.Trim(), txtValue.Text.Trim(), txtConfigTypeValueID.Text.Trim(),0);
                                    detail.Insert();
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }

                            }
                            else
                            {
                                MessageBox.Show("Value " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                            }

                        }

                        catch (Exception ex)
                        {
                            clsValidate.WriteErrorLog("", iFormID,ex);
                            SEACCException.Show(ex);
                        }
                        finally
                        {
                            Cursor = Cursors.Default;
                            ClearFields();
                            RefreshGrid();
                        }
                    }
                }
            }
        } 
        #endregion


        #region Datagrid Format

        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvDetail);
        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                int iRow;
                dgvDetail.Rows.Clear();

                List<tbl_securityConfigValue> details = tbl_securityConfigValue.SelectAll();
                foreach (tbl_securityConfigValue detail in details)
                {
                    if (detail.ValueID != 0)
                    {
                        dgvDetail.Rows.Add();
                        iRow = dgvDetail.Rows.Count - 1;
                        dgvDetail["ValueID", iRow].Value = detail.ValueID;
                        dgvDetail["ValueName", iRow].Value = detail.ValueName;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            //set the flag and enable the id
            IsUpdate = false;
            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeValueID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, true);


            txtTypeValueName.Clear();
            txtValue.Clear();
            txtConfigTypeValueID.Clear();

            if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                txtTypeValueID.Text = "<Auto Generate>";
            else
                txtTypeValueID.Clear();
            if (txtTypeValueID.Enabled)
            {
                txtTypeValueID.SelectAll();
                txtTypeValueID.Focus();
            }
        }
        #endregion

        #region Fill Details

        private void FillDetails(string sID)
        {
            try
            {
                int iId;

                if (sID.Length > 0)
                {
                    int.TryParse(sID, out iId);
                    tbl_securityConfigValue detail = tbl_securityConfigValue.Select(iId);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeValueID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, false);

                        //asign values
                        txtTypeValueID.Text =Convert.ToString( detail.ValueID);
                        txtConfigTypeValueID.Text = detail.ConfigTypeValue_ID;
                        txtTypeValueName.Text = detail.ValueName;
                        txtValue.Text = detail.ConfigValue;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        private void FillDetails(int sID)
        {
            try
            {
                if (sID!= 0)
                {
                    tbl_securityConfigValue detail = tbl_securityConfigValue.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtTypeValueID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblTypeValueID, false);

                        //asign values
                        txtTypeValueID.Text = Convert.ToString(detail.ValueID);
                        txtConfigTypeValueID.Text = detail.ConfigTypeValue_ID;
                        txtTypeValueName.Text = detail.ValueName;
                        txtValue.Text = detail.ConfigValue;

                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion
        

        #region Events KeyDown
        private void txtTypeValueID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                Search_SecurityValueID();
            }
        }

        private void frm_securityConfigValue_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }
        #endregion

        #region Events DoubleClick
        private void txtTypeValueID_DoubleClick(object sender, EventArgs e)
        {
            Search_SecurityValueID();
        }
        #endregion

        #region key up
        private void textBox1_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyCode==Keys.F1)
            {
                Search_SecurityValueID_Config();
            }
        } 
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex >= 0)
                {
                    string sID = dgvDetail["ValueID", e.RowIndex].Value.ToString();
                    if (sID.Length > 0)
                    {
                        //fills the values to controls
                        FillDetails(sID.Trim());
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        } 
        #endregion

        #region Check Validity
        private bool CheckValidity()
        {
            string strMassage = "";
            bool bStatus = true;

            if (txtTypeValueName.Text.Trim().Length == 0)
            {
                strMassage = strMassage + "\n " + "Name";
                //  string.Concat(strMassage, "\n ", "Type Status");
                bStatus = false;
            }

            if (txtValue.Text.Trim().Length == 0)
            {
                strMassage += "\n " + "Value";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (txtConfigTypeValueID.Text.Trim().Length == 0)
            {
                strMassage += "\n " + "Configuration Type Value ID";
                //string.Concat(strMassage, "\n ", "Remark");
                bStatus = false;
            }

            if (!bStatus)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInsert, strMassage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            return bStatus;

        }

        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Search Methods
        private void Search_SecurityValueID()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigValueID_Value();//change it later ...TODO
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtTypeValueID.Text = frmSearchMaster.s_SearchID;
                    FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Search_SecurityValueID_Config()
        {
            try
            {
                Form frmhelpsearch = new frmSearchMaster();
                clsSearch.passValue_securityConfigValueID();//change it later ...TODO
                frmhelpsearch.ShowDialog();

                if (frmSearchMaster.s_SearchID.Length > 0)
                {
                    txtConfigTypeValueID.Text = frmSearchMaster.s_SearchID;
                  //  FillDetails(frmSearchMaster.s_SearchID);
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

    }
}
