using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DataTire;
using Digiteq_Logic;
using System.Data;
using SEACC_WPFControls;

namespace Digiteq
{
    /// <summary>
    /// Interaction logic for UC_DeptMaster.xaml
    /// </summary>
    public partial class UC_DeptMaster : UserControl
    {
        #region Globle Variable
        //    DataTable dt = new DataTable();
        #endregion

        #region Form Load
        public UC_DeptMaster()
        {
            #region Initialize Usercontrol
            InitializeComponent();

            SEACC_Form.enmFormName = FormName.Department_Creation;
            SEACC_Form.Initialize();
            #endregion

            #region Initialize Data Table
            dgr_Main.dt.Columns.Add("DeptID");
            dgr_Main.dt.Columns.Add("DeptName");
            dgr_Main.dt.Columns.Add("DeptAdd");
            dgr_Main.dt.Columns.Add("DevisionID");
            dgr_Main.dt.Columns.Add("Telephone");
            dgr_Main.dt.Columns.Add("Fax");
            dgr_Main.dt.Columns.Add("ContactPerson");
            dgr_Main.dt.Columns.Add("Remarks");
            #endregion

            #region Initialize Action Buttons
            SEACC_Form.SetVisibility_ActionButons(true, false, true, true);
            this.SEACC_Form.btn_New.Click += btn_New_Click;
            this.SEACC_Form.btn_Save.Click += btn_Save_Click;
            this.SEACC_Form.btn_Cancel.Click += btn_Cancel_Click;
            #endregion

            #region Initialize Data Grid
            dgr_Main.Add_DatagridColoumn("Dept. Code", "DeptID", 70);
            dgr_Main.Add_DatagridColoumn("Dept. Name", "DeptName", 150);
            dgr_Main.Add_DatagridColoumn("Address", "DeptAdd", 200);
            dgr_Main.Add_DatagridColoumn("Division", "DevisionID", 150);
            dgr_Main.Add_DatagridColoumn("Telephone", "Telephone", 75);
            dgr_Main.Add_DatagridColoumn("Fax", "Fax", 75);
            dgr_Main.Add_DatagridColoumn("HOD", "ContactPerson", 120);
            dgr_Main.Add_DatagridColoumn("Remarks", "Remarks", 200);
            #endregion

            RefreshGrid();
            ClearFillds();
        }
        #endregion

        #region Form Responsive
        private void SEACC_Form_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (SEACC_Form.ActualWidth < 850)
                coloumnA.Width = new GridLength(210);
            else
                coloumnA.Width = new GridLength(470);
        }
        #endregion

        #region Action Button

        void btn_Save_Click(object sender, RoutedEventArgs e)
        {
            if (CheckValidity())
            {
                try
                {
                    #region Update
                    if (SEACC_Form.IsUpdateMode)
                    {
                        if (SEACC_Form.CheckPermisshion_ToUpdate())
                        {
                            #region Update
                            tbl_genMasDepartment oldRecord = tbl_genMasDepartment.Select(txtDepartmentID.Text.Trim(), clsSecurity.CompanyID, clsSecurity.BranchID);
                            if (oldRecord != null)
                            {
                                tbl_genMasDepartment detail = new tbl_genMasDepartment(clsSecurity.CompanyID, clsSecurity.BranchID, txtDepartmentID.Text, txtDeptName.Text, txtDivisionID.Tag.ToString(), txtAddress.Text, txtTelephone.Text, txtTelephone1.Text, txtExtension.Text, txtFax.Text, txtContactPerson.Tag.ToString(), txtDescription.Text, oldRecord.IsCanceled, oldRecord.UserID_Created, clsSecurity.UserIDLoged, oldRecord.UserID_Canceled, oldRecord.TerminalID_Created, clsSecurity.TerminalID, oldRecord.TerminalID_Canceled, oldRecord.Date_Created, clsSecurity.getServerDateTime(), oldRecord.Date_Canceled);
                                detail.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Updated);
                            }
                            #endregion
                        }
                    }
                    #endregion

                    #region Insert
                    else
                    {
                        if (SEACC_Form.isAutoGenaratedCode)
                            txtDepartmentID.Text = SEACC_Form.getAutoGeneratedCode();

                        tbl_genMasDepartment InsertData = new tbl_genMasDepartment(clsSecurity.CompanyID, clsSecurity.BranchID, txtDepartmentID.Text, txtDeptName.Text, txtDivisionID.Tag.ToString(), txtAddress.Text, txtTelephone.Text, txtTelephone1.Text, txtExtension.Text, txtFax.Text, txtContactPerson.Tag.ToString(), txtDescription.Text, false, clsSecurity.UserIDLoged, "Default", "Default", clsSecurity.TerminalID, "Default", "Default", clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime(), clsSecurity.getServerDateTime());
                        InsertData.Insert();
                        SEACCMessageBox.Show(MessegeBoxType.Successfully_Created);

                        #endregion
                    }
                }
                catch (Exception ex)
                {
                    SEACCExeption.Show(ex);
                }
                finally
                {
                    RefreshGrid();
                    ClearFillds();
                }


            }
        }

        void btn_New_Click(object sender, RoutedEventArgs e)
        {
            ClearFillds();
        }

        void btn_Cancel_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (SEACC_Form.IsUpdateMode)
                {
                    if (txtDepartmentID.Tag != null)
                    {
                        bool bMessegeBoxResult = SEACCMessageBox.Show(MessegeBoxType.Cancel_Confirmation);
                        if (bMessegeBoxResult)
                        {
                            tbl_genMasDepartment oDeleteDetails = tbl_genMasDepartment.Select(txtDepartmentID.Text.Trim(), clsSecurity.CompanyID, clsSecurity.BranchID);
                            if (oDeleteDetails != null)
                            {
                                oDeleteDetails.IsCanceled = true;
                                oDeleteDetails.TerminalID_Canceled = clsSecurity.TerminalID;
                                oDeleteDetails.UserID_Canceled = clsSecurity.UserIDLoged;
                                oDeleteDetails.Date_Canceled = clsSecurity.getServerDateTime();
                                oDeleteDetails.Update();
                                SEACCMessageBox.Show(MessegeBoxType.Successfully_Canceled);
                                ClearFillds();
                                RefreshGrid();
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }

        #endregion

        #region Clear Fields
        private void ClearFillds()
        {
            SEACC_Form.IsUpdateMode = false;

            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtDepartmentID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtDeptName, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtAddress, true, false, true);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtDivisionID, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtFax, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtTelephone, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtTelephone1, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtExtension, true, false, false);
            cls_Formater.SetEnableDisable_ForigenKeyLabelTextBox(txtContactPerson, true, false, false);
            cls_Formater.SetEnableDisable_LableTextbox(txtDescription, true, false, true);

            txtDepartmentID.Text = "";
            txtDepartmentID.Tag = null;
            txtDeptName.Text = "";
            txtAddress.Text = "";
            txtDivisionID.Text = "";
            txtDivisionID.Tag = "default";
            txtFax.Text = "";
            txtTelephone.Text = "";
            txtTelephone1.Text = "";
            txtExtension.Text = "";
            txtContactPerson.Text = "";
            txtContactPerson.Tag = "default";
            txtDescription.Text = "";

            if (SEACC_Form.isAutoGenaratedCode)
            {
                txtDepartmentID.setReadOnlyStatus(true);
                txtDepartmentID.Text = "<Auto Generate>";
            }
            else
                txtDepartmentID.setReadOnlyStatus(false);

        }
        #endregion

        #region Refresh Grid
        private void RefreshGrid()
        {
            try
            {
                dgr_Main.dt.Clear();
                foreach (tbl_genMasDepartment detail in tbl_genMasDepartment.SelectAll().Where(p => p.Department_ID != "default" && p.IsCanceled == false))
                {
                    dgr_Main.dt.Rows.Add(detail.Department_ID, detail.DepartmentName, detail.Address, (detail.Division_ID == "default") ? "-" : clsRef_Name.get_Division_Name(detail.Division_ID), detail.Telephone1, detail.Fax, (detail.Employee_ID_HOD == "default") ? "-" : clsRef_Name.get_EmployeeName(detail.Employee_ID_HOD), detail.Remarks);
                }
                dgr_Main.RefreshGrid();
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region CheckValidity

        private bool CheckValidity()
        {
            bool bStatus = false;
            if (CheckValidity_EmptyField())
            {
                if (CheckValidity_DuplicateFiled())
                    bStatus = true;
                if (!ChekValidity_DuplicateNames())
                    bStatus = false;
            }
            return bStatus;
        }
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = true;
            if (!clsValidation.Validate_EmptyValue(txtDepartmentID))
            {
                bStatus = false;
            }

            if (!clsValidation.Validate_EmptyValue(txtDeptName))
            {
                bStatus = false;
            }

            return bStatus;

        }
        public bool CheckValidity_DuplicateFiled()
        {
            bool bStatus = true;
            if (!SEACC_Form.IsUpdateMode)
            {
                tbl_genMasDepartment detail = tbl_genMasDepartment.Select(txtDepartmentID.Text.Trim(), clsSecurity.CompanyID, clsSecurity.BranchID);
                if (detail != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.RecordAlreadyExist);
                }
            }

            return bStatus;
        }
        public bool CheckNumberValidity()
        {
            return true;
        }


        public bool ChekValidity_DuplicateNames()
        {
            bool bStatus = true;
            foreach (tbl_genMasDepartment detail1 in tbl_genMasDepartment.SelectAll().Where(p => p.DepartmentName == txtDeptName.Text && p.IsCanceled == false && p.Department_ID != txtDepartmentID.Text))
            {
                if (detail1 != null)
                {
                    bStatus = false;
                    SEACCMessageBox.Show(MessegeBoxType.FieldAlreadyExist, "Department Name");
                    break;
                }
            }
            return bStatus;
        }

        #endregion

        #region FillDetails
        private void fillDetails(string sID)
        {
            try
            {
                if (sID != null)
                {
                    tbl_genMasDepartment detail = tbl_genMasDepartment.Select(sID, clsSecurity.CompanyID, clsSecurity.BranchID);
                    if (detail != null)
                    {
                        SEACC_Form.IsUpdateMode = true;
                        txtDepartmentID.IsEnabled = false;
                        txtDepartmentID.Text = detail.Department_ID;
                        txtDepartmentID.Tag = detail.Department_ID;
                        txtDeptName.Text = detail.DepartmentName;
                        txtAddress.Text = detail.Address;
                        if (detail.Division_ID != "default")
                        {
                            txtDivisionID.Text = clsRef_Name.get_Division_Name(detail.Division_ID);
                            txtDivisionID.Tag = detail.Division_ID;
                        }
                        else
                        {
                            txtDivisionID.Text = "-";
                            txtDivisionID.Tag = detail.Division_ID;
                        }

                        txtTelephone.Text = detail.Telephone1;
                        txtTelephone1.Text = detail.Telephone1;
                        txtExtension.Text = detail.Extention;
                        txtFax.Text = detail.Fax;
                        if (detail.Employee_ID_HOD != "default")
                        {
                            txtContactPerson.Text = detail.Employee_ID_HOD + "-" + clsRef_Name.get_EmployeeName(detail.Employee_ID_HOD);
                            txtContactPerson.Tag = detail.Employee_ID_HOD;
                        }
                        else
                        {
                            txtContactPerson.Text = "-";
                            txtContactPerson.Tag = detail.Employee_ID_HOD;
                        }

                        txtDescription.Text = detail.Remarks;
                    }
                }
            }
            catch (Exception ex)
            {
                SEACCExeption.Show(ex);
            }
        }
        #endregion

        #region Grid Event
        private void grd_DeptMaster_MouseLeftButtonUp1(object sender, EventArgs e)
        {
            try
            {
                object item = dgr_Main.grdMain.SelectedItem;
                if (item != null)
                {
                    string GridID = (dgr_Main.grdMain.SelectedCells[0].Column.GetCellContent(item) as TextBlock).Text;
                    fillDetails(GridID);
                }
            }
            catch (Exception ex)
            {
                SEACCMessageBox.Show("Error", ex.Message, MessageBoxButton.OK);
            }
        }
        #endregion

        #region Search Event
        private void txtDepartmentID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            var location = this.PointToScreen(new Point(0, 0));
            base.OnMouseDown(e);
            Point p = e.GetPosition(this);


            frmSearch RowDataSearch = new frmSearch();
            RowDataSearch.Left = location.X - 5;
            RowDataSearch.Top = location.Y + this.Height;
            List<string> lstResult = RowDataSearch.Show(Search.Departments);

            if (RowDataSearch.DialogResult == true)
            {
                ClearFillds();
                txtDepartmentID.Text = lstResult[0];
                txtDeptName.Text = lstResult[1];
                fillDetails(lstResult[0]);
            }
        }
        private void txtContactPerson_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            e.Handled = false;
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Employee_Master);
            if (RowDataSearch.DialogResult == true)
            {
                txtContactPerson.Text = lstResult[0] + " - " + lstResult[2];
                txtContactPerson.Tag = lstResult[0];
            }

        }
        private void txtDivisionID_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            frmSearch RowDataSearch = new frmSearch();
            List<string> lstResult = RowDataSearch.Show(Search.Division);
            if (RowDataSearch.DialogResult == true)
            {
                txtDivisionID.Text = lstResult[0];
                txtDivisionID.Tag = lstResult[0];
                txtDivisionID.Text = lstResult[1];
            }
        }
        #endregion
    }
}
