using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq; 
using Digiteq_Logic;
using System.Text;
using System.Windows.Forms;
using DataTire;
using System.IO;

namespace Digiteq
{
    public partial class frm_bpsSalesCommission : Form
    {
        #region Variables
        //to manage update and insert
        static bool IsUpdate = false;

        //to keep form detail       
        string sFormConfigCode;
           public int iFormID;
        public bool bNoAccess;
        public string glbPettyCashAccount = "";
        public string glbPettyCashAccountName = "";
        public string glbSupperUserID = "";
        public string sEmployeeID = "default";

        string glb_sColCustomerName = "", glb_sColInvoiceNo = "", glb_sColCreditNoteNo = "", glb_sColDeductionName = "", glb_sColOverdues = "";
        Color glb_clRowColor_Invoice = Color.Blue, glb_clRowColor_CreditNote = Color.Blue, glb_clRowColor_Payment = Color.Blue, glb_clRowColor_Deduction = Color.Blue, glb_clRowColor_OverDues = Color.Blue;
        int glb_iColCount_Invoice = 0, glb_iColCount_CreditNote = 0, glb_iColCount_Payment = 0, glb_iColCount_Deduction = 0, glb_iColCount_OverDues = 0;
        private bool bHasChecked;
        private bool bHasApproved;
        private DateTime glbApprovedDate;
        #endregion

        #region Form Load
        public frm_bpsSalesCommission()
        {
            sFormConfigCode = clsAutocode.getFormConfigCode(FormName.PettyCashAccount);
            iFormID = clsSecurity.getFormID(FormName.PettyCashAccount);
            if (!clsSecurity.PermissionToRead(clsSecurity.UserIDLoged, iFormID))
            {
                bNoAccess = true;
            }
            InitializeComponent();

        }

        private void frm_bpsSalesCommission_Load(object sender, EventArgs e)
        {
            //add data to the datagrid and format        
            clsFormatter.setFormatForm(this, "Sales Commission Calculator", 2, iFormID);
            CusDataGridViewFormat();
            ClearFields();

            //txtpettyCashAccount_ID.Tag = glbPettyCashAccount;
            //txtpettyCashAccount_ID.Text = glbPettyCashAccountName;
            //RefreshGrid();
            //clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtpettyCashAccount_ID, false);
            //clsCommon.SetEnableDisable_NormalLabel(lblBranchD, false);
        }
        #endregion

        #region Btn New
        private void btnNew_Click(object sender, EventArgs e)
        {
            ClearFields();
        }
        #endregion

        #region Btn Calculate
        private void btnCalculate_Click(object sender, EventArgs e)
        {
            dgvCommission.Rows.Clear();
            dgvCreditNoteDetail.Rows.Clear();
            dgvDeductions.Rows.Clear();
            dgvInvoiceDetails.Rows.Clear();
            dgvPaymentDetails.Rows.Clear();
            dgvReimbursement.Rows.Clear();

            CalculateCommission();
        }
        #endregion

        #region Btn Save
        private void btnSave_Click(object sender, EventArgs e)
        {
            if (CheckValidity_EmptyField())
            {
                if (CheckNumberValidity())
                {
                    if (CheckValidity_CommissionDate())
                    {
                        if (clsSecurity.PermissionToSave(clsSecurity.UserIDLoged, iFormID, IsUpdate))
                        {
                            try
                            {
                                Cursor = Cursors.WaitCursor;

                                if (IsUpdate)  //update records 
                                {
                                    MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.RecordUpdateIsBlock), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                                else  //insert records 
                                {
                                    #region Insert
                                    if (clsAutocode.IsAutoGenerated(sFormConfigCode))
                                        txtCommissionID.Text = clsAutocode.getAutoGeneratedCode(sFormConfigCode);

                                    if (clsValidate.CheckValidity_TransactionCodeLength(txtCommissionID.Text)) //if (txtCommissionID.TextLength > 0)
                                    {
                                        DateTime dtmCommissionDate = DateTime.Parse("1." + txtMonth.Text.Trim() + " " + txtYear.Text.Trim());
                                        tbl_sasSalesCommission oCommission = new tbl_sasSalesCommission(txtCommissionID.Text.Trim(), dtmCommissionDate, txtRemark.Text.Trim(), txtSalesPerson.Tag.ToString(),
                                            txtMonth.Text.Trim(), txtYear.Text.Trim(), decimal.Parse(txtCom_ValidAmt.Text.Trim()), decimal.Parse(txtInvoices_OverDue.Text.Trim()), decimal.Parse(txtInvoices_Deduction.Text.Trim()), 
                                            decimal.Parse(txtInvoices_Total.Text.Trim()), decimal.Parse(txtCom_SalesTarget.Text.Trim()), decimal.Parse(txtInvoices_Valied.Text.Trim()), decimal.Parse(txtCom_CreditNoteAmt .Text.Trim()),
                                            decimal.Parse(txtInvoices_Valied.Text.Trim()),decimal.Parse(txtCom_Commission.Text.Trim()),decimal.Parse(txtCom_ValidAmt.Text.Trim()),decimal.Parse(txtTot_ExceededSales.Text.Trim()),
                                            decimal.Parse(txtTot_Deductions.Text.Trim()),decimal.Parse(txtTot_Reimbursed.Text.Trim()),decimal.Parse(txtTot_Commission.Text.Trim()),0m);
                                        oCommission.Insert();

                                        #region SalesCommission_Slab
                                        foreach (DataGridViewRow Row in dgvCommission.Rows)
                                        {
                                            int iSlabID = clsValidate.ValidateGridValue(dgvCommission, "CM_SlabID", Row.Index, int.Parse("0"));
                                            decimal dFromAmount = clsValidate.ValidateGridValue(dgvCommission, "CM_FromAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dToAmount = clsValidate.ValidateGridValue(dgvCommission, "CM_ToAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dCommissionPercentage = clsValidate.ValidateGridValue(dgvCommission, "CM_Percentage", Row.Index, decimal.Parse("0.00"));
                                            decimal dCommissionAmount = clsValidate.ValidateGridValue(dgvCommission, "CM_Amount", Row.Index, decimal.Parse("0.00"));
                                            tbl_sasSalesCommission_Slab oSlab = new tbl_sasSalesCommission_Slab(txtCommissionID.Text.Trim(), txtSalesPerson.Tag.ToString(), iSlabID, dFromAmount, dToAmount, dCommissionPercentage, dCommissionAmount);
                                            oSlab.Insert();
                                        } 
                                        #endregion

                                        #region SalesCommission_Invoices
                                        foreach (DataGridViewRow Row in dgvInvoiceDetails.Rows)
                                        {
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            string sInvoice_ID = clsValidate.ValidateGridValue(dgvInvoiceDetails, "InvoiceNo", Row.Index, "default");
                                            DateTime InvoiceDate = clsValidate.ValidateGridValue(dgvInvoiceDetails, "InvoiceDate", Row.Index, clsSecurity.getServerDateTime());
                                            //DateTime InvoiceDate = clsSecurity.getServerDateTime(); //ToDo
                                            decimal dInvoiceAmount = clsValidate.ValidateGridValue(dgvInvoiceDetails, "InvoiceAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dAllocationAmount = clsValidate.ValidateGridValue(dgvInvoiceDetails, "AllocationAmount", Row.Index, decimal.Parse("0.00"));
                                            int iDays = clsValidate.ValidateGridValue(dgvInvoiceDetails, "Days", Row.Index, int.Parse("0"));
                                            string sCustomerName = clsValidate.ValidateGridValue(dgvInvoiceDetails, "Customer", Row.Index, "default");
                                            bool bIsRejected = clsValidate.ValidateGridValue(dgvInvoiceDetails, "InvoiceReject", Row.Index, false);
                                            string sStatus = clsValidate.ValidateGridValue(dgvInvoiceDetails, "Status", Row.Index, "");
                                            bool bIsValid = (sStatus == "Valied")? true : false;
                                            bool bIsDeduction = (sStatus == "Deduction") ? true : false;
                                            bool bIsOverdue = (sStatus == "OverDue") ? true : false;

                                            tbl_sasSalesCommission_Invoices oComInv = new tbl_sasSalesCommission_Invoices(Row.Index, sCommission_ID, sInvoice_ID, InvoiceDate, dInvoiceAmount, dAllocationAmount, iDays, sCustomerName, bIsRejected, bIsValid, bIsOverdue, bIsDeduction); 
                                            oComInv.Insert();
                                        } 
                                        #endregion

                                        #region SalesCommission_Invoices_Payments
                                        foreach (DataGridViewRow Row in dgvPaymentDetails.Rows)
                                        {
                                            int iLine_No = Row.Index + 1;
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            string sInvoice_ID = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_InvoiceID", Row.Index, "default");
                                            DateTime invoiceDate = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_InvoiceDate", Row.Index, clsSecurity.getServerDateTime());
                                            string sPayment_ID = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_PaymentID", Row.Index, "default");
                                            DateTime paymentDate = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_PaymentDate", Row.Index, clsSecurity.getServerDateTime());
                                            string sPaymentRemark = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_PaymentDetails", Row.Index, "default");
                                            decimal dAllocationAmount = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_InvoiceAmount", Row.Index, decimal.Parse("0.00"));
                                            int iDays = clsValidate.ValidateGridValue(dgvPaymentDetails, "PD_Days", Row.Index, int.Parse("0"));

                                            tbl_sasSalesCommission_Invoices_Payments oComInvPayments = new tbl_sasSalesCommission_Invoices_Payments(iLine_No, sCommission_ID, sInvoice_ID, invoiceDate, sPayment_ID, paymentDate, sPaymentRemark, dAllocationAmount, iDays);
                                            oComInvPayments.Insert();
                                        } 
                                        #endregion

                                        //tbl_sasSalesCommission_PaymentSettlement oComPaymentsSettle = new tbl_sasSalesCommission_PaymentSettlement();
                                        //oComPaymentsSettle.Insert();

                                        #region SalesCommission_OverDue
                                        foreach (DataGridViewRow Row in dgvOverDue.Rows)
                                        {
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            string sInvoice_ID = clsValidate.ValidateGridValue(dgvOverDue, "OD_InvoiceNo", Row.Index, "default");
                                            DateTime invoiceDate = clsValidate.ValidateGridValue(dgvOverDue, "OD_InvoiceDate", Row.Index, clsSecurity.getServerDateTime());
                                            decimal dInvoiceAmount = clsValidate.ValidateGridValue(dgvOverDue, "OD_InvoiceAmt", Row.Index, decimal.Parse("0.00"));
                                            decimal dAllocationAmount = clsValidate.ValidateGridValue(dgvOverDue, "OD_ValidInvoiceAmt", Row.Index, decimal.Parse("0.00"));
                                            int iDays = clsValidate.ValidateGridValue(dgvOverDue, "OD_Days", Row.Index, int.Parse("0"));
                                            string sCustomerName = clsValidate.ValidateGridValue(dgvOverDue, "OD_Customer", Row.Index, "default");

                                            tbl_sasSalesCommission_OverDue oOverDue = new tbl_sasSalesCommission_OverDue(sCommission_ID, sInvoice_ID, invoiceDate, dInvoiceAmount, dAllocationAmount, iDays, sCustomerName);
                                            oOverDue.Insert();
                                        } 
                                        #endregion

                                        #region SalesCommission_CreditNote
                                        foreach (DataGridViewRow Row in dgvCreditNoteDetail.Rows)
                                        {
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            string sCreditNote_ID = clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_CreditNoteID", Row.Index, "default");
                                            string sCustomerName = clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_Customer", Row.Index, "default");
                                            DateTime creditNoteDate = clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_CreditNoteDate", Row.Index, clsSecurity.getServerDateTime());
                                            string sRemark = clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_Remarks", Row.Index, "default");
                                            decimal dCreditNoteAmount = clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_Amount", Row.Index, decimal.Parse("0.00"));

                                            tbl_sasSalesCommission_CreditNote oCreditNote = new tbl_sasSalesCommission_CreditNote(sCommission_ID, sCreditNote_ID, sCustomerName, creditNoteDate, sRemark, dCreditNoteAmount);
                                            oCreditNote.Insert();
                                        } 
                                        #endregion

                                        #region SalesCommission_Deduction
                                        foreach (DataGridViewRow Row in dgvDeductions.Rows)
                                        {
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            Int64 iDeduction_ID = clsValidate.ValidateGridValue(dgvDeductions, "D_DeductionID", Row.Index, int.Parse("0"));
                                            string sInvoice_ID = clsValidate.ValidateGridValue(dgvDeductions, "D_InvoiceID", Row.Index, "default");
                                            DateTime invoiceDate = clsValidate.ValidateGridValue(dgvDeductions, "D_InvoiceDate", Row.Index, clsSecurity.getServerDateTime());
                                            decimal dInvoiceAmount = clsValidate.ValidateGridValue(dgvDeductions, "D_InvoiceAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dPendingAmount = clsValidate.ValidateGridValue(dgvDeductions, "D_PendingAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dDeductionAmount = clsValidate.ValidateGridValue(dgvDeductions, "D_DeductionAmount", Row.Index, decimal.Parse("0.00"));
                                            bool bIsDeductionApproved = (dDeductionAmount > 0) ? true : false;
                                            bool bIsSettled = false;
                                            bool bIsInvoiceDeduction = (sInvoice_ID != "default") ? true : false;
                                            string sEmployee_ID = txtSalesPerson.Tag.ToString();

                                            tbl_sasSalesCommission_Deduction oComDeduct = new tbl_sasSalesCommission_Deduction(sCommission_ID, iDeduction_ID, sInvoice_ID, invoiceDate, dInvoiceAmount, dPendingAmount, dDeductionAmount,
                                                bIsDeductionApproved, bIsSettled, bIsInvoiceDeduction, sEmployee_ID);
                                            oComDeduct.Insert();
                                        } 
                                        #endregion

                                        #region SalesCommission_Reimbursment
                                        foreach (DataGridViewRow Row in dgvReimbursement.Rows)
                                        {
                                            string sCommission_ID = txtCommissionID.Text.Trim();
                                            string sCommission_ID_Deducted = clsValidate.ValidateGridValue(dgvReimbursement, "RI_CommmissionID_Deducted;", Row.Index, "default");
                                            Int64 iDeduction_ID = clsValidate.ValidateGridValue(dgvDeductions, "D_DeductionID", Row.Index, int.Parse("0"));
                                            string sInvoice_ID = clsValidate.ValidateGridValue(dgvReimbursement, "RI_InvoiceID;", Row.Index, "default");
                                            string sRemark = clsValidate.ValidateGridValue(dgvReimbursement, "RI_Remark;", Row.Index, "");
                                            DateTime dtmDeductedDate = clsValidate.ValidateGridValue(dgvDeductions, "RI_DeductedDate", Row.Index, clsSecurity.getServerDateTime());
                                            decimal dDeductedAmount = clsValidate.ValidateGridValue(dgvReimbursement, "RI_DeductedAmount", Row.Index, decimal.Parse("0.00"));
                                            decimal dReimburseAmount = clsValidate.ValidateGridValue(dgvReimbursement, "RI_ReimbursedAmount", Row.Index, decimal.Parse("0.00"));

                                            tbl_sasSalesCommission_Reimbursment oReimburse = new tbl_sasSalesCommission_Reimbursment(sCommission_ID, sInvoice_ID, dDeductedAmount, dReimburseAmount);
                                            oReimburse.Insert();

                                            if (sInvoice_ID != "default")
                                            {
                                                tbl_sasSalesCommission_Deduction oDeduction = tbl_sasSalesCommission_Deduction.Select(sCommission_ID_Deducted, iDeduction_ID, sInvoice_ID);
                                                if (oDeduction != null)
                                                {
                                                    oDeduction.IsSettled = true;
                                                    oDeduction.Update();
                                                }
                                            }

                                        } 
                                        #endregion

                                        MessageBox.Show(clsFormatter.GetMessageFrom(MessageType.SaveDone), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    }
                                    //else
                                    //{
                                    //    MessageBox.Show("Customer Order " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                                    //}
                                    #endregion
                                }
                            }
                            catch (Exception ex)
                            {
                                clsValidate.WriteErrorLog("", iFormID,ex);
                                SEACCException.Show(ex);
                            }
                            finally
                            {
                                Cursor = Cursors.Default;
                                ClearFields();
                                FillDetails(txtCommissionID.Text);
                            }
                        }
                        else
                        {
                            MessageBox.Show(" Permission " + clsFormatter.GetMessageFrom(MessageType.IDIsEmpty), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                }
            }
        }
        #endregion


        #region Datagrid Format
        private void CusDataGridViewFormat()
        {
            clsFormatter.ApplyGridFormat(dgvCommission, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour);
            clsFormatter.ApplyGridFormatModify(dgvInvoiceDetails, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour, clsFormatter.colorDigiteqTheamColorSales1BackColour);            
            clsFormatter.ApplyGridFormatModify(dgvDeductions, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour, clsFormatter.colorDigiteqTheamColorSales1BackColour);
            clsFormatter.ApplyGridFormat(dgvReimbursement, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour);
            clsFormatter.ApplyGridFormat(dgvCreditNoteDetail, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour);
            clsFormatter.ApplyGridFormat(dgvPaymentDetails, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour);
            clsFormatter.ApplyGridFormat(dgvOverDue, clsFormatter.colorDigiteqTheamColorSales1, clsFormatter.colorDigiteqTheamColorSales1ForColour);            
        }
        #endregion

        #region Clear Fields
        private void ClearFields()
        {
            IsUpdate = false;

            clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCommissionID, true);
            clsCommon.SetEnableDisable_NormalLabel(lblCommissionID, true);
            clsCommon.SetEnableDisable_ForeignKeyTextboxMust(txtSalesPerson, true);

            txtSalesPerson.Clear();
            txtYear.Clear();
            txtMonth.Clear();
            txtSalesPerson.Tag = null;
            txtYear.Tag = null;
            txtMonth.Tag = null;

            dgvCommission.Rows.Clear();
            dgvInvoiceDetails.Rows.Clear();
            dgvPaymentDetails.Rows.Clear();
            dgvDeductions.Rows.Clear();
            dgvReimbursement.Rows.Clear();
            dgvCreditNoteDetail.Rows.Clear();

            txtCom_SalesTarget.Text = "0.00";
            txtCom_ValidInvoicesAmt.Text = "0.00";
            txtCom_CreditNoteAmt.Text = "0.00";
            txtCom_ValidAmt.Text = "0.00";
            txtCom_Commission.Text = "0.00";
            
            txtInvoices_Valied.Text = "0.00";
            txtInvoices_OverDue.Text = "0.00";
            txtInvoices_Deduction.Text = "0.00";
            txtInvoices_Rejected.Text = "0.00";
            txtInvoices_Total.Text = "0.00";

            txtTot_ValidCommission.Text = "0.00";
            txtTot_ExceededSales.Text = "0.00";
            txtTot_Deductions.Text = "0.00";
            txtTot_Reimbursed.Text = "0.00";
            txtTot_Commission.Text = "0.00";

            txtRemark.Clear();
            if (txtSalesPerson.Enabled)
            {
                txtSalesPerson.SelectAll();
                txtSalesPerson.Focus();
            }           
        }
        #endregion

        #region Refresh All the Grids
        private void RefreshAllTheGrids()
        {
            RefreshGrid_Commission();
            RefreshGrid_InvoiceDetails();
            RefreshGrid_PaymentDetails();
            RefreshGrid_Deductions();
            RefreshGrid_Reimbursement();
        }

        #endregion

        #region Refresh Grid Commission
        private void RefreshGrid_Commission()
        {
            try
            {
                int iRow;
                dgvInvoiceDetails.Rows.Clear();

                if (txtCommissionID.Tag != null)
                {
                    tbl_sasSalesCommission oSasCommission = tbl_sasSalesCommission.Select(txtCommissionID.Tag.ToString());
                    if (oSasCommission.Commission_ID != null)
                    {
                        foreach (tbl_sasSalesCommission_Slab oCommission in tbl_sasSalesCommission_Slab.SelectAllByCommission_ID(oSasCommission.Commission_ID))
                        {
                            if (oCommission.Commission_ID.Trim() != "default")
                            {
                                dgvInvoiceDetails.Rows.Add();
                                iRow = dgvInvoiceDetails.Rows.Count - 1;
                                Fill_Datagrid_Commission(iRow, oCommission.FromAmount, oCommission.ToAmount, oCommission.CommissionPercentage, oCommission.CommissionAmount);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh Grid Invoice Details
        private void RefreshGrid_InvoiceDetails()
        {
            try
            {
                int iRow;
                dgvInvoiceDetails.Rows.Clear();
                if (txtCommissionID.Tag != null)
                {                 
                    tbl_sasSalesCommission oSasCommission = tbl_sasSalesCommission.Select(txtCommissionID.Tag.ToString());
                    if (oSasCommission.Commission_ID != null)
                    {                        
                        foreach (tbl_sasSalesCommission_Invoices oComInv in tbl_sasSalesCommission_Invoices.SelectAllByCommission_ID(oSasCommission.Commission_ID))
                        {
                            if (oComInv.Invoice_ID.Trim() != "default")
                            {                                
                                dgvInvoiceDetails.Rows.Add();
                                iRow = dgvInvoiceDetails.Rows.Count - 1;
                                string sStatus = "";//TODO Need a database field
                                Fill_Datagrid_Invoice(iRow, oComInv.CustomerName, oComInv.Invoice_ID, oComInv.InvoiceDate, oComInv.InvoiceAmount, oComInv.AllocationAmount, oComInv.Days, oComInv.IsRejected, sStatus);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh Grid Payment Details
        private void RefreshGrid_PaymentDetails()
        {
            try
            {
                int iRow;
                dgvInvoiceDetails.Rows.Clear();
                if (txtCommissionID.Tag != null)
                {
                  
                    tbl_sasSalesCommission oSasCommission = tbl_sasSalesCommission.Select(txtCommissionID.Tag.ToString());
                    if (oSasCommission.Commission_ID != null)
                    {
                        foreach (tbl_sasSalesCommission_Invoices_Payments oComInvPayment in tbl_sasSalesCommission_Invoices_Payments.SelectAllByCommission_ID(oSasCommission.Commission_ID))
                        {
                            if (oComInvPayment.Payment_ID.Trim() != "default")
                            {                               
                                decimal dInvoiceAmount = 0;
                                tbl_sasInvoice oComInv = tbl_sasInvoice.Select(oComInvPayment.Invoice_ID);
                                if (oComInv != null)
                                    dInvoiceAmount = oComInv.GrandTotal;
                                dgvInvoiceDetails.Rows.Add();
                                iRow = dgvInvoiceDetails.Rows.Count - 1;
                                Fill_Datagrid_Payment(iRow, "", oComInvPayment.Invoice_ID, oComInvPayment.InvoiceDate, dInvoiceAmount, oComInvPayment.Payment_ID, oComInvPayment.PaymentDate, oComInvPayment.Days);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh Grid Deductions
        private void RefreshGrid_Deductions()
        {
            try
            {
                int iRow;
                dgvDeductions.Rows.Clear();

                if (txtCommissionID.Tag != null)
                {
                    tbl_sasSalesCommission oSasCommission = tbl_sasSalesCommission.Select(txtCommissionID.Tag.ToString());
                    if (oSasCommission.Commission_ID != null)
                    {
                        string sCustomerName = "";
                        Int64 iDeduction_ID = 0;
                        foreach (tbl_sasSalesCommission_Deduction oDeduction in tbl_sasSalesCommission_Deduction.SelectAllByCommission_ID(oSasCommission.Commission_ID))
                        {
                            if (!oDeduction.IsInvoiceDeduction)
                            {
                                tbl_zDeductionMaster oDeductionMaster = tbl_zDeductionMaster.Select(oDeduction.Deduction_ID);
                                if (oDeductionMaster != null && oDeductionMaster.Deduction_ID != 0)
                                {
                                    sCustomerName = oDeductionMaster.Remark;
                                    iDeduction_ID = oDeductionMaster.Deduction_ID;
                                }
                            }

                            dgvDeductions.Rows.Add();
                            iRow = dgvDeductions.Rows.Count - 1;
                            Fill_Datagrid_Deduction(iRow, sCustomerName, oDeduction.Invoice_ID, oDeduction.InvoiceDate, oDeduction.InvoiceAmount, 0, oDeduction.PendingAmount, oDeduction.DeductionAmount, iDeduction_ID);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Refresh Grid Reimbursement
        private void RefreshGrid_Reimbursement()
        {
            try
            {
                int iRow;
                dgvInvoiceDetails.Rows.Clear();

                if (txtCommissionID.Tag != null)
                {
                    tbl_sasSalesCommission oSasCommission = tbl_sasSalesCommission.Select(txtCommissionID.Tag.ToString());
                    if (oSasCommission.Commission_ID != null)
                    {
                        foreach (tbl_sasSalesCommission_Reimbursment oReimbursement in tbl_sasSalesCommission_Reimbursment.SelectAllByCommission_ID(oSasCommission.Commission_ID))
                        {
                            if (oReimbursement.Invoice_ID != "default")
                            {
                                decimal dInvoiceAmount = 0;
                                DateTime dtmInvoiceDate = clsSecurity.getServerDateTime();
                                tbl_sasInvoice oComInv = tbl_sasInvoice.Select(oReimbursement.Invoice_ID);
                                if (oComInv != null)
                                {
                                    dInvoiceAmount = oComInv.GrandTotal;
                                    dtmInvoiceDate = oComInv.InvoiceDate;
                                }
                                dgvInvoiceDetails.Rows.Add();
                                iRow = dgvInvoiceDetails.Rows.Count - 1;
                                Fill_Datagrid_Reimbursement(iRow, oReimbursement.Invoice_ID, dtmInvoiceDate, oReimbursement.ReimburseAmount, oReimbursement.DeductedAmount);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }

        #endregion        

        #region Fill Details
        private void FillDetails(string sID)
        {
            try
            {
                if (sID.Length > 0)
                {
                    tbl_sasSalesCommission detail = tbl_sasSalesCommission.Select(sID);
                    if (detail != null)
                    {
                        //set the update flag and Locked
                        IsUpdate = true;
                        clsCommon.SetEnableDisable_PrimaryKeyTextbox(txtCommissionID, false);
                        clsCommon.SetEnableDisable_NormalLabel(lblCommissionID, false);

                        //assign values
                        txtSalesPerson.Text = clsGenaralName.getName_Employee(detail.Employee_ID);
                        txtSalesPerson.Tag = detail.Employee_ID;

                        txtYear.Text = detail.YearName;
                        txtYear.Tag = detail.YearName;
                        txtMonth.Tag = clsGenaralName.getMonthNumber(detail.MonthName);
                        txtMonth.Text = detail.MonthName;

                        RefreshAllTheGrids();

                        //-K-//Complete
                        txtCom_SalesTarget.Text = "0.00";
                        txtCom_ValidInvoicesAmt.Text = "0.00";
                        txtCom_CreditNoteAmt.Text = "0.00";
                        txtCom_ValidAmt.Text = "0.00";
                        txtCom_Commission.Text = "0.00";

                        txtRemark.Text = detail.Remark;

                        //-K-//Complete
                        txtTot_ValidCommission.Text = string.Empty;
                        txtTot_ExceededSales.Text = string.Empty;
                        txtTot_Deductions.Text = string.Empty;
                        txtTot_Reimbursed.Text = string.Empty;
                        txtTot_Commission.Text = string.Empty;
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion

        #region Fill Datagrid
        private void Fill_Datagrid_Invoice(int iRow, string sCustomerName, string sInvoiceID, DateTime dtmInvoiceDate, decimal dInvoiceAmount, decimal dAllocatedAmount, decimal dDays, bool bIsRejected, string sStatus)
        {
            try
            {
                if (glb_iColCount_Invoice == 0)
                {
                    glb_sColCustomerName = sCustomerName;
                    glb_iColCount_Invoice++;
                }
                else if (glb_sColCustomerName != sCustomerName)
                {
                    glb_sColCustomerName = sCustomerName;
                    glb_clRowColor_Invoice = (glb_clRowColor_Invoice == Color.Blue) ? Color.Green : Color.Blue;
                }

                dgvInvoiceDetails["Customer", iRow].Value = sCustomerName;
                dgvInvoiceDetails["InvoiceNoAndDate", iRow].Value = sInvoiceID + " - " + clsFormatter.FormatDate_Short(dtmInvoiceDate);
                dgvInvoiceDetails["InvoiceAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dInvoiceAmount);
                dgvInvoiceDetails["AllocationAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dAllocatedAmount);
                dgvInvoiceDetails["Days", iRow].Value = dDays;
                dgvInvoiceDetails["Status", iRow].Value = sStatus;
                dgvInvoiceDetails["InvoiceNo", iRow].Value = sInvoiceID;
                dgvInvoiceDetails["InvoiceDate", iRow].Value = dtmInvoiceDate.ToString("dd/MM/yyyy");

                dgvInvoiceDetails.Columns["Customer"].Width = 270;
                if (dgvInvoiceDetails.Rows.Count > 10)
                    dgvInvoiceDetails.Columns["Customer"].Width -= 16;
                dgvInvoiceDetails.Rows[iRow].DefaultCellStyle.ForeColor = glb_clRowColor_Invoice;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_OverDues(int iRow, string sCustomerName, string sInvoiceID, DateTime dtmInvoiceDate, decimal dInvoiceAmount, decimal dAllocatedAmount, decimal dDays)
        {
            try
            {
                if (glb_iColCount_OverDues == 0)
                {
                    glb_sColOverdues = sCustomerName;
                    glb_iColCount_OverDues++;
                }
                else if (glb_sColCustomerName != sCustomerName)
                {
                    glb_sColOverdues = sCustomerName;
                    glb_clRowColor_OverDues = (glb_clRowColor_OverDues == Color.Blue) ? Color.Green : Color.Blue;
                }

                dgvOverDue["OD_Customer", iRow].Value = sCustomerName;
                dgvOverDue["OD_InvNo_InvDate", iRow].Value = sInvoiceID + " - " + clsFormatter.FormatDate_Short(dtmInvoiceDate);
                dgvOverDue["OD_InvoiceAmt", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dInvoiceAmount);
                dgvOverDue["OD_ValidInvoiceAmt", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dAllocatedAmount);
                dgvOverDue["OD_Days", iRow].Value = dDays;
                dgvOverDue["OD_InvoiceNo", iRow].Value = sInvoiceID;
                dgvOverDue["OD_InvoiceDate", iRow].Value = dtmInvoiceDate.ToString("dd/MM/yyyy");

                dgvOverDue.Columns["OD_Customer"].Width = 384;
                if (dgvOverDue.Rows.Count > 10)
                    dgvOverDue.Columns["OD_Customer"].Width -= 16;
                dgvOverDue.Rows[iRow].DefaultCellStyle.ForeColor = glb_clRowColor_OverDues;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_CreditNote(int iRow, string sCustomerName, string sCreditNoteID, DateTime dtmCreditNoteDate, decimal dCreditNoteAmount, string sRemarks)
        {
            try
            {
                if (glb_iColCount_CreditNote == 0)
                {
                    glb_sColCreditNoteNo = sCustomerName;
                    glb_iColCount_CreditNote++;
                }
                else if (glb_sColCreditNoteNo != sCustomerName)
                {
                    glb_sColCreditNoteNo = sCustomerName;
                    glb_clRowColor_CreditNote = (glb_clRowColor_CreditNote == Color.Blue) ? Color.Green : Color.Blue;
                }

                dgvCreditNoteDetail["CR_Customer", iRow].Value = sCustomerName;
                dgvCreditNoteDetail["CR_CreditNoteID", iRow].Value = sCreditNoteID;
                dgvCreditNoteDetail["CR_CreditNoteDate", iRow].Value = clsFormatter.FormatDate_Short(dtmCreditNoteDate);
                dgvCreditNoteDetail["CR_Amount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dCreditNoteAmount);
                dgvCreditNoteDetail["CR_Remarks", iRow].Value = sRemarks;

                dgvCreditNoteDetail.Columns["CR_Customer"].Width = 290;
                if (dgvCreditNoteDetail.Rows.Count > 10)
                    dgvCreditNoteDetail.Columns["CR_Customer"].Width -= 16;
                dgvCreditNoteDetail.Rows[iRow].DefaultCellStyle.ForeColor = glb_clRowColor_CreditNote;
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_Commission(int iRow, decimal dCommissionFromAmount, decimal dCommissionToAmount, decimal dPercentage, decimal CommissionAmount)
        {
            try
            {
                dgvInvoiceDetails["CommissionSlab", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dCommissionFromAmount) + " - " + clsFormatter.FormatDecimalPlaces_Price(dCommissionToAmount);
                dgvInvoiceDetails["CommissionSlabValue", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dPercentage);
                dgvInvoiceDetails["CommissionSlabAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(CommissionAmount);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_Payment(int iRow, string sCustomerName, string sInvoiceID, DateTime dtmInvoiceDate, decimal dInvoiceAmount, string sPaymentID, DateTime dtmPaymentDate, decimal dDays)
        {
            try
            {
                if (glb_iColCount_Payment == 0)
                {
                    glb_sColInvoiceNo = sCustomerName;
                    glb_iColCount_Payment++;
                }
                else if (glb_sColInvoiceNo != sCustomerName)
                {
                    glb_sColInvoiceNo = sCustomerName;
                    glb_clRowColor_Payment = (glb_clRowColor_Payment == Color.Blue) ? Color.Green : Color.Blue;
                }

                dgvPaymentDetails["PD_CustomerName", iRow].Value = sCustomerName;
                dgvPaymentDetails["PD_InvoiceID", iRow].Value = sInvoiceID;
                dgvPaymentDetails["PD_InvoiceDate", iRow].Value = dtmInvoiceDate.ToString("dd/MM/yyyy");
                dgvPaymentDetails["PD_InvoiceAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dInvoiceAmount);
                dgvPaymentDetails["PD_PaymentID", iRow].Value = sPaymentID;
                dgvPaymentDetails["PD_PaymentDetails", iRow].Value = sPaymentID;
                //dgvPaymentDetails["PD_PaymentDate", iRow].Value = clsFormatter.FormatDate_Short(dtmPaymentDate);                //dtmInvoiceDate.ToString("dd/MM/yyyy");
                dgvPaymentDetails["PD_PaymentDate", iRow].Value = dtmPaymentDate.ToString("dd/MM/yyyy");
                dgvPaymentDetails["PD_Days", iRow].Value = dDays;                

                dgvPaymentDetails.Columns["PD_CustomerName"].Width = 228;
                if (dgvPaymentDetails.Rows.Count > 10)
                    dgvPaymentDetails.Columns["PD_CustomerName"].Width -= 16;
                dgvPaymentDetails.Rows[iRow].DefaultCellStyle.ForeColor = glb_clRowColor_Payment; 
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_Deduction(int iRow, string sCustomerName, string sInvoiceID, DateTime dtmInvoiceDate, decimal dInvoiceAmount, decimal dDays, decimal dPendingAmount, decimal dDeductionAmount, Int64 dDeductionID)
        {
            try
            {
                if (glb_iColCount_Deduction == 0)
                {
                    glb_sColDeductionName = sCustomerName;
                    glb_iColCount_Deduction++;
                }
                else if (glb_sColDeductionName != sCustomerName)
                {
                    glb_sColDeductionName = sCustomerName;
                    glb_clRowColor_Deduction = (glb_clRowColor_Deduction == Color.Blue) ? Color.Green : Color.Blue;
                }

                dgvDeductions["D_CustomerName", iRow].Value = sCustomerName;
                dgvDeductions["D_InvoiceID", iRow].Value = sInvoiceID;
                dgvDeductions["D_InvoiceDate", iRow].Value = clsFormatter.FormatDate_Short(dtmInvoiceDate);
                dgvDeductions["D_InvoiceAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dInvoiceAmount);
                dgvDeductions["D_Days", iRow].Value = dDays;
                dgvDeductions["D_PendingAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dPendingAmount);
                dgvDeductions["D_DeductionAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dDeductionAmount);
                dgvDeductions["D_DeductionID", iRow].Value = dDeductionID;

                dgvDeductions.Columns["D_CustomerName"].Width = 245;
                if (dgvDeductions.Rows.Count > 10)
                    dgvDeductions.Columns["D_CustomerName"].Width -= 16;
                dgvDeductions.Rows[iRow].DefaultCellStyle.ForeColor = glb_clRowColor_Deduction; 
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        private void Fill_Datagrid_Reimbursement(int iRow, string sInvoiceID, DateTime dtmInvoiceDate, decimal dReimbursementAmount, decimal dDeductionAmount)
        {
            try
            {
                dgvInvoiceDetails["RI_InvoiceID", iRow].Value = sInvoiceID;
                dgvInvoiceDetails["RI_InvoiceDate", iRow].Value = clsFormatter.FormatDate_Short(dtmInvoiceDate);
                dgvInvoiceDetails["RI_DeductedAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dDeductionAmount);
                dgvInvoiceDetails["RI_ReimbursedAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dReimbursementAmount);
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
        }
        #endregion


        #region Check Validity
        private bool CheckValidity_EmptyField()
        {
            bool bStatus = false;
            if (clsValidate.ValidateTextBox_EmptyValue(txtSalesPerson, "Sales Person"))
            {
                if (clsValidate.ValidateTextBox_EmptyValue(txtYear, "Year"))
                {
                    if (clsValidate.ValidateTextBox_EmptyValue(txtMonth, "Month"))
                    {
                        bStatus = true;
                    }
                }
            }
            return bStatus;
        }
        private bool CheckNumberValidity()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {


            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(clsFormatter.getCommonStatusStripMessage(StatusStripMessageTypes.WhenInserNumber, strMessage), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        private bool CheckValidity_CommissionDate()
        {
            string strMessage = "";
            bool bStatus = true;

            try
            {
                DateTime dtCommissionDate = DateTime.Parse("1." + txtMonth.Text.Trim() + " " + txtYear.Text.Trim());
                foreach (tbl_sasSalesCommission detail in tbl_sasSalesCommission.SelectAll())
                {
                    if (dtCommissionDate.Date == detail.CommissionDate.Date && txtSalesPerson.Tag.ToString() == detail.Employee_ID)
                    {
                        bStatus = false;
                        strMessage = "Invalid Commission Date: Already commission has given to the above month";
                    }
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            if (bStatus == false)
            {
                MessageBox.Show(strMessage, clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            return bStatus;
        }
        #endregion

        #region Events KeyDown
        private void txtSalesPerson_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_MasterEmployee_Advance(ref txtSalesPerson, false, true, false, false);
            }
        }
        private void txtYearFrom_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_Year(ref txtYear);
            }
        }

        private void txtMonthFrom_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_Month(ref txtMonth);
            }
        }

        private void txtCommissionID_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F1)
            {
                clsSearch.Search_SalesCommission(ref txtCommissionID);

                if (txtCommissionID.Tag != null && txtCommissionID.Tag.ToString().Trim().Length > 0)
                    FillDetails(txtCommissionID.Tag.ToString());
            }

        }
        #endregion

        #region Events TextChanged
        private void txtSalesPerson_TextChanged(object sender, EventArgs e)
        {
            if (txtSalesPerson.Tag != null)
                sEmployeeID = txtSalesPerson.Tag.ToString();
        }
        #endregion   

        #region Events DoubleClick
        private void txtSalesPerson_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_MasterEmployee_Advance(ref txtSalesPerson, false, true, false, false);
        }

        private void txtYearFrom_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_Year(ref txtYear);
        }

        private void txtMonthFrom_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_Month(ref txtMonth);
        }

        private void txtCommissionID_DoubleClick(object sender, EventArgs e)
        {
            clsSearch.Search_SalesCommission(ref txtCommissionID);

            if (txtCommissionID.Tag != null && txtCommissionID.Tag.ToString().Trim().Length > 0)
                FillDetails(txtCommissionID.Tag.ToString());
        }

        #endregion

        #region Events SelectedIndexChanged
        private void tabControl_SelectedIndexChanged(object sender, EventArgs e)
        {
            CalculateTotals();
        }
        #endregion

        #region Events Datagrid
        private void dgvDetail_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            //try
            //{
            //    string sID = dgvDetail["EmployeeID", e.RowIndex].Value.ToString();
            //    if (sID.Length > 0)
            //    {
            //        //fills the values to controls
            //        FillDetails(sID.Trim());
            //    }
            //}
            //catch (Exception ex)
            //{
            //    clsValidate.WriteErrorLog("", iFormID,ex);
            //    SEACCException.Show(ex);
            //}
        }

        private void dgvDetail_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            //dgvDetail_CellClick(sender, e);
        }
        #endregion        



        #region Calculate Commission
        private void CalculateCommission()
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                if (CheckValidity_EmptyField())
                {                    
                    DateTime dtFromDate = DateTime.Parse("1." + txtMonth.Text.Trim() + " " + txtYear.Text.Trim());
                    DateTime dtToDate = clsSecurity.LastDayOfMonthFromDateTime(dtFromDate);

                    List<tbl_genCustomerMaster> oCustomers = tbl_genCustomerMaster.SelectAll().Where(p => p.Customer_ID != "default" && !p.IsDeleted && p.SalesRep_ID == txtSalesPerson.Tag.ToString()).ToList();
                    foreach (tbl_genCustomerMaster oCustomer in oCustomers)
                    {                        
                        tbl_genCustomerFinance oCusFin = tbl_genCustomerFinance.Select(oCustomer.Customer_ID);
                        if (oCusFin != null && oCusFin.Customer_ID != "default")
                        {
                            #region Invoices
                            decimal dValidAmount = 0, dOverDueAmount = 0, dDeductionAmount = 0;
                            foreach (tbl_sasInvoice detail in tbl_sasInvoice.SelectAll_ByCustomerIDandDateRange(dtFromDate, dtToDate, oCustomer.Customer_ID).Where(p => p.Invoice_ID != "default" && !p.IsDeleted && !p.IsReturnedCheque && !p.IsDebitNote))
                            {
                                DateTime dtLastDayForThePayment = detail.InvoiceDate.AddDays(double.Parse(oCusFin.CommissionCreditPeriod.ToString()));
                                DateTime dtLastDayOfThePayment_ValidInvoices = detail.InvoiceDate;
                                DateTime dtLastDayOfThePayment_OverDues = detail.InvoiceDate;
                                dValidAmount = 0;
                                dOverDueAmount = 0;
                                dDeductionAmount = 0;

                                if (detail.Quotation_ID != "default" || (detail.Job_ID == "default" && detail.DeliveryOrder_ID != "default"))
                                    continue;

                                #region Payment Validation
                                foreach (tbl_sasInvoice_Sattled oSettment in tbl_sasInvoice_Sattled.SelectAllByInvoice_ID(detail.Invoice_ID))
                                {
                                    #region Cheque
                                    if (oSettment.ChequeRegister_ID != "default" && oSettment.Receipt_ID != "default") //Cheque
                                    {
                                        tbl_bpsChequeRegister oCheque = tbl_bpsChequeRegister.Select(oSettment.ChequeRegister_ID);
                                        if (oCheque != null && oCheque.ChequeRegister_ID != "default")
                                        {
                                            if (oCheque.IsReconcilied || oCheque.IsReIssued)
                                            {
                                                if (oCheque.ChequeStatus_ID != clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_C) && oCheque.ChequeStatus_ID != clsAutocode.getChequeStatusID(ChequeStatus.Returned_NR_O) && oCheque.ChequeStatus_ID != clsAutocode.getChequeStatusID(ChequeStatus.Returned_R))
                                                {
                                                    if (oCheque.DateReconcilied <= dtLastDayForThePayment)
                                                    {
                                                        //ok       
                                                        dValidAmount += oSettment.SattledAmount;
                                                        dtLastDayOfThePayment_ValidInvoices = oCheque.DateReconcilied > dtLastDayOfThePayment_ValidInvoices ? oCheque.DateReconcilied : dtLastDayOfThePayment_ValidInvoices;

                                                        dgvPaymentDetails.Rows.Add();
                                                        int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                        int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oCheque.DateReconcilied);
                                                        Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "Cheque " + oCheque.ChequeNumber, oCheque.DateReconcilied, iDays_Payment);
                                                    }
                                                    else
                                                    {
                                                        dOverDueAmount += oSettment.SattledAmount;
                                                        dtLastDayOfThePayment_OverDues = oCheque.DateReconcilied > dtLastDayOfThePayment_OverDues ? oCheque.DateReconcilied : dtLastDayOfThePayment_OverDues;

                                                        dgvPaymentDetails.Rows.Add();
                                                        int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                        int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oCheque.DateReconcilied);
                                                        Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "Cheque " + oCheque.ChequeNumber, oCheque.DateReconcilied, iDays_Payment);
                                                    }
                                                }
                                            }
                                            else
                                            {
                                                dOverDueAmount += oSettment.SattledAmount;
                                                dtLastDayOfThePayment_OverDues = oCheque.DateReconcilied > dtLastDayOfThePayment_OverDues ? oCheque.DateReconcilied : dtLastDayOfThePayment_OverDues;

                                                dgvPaymentDetails.Rows.Add();
                                                int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                int iDays_Payment = clsCommon.getDaysUptoDate(detail.InvoiceDate);
                                                Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "Cheque " + oCheque.ChequeNumber, oCheque.DateReconcilied, iDays_Payment);
                                            }
                                        }
                                    }
                                    #endregion

                                    #region Cash
                                    else if (oSettment.ChequeRegister_ID == "default" && oSettment.Receipt_ID != "default")
                                    {
                                        tbl_bpsReceipt oReceipt = tbl_bpsReceipt.Select(oSettment.Receipt_ID);
                                        if (oReceipt != null && oReceipt.Receipt_ID != "default")
                                        {
                                            if (oReceipt.ReceiptDate <= dtLastDayForThePayment)
                                            {
                                                dValidAmount += oSettment.SattledAmount;
                                                dtLastDayOfThePayment_ValidInvoices = oReceipt.ReceiptDate > dtLastDayOfThePayment_ValidInvoices ? oReceipt.ReceiptDate : dtLastDayOfThePayment_ValidInvoices;

                                                dgvPaymentDetails.Rows.Add();
                                                int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oReceipt.ReceiptDate);
                                                Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "Cash " + oReceipt.Receipt_ID, oReceipt.ReceiptDate, iDays_Payment);
                                            }
                                            else
                                            {
                                                dOverDueAmount += oSettment.SattledAmount;
                                                dtLastDayOfThePayment_OverDues = oReceipt.ReceiptDate > dtLastDayOfThePayment_OverDues ? oReceipt.ReceiptDate : dtLastDayOfThePayment_OverDues;

                                                dgvPaymentDetails.Rows.Add();
                                                int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oReceipt.ReceiptDate);
                                                Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "Cash " + oReceipt.Receipt_ID, oReceipt.ReceiptDate, iDays_Payment);
                                            }
                                        }
                                    }
                                    #endregion

                                    #region Credit Note - Adding To Credit Note Total
                                    else if (oSettment.CreditNote_ID != "default")
                                    {
                                        tbl_bpsCreditNote oCreditNote = tbl_bpsCreditNote.Select(oSettment.CreditNote_ID);
                                        if (oCreditNote != null && oCreditNote.CreditNote_ID != "default")
                                        {
                                            if (oCreditNote.CreditNoteDate <= dtLastDayForThePayment)
                                            {
                                                dValidAmount += oSettment.SattledAmount;
                                                dtLastDayOfThePayment_ValidInvoices = oCreditNote.CreditNoteDate > dtLastDayOfThePayment_ValidInvoices ? oCreditNote.CreditNoteDate : dtLastDayOfThePayment_ValidInvoices;

                                                dgvPaymentDetails.Rows.Add();
                                                int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oCreditNote.CreditNoteDate);
                                                Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "CRN " + oCreditNote.CreditNote_ID, oCreditNote.CreditNoteDate, iDays_Payment);
                                            }
                                            else
                                            {
                                                dOverDueAmount += oSettment.SattledAmount;
                                                dtLastDayOfThePayment_OverDues = oCreditNote.CreditNoteDate > dtLastDayOfThePayment_OverDues ? oCreditNote.CreditNoteDate : dtLastDayOfThePayment_OverDues;

                                                dgvPaymentDetails.Rows.Add();
                                                int iRow_Payment = dgvPaymentDetails.Rows.Count - 1;
                                                int iDays_Payment = clsCommon.getDays(detail.InvoiceDate, oCreditNote.CreditNoteDate);
                                                Fill_Datagrid_Payment(iRow_Payment, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, oSettment.SattledAmount, "CRN " + oCreditNote.CreditNote_ID, oCreditNote.CreditNoteDate, iDays_Payment);
                                            }
                                        }
                                    }
                                    #endregion
                                }
                                #endregion
                
                                #region Reduce Taxes
                                dDeductionAmount = (detail.GrandTotal - detail.SeattleAmount);
                                if (oCustomer.CustomerType_ID == "2")
                                {
                                    dValidAmount = clsProcessMethods.Reduce_VATnNBT_FromGrandTotal(dValidAmount, detail.VatPercentage, detail.NbtPercentage);
                                    dDeductionAmount = clsProcessMethods.Reduce_VATnNBT_FromGrandTotal(dDeductionAmount, detail.VatPercentage, detail.NbtPercentage);
                                    dOverDueAmount = clsProcessMethods.Reduce_VATnNBT_FromGrandTotal(dOverDueAmount, detail.VatPercentage, detail.NbtPercentage);
                                } 
                                #endregion

                                #region Add Valid Invoice Detail
                                if (dValidAmount > 0)
                                {
                                    int iDaysForLastPayment = clsCommon.getDays(detail.InvoiceDate, dtLastDayOfThePayment_ValidInvoices);
                                    dgvInvoiceDetails.Rows.Add();
                                    int iRow = dgvInvoiceDetails.Rows.Count - 1;
                                    Fill_Datagrid_Invoice(iRow, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, detail.GrandTotal, dValidAmount, iDaysForLastPayment, false, "Valied");
                                }
                                #endregion

                                #region Add Deduction detail
                                if (dDeductionAmount > 0)
                                {
                                    int iDaysUntilToday = clsCommon.getDaysUptoDate(detail.InvoiceDate);                                    
                                    dgvDeductions.Rows.Add();
                                    int iRowDeduction = dgvDeductions.Rows.Count - 1;
                                    Fill_Datagrid_Deduction(iRowDeduction, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, detail.GrandTotal, iDaysUntilToday, dDeductionAmount, dDeductionAmount, 0);

                                    //Add Invoice Record                                   
                                    dgvInvoiceDetails.Rows.Add();
                                    int iRow = dgvInvoiceDetails.Rows.Count - 1;
                                    Fill_Datagrid_Invoice(iRow, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, detail.GrandTotal, dDeductionAmount, iDaysUntilToday, false, "Deduction");
                                }
                                #endregion

                                #region Add Overdue detail
                                if (dOverDueAmount > 0)
                                {
                                    int iDaysForOverDues = clsCommon.getDays(detail.InvoiceDate, dtLastDayOfThePayment_OverDues);                                    
                                    dgvOverDue.Rows.Add();
                                    int iRowOverDue = dgvOverDue.Rows.Count - 1;
                                    Fill_Datagrid_OverDues(iRowOverDue, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, detail.GrandTotal, dOverDueAmount, iDaysForOverDues);

                                    //Add Invoice Record                                    
                                    dgvInvoiceDetails.Rows.Add();
                                    int iRow = dgvInvoiceDetails.Rows.Count - 1;
                                    Fill_Datagrid_Invoice(iRow, oCustomer.CustomerName, detail.Invoice_ID, detail.InvoiceDate, detail.GrandTotal, dOverDueAmount, iDaysForOverDues, false, "OverDue");
                                }
                                #endregion
                            } 
                            #endregion

                            #region CreditNotes
                            foreach (tbl_bpsCreditNote oCRN in tbl_bpsCreditNote.SelectAll_ByCustomerIDandDateRange(dtFromDate, dtToDate, oCustomer.Customer_ID).Where(p => p.CreditNote_ID != "default" && !p.IsDeleted && p.IsSeattled))
                            {
                                decimal dCreditAmount = 0;
                                if (oCustomer.CustomerType_ID == "2")
                                {
                                    dCreditAmount = clsProcessMethods.Reduce_VATnNBT_FromGrandTotal(oCRN.TotalAmount, oCRN.VatPercentage, oCRN.NbtPercentage);                                   
                                }

                                dgvCreditNoteDetail.Rows.Add();
                                int iRow = dgvCreditNoteDetail.Rows.Count - 1;
                                Fill_Datagrid_CreditNote(iRow, oCustomer.CustomerName, oCRN.CreditNote_ID, oCRN.CreditNoteDate, dCreditAmount, clsGenaralName.getName_CreditNoteType(oCRN.CreditNoteType_ID));
                            }
                            #endregion
                        }
                    }

                    #region Add Deduction detail
                    foreach (tbl_zDeductionMaster oDeduction in tbl_zDeductionMaster.SelectAllByEmployee_ID(txtSalesPerson.Tag.ToString()).Where(p=> !p.IsSettled))
                    {
                        int iDaysForLastPayment = clsCommon.getDaysUptoDate(oDeduction.DeductionDate);
                        decimal dPendingAmount = (oDeduction.DeductionAmount - oDeduction.SettledAmount);
                        dgvDeductions.Rows.Add();
                        int iRow = dgvDeductions.Rows.Count - 1;
                        Fill_Datagrid_Deduction(iRow, oDeduction.Remark, oDeduction.Deduction_ID.ToString(), oDeduction.DeductionDate, oDeduction.DeductionAmount, iDaysForLastPayment, dPendingAmount, dPendingAmount, oDeduction.Deduction_ID);
                    }

                    #endregion

                    CalculateTotals();
                }
            }
            catch (Exception ex)
            {
                clsValidate.WriteErrorLog("", iFormID,ex);
                SEACCException.Show(ex);
            }
            finally {
                Cursor = Cursors.Default;
            }
        } 
        #endregion

        #region Calculate Totals
        private void CalculateTotals()
        {
            if (CheckValidity_EmptyField())
            {
                decimal dSalesTarget = 0, dTotalValiedAmount = 0, dCreditnoteTotal = 0, dTotalCommission = 0, dDeductionTotal = 0, dExceededTotal = 0, dReimbursmentTotal = 0, dTotalPaid = 0;
                decimal dInvValied = 0, dInvOverDue = 0, dInvDeduction = 0, dInvTotal = 0, dInvRejected = 0;
                foreach (DataGridViewRow row in dgvInvoiceDetails.Rows)
                {
                    string sStatus = clsValidate.ValidateGridValue(dgvInvoiceDetails, "Status", row.Index, "");
                    decimal dAllocatedAmount = clsValidate.ValidateGridValue(dgvInvoiceDetails, "AllocationAmount", row.Index, decimal.Parse("0.00"));
                    bool bRejected = clsValidate.ValidateGridValue(dgvInvoiceDetails, "InvoiceReject", row.Index, false);

                    if (!bRejected)
                    {
                        if (sStatus == "Valied")
                            dInvValied += dAllocatedAmount;
                        else if (sStatus == "Deduction")
                            dInvDeduction += dAllocatedAmount;
                        else if (sStatus == "OverDue")
                            dInvOverDue += dAllocatedAmount;
                    }
                    else
                        dInvRejected += dAllocatedAmount;
                    dInvTotal += dAllocatedAmount;
                }
                foreach (DataGridViewRow row in dgvCreditNoteDetail.Rows)
                {
                    dCreditnoteTotal += clsValidate.ValidateGridValue(dgvCreditNoteDetail, "CR_Amount", row.Index, decimal.Parse("0.00"));
                }
                foreach (DataGridViewRow row in dgvDeductions.Rows)
                {
                    dDeductionTotal += clsValidate.ValidateGridValue(dgvDeductions, "D_DeductionAmount", row.Index, decimal.Parse("0.00"));
                }
                dTotalValiedAmount = (dInvValied - dCreditnoteTotal);

                #region Fill Grid
                dgvCommission.Rows.Clear();
                foreach (tbl_zEmployeeSlabSettings oSlab in tbl_zEmployeeSlabSettings.SelectAllByEmployee_ID(txtSalesPerson.Tag.ToString()).OrderBy(p => p.SlabID))
                {
                    decimal dAllocatedAmount = 0, dTmpTotalValiedAmount = dTotalValiedAmount;
                    decimal dAmount = 0;
                    if (dTmpTotalValiedAmount >= oSlab.ToAmount)
                    {
                        dAllocatedAmount = oSlab.ToAmount;
                        dAmount = (dAllocatedAmount * oSlab.CommissionPercentage) / 100;
                        dTotalCommission += dAmount;
                        dTmpTotalValiedAmount -= dAllocatedAmount;
                    }
                    else if (dTmpTotalValiedAmount < oSlab.ToAmount)
                    {
                        dAllocatedAmount = dTmpTotalValiedAmount;
                        dAmount = (dAllocatedAmount * oSlab.CommissionPercentage) / 100;
                        dTotalCommission += dAmount;
                        dTmpTotalValiedAmount -= dAllocatedAmount;
                    }

                    dgvCommission.Rows.Add();
                    int iRow = dgvCommission.Rows.Count - 1;
                    dgvCommission["CM_SlabID", iRow].Value = oSlab.SlabID;
                    dgvCommission["CM_FromAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(oSlab.FromAmount);
                    dgvCommission["CM_ToAmount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(oSlab.ToAmount);
                    dgvCommission["CM_Percentage", iRow].Value = clsFormatter.FormatToNumberWithOneDecimalPlaces(oSlab.CommissionPercentage);
                    dgvCommission["CM_Amount", iRow].Value = clsFormatter.FormatDecimalPlaces_Price(dAmount);
                }
                #endregion

                txtInvoices_Valied.Text = clsFormatter.FormatDecimalPlaces_Price(dInvValied);
                txtInvoices_OverDue.Text = clsFormatter.FormatDecimalPlaces_Price(dInvOverDue);
                txtInvoices_Deduction.Text = clsFormatter.FormatDecimalPlaces_Price(dInvDeduction);
                txtInvoices_Rejected.Text = clsFormatter.FormatDecimalPlaces_Price(dInvRejected);
                txtInvoices_Total.Text = clsFormatter.FormatDecimalPlaces_Price(dInvTotal);

                txtCom_SalesTarget.Text = clsFormatter.FormatDecimalPlaces_Price(dSalesTarget);
                txtCom_ValidInvoicesAmt.Text = clsFormatter.FormatDecimalPlaces_Price(dInvValied);
                txtCom_CreditNoteAmt.Text = clsFormatter.FormatDecimalPlaces_Price(dCreditnoteTotal);
                txtCom_ValidAmt.Text = clsFormatter.FormatDecimalPlaces_Price(dTotalValiedAmount);
                txtCom_Commission.Text = clsFormatter.FormatDecimalPlaces_Price(dTotalCommission);

                dTotalPaid = (dTotalCommission - dDeductionTotal) + dReimbursmentTotal;
                txtTot_ValidCommission.Text = clsFormatter.FormatDecimalPlaces_Price(dTotalCommission);
                txtTot_Deductions.Text = clsFormatter.FormatDecimalPlaces_Price(dDeductionTotal);
                txtTot_Reimbursed.Text = clsFormatter.FormatDecimalPlaces_Price(dReimbursmentTotal);
                txtTot_ExceededSales.Text = clsFormatter.FormatDecimalPlaces_Price(dExceededTotal);
                txtTot_Commission.Text = clsFormatter.FormatDecimalPlaces_Price(dTotalPaid);
            }
        }
        #endregion
    }

    class clsPaymentDetail
    {
        #region Fields
        string sCustomerName;
        string sInvoiceID;
        DateTime dtmInvoiceDate;
        decimal dInvoiceAmount;
        string sPaymentID;
        string sPaymentDetail;
        string sPaymentDate;
        decimal dDays;

        public string SCustomerName
        {
            get { return sCustomerName; }
            set { sCustomerName = value; }
        }
        public string SInvoiceID
        {
            get { return sInvoiceID; }
            set { sInvoiceID = value; }
        }
        public DateTime DtmInvoiceDate
        {
            get { return dtmInvoiceDate; }
            set { dtmInvoiceDate = value; }
        }
        public decimal DInvoiceAmount
        {
            get { return dInvoiceAmount; }
            set { dInvoiceAmount = value; }
        }
        public string SPaymentID
        {
            get { return sPaymentID; }
            set { sPaymentID = value; }
        }
        public string SPaymentDetail
        {
            get { return sPaymentDetail; }
            set { sPaymentDetail = value; }
        }
        public string SPaymentDate
        {
            get { return sPaymentDate; }
            set { sPaymentDate = value; }
        }
        public decimal DDays
        {
            get { return dDays; }
            set { dDays = value; }
        } 
        #endregion

        #region Constructors
        clsPaymentDetail(string sCustomerName, string sInvoiceID, DateTime dtmInvoiceDate, decimal dInvoiceAmount, string sPaymentID, string sPaymentDetail, string sPaymentDate, decimal dDays)
        {
            this.sCustomerName = sCustomerName;
            this.sInvoiceID = sInvoiceID;
            this.dtmInvoiceDate = dtmInvoiceDate;
            this.dInvoiceAmount = dInvoiceAmount;
            this.sPaymentID = sPaymentID;
            this.sPaymentDetail = sPaymentDetail;
            this.sPaymentDate = sPaymentDate;
            this.dDays = dDays;
        }
        #endregion
    }
}

    



