const STATUS_CLASS = {
  Active: 'ml-badge-open',
  Approved: 'ml-badge-open',
  Approve: 'ml-badge-open',
  'Approval On-Hold': 'ml-badge-locked',
  'Approval Rejected': 'ml-badge-void',
  Audited: 'ml-badge-open',
  Cancelled: 'ml-badge-void',
  Certified: 'ml-badge-open',
  Cleared: 'ml-badge-open',
  Closed: 'ml-badge-void',
  Confirm: 'ml-badge-open',
  Confirmed: 'ml-badge-open',
  Countersigned: 'ml-badge-open',
  Draft: 'ml-badge-draft',
  Inactive: 'ml-badge-locked',
  'On-Hold': 'ml-badge-locked',
  OnHold: 'ml-badge-locked',
  Overdue: 'ml-badge-void',
  Paid: 'ml-badge-open',
  Posted: 'ml-badge-open',
  Reject: 'ml-badge-void',
  Rejected: 'ml-badge-void',
  Requested: 'ml-badge-draft',
  Settled: 'ml-badge-open',
  Signed: 'ml-badge-locked',
  Submitted: 'ml-badge-locked',
  Verified: 'ml-badge-locked',
};

export default STATUS_CLASS;
