using DataTire;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.IO.Ports;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using System.IO;
using System.Data.SqlClient;
using System.Drawing;

namespace Digiteq_Logic
{
   public class clsUtil
    {
      
        //Email Create
        //Email Settings & Others

        #region Send Mail
        //public static bool SendMail(string sUserID, ArrayList sMailTo, ArrayList sFilePaths, string Subject, string Body, bool bShowMessage)
        //{
        //    bool bSuccess = false;
        //    tbl_utlEmailConfig mail = tbl_utlEmailConfig.Select(sUserID);
        //    if (mail != null)
        //    {
        //        try
        //        {
        //            MailAddress From = new MailAddress(mail.EmailAddress);
        //            MailMessage message = new MailMessage();
        //            message.From = From;

        //            foreach (string ToAdd in sMailTo)
        //            {
        //                MailAddress to = new MailAddress(ToAdd.ToString());
        //                message.To.Add(to);
        //            }

        //            message.Subject = Subject;
        //            message.Body = Body;

        //            SmtpClient smtp = new SmtpClient();
        //            smtp.Host = mail.SmtpClient;
        //            smtp.Port = mail.SmtpPort;
        //            smtp.EnableSsl = true;
        //            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
        //            smtp.UseDefaultCredentials = false;
        //            smtp.Credentials = new NetworkCredential(From.Address, clsSecurity.decryptPassword(mail.EmailPassword));

        //            foreach (String sFilpath in sFilePaths)
        //            {
        //                Attachment att = new Attachment(sFilpath);
        //                message.Attachments.Add(att);
        //            }

        //            smtp.Send(message);
        //            if (bShowMessage)
        //            {
        //                MessageBox.Show("Email sent successfully!");

        //            } bSuccess = true;
        //        }

        //        catch (Exception ex)
        //        {
        //            bSuccess = false;
        //            if (bShowMessage)
        //                MessageBox.Show("Failed to send message because " + ex.Message);
        //        }

        //    }
        //    return bSuccess;
        //}
        //#endregion

        //#region Send Mail HTML
        //public static void SendMailHTML(string sAlertID, string sSubject, string sBodyHTML)
        //{
        //    int Emailid = int.Parse(clsAutocode.getAutoGeneratedCode(clsAutocode.getFormConfigCode(FormName.EmailBox)));
        //    tbl_utlAlertMailBox_Pending oAlerts = new tbl_utlAlertMailBox_Pending(Emailid, sAlertID, sSubject, sBodyHTML, 0);
        //    oAlerts.Insert();
        //    int i = 0;
        //    foreach (tbl_utlAlertSettings oAlertSetting in tbl_utlAlertSettings.SelectAllByAlert_ID(sAlertID))
        //    {
        //        if (oAlertSetting.UserEmail1.Length > 0)
        //        {
        //            tbl_utlAlertMailBox_Receiver oAlertRes = new tbl_utlAlertMailBox_Receiver(Emailid, i, 0, oAlertSetting.PersonName, oAlertSetting.UserEmail1);
        //            oAlertRes.Insert();
        //            i++;
        //        }
        //    }
        //}
        //public static bool SendMailHTML(string sUserID, ArrayList sMailTo, ArrayList sFilePaths, string Subject, string Body, bool bShowMessage)
        //{
        //    bool bSuccess = false;
        //    tbl_utlEmailConfig mail = tbl_utlEmailConfig.Select(sUserID);
        //    if (mail != null)
        //    {
        //        try
        //        {
        //            MailAddress From = new MailAddress(mail.EmailAddress);
        //            MailMessage message = new MailMessage();
        //            message.IsBodyHtml = true;
        //            message.From = From;

        //            foreach (string ToAdd in sMailTo)
        //            {
        //                MailAddress to = new MailAddress(ToAdd.ToString());
        //                message.To.Add(to);
        //            }

        //            message.Subject = Subject;
        //            message.Body = Body;

        //            SmtpClient smtp = new SmtpClient();
        //            smtp.Host = mail.SmtpClient;
        //            smtp.Port = mail.SmtpPort;
        //            smtp.EnableSsl = true;
        //            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
        //            smtp.UseDefaultCredentials = false;
        //            smtp.Credentials = new NetworkCredential(From.Address, clsSecurity.decryptPassword(mail.EmailPassword));

        //            foreach (String sFilpath in sFilePaths)
        //            {
        //                Attachment att = new Attachment(sFilpath);
        //                message.Attachments.Add(att);
        //            }

        //            smtp.Send(message);
        //            if (bShowMessage)
        //            {
        //                MessageBox.Show("Email sent successfully!");

        //            } bSuccess = true;
        //        }

        //        catch (Exception ex)
        //        {
        //            bSuccess = false;
        //            if (bShowMessage)
        //                MessageBox.Show("Failed to send message because " + ex.Message);
        //        }
        //    }
        //    return bSuccess;

        //}
        //#endregion 
        #endregion

        #region SMS
        // SMS Create

        #region SMS Alerts JIT

        #region Creating Invoice
        public static void CreateSMS_InvoiceCreate(enum_Alerts alertType, string sMobile, string sMessage)
        {
            bool SmsStatus = false;
            try
            {
                tbl_utlAlert oAlert = tbl_utlAlert.Select(clsAutocode.getAlertID(alertType));
                if (oAlert != null && oAlert.Alert_ID != "default" && oAlert.IsActive)
                {
                    //Send Direct Number if Exists
                    if (sMobile.Length > 0)
                    {
                        SmsStatus = sendMessage_UsingShareFolder(sMobile, sMessage);
                    }

                    //Send For Setting Number
                    foreach (tbl_utlAlertSettings oAlertSetting in tbl_utlAlertSettings.SelectAllByAlert_ID(oAlert.Alert_ID))
                    {
                        if (oAlertSetting.PhoneNo1.Length > 0)
                        {
                            SmsStatus = sendMessage_UsingShareFolder(oAlertSetting.PhoneNo1, sMessage);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString(), clsFormatter.GetMessageCaption(), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
        #endregion
        #endregion

        //SMS Settings & Others

        #region SMS Open and Close Ports
        public static AutoResetEvent receiveNow;

        //Open Port
        public static SerialPort OpenPort(string p_strPortName, int p_uBaudRate, int p_uDataBits, int p_uReadTimeout, int p_uWriteTimeout)
        {
            receiveNow = new AutoResetEvent(false);
            SerialPort port = new SerialPort();

            try
            {
                port.PortName = p_strPortName;                 //COM1
                port.BaudRate = p_uBaudRate;                   //9600
                port.DataBits = p_uDataBits;                   //8
                port.StopBits = StopBits.One;                  //1
                port.Parity = Parity.None;                     //None
                port.ReadTimeout = p_uReadTimeout;             //300
                port.WriteTimeout = p_uWriteTimeout;           //300
                port.Encoding = Encoding.GetEncoding("iso-8859-1");
                port.DataReceived += new SerialDataReceivedEventHandler(port_DataReceived);
                port.Open();
                port.DtrEnable = true;
                port.RtsEnable = true;
            }
            catch (Exception)
            {
            }
            return port;
        }

        //Close Port
        public static void ClosePort(SerialPort port)
        {
            try
            {
                port.Close();
                port.DataReceived -= new SerialDataReceivedEventHandler(port_DataReceived);
                port = null;
            }
            catch (Exception)
            {
            }
        }
        #endregion

        #region Receive data from port
        //Receive data from port
        public static void port_DataReceived(object sender, SerialDataReceivedEventArgs e)
        {
            try
            {
                if (e.EventType == SerialData.Chars)
                {
                    receiveNow.Set();
                }
            }
            catch (Exception)
            {
            }
        }
        public static string ReadResponse(SerialPort port, int timeout)
        {
            string buffer = string.Empty;
            try
            {
                do
                {
                    if (receiveNow.WaitOne(timeout, false))
                    {
                        string t = port.ReadExisting();
                        buffer += t;
                    }
                    else
                    {
                        if (buffer.Length > 0)
                            throw new ApplicationException("Response received is incomplete.");
                        else
                            throw new ApplicationException("No data received from phone.");
                    }
                }
                while (!buffer.EndsWith("\r\nOK\r\n") && !buffer.EndsWith("\r\n> ") && !buffer.EndsWith("\r\nERROR\r\n"));
            }
            catch (Exception)
            {
            }
            return buffer;
        }
        #endregion

        #region Execute AT Command
        //Execute AT Command
        public static string ExecCommand(SerialPort port, string command, int responseTimeout, string errorMessage)
        {
            try
            {

                port.DiscardOutBuffer();
                port.DiscardInBuffer();
                receiveNow.Reset();
                port.Write(command + "\r");

                string input = ReadResponse(port, responseTimeout);
                if ((input.Length == 0) || ((!input.EndsWith("\r\n> ")) && (!input.EndsWith("\r\nOK\r\n"))))
                    throw new ApplicationException("No success message was received.");
                return input;
            }
            catch (Exception)
            {
                throw;
            }
        }
        #endregion

        #region Send SMS
        static AutoResetEvent readNow = new AutoResetEvent(false);
        public static bool sendMessage(string PhoneNo, string Message)
        {
            bool isSend = false;

            try
            {
                SerialPort port = OpenPort(clsConfig.sDonglePortNo, 9600, 8, 300, 300);

                string recievedData = ExecCommand(port, "AT", 300, "No phone connected");
                recievedData = ExecCommand(port, "AT+CMGF=1", 300, "Failed to set message format.");
                String command = "AT+CMGS=\"" + PhoneNo + "\"";
                recievedData = ExecCommand(port, command, 300, "Failed to accept phoneNo");
                command = Message + char.ConvertFromUtf32(26) + "\r";
                recievedData = ExecCommand(port, command, 3000, "Failed to send message"); //3 seconds
                if (recievedData.EndsWith("\r\nOK\r\n"))
                {
                    isSend = true;
                }
                else if (recievedData.Contains("ERROR"))
                {
                    isSend = false;
                }

                ClosePort(port);
                return isSend;
            }
            catch (Exception)
            {
                throw;
            }

        }
        public static bool sendMessage_UsingShareFolder(string iPhoneNo, string sMessage)
        {
            bool bRaisedError = false;
            string sFileName = "";
            StreamWriter file = null;
            try
            {
                sFileName = DateTime.Now.ToString() + ".dat";
                sFileName = sFileName.Replace("/", "-");
                sFileName = sFileName.Replace(":", ".");
                using (file = new StreamWriter(clsConfig.sGbl_SMS_Shared_Folder_Parth + sFileName))
                {
                    file.Write(iPhoneNo.ToString() + ";" + sMessage);
                    clsValidate.WriteSMSLog(iPhoneNo.ToString() + ";" + sMessage+"\r\n");
                    bRaisedError = true;                    
                }
            }
            catch (DirectoryNotFoundException)
            {

               Directory.CreateDirectory(clsConfig.sGbl_SMS_Shared_Folder_Parth);
                using (file = new StreamWriter(clsConfig.sGbl_SMS_Shared_Folder_Parth + sFileName))
                {
                    file.Write(iPhoneNo.ToString() + ";" + sMessage);
                    clsValidate.WriteSMSLog(iPhoneNo.ToString() + ";" + sMessage);
                    bRaisedError = true;
                }
            }
            catch (Exception exception)
            {
                bRaisedError = false;
                MessageBox.Show("Failed to send message because " + exception.Message);
            }
            finally
            {
                file.Close();
                file.Dispose();
            }
            return bRaisedError;

        }
        static void DataReceived(object sender, SerialDataReceivedEventArgs e)
        {
            try
            {
                if (e.EventType == SerialData.Chars)
                    readNow.Set();
            }
            catch (Exception)
            {
            }
        }
        #endregion

        #region Read SMS
        //public AutoResetEvent receiveNow;
        //public ShortMessageCollection ReadSMS(SerialPort port, string p_strCommand, bool bMsgType)
        //{

        //    // Set up the phone and read the messages
        //    ShortMessageCollection messages = null;
        //    try
        //    {

        //        #region Execute Command
        //        // Check connection
        //        ExecCommand(port, "AT", 300, "No phone connected");
        //        // Use message format "Text mode"
        //        ExecCommand(port, "AT+CMGF=1", 300, "Failed to set message format.");
        //        //// Use character set "PCCP437"
        //        //ExecCommand(port,"AT+CSCS=\"PCCP437\"", 300, "Failed to set character set.");               
        //        // Select SIM storage
        //        ExecCommand(port, "AT+CPMS=\"SM\"", 300, "Failed to select message storage.");
        //        // Read the messages
        //        string input = ExecCommand(port, p_strCommand, 5000, "Failed to read the messages.");
        //        #endregion

        //        #region Parse messages
        //        messages = ParseMessages(input, bMsgType);
        //        #endregion

        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }

        //    if (messages != null)
        //        return messages;
        //    else
        //        return null;

        //}
        //public ShortMessageCollection ParseMessages(string input, bool bMsgType)
        //{
        //    ShortMessageCollection messages = new ShortMessageCollection();
        //    try
        //    {
        //        Regex r;
        //        if (bMsgType)
        //            r = new Regex(@"\+CMGL: (\d+),""(.+)"",""(.+)"",(.*),""(.+)""\r\n(.+)\r\n");
        //        else
        //            r = new Regex(@"\+CMGL: (\d+),""(.+)"",(\d+),(\d+),""(.+)"",(\d+),""(.+)"",""(.+)"",(\d+)\r\n");

        //        Match m = r.Match(input);
        //        while (m.Success)
        //        {
        //            ShortMessage msg = new ShortMessage();

        //            if (bMsgType)
        //            {
        //                msg.Index = m.Groups[1].Value;
        //                msg.Status = m.Groups[2].Value;
        //                msg.Sender = m.Groups[3].Value;
        //                msg.Alphabet = m.Groups[4].Value;
        //                msg.Sent = m.Groups[5].Value;
        //                msg.Message = m.Groups[6].Value;
        //            }
        //            else
        //            {
        //                msg.Index = m.Groups[1].Value;
        //                msg.Status = m.Groups[2].Value;
        //                msg.Alphabet = m.Groups[4].Value;
        //                msg.Sent = m.Groups[8].Value;
        //                msg.Sender = m.Groups[5].Value;
        //                if (m.Groups[9].Value == "0")
        //                    msg.Message = "Delivered";
        //                else if (m.Groups[9].Value == "34")
        //                    msg.Message = "Pending";
        //            }

        //            messages.Add(msg);
        //            m = m.NextMatch();
        //        }

        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //    return messages;
        //}
        #endregion 
        #endregion

        #region Barcode/QR Code
        public static byte[] GetBarcode(string sValue)
        {
            byte[] barcodeInBytes=null;
            //Image myimg = Code128Rendering.MakeBarcodeImage(sValue, 2, true);
            //ImageConverter _imageConverter = new ImageConverter();
            //barcodeInBytes = (byte[])_imageConverter.ConvertTo(myimg, typeof(byte[]));            
            return barcodeInBytes;
        }
      //  public static byte[] GetQRcode(string sValue)
        //{
            //byte[] barcodeInBytes;         

            //QRCodeEncoder qrCodeEncoder = new QRCodeEncoder();
            //String encoding = "Byte"; //encoding is hardcoded to alphanumeric
            //if (encoding == "Byte")            
            //    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE;            
            //else if (encoding == "AlphaNumeric")          
            //    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.ALPHA_NUMERIC;           
            //else if (encoding == "Numeric")
            //    qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.NUMERIC;

            //try
            //{
            //    int scale = Convert.ToInt16(4); // size is hardcoded to 4
            //    qrCodeEncoder.QRCodeScale = scale;
            //}
            //catch (Exception )
            //{
            //    MessageBox.Show("QR Value Size is Invalid!");               
            //}
            //try
            //{                
            //    int version = Convert.ToInt16(7); //version is hardcoded to 7
            //    qrCodeEncoder.QRCodeVersion = version;
            //}
            //catch (Exception )
            //{
            //    MessageBox.Show("QR Version is Invalid!");
            //}

            //string errorCorrect = "M"; //correction level is hardcoded to M
            //if (errorCorrect == "L")
            //    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.L;
            //else if (errorCorrect == "M")
            //    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.M;
            //else if (errorCorrect == "Q")
            //    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.Q;
            //else if (errorCorrect == "H")
            //    qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.H;
            // Image myimg;
            //try
            //{
            //    myimg = qrCodeEncoder.Encode(sValue);
            //}
            //catch(Exception )
            //{
            //    myimg = qrCodeEncoder.Encode("Error");
            //}
            //ImageConverter _imageConverter = new ImageConverter();
            //barcodeInBytes = (byte[])_imageConverter.ConvertTo(myimg, typeof(byte[]));
            //return barcodeInBytes;
    //    }
        #endregion
    }
}


class tmpInvoiceExceededCreditPeriod
{
    public string CustomerName;
    public string InvoiceNo;
    public string InvoiceDate;
    public decimal CreditPeriod;
    public decimal Days;
    public decimal Amount;
}

class tmpCustomerExceededCredit
{
    public string CustomerCode;
    public string CustomerName;
    public string Salesman;
    public decimal Creditlimit;
    public decimal OutstandingAmu;
    public decimal ChequeInHandAmu;
    public decimal ExceedeAmu;
}

class tmpTurnOverSalesRepWise
{
    public string SalesmanID;
    public decimal AmtInvoices;
    public decimal AmtCreditNote;
    public decimal AmtCollection_Cash;
    public decimal AmtCollection_Cheque;
    public decimal AmtApprovedOrders;
    public decimal dSalesReturnValue;
}

class tmpJobOutsStanding
{
    public int count;
    public string sProductionJob_ID;
    public string sPONo;
    public string sCustomerName;
    public DateTime CustomerOrderDate;
    public int iAgeing;
    public string sItemCode;
    public string sUom;
    public string sOrderQty;
    public string sDeliveryQty;
    public string sBalanceQty;
    public decimal dBalancePasantage;
}

class tmpSectionPlan
{
    public string sJobNo;
    public string sCustomerName;
    public string sItemName;
    public decimal dQty;
    public string sUom;
}